### ISSUE TITLE
Azure Function .Net Core 3.1 - Failed to launch chromium because executable doesn't exist

### ISSUE THREAD

**Issue by alvipeo** [microsoft/playwright-dotnet#1076]
I published a simple example to Azure Function (Windows) and I got the error:

>Failed to launch chromium because executable doesn't exist at C:\local\LocalAppData\ms-playwright\chromium-833159\chrome-win\chrome.exe Try re-installing the browsers running `playwright-cli.exe install` in windows or `playwright-cli install` in MacOS or Linux. Note: pass `debug: "pw:api"` to LaunchAsync to capture Playwright logs.

Any idea how to fix this?
Thank you!

**Comment by alvipeo** [comment]
If I use `await Playwright.InstallAsync(browsersPath);' then I get:

> Access to the path 'C:\Program Files (x86)\SiteExtensions\Functions\3.0.15193\32bit\browsers' is denied.

**Comment by alvipeo** [comment]
ok, I included `browsers` folder into my project and passed `browserPath` value. Now it finds a browser but fails to run it. Well, I guess this is not Playwright's issue... :/

**Comment by kblok** [comment]
Could you try using Linux in the Azure Function?
You can get some help from these posts https://anthonychu.ca/post/azure-functions-puppeteer-pdf-razor-template/ https://anthonychu.ca/post/azure-functions-headless-chromium-puppeteer-playwright/

**Comment by alvipeo** [comment]
@kblok if you look closely to SO question's comments, this is where I started. I don't know how he made it to work, but all of my attempts failed. Trust me, I tried everything I could.

**Comment by danbasszeti** [comment]
I'd second this. I keep getting a message complaining that it can't find the playwright driver in the bin folder, despite it being there. I use Linux on deployed and WSL/Windows locally and get the same message everywhere, but my unit test project doesn't seem to have a problem finding and using playwright

**Comment by alvipeo** [comment]
@anthonychu, how did you exactly made this work? Can you please share the details?

**Comment by anthonychu** [comment]
I haven't been able to get playwright-sharp to work. The Razor sample I have is puppeteer-sharp and I was only able to get it to work when it downloads Chromium on startup.

**Comment by alvipeo** [comment]
Thank you, now it's clear!

If anyone from Dev Team and Azure Functions Team could make it work that would be very helpful!

**Comment by PaulDHerrmann** [comment]
Folks, just checking to see if anyone has gotten this to work.  I'm in Win env App Service and can't get Chromium to load.  Is PuppeteerSharp only working in Linux env in Azure?  Everything runs fine on local.

**Comment by alvipeo** [comment]
I don't think it's possible with Azure Functions. Use VM.

**Comment by 12masta** [comment]
Someone done some improvements in that matter?

**Comment by avodovnik** [comment]
> I don't think it's possible with Azure Functions. Use VM.

While we're working on getting the scenario documented and working, you can use a docker container: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-csharp

as long as you have ran `playwright install` it should work.

But this is something we're working on.

**Comment by pavelfeldman** [comment]
I believe we've moved from 2.1 to 3.1. Please feel free to open a new issue if there are outstanding questions.
