### ISSUE TITLE
[Feature] add BrowserType.connectOverCDP()

### ISSUE THREAD

**Issue by javiercn** [microsoft/playwright-dotnet#1291]
A few weeks ago I asked on the playwright repo about support for webview2 and they pointed me to a sample on how to achieve it [(here)](https://github.com/microsoft/playwright/issues/1122#issuecomment-802500776).

I'm trying to replicate the same process with playwright-sharp, however I don't seem to be able to find the right APIs. I believe the mapping not might be present?

Is there a way we could expose this? Ideally I would want to be able to do [this](https://gist.github.com/JoelEinbinder/e81d3533b9fcde7848251e35216487e8) in C#

Thanks in advance!

**Comment by kblok** [comment]
We don't have `connectOverCDP` on our side yet, but it's coming :)

**Comment by marcel-zumrails** [comment]
any idea when this will be ready? Thanks very much

**Comment by mxschmitt** [comment]
@marcel-zumrails it's released now!
