### ISSUE TITLE
RegAsm.exe - Could not load file or assembly System.Threading.Tasks.Extensions, Version=4.2.0.0

### ISSUE THREAD

**Issue by cirrusone** [microsoft/playwright-dotnet#1425]
I'm trying to use PlaywrightSharp in a .NET 4.8 COM Interop class library. When trying to register in a post-build event

`"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe" /tlb /codebase "$(ProjectDir)$(OutDir)$(TargetName).dll"`

It gives error 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Type library exporter encountered an error while processing 'ProjectX.PlayWrightSharp+<Start>d__8, ProjectX'. 
Error: Type library exporter cannot load type '<Start>d__8' (error: Could not load file or assembly 
'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its 
dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 
0x80131040)).	ProjectX	C:\Users\o\Desktop\ProjectX\ProjectX\RegAsm

```

After some investigation it looks like `Microsoft.Bcl.AsyncInterfaces 5.0.0` is using `System.Threading.Tasks.Extensions, Version=4.2.1.0` but `System.Text.Json 5.0.2` is using `System.Threading.Tasks.Extensions, Version=4.2.0.0`

I'm not having any luck changing the bindingRedirects or manually adding the dll separately. Eg current app.config is 

```
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
      </dependentAssembly>
```

Is it possible to align the versions for the next release? I can give you a working project that raises this error if you want it.

**Comment by avodovnik** [comment]
@cirrusone if you have that sample project you can share, that would be helpful! We've cleaned-up some of the references in the new version, but there might be some still lingering about, when it comes to 4.8 targeting.

**Comment by cirrusone** [comment]
Here is a link to minimal example where this problem occurs. It's just a simple COM class using PlaywrightSharp, the post build event command line includes the following script to auto register the COM using RegAsm depending on current x86 or x64 build configuration.

https://www.dropbox.com/s/fzwylhpsvlpkxz4/PlaywrightSharpCOM.zip?dl=0


```
REM register as x86 or x64 (note Framework vs Framework64)

if $(PlatformName) == x86 (

echo "RegAsm x86 Framework"
"C:\Windows\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe" /unregister "$(ProjectDir)$(OutDir)$(TargetName).dll"
"C:\Windows\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe" /tlb /codebase "$(ProjectDir)$(OutDir)$(TargetName).dll"

) ELSE (

echo "RegAsm x64 Framework64"
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe" /unregister "$(ProjectDir)$(OutDir)$(TargetName).dll"
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe" /tlb /codebase "$(ProjectDir)$(OutDir)$(TargetName).dll"

)
```

It won't register though due to clashing dependencies on `System.Threading.Tasks.Extensions, Version=4.2.0.0` which you should see on the output window when attempting to build.

**Comment by avodovnik** [comment]
@cirrusone I've tried the project with the new version of Playwright (new NuGet package - now `Microsoft.Playwright`) and was able to successfully register the type. 

```
C:\Users\anvod\src\triage\com\PlaywrightSharpCOM\PlaywrightSharpCOM\bin\Debug>regasm /tlb /codebase "PlaywrightSharpCOM.dll"
Microsoft .NET Framework Assembly Registration Utility version 4.8.4084.0
for Microsoft .NET Framework version 4.8.4084.0
Copyright (C) Microsoft Corporation.  All rights reserved.

RegAsm : warning RA0000 : Registering an unsigned assembly with /codebase can cause your assembly to interfere with other applications that may be installed on the same computer. The /codebase switch is intended to be used only with signed assemblies. Please give your assembly a strong name and re-register it.
Types registered successfully
Assembly exported to 'C:\Users\anvod\src\triage\com\PlaywrightSharpCOM\PlaywrightSharpCOM\bin\Debug\PlaywrightSharpCOM.tlb', and the type library was registered successfully
```

Can you verify on your side as well?

As for the binding redirect, the "problem" with the local ones not having a difference, is actually not a problem but by-design. The reason that's happening is that the `TypeLoadException` is happening in `RegAsm`, not in your code. To get around it, you _could_ copy `RegAsm.exe` and `RegAsm.exe.config` to a local folder (from `C:\Windows\Microsoft.NET\Framework\v4.0.30319`) and add the binding redirects to the config file. That will _theoretically_ work. It's also the same approach as in this [question on StackOverflow](https://stackoverflow.com/questions/20134783/regasm-failing-for-a-net-4-0-assembly-using-microsoft-bcl-async).

**Comment by cirrusone** [comment]
Excellent, this is working okay now. Thank you.
