### ISSUE TITLE
can no longer use PLAYWRIGHT_DRIVER_PATH as a workaround to use from LINQPad - can we add that support back, please?

### ISSUE THREAD

**Issue by jamesmanningrapidscale** [microsoft/playwright-dotnet#1515]
Earlier (1.11.1-alpha-2) I was able to set the PLAYWRIGHT_DRIVER_PATH environment variable to point to the exact dir that contained playwright.cmd as a workaround for the fact that in LINQPad the existing logic didn't come up with the "right" path. This seems to have broken in 1.12.1

The actual path of the playwright.cmd that needs to get used is under $env:UserProfile\\.nuget\packages\microsoft.playwright\\[version]\Drivers\win-x64\native\playwright.cmd

This was the code I was using with 1.11.1-alpha-2 to set the env var for use in linqpad:

```csharp
var playwrightAssembly = typeof(Playwright).Assembly;
var driversPath = new FileInfo(playwrightAssembly.Location).Directory!.FullName;
while (Directory.Exists(Path.Combine(driversPath, "Drivers")) == false && Path.GetPathRoot(driversPath) != driversPath)
{
    driversPath = Path.GetDirectoryName(driversPath);
}
// since the default path it checks includes a .playwright dir that doesn't exist for us, need to point to the exact dir with the .cmd file
driversPath = Path.Combine(driversPath, "Drivers", ((RuntimeInformation.OSArchitecture == Architecture.X64) ? "win-x64" : "win-x86"), "native");
Environment.SetEnvironmentVariable("PLAYWRIGHT_DRIVER_PATH", driversPath);
```

AFAICT this support for PLAYWRIGHT_DRIVER_PATH got removed with https://github.com/microsoft/playwright-dotnet/commit/55867b054cf1df8969fd935d98d536e37a8669e1#diff-a387ff4bbdf5b27cc00330eae6e3c41df555197a80d35f8cc21dec46152e8d0cL289-L292

Now there's no workaround for pointing to the driver location, so trying to use from linqpad doesn't have a simple workaround and we get a PlaywrightException trying to Playwright.CreateAsync as it's looking for the driver under $env:UserProfile\.nuget\packages\Microsoft.Playwright\1.12.1\lib\net5.0\\.playwright\node\win32_x64\playwright.cmd

Message: 
`Driver not found: [userprofile dir here]\.nuget\packages\Microsoft.Playwright\1.12.1\lib\net5.0\.playwright\node\win32_x64\playwright.cmd
`
```
   at Microsoft.Playwright.Helpers.Paths.GetExecutablePath()
   at Microsoft.Playwright.Transport.Connection.GetProcess()
   at Microsoft.Playwright.Transport.Connection..ctor()
   at Microsoft.Playwright.Playwright.CreateAsync()
   at UserQuery.Main(), line 1
```

If we can add that back (not sure why the env var support needed to be killed off-hand?), users can then have a workaround for when the existing logic doesn't Just Work(tm)

**Comment by pavelfeldman** [comment]
Thanks for the report, let me see what we can do for you. I might have a question or two about your setup!

**Comment by pavelfeldman** [comment]
I'll document my findings here. Playwright looks for the driver in the following folder:

```csharp
var assembly = typeof(Playwright).Assembly;
string driversPath = new FileInfo(assembly.Location).Directory.FullName;
// platformId == win32_x64
// runnerName == playwright.cmd
Path.Combine(driversPath, ".playwright", "node", platformId, runnerName)
```

In your case it ends up with the following result:
`.nuget\packages\Microsoft.Playwright\1.12.1\lib\net5.0.playwright\node\win32_x64\playwright.cmd`

I wonder under which circumstances `Path.Combine` would not insert `\` before ".playwright" and what the result of new `FileInfo(assembly.Location).Directory.FullName;` is in your case. Could you provide the value you are getting for `new FileInfo(assembly.Location).Directory.FullName;` ?

**Comment by avodovnik** [comment]
As I've commented in the PR (#1520), we need to figure out what's happening. But, we can at least consider brining back the env variable.

**Comment by pavelfeldman** [comment]
I think we can make Playwright read the driver from the nuget registry instead of the output folder if it finds itself running from there. Should be an easy fix and should not require any env variables.

**Comment by avodovnik** [comment]
@pavelfeldman I agree, this sounds like a "bug"/by-design in LinqPad (i.e. not running `.targets`) which is fine/acceptable/expected. I've changed the PR to do a fallback to the global NuGet repository. I've also verified this locally with LinqPad (and a local NuGet source).

**Comment by onionhammer** [comment]
Being able to build UI automation interactively using CSX or .NET interactive notebooks would be *very* useful for an efficient developer loop
