### ISSUE TITLE
Selective browser install at runtime?

### ISSUE THREAD

**Issue by FutureTD** [microsoft/playwright-dotnet#1516]
Is it possible to install a selected browsers at runtime?

For my instance I have a wpf/winforms application that uses playwright. When I distribute my application to customers, I need to be able to have my application download a specific browser such as chrome only so that it can utilize playwright. Is this possible at the moment?

**Comment by pavelfeldman** [comment]
Playwright CLI is exposed as a public class Microsoft.Playwright.Program. So everything CLI can do, you can do programmatically, including browser install. Could you try calling `Microsoft.Playwright.Program.Main(new string[] { "install", "chromium" })` and tell us if that worked?

**Comment by FutureTD** [comment]
Yes that seemed to have worked. Thank you.
