### ISSUE TITLE
WaitForLoadStateAsync (CustomNetworkIdle)

### ISSUE THREAD

**Issue by CheloXL** [microsoft/playwright-dotnet#1521]
Hi,

Feature request:
An overload for the WaitForLoadStateAsync where we can provide an options object with some definitions for when the network should be considered idle.

This is similar to an existing feature in puppeteer (networkidle2), but I would like the ability to provide my custom definition of what I define idle.

Right now I'm working with a site that is always pinging servers for tracking/analytics purposes every few seconds so this feature could account for those events.

**Comment by pavelfeldman** [comment]
I would not use any variation of network idle. As you already figured out, this signal is pretty much useless in the wild, it only works in a controlled environment of your tests. I can't imagine the terms you will be expressing the CustomNetworkIdle in, so I would recommend using WaitForSelectorAsync or WaitForFunctionAsync.

**Comment by CheloXL** [comment]
The problem with those methods is that it's quite difficult, if not impossible, to use them across iframes when you don't have a way to identify each one of them.

Currently, I need to wait for a page to completely load so I can grab a screenshot. The main page creates iframes (that are created based on network requests, so the order in the source is always changing) and each iframe does something similar (more iframes inside iframes).

Main page also pings servers about every second. NetworkIdle never fires.

I was thinking in something like `CustomNetworkIdle { int NetworkConnections, int Timespan }`, so I can decide if I want to emulate networkidle2 I can use `new CustomNetworkIdle(2, 500)`.

**Comment by mxschmitt** [comment]
A custom network idle is not supported, we recommend [waitForSelector](https://playwright.dev/dotnet/docs/api/class-page#page-wait-for-selector) to ensure elements are there or waitForResponse to ensure a http resource got loaded.

If you are still interested in a custom network idle timeout, please open a feature request upstream: https://github.com/microsoft/playwright
