### ISSUE TITLE
What versions of .NET does this work with?

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-dotnet#1525]
I got asked if this works with 3.1 or 5 or both. It doesn't say anywhere in the docs.

**Comment by kblok** [comment]
The right answer is that it's `netstandard2.0` (https://docs.microsoft.com/en-us/dotnet/standard/net-standard). It will work in 3.1 and 5.
The Nunit package is `netcoreapp3.1`, `net5.0`, and `net48`.

**Comment by alindgren** [comment]
When I ran the install on a machine with .NET 3.1 (`dotnet tool install --global Microsoft.Playwright.CLI`), I get this error: 

![image (4)](https://user-images.githubusercontent.com/910359/121599531-2c372b80-ca11-11eb-9490-383a9eaa53bb.png)

**Comment by pavelfeldman** [comment]
`Microsoft.Playwright.CLI` currently targets only .net5.0. As a workaround do:

`dotnet ./bin/Debug/.../Microsoft.Playwright.dll`

or 

`.bin/Debug/.../playwright.ps1`

We'll add targets to CLI to work everywhere in 1.0.1
