### ISSUE TITLE
Issue with updating dockerfile to use Microsoft.Playwright

### ISSUE THREAD

**Issue by tehmufifnman** [microsoft/playwright-dotnet#1546]
I've tried everything I can think of from the docs and googling to update this Dockerfile to properly install Playwright when building, but I can't seem to get `playwright install` to work.  It may be due to my only intermediate knowledge of Docker.

Can anyone tell me what an updated Dockerfile would look like?  I got past the battle of getting `dotnet tool` commands to work.  There also seems to be an is sue with the tools path inside a Docker, but even when I got that fixed `playwright install` would still fail because I am building the project in a source image.

Current Dockerfile I am using with `<PackageReference Include="PlaywrightSharp" Version="0.192.0" />`
```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY .nuget/NuGet.Config ./


# Copy everything else and build
COPY . ./
ARG RELEASE_CONFIG=Debug
RUN dotnet restore --configfile .nuget/NuGet.Config
RUN dotnet publish --framework net5.0 Foo.Bar/Foo.Bar.csproj -c ${RELEASE_CONFIG} -o out \
    && mkdir /app/out/.playwright \
    && cp -r /app/Foo.Bar/bin/${RELEASE_CONFIG}/net5.0/.playwright/unix /app/out/.playwright

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
ARG DEFAULT_ENV=DEV
ENV ASPNETCORE_ENVIRONMENT=${DEFAULT_ENV}
WORKDIR /app
COPY --from=build-env /app/out/ .
RUN apt-get update \
    && apt-get install libglib2.0-0 -y \
    && apt-get install libnss3 -y \
    && apt-get install libnspr4 -y \
    && apt-get install libatk1.0-0 -y \
    && apt-get install libatk-bridge2.0-0 -y \
    && apt-get install libcups2 -y \
    && apt-get install libdrm2 -y \
    && apt-get install libdbus-1-3 -y \
    && apt-get install libexpat1 -y \
    && apt-get install libxcb1 -y \
    && apt-get install libxkbcommon0 -y \
    && apt-get install libx11-6 -y \
    && apt-get install libxcomposite1 -y \
    && apt-get install libxdamage1 -y \
    && apt-get install libxext6 -y \
    && apt-get install libxfixes3 -y \
    && apt-get install libxrandr2 -y \
    && apt-get install libgbm1 -y \
    && apt-get install libgtk-3-0 -y \
    && apt-get install libpango-1.0-0 -y \
    && apt-get install libcairo2 -y \
    && apt-get install libasound2 -y \
    && apt-get install libatspi2.0-0 -y \
    && apt-get install libxshmfence1 -y \
    && .playwright/unix/native/playwright.sh install

CMD ["dotnet","Foo.Bar.dll"]
```

**Comment by tehmufifnman** [comment]
Ugh haha still no luck!  Anyone had success with this?

**Comment by avodovnik** [comment]
This seems related to: https://github.com/microsoft/playwright-dotnet/issues/1584

Could you attempt using the newer version? Ideally trying out with `1.13-next`? There's a significant change there around publishing and locating the drivers.

**Comment by tehmufifnman** [comment]
> This seems related to: #1584
> 
> Could you attempt using the newer version? Ideally trying out with `1.13-next`? There's a significant change there around publishing and locating the drivers.

That does look like it could be potentially related,  My issue is I cannot figure out how to run the install for Playwright with the new version (not that its not working).  I can't figured out how to transition my old Dockerfile (pictured above).

Maybe I am missing something? Sorry if a stupid question haha

**Comment by tehmufifnman** [comment]
I am under the impression that something like the below is required within my Dockerfile, but I am unsure;
```
 Create project
dotnet new console -n PlaywrightDemo
cd PlaywrightDemo

# Install dependencies, build project and download necessary browsers.
dotnet add package Microsoft.Playwright
dotnet build
playwright install
```

**Comment by tehmufifnman** [comment]
```
RUN dotnet restore --configfile .nuget/NuGet.Config
RUN dotnet publish --framework net5.0 Carvana.TopAutomation.EventedJob/Carvana.TopAutomation.EventedJob.csproj -c ${RELEASE_CONFIG} -o out
RUN playwright install
```

errors:
```
 > [build-env 8/8] RUN playwright install:
#15 0.450 /bin/sh: 1: playwright: not found
```

**Comment by pavelfeldman** [comment]
https://playwright.dev/dotnet/docs/intro/#installation should list all the steps necessary for installation.

**Comment by tehmufifnman** [comment]
> https://playwright.dev/dotnet/docs/intro/#installation should list all the steps necessary for installation.
Yup thats where I pulled those commands from - it does not work inside a Dockerfile, thats my issue =)

**Comment by Jaxter** [comment]
I'm also having the same issue. Anyone managed to find a solution?

**Comment by baltazar71** [comment]
This is what worked for me.

`
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS base
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-liberation\
    libasound2\
    libatk-bridge2.0-0\
    libatk1.0-0\
    libatspi2.0-0\
    libcairo2\
    libcups2\
    libdbus-1-3\
    libdrm2\
    libgbm1\
    libglib2.0-0\
    libgtk-3-0\
    libnspr4\
    libnss3\
    libpango-1.0-0\
    libx11-6\
    libxcb1\
    libxcomposite1\
    libxdamage1\
    libxext6\
    libxfixes3\
    libxrandr2 \
    libxshmfence1

RUN dotnet tool install --global Microsoft.Playwright.CLI

RUN mkdir -p /config
EXPOSE 5000

FROM base AS final
WORKDIR /src
COPY ["FooBarAppWorker/FooBarAppWorker.csproj", "FooBarAppWorker/"]
COPY ["FooBarAppShared/FooBarAppShared.csproj", "FooBarAppShared/"]
RUN dotnet restore "FooBarAppWorker/FooBarAppWorker.csproj"
COPY . .
WORKDIR "/src/FooBarAppWorker"
RUN dotnet build "FooBarAppWorker.csproj" -c Release -o /app/build
WORKDIR /app
RUN /root/.dotnet/tools/playwright install

WORKDIR "/src/FooBarAppWorker"
RUN dotnet publish "FooBarAppWorker.csproj" -c Release -o /app/publish

WORKDIR /app
ENTRYPOINT ["dotnet", "FooBarAppWorker.dll"]
`

**Comment by avodovnik** [comment]
@tehmufifnman you're missing the installation of the `dotnet tool`. This is documented [here](https://playwright.dev/dotnet/docs/next/intro#installation), before the `First Project` part :-). 

So, effectively, you need to do the following:

```bash
dotnet tool install --global Microsoft.Playwright.CLI
dotnet add package Microsoft.Playwright
dotnet build
playwright install
```

As per @baltazar71's answer, make sure your `DOCKERFILE` has 

```dockerfile
RUN dotnet tool install --global Microsoft.Playwright.CLI
```

**Comment by tehmufifnman** [comment]
> @tehmufifnman you're missing the installation of the `dotnet tool`. This is documented [here](https://playwright.dev/dotnet/docs/next/intro#installation), before the `First Project` part :-).
> 
> So, effectively, you need to do the following:
> 
> ```shell
> dotnet tool install --global Microsoft.Playwright.CLI
> dotnet add package Microsoft.Playwright
> dotnet build
> playwright install
> ```
> 
> As per @baltazar71's answer, make sure your `DOCKERFILE` has
> 
> ```dockerfile
> RUN dotnet tool install --global Microsoft.Playwright.CLI
> ```

No i'm not sadly - I mentioned above that I just accidentally missed that bit in my copy/paste.
`playwright install` fails because it does not find the playwright executable.  it seems for some reason this is not placed in the PATH.

**Comment by tehmufifnman** [comment]
You can even see in one of the replies above that another user had to get around this by doing:
```
RUN /root/.dotnet/tools/playwright install
```

The below results in an error
```
...
ARG RELEASE_CONFIG=Debug
RUN dotnet tool install --global Microsoft.Playwright.CLI
RUN dotnet restore --configfile .nuget/NuGet.Config
RUN dotnet add Foo.Service/Foo.Service.csproj package Microsoft.Playwright
RUN dotnet build
RUN dotnet publish --framework net5.0 Foo.Service/Foo.Service.csproj -c ${RELEASE_CONFIG} -o out
RUN playwright install
...
```

```
 => ERROR [build-env 10/10] RUN playwright install                                                                                                                                                                                                                                                                 0.5s
------
 > [build-env 10/10] RUN playwright install:
#17 0.486 /bin/sh: 1: playwright: not found
------
```

**Comment by tehmufifnman** [comment]
This Dockerfile works (and the same solution works with the release version of the CLI/LIB even though the below is using the previous).  It still has to reference the playwright install via the full path because the playwright executable is not being put in the path when the global tool is installed.

You can also ignore the final RUN command, this is just something I had to do because of the interim copy and some permissions shenanigans caused by the security in my org's k8s cluster.

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Install Playwright CLI
RUN dotnet tool install --global Microsoft.Playwright.CLI --version 1.0.1-next-1

# Copy csproj and restore as distinct layers
COPY .nuget/NuGet.Config ./

# Copy everything else and build
COPY . ./
ARG RELEASE_CONFIG=Debug
RUN dotnet restore --configfile .nuget/NuGet.Config
RUN dotnet publish --framework net5.0 FooService/FooService.csproj -c ${RELEASE_CONFIG} -o out
ENV PLAYWRIGHT_BROWSERS_PATH=/app/out/browsers
RUN /root/.dotnet/tools/playwright install

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
ARG DEFAULT_ENV=DEV
ENV ASPNETCORE_ENVIRONMENT=${DEFAULT_ENV}
WORKDIR /app
COPY --from=build-env /app/out/ .
RUN apt-get update \
    && apt-get install libglib2.0-0 -y \
    && apt-get install libnss3 -y \
    && apt-get install libnspr4 -y \
    && apt-get install libatk1.0-0 -y \
    && apt-get install libatk-bridge2.0-0 -y \
    && apt-get install libcups2 -y \
    && apt-get install libdrm2 -y \
    && apt-get install libdbus-1-3 -y \
    && apt-get install libexpat1 -y \
    && apt-get install libxcb1 -y \
    && apt-get install libxkbcommon0 -y \
    && apt-get install libx11-6 -y \
    && apt-get install libxcomposite1 -y \
    && apt-get install libxdamage1 -y \
    && apt-get install libxext6 -y \
    && apt-get install libxfixes3 -y \
    && apt-get install libxrandr2 -y \
    && apt-get install libgbm1 -y \
    && apt-get install libgtk-3-0 -y \
    && apt-get install libpango-1.0-0 -y \
    && apt-get install libcairo2 -y \
    && apt-get install libasound2 -y \
    && apt-get install libatspi2.0-0 -y \
    && apt-get install libxshmfence1 -y

RUN chmod +rx,o+rx /app/.playwright \
    && chmod +rx,o+rx /app/.playwright/node \
    && chmod +rx,o+rx /app/.playwright/node/linux \
    && chmod +rx,o+rx /app/.playwright/node/linux/playwright.sh

CMD ["dotnet","FooService.dll"]
```

**Comment by avodovnik** [comment]
Great news that you got it working! 💪🏻 

There's one additional thing I would have suggested, which is that instead of installing the tool, you can also "piggy back" off the built-in tooling, by doing 

`RUN dotnet out/Microsoft.Playwright.dll -- install`

So, basically your DOCKERFILE would look like:

```DOCKERFILE
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY .nuget/NuGet.Config ./

# Copy everything else and build
COPY . ./
ARG RELEASE_CONFIG=Debug
RUN dotnet restore --configfile .nuget/NuGet.Config
RUN dotnet publish --framework net5.0 FooService/FooService.csproj -c ${RELEASE_CONFIG} -o out
ENV PLAYWRIGHT_BROWSERS_PATH=/app/out/browsers
RUN dotnet out/Microsoft.Playwright.dll -- install

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
ARG DEFAULT_ENV=DEV
ENV ASPNETCORE_ENVIRONMENT=${DEFAULT_ENV}
WORKDIR /app
COPY --from=build-env /app/out/ .
RUN apt-get update \
    && apt-get install libglib2.0-0 -y \
    && apt-get install libnss3 -y \
    && apt-get install libnspr4 -y \
    && apt-get install libatk1.0-0 -y \
    && apt-get install libatk-bridge2.0-0 -y \
    && apt-get install libcups2 -y \
    && apt-get install libdrm2 -y \
    && apt-get install libdbus-1-3 -y \
    && apt-get install libexpat1 -y \
    && apt-get install libxcb1 -y \
    && apt-get install libxkbcommon0 -y \
    && apt-get install libx11-6 -y \
    && apt-get install libxcomposite1 -y \
    && apt-get install libxdamage1 -y \
    && apt-get install libxext6 -y \
    && apt-get install libxfixes3 -y \
    && apt-get install libxrandr2 -y \
    && apt-get install libgbm1 -y \
    && apt-get install libgtk-3-0 -y \
    && apt-get install libpango-1.0-0 -y \
    && apt-get install libcairo2 -y \
    && apt-get install libasound2 -y \
    && apt-get install libatspi2.0-0 -y \
    && apt-get install libxshmfence1 -y

RUN chmod +rx,o+rx /app/.playwright \
    && chmod +rx,o+rx /app/.playwright/node \
    && chmod +rx,o+rx /app/.playwright/node/linux \
    && chmod +rx,o+rx /app/.playwright/node/linux/playwright.sh

CMD ["dotnet","FooService.dll"]

```

**Comment by corygehr** [comment]
Microsoft.Playwright.CLI doesn't seem to support .NET Core 3.1. This might work for .NET 5 and .NET Core 2.1 and I might try the piggyback approach above to get things working in my Dockerfile.

For what it's worth, the current pre-release package helps me get past the missing /app/.playwright directory error.

**Comment by avodovnik** [comment]
@corygehr The 3.1 compatibility should be sorted now in the new release. 

I'll be closing this issue for now, but feel free to open a new one if the problem re-appears.

**Comment by corygehr** [comment]
Confirmed working for me with v1.13.0. Thanks!
