### ISSUE TITLE
Null ref in ApiChecker.EvaluateArgument

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#1548]
https://github.com/microsoft/playwright-dotnet/blob/main/src/tools/Playwright.Tooling/ApiChecker.cs#L341-L343
```
membersQueue.Remove(overloadMethod);
playwrightSharpArgument = overloadMethod.GetParameters().FirstOrDefault(p => IsParameterNameMatch(p.Name, arg.Name));
report.AppendLine("<li>");
report.AppendLine($"{arg.Name} ({type.Name.ToHtml()}): found as {playwrightSharpArgument.Name} ({playwrightSharpArgument.ParameterType})");
```

so `overloadMethod.GetParameters().FirstOrDefault` implies it might not find one and `playwrightSharpArgument` could be null, which would result in a null ref. so should FirstOrDefault` be changed to a `First`, or should `playwrightSharpArgument` be null checked and a helpful exception be thrown?

**Comment by SimonCropp** [comment]
same issue on line 379 and 409

**Comment by pavelfeldman** [comment]
I don't think this checker is functional. @avodovnik does it work?

**Comment by mxschmitt** [comment]
Closing since it was removed in #1597.
