### ISSUE TITLE
Add TryQuerySelectorAsync

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#1574]
IMO there should be a TryQuerySelectorAsync which returns a nullable and QuerySelectorAsync should be changed to throw if not found. 

Thoughts?

**Comment by pavelfeldman** [comment]
We return a lot of nullable stuff and use nullable reference annotations to handle this w/o forking our api into Foo and TryFoo.

**Comment by kblok** [comment]
That could be solved by the client with an extension method throwing an exception if null.

**Comment by SimonCropp** [comment]
for me it seems "expecting a result is returned" would be the most common scenario, hence i feel it should throw on not found by default. but perhaps thats just me. so will close this
