### ISSUE TITLE
in what cases is PlaywrightException valid?

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#1577]
We should not be throwing a custom exception if there are no scenarios that it should be caught. It seems most cases PlaywrightException should be replaced with Exception

**Comment by pavelfeldman** [comment]
We keep it in other languages for people to know it comes from us. They asked for it there.

**Comment by kblok** [comment]
I think it's important to identify an exception thrown by a library.

**Comment by SimonCropp** [comment]
accepting all that. shouldnt it be internal? since there is no scenario where people should catch it

**Comment by kblok** [comment]
If I want to catch an error from playwright I will need this exception.

**Comment by SimonCropp** [comment]
can you share a scenario where something useful can be done when catching PlaywrightException ? as in why would a `catch PlaywrightException` be preferred over a `catch Exception`?

**Comment by kblok** [comment]
I have a piece of code that inserts a record in a SQL table before launching playwright to generate a PDF. I want to distinguish between a playwright exception and a SQL exception.

**Comment by SimonCropp** [comment]
what code would you write in `catch PlaywrightException` that would be different from `catch Exception`

**Comment by kblok** [comment]
If it's a `PlaywrightException` I tell the user that he needs to try another URL. If it's a division by zero I throw the exception.
All in all. I do think we need this exception. You can use `Exception` and it will catch it.

**Comment by SimonCropp** [comment]
ok
