### ISSUE TITLE
Possible Memory Leak Request/Response-dictionary

### ISSUE THREAD

**Issue by Wuerzburger** [microsoft/playwright-dotnet#1585]
Hello,
while playing around with Playwright I detected that the memory consumption for each new page and each navigation is increasing continously. It seems that there is no release of memory until you close and destroy the context/browser.
I've done a memory snapshot with VS and there is a dictionary<string,string> which keeps on growing but is never shrinking. As far as I can tell this dictionary links a request with a response (see screenshot). 

![grafik](https://user-images.githubusercontent.com/50401694/122683733-7a161580-d201-11eb-96b7-68d1043857a5.png)

Could this be that this is a bug? Is there a way to avoid that behaviour without destroying the context/browser?

**Comment by SimonCropp** [comment]
on a side note: does it make sense that you have 4000+ instances of `Filiale` in memory?

**Comment by avodovnik** [comment]
Can you provide more context as to what (and how) you're executing the tests? Are you running them in-parallel? What version of Playwright are you using? Can you provide us with a way to effectively repro this?

**Comment by pavelfeldman** [comment]
This behavior is expected. Playwright will retain request information (headers) for all requests in the context. Since contexts are short-lived, this should not be a problem. If you are using context for many navigations, you might be suing it wrong.

**Comment by pavelfeldman** [comment]
Closing as per above.
