### ISSUE TITLE
Save Screenshots and Video as base64 encoded to Nunit .trx files

### ISSUE THREAD

**Issue by rschoessler** [microsoft/playwright-dotnet#1588]
We have a use case that we run Playwright tests in docker and then send the results to another application where results are displayed including any screenshots of test failures.  The receiving application processes the test results and stores screenshots in an object storage server.

Is there a way to take a screenshot and save it to the .trx results file that is may be easier with Microsoft.Playwright.Nunit?  Things I have tried:

- `TestContext.AddTestAttachment()` - this seems to always write a local filepath like `MACHINENAME\my_custom_file.png` but I am actually saving it to a network drive.  This only allows adding a path.  Feels like this method is buggy.
- `WriteLine(Convert.ToBase64String(bytes));` - take the file and base64 encode it as a node in the xml.  However, this ends up written to the <Results><UnitTestResult><Output><StdOut> path.  This is not a great solution if there's other `StdOut` written.  It also gives me issues with escaping characters:

Code:
```        [TearDown]
        public async Task PageTearDown()
        {
            if (TestOk() == false)
            {
                var bytes = await Page.ScreenshotAsync(new PageScreenshotOptions { FullPage = true, });
                WriteLine("<Attachments>");
                WriteLine(Convert.ToBase64String(bytes));
                WriteLine("</Attachments>");
            }
        }
```
...results in....
```
<Output>
        <StdOut>&lt;Attachments&gt;&#xD;iVBORw0KGgoAAAANSUhEUgAAB4AAAASwCAYAA......CYII=&#xD;&lt;/Attachments&gt</StdOut>
```

Is there a way to do this now that I'm just missing?

If this were a new feature in Microsoft.Playwright.Nunit, would it be possible to add a node that was something like:

```
<UnitTestResult>
    <StdOut></StdOut>
    <Attachments>
        <Attachment>**file1 base64 encoded string**_</Attachment>
        <Attachment>**file2 base64 encoded string**_</Attachment>
    </Attachments>
</UnitTestResult>
```

Perhaps it could be an overload of `TestContext.AddTestAttachment()` that takes a base64 encoded string?

**Comment by avodovnik** [comment]
`TestContext` is a `NUnit` construct, not Playwright's, so we don't actually control that part.

I may be missing something, but what's wrong with using the built-in `TestContext.AddTestAttachment`? AFAICS, the screenshot is placed alongside the resulting trx:

![image](https://user-images.githubusercontent.com/1932563/122788724-ed2d9380-d2b6-11eb-9da7-bd1b646c7b95.png)

I was able to very quickly get the screenshot:

```csharp
await Page.GotoAsync("https://www.bing.com");
var image = await Page.ScreenshotAsync(new() { Path = "name.png" });
TestContext.AddTestAttachment("name.png");
```

![image](https://user-images.githubusercontent.com/1932563/122788859-0c2c2580-d2b7-11eb-9e8f-5f68b8e2a008.png)

this seemed to also work correctly in Azure Pipelines.

**Comment by rschoessler** [comment]
@avodovnik thanks for the response.  It's possible I'm missing something too.  Let me look into this more, it seems I need to perhaps send the dirs/files along with my .trx file, rather than send them embedded in the file.  I was hoping to be able to send the base64 encoded string as a node in the .trx file such that my receiving system could process only the .trx file.

**Comment by avodovnik** [comment]
This is a highly subjective opinion, obviously, but I'd rather do the work to upload the folder, because that will give you a lot more flexibility down the road, with video, etc. I really don't want to imagine what a trx file would look like with a bunch of screenshots or a longer video capture :-). 

But, as with all things programming, your mileage may vary. Let us know what you find out!

**Comment by rschoessler** [comment]
Yes, I am concerned about the file size as well.  I think this is pointing me in another direction.  I think I'll close this out.  This helped me understand a little better about what is going on.
