### ISSUE TITLE
[Feature] make Options classes records

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-dotnet#1591]
A common use-case with Options classes might be that we will have base options and want to modify one of more properties.

with records we will be able to use the `with` keyword

for example:
```cs
BrowserNewContextOptions baseOptions = ...;
BrowserNewContextOptions options = baseOptions with { IsMobile = true, HasTouch = true };
```

if this will be done then we might want to consider changing the propertes from `{ get; set; }` to be `{ get; init; }`

**Comment by avodovnik** [comment]
The way I understand `record` types is, that they don't work out of the box on older targets (i.e. `4.7`). IIRC, I read [somewhere](https://sergiopedri.medium.com/enabling-and-using-c-9-features-on-older-and-unsupported-runtimes-ce384d8debb) that you need `IsExternalInit` which is something I don't feel comfortable imposing on our users. 

Am I missing something?

**Comment by avodovnik** [comment]
To add some clarity, looking at the [proposal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init#modreqs-vs-attributes) it seems the blog post is correct, and the decision was made to use `modreq` which also means:

> The downside of modreq is init becomes a part of the binary signature of the set accessor. Adding or removing init will break binary compatbility of the application.

That means it's a slightly more complicated decision, if we want to go down this road.

**Comment by pavelfeldman** [comment]
Sounds like we are not doing it...
