### ISSUE TITLE
[Bug] driver stderr does not get forwarded (DEBUG=pw:api does not work)

### ISSUE THREAD

**Issue by Xen0byte** [microsoft/playwright-dotnet#1592]
I used to do...

`var playwright = await Playwright.CreateAsync(playwrightLogger, debug: "pw:api");`

...however now that doesn't work anymore, as far as I can tell.

I've tried setting the `DEBUG` env var to `pw:api` both for the user and the machine, but that didn't seem to help. What am I doing wrong?

**Comment by pavelfeldman** [comment]
How do you consume logs, what is your use case?

**Comment by Xen0byte** [comment]
For this particular use case, I would just like to see the logs in the Debug channel of the Output window in Visual Studio.

![2021-06-22_01-01-33](https://user-images.githubusercontent.com/6122296/122842585-95624d00-d2f5-11eb-9418-03c8eeee5d86.png)

This used to be possible prior to upgrading to the stable version.

**Comment by pavelfeldman** [comment]
What kind of logs would you like to see though? Is `DEBUG=pw:api` enough for you?

**Comment by Xen0byte** [comment]
Hi @pavelfeldman, I believe so, yes. To provide a bit of context, I'm using Playwright via Specflow, and debugging Specflow is a fairly horrible experience since, short of putting breakpoints everywhere, most times the debugger will stop on the step from the BDD feature file rather than the line of code that actually threw the exception. Being able to inspect the verbose Playwright API logs again would be incredibly helpful.

**Comment by pavelfeldman** [comment]
I missed the fact that simply specifying DEBUG=pw:api environment variable does not log into stderr. We'll fix this.
