### ISSUE TITLE
[Question] What `<PackageId>` and `namespace` to use when publishing third party NuGet packages

### ISSUE THREAD

**Issue by hlaueriksson** [microsoft/playwright-dotnet#1595]
I would like to publish NuGet packages that will use and offer extensions to `Microsoft.Playwright`.

(In a similar fashion as I have done with [PuppeteerSharp](https://www.nuget.org/packages?q=PackageId%3APuppeteerSharp.Contrib.Extensions+PackageId%3APuppeteerSharp.Contrib.Should+PackageId%3APuppeteerSharp.Contrib.PageObjects))

What `<PackageId>` and `namespace` should I use?

The code is in this repo:
https://github.com/hlaueriksson/playwright-dotnet-contrib

My suggested PackageIds:

- Playwright.Contrib.Extensions
- Playwright.Contrib.FluentAssertions
- Playwright.Contrib.PageObjects

My suggested namespaces:

- Microsoft.Playwright.Contrib.Extensions
- Microsoft.Playwright.Contrib.FluentAssertions
- Microsoft.Playwright.Contrib.PageObjects

Is it OK to prefix the namespace with `Microsoft.`?

The reason behind this is to make it straightforward to use the static `Playwright` class:

```cs
using Microsoft.Playwright;
using Microsoft.Playwright.Contrib.Extensions;

var playwright = await Playwright.CreateAsync();
```

If I use the namespace `Playwright.Contrib.Extensions` then it will not be as easy to refer to the class `Playwright`.

**Comment by kblok** [comment]
I created this repo https://github.com/hardkoded/playwright-sharp-contrib/projects/1, but I only created the issues 🙈 
I like your package ids and namespaces ideas. I think there is no issue using the `Microsoft.` namespace. You won't be able to create packages with those names tho.

**Comment by pavelfeldman** [comment]
I would only use Microsoft.* for something coming from Microsoft! Looks like we are on the same page already.

**Comment by hlaueriksson** [comment]
I ended up with both PackageId and namespace like this:

* `PlaywrightContrib.Extensions`
* `PlaywrightContrib.FluentAssertions`
* `PlaywrightContrib.PageObjects`

Now available on NuGet: https://www.nuget.org/packages?q=PlaywrightContrib
