### ISSUE TITLE
Issue when running Playwright dotnet in docker container

### ISSUE THREAD

**Issue by AndreiToader1** [microsoft/playwright-dotnet#1599]
When trying to run playwright  dotnet in docker container I get the following exception:
Host system is missing dependencies!

        Install missing packages with:
            sudo apt-get install libglib2.0-0\
             libnss3\
             libnspr4\
                libatk1.0-0\
                libatk-bridge2.0-0\
                libcups2\
               libdrm2\
                 libdbus-1-3\
                libxcb1\
               libxkbcommon0\
               libx11-6\
                 libxcomposite1\
                 libxdamage1\
                 libxext6\
                 libxfixes3\
               libxrandr2\
                 libgbm1\
                libpango-1.0-0\
                 libcairo2\
                 libasound2\
                 libatspi2.0-0

         Missing libraries we didn't find packages for:
             libexpat.so.1
             libxshmfence.so.1
Playwright version: 1.12.2
Already tried pulling the image 
FROM mcr.microsoft.com/playwright:v1.12.2-focal
which I found on some answers that should install the dependencies.

Linux version:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

**Comment by mxschmitt** [comment]
Could you try running `playwright install-deps`? This will install all the necessary system dependencies, see [here](https://playwright.dev/dotnet/docs/cli/#install-system-dependencies) for more information.

**Comment by AndreiToader1** [comment]
Manage to make it work by running install-deps. however, I got another error related to some invalid certificates. But I opened another issue for that. I think this one can be closed. Thank you for help
