### ISSUE TITLE
IgnoreHTTPSErrors option removed ?

### ISSUE THREAD

**Issue by thomaschanneladvisor** [microsoft/playwright-dotnet#1600]
https://playwright.dev/dotnet/docs/api/class-browser#browser-new-context
Does the documentation need to be updated or will IgnoreHTTPSErrors be added back as a configurable option? I cannot access the property in BrowserNewContextOptions in the latest version 12.2.0 and also 1.13.0-next-1.

**Comment by kblok** [comment]
I see the property here https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/API/Generated/Options/BrowserNewContextOptions.cs#L88

**Comment by thomaschanneladvisor** [comment]
@kblok Very sorry...we can close this. I had it set and was trying to di it again and missed it 😞
