### ISSUE TITLE
Trying to determine if Playwright will suit my needs

### ISSUE THREAD

**Issue by ftpguy** [microsoft/playwright-dotnet#1609]
### Your question

I plan to use Playwright as a tool to automate browser activity such as clicks, changing form input values (textboxes, checkboxes, dropdowns), etc. Essentially, I am creating a web bot that will monitor activity on a social media site. Here are my questions:

- Can Playwright acquire an existing browser instance that was previously created by Playwright? If I navigate through a series of pages and then have to stop my debugger to make some code changes, I don't want to have to start my browsing session all over again. I'd want to continue where I left off on the page I was on
- Can I use Playwright to scrub HTML?
- Are AJAX calls taken into account so that I can access content that was loaded after the page has completed loading?

**Comment by avodovnik** [comment]
> * Can Playwright acquire an existing browser instance that was previously created by Playwright? If I navigate through a series of pages and then have to stop my debugger to make some code changes, I don't want to have to start my browsing session all over again. I'd want to continue where I left off on the page I was on

Playwright for .NET does not support this, yet, but you can _sort_ of do it via Playwright, by [connecting over CDP](https://playwright.dev/docs/next/api/class-cdpsession).

> * Can I use Playwright to scrub HTML?

Is [this](https://playwright.dev/docs/api/class-elementhandle#element-handle-text-content) enough?

> * Are AJAX calls taken into account so that I can access content that was loaded after the page has completed loading?

Yes.

**Comment by avodovnik** [comment]
@ftpguy I hope this answered your questions - do you have any others? If so, feel free to comment and I'll reopen - or open a new issue.
