### ISSUE TITLE
Playwright Specflow Parallel execution

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#1615]
Hi, i am using Playwright with Specflow and Nunit to execute Front End Test. the issue i am having is parallel execution does not seem to work like i expected. it is difficult to find good documentation as its still the new boy on the block
I found a good Video from someone at spec flow here:https://www.youtube.com/watch?v=wZrnBHoRzvg
and the associated Repo: https://github.com/specflowoss/streaming-projects/tree/Playwright

I have implemented my hooks class the same way using specflows inbuilt context injection
https://github.com/SpecFlowOSS/Streaming-Projects/blob/Playwright/CommunityContentSubmissionPage/CommunityContentSubmissionPage.Specs/Hooks/DIConfiguration.cs

The issue i am seeing is after adding [assembly: Parallelizable(ParallelScope.Fixtures)]
tests across other feature will randomly not be able to find the right selector

```
  Message: 
    System.TimeoutException : Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for selector "text=RoutePage Template >> input"
    ============================================================
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

i cant share a lot of my code as it internal private and the website it testing is for work.
is the code example the correct way to implement and launch playwright using the context injection?

**Comment by avodovnik** [comment]
It's very difficult to attempt to help here, without at least a minimum repro/sample project. If you have one, that only covers the basics, without the work-specific code, it would be helpful and would help us get to a solution faster.

**Comment by infinitejest69** [comment]
So i am going to close this issue as i believe its somewhere in my code base 
I made a repo to try and show the issues but it was using old rest sharp, i took a a branch an updated nuget to miscorsoft,playwright and fixed the breaking changes.
both branches work with parallel execution. sorry for the time waste

Examples for future souls who wade in these waters:
[My Example Playwright Repo](https://github.com/infinitejest69/DotNetSpecFlowPlaywright)
