### ISSUE TITLE
[Bug]: Microsoft.Playwright.CLI installs incorrect version of Chromium

### ISSUE THREAD

**Issue by romfir** [microsoft/playwright-dotnet#1638]
### Playwright version

1.13.0 (CLI 1.0.2)

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

dotnet --version: 6.0.100-preview.6.21355.2

### What happened? / Describe the bug

`playwright install` installs Chromium 888113, but `_playwright.Chromium.LaunchAsync()` requires  Chromium 901522

### Code snippet to reproduce your bug

```shell
dotnet tool install --global Microsoft.Playwright.CLI
playwright install 

in C# unit test:
_playwright = await Playwright.CreateAsync().ConfigureAwait(false);

  Browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
  { Timeout = 5000, Headless = _headless })
```

### Relevant log output

```shell
playwright install
Playwright build of chromium v888113 downloaded to C:\Users\romfi\AppData\Local\ms-playwright\chromium-888113
Playwright build of firefox v1271 downloaded to C:\Users\romfi\AppData\Local\ms-playwright\firefox-1271
Playwright build of webkit v1492 downloaded to C:\Users\romfi\AppData\Local\ms-playwright\webkit-1492
Playwright build of ffmpeg v1005 downloaded to C:\Users\romfi\AppData\Local\ms-playwright\ffmpeg-1005

from unit tests:
Microsoft.Playwright.PlaywrightException
Executable doesn't exist at C:\Users\romfi\AppData\Local\ms-playwright\chromium-901522\chrome-win\chrome.exe
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

**Comment by avodovnik** [comment]
This sounds like it's picking up the "wrong" library version. A couple quick questions, to help me diagnose:

- Are you running the command _from_ the project location? 
- Do you also have the node/npm version installed?
- Can you try running `dotnet .\bin\Debug\net5.0\Microsoft.Playwright.dll -- install`? Does that install the correct version?

**Comment by romfir** [comment]
> * Are you running the command _from_ the project location?

No, I was runnig from solution folder, when I run it from project folder it downloaded correct version - `chromium-901522`
> * Do you also have the node/npm version installed?

yes, 16.5.0
> * Can you try running `dotnet .\bin\Debug\net5.0\Microsoft.Playwright.dll -- install`? Does that install the correct version?

dotnet ./bin/Debug/net6.0/Microsoft.Playwright.dll
```
dotnet : Cannot use file stream for [C:\Users\romfi\source\repos\HtmlRaportGenerator\HtmlRaportGenerator.Tests\bin\Debug\net6.0\Microsoft.Playwright.deps.json]: No such file or directory
At line:1 char:1
+ dotnet ./bin/Debug/net6.0/Microsoft.Playwright.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cannot use file...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\romfi\source\repos\HtmlRaportGenerator\HtmlRaportGenerator.Tests\bin\Debug\net6.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Users\romfi\source\repos\HtmlRaportGenerator\HtmlRaportGenerator.Tests\bin\Debug\net6.0\Microsoft.Playwright.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Users\romfi\source\repos\HtmlRaportGenerator\HtmlRaportGenerator.Tests\bin\Debug\net6.0\Microsoft.Playwright.runtimeconfig.json' file and specify th
e appropriate framework.
```

So `playwright install` on Windows must be run from project folder, but on linux it can also be run form solution? I have a github runner that installs playwright and it works ok
![image](https://user-images.githubusercontent.com/33402460/127191541-1b1a225c-0b6e-4654-961d-fc158fb63946.png)

**Comment by avodovnik** [comment]
What I think is happening is, `playwright install` is picking up an _older_ version of the DLL somewhere in your solution folder structure. Have you had a previous version of the NuGet installed there, by any chance? Is there a reference by another project to an older version? 

That will also explain why it's working (as expected) on CI - there's likely no older versions there.

**Comment by romfir** [comment]
In my sln structure there are just 2 projects, blazor wasm app and playwright test app, the older version was installed in the test app previously, but the new (1.13.0) was installed before running `playwright install`

**Comment by avodovnik** [comment]
When you updated the reference, did you clean/rebuilt the project before doing `install`?

**Comment by romfir** [comment]
I thought so, but mb I forgot. Now I manually deleted bin and obj folders, uninstalled CLI tool and removed `ms-playwright` folder, rebuilt and reinstalled CLI and `playwright install` installs correct version `901522`. Thanks for Your help, I'm closing this issue.
