### ISSUE TITLE
[Bug]: playwright CLI run emulate devices script won't work

### ISSUE THREAD

**Issue by kenjfz** [microsoft/playwright-dotnet#1653]
### Playwright version

Version 1.13.0-1626733671000

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

.net 6 preview6

### What happened? / Describe the bug

playwright CLI run Emulate devices script won't work

### Code snippet to reproduce your bug

```shell
cmd$> playwright open --device="iPhone 11" wikipedia.org
```

### Relevant log output

```shell
Device descriptor not found: 'iPhone', available devices are:
...
...
```

**Comment by avodovnik** [comment]
This is an interesting by-design/bug behaviour result of .NET unfortunately, as it strips out the quotes in the arguments entirely.
