### ISSUE TITLE
[Bug]: WaitForSelectorAsync("selector", WaitForSelectorState) not working

### ISSUE THREAD

**Issue by kenjfz** [microsoft/playwright-dotnet#1654]
### Playwright version

Version 1.13.0-1626733671000

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

.net 6 preview6

### What happened? / Describe the bug

Below code won't work:
`await page.WaitForSelectorAsync("#search", WaitForSelectorState.Attached);`
Because the second parameter is set as PageWaitForSelectorOptions.

### Code snippet to reproduce your bug

```shell
...
await page.WaitForSelectorAsync("#search", WaitForSelectorState.Attached);
...
```

### Relevant log output

```shell
parameter 2: unable to transform "Microsoft.Playwright.WaitForSelectorState" as "Microsoft.Playwright.PageWaitForSelectorOptions?"
```

**Comment by avodovnik** [comment]
Yes, this is by design. You should be using

```csharp
await page.WaitForSelectorAsync("#search", new() { State = WaitForSelectorState.Attached });
```

**Comment by kenjfz** [comment]
> Yes, this is by design. You should be using
> 
> ```cs
> await page.WaitForSelectorAsync("#search", new() { State = WaitForSelectorState.Attached });
> ```
> 
> Just to clarify, does your code actually compile? Because it shouldn't, AFAIK.

Your code works! Of course the previous one did't work/compile. I just followed the docs guidelines(https://playwright.dev/dotnet/docs/core-concepts#auto-waiting). Thanks!

**Comment by avodovnik** [comment]
Thanks for pointing that out! I've opened a PR to address that.
