### ISSUE TITLE
[Question]: Playwright, Specflow, Nunit - how to run tests in multiple browsers in parallel 

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#1663]
### Your question

Hey All i am looking for some guidance and suggestions.
I am using a combination of Playwright, Nunit and Specflow. i am creating my playwright instance in a before scenario hook and paralleled running seems ok. i am stuck on how to implement parallel running across multiple browsers.
so i want each test to run 3 times once for each browser. i have a sample repo here that should explain my implementation

[Repo](https://github.com/infinitejest69/DotNetSpecFlowPlaywright)
Is there a Nunit config file that can be added and how do i setup playwright to pass multiple brewers instances

I guess the mix of tech stack it throwing me off to know if its Nunit , playwright or Specflow that deals with running tests multiple times

EDIT: to add more clarification i come from testing selenium where i think the solution to this problem would be to use selenium Grid in a docker container to distribute a test across multiple browsers at once. this is why i started with the question in playwright repo as i thought there might be a way to solve it i am not aware off. like docker containers. Nunit Test Fixtures etc.
still trying to google my way out the problem

**Comment by uchagani** [comment]
@infinitejest69 my guess would be the runner would be responsible for this. See https://docs.specflow.org/projects/specflow/en/latest/Guides/multiplebrowser.html and adapt it for playwright

**Comment by infinitejest69** [comment]
Thanks. My issue is I am not using the specflow+ runner. So I guess it would be down to nunit to run test multiple browsers. But specflow controls the generation of the nunit code. Either way not really Playwright issue.
 If push comes to shove I guess I can set up tests in multiple pipelines and pass the browser in via config file.
