### ISSUE TITLE
[Question]: Setting headless in Visual Studio Test Runner with NUnit base classes

### ISSUE THREAD

**Issue by Swellenator** [microsoft/playwright-dotnet#1666]
### Your question

Using the built in NUnit base classes, I have tests inheriting `PageTest`. How can I flip between headless states in Visual Studio test runner?

I can't seem to set 

```
 BrowserType.LaunchAsync(new BrowserTypeLaunchOptions()
            {
                Headless = false,
                
            }
```
When inheriting `PageTest`. In some of the docco it says to set an environment variable, but that seems to be for using the command line to execute tests.

**Comment by avodovnik** [comment]
At the moment, your best bet is to set the `HEADED` environment variable to `1`. This gets picked up by our [test infrastructure](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright.NUnit/BrowserService.cs#L40).

**Comment by avodovnik** [comment]
Closing this as it seems like it was answered. Feel free to open another issue, if you still have problems doing this.
