### ISSUE TITLE
[Question]: how to use edge 's private mode and not to use it

### ISSUE THREAD

**Issue by interiv** [microsoft/playwright-dotnet#1671]
### Your question

Privacy mode is used by default, so how to set it to not use privacy mode? I didn't find her option, you know how to use it?

**Comment by avodovnik** [comment]
I believe what you're looking for is Persistent Contexts, you can use them by launching it via:

```csharp
await using var browser = await pw.Chromium.LaunchPersistentContextAsync("C:/path/to/profile", new() { Headless = false });
```

**Comment by interiv** [comment]
thanks got it
