### ISSUE TITLE
[internal] Consider merging SourcePosition and TargetPosistion types with `Position`

### ISSUE THREAD

**Issue by avodovnik** [microsoft/playwright-dotnet#1680]
Would it make sense to merge SourcePosition and TargetPosistion types with Position ? At least that's what we did in java

_Originally posted by @yury-s in https://github.com/microsoft/playwright-dotnet/pull/1674#discussion_r687981891_

**Comment by mxschmitt** [comment]
Not relevant anymore, since it would be a breaking change as discussed in the meeting IIRC.
