### ISSUE TITLE
[Feature request]: Scaling Playwright "out" to multiple services/hosts

### ISSUE THREAD

**Issue by Andrei-Sav** [microsoft/playwright-dotnet#1691]
### Your question

How can I run my tests on remote vm or several vm, like we did it with selenium grid? I am using .NET version of playwright.
Now I have selenium grid with 15 windows10 agents (CI - TeamCity). I would like to use it for playwright tests too.

**Comment by avodovnik** [comment]
At the moment, this isn't something we provide.

**Comment by mxschmitt** [comment]
In 1.15 BrowserType.Connect gets added, then you can build your own grid (launchServer via Node.js and Connect() via .NET). See also https://github.com/microsoft/playwright-dotnet/issues/1291 for BrowserType.ConnectOverCDP support.
