### ISSUE TITLE
[Bug]: connect tests are leaking server processes

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-dotnet#1693]
### Playwright version

1.14

### What happened? / Describe the bug

 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
34420 s001  S      0:00.43 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
34495 s001  S      0:00.43 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
34602 s001  S      0:00.45 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
34697 s001  S      0:00.45 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
34847 s001  S      0:00.41 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
34990 s001  S      0:00.42 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
35089 s001  S      0:00.43 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
35183 s001  S      0:00.41 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
35250 s001  S      0:00.42 /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/node /Users/pfeldman/code/playwright-sharp/src/Playwright.Tests/bin/Debug/net5.0/.playwright/node/mac/../../package/lib/cli/cli.js launch-server chromium
35442 s001  S      0:00.45 /Users/pfeldman/code/playwright-sharp/

**Comment by avodovnik** [comment]
This should have been addressed with the roll to 1.15: https://github.com/microsoft/playwright-dotnet/commit/682cf54a83cc025bbcc6bd92d36dfb9bdc30d856#diff-4fde6de6200a1a761d3c6fe0ad8118dbb590117fb667507beb26f468fb110da8R79
