### ISSUE TITLE
[Question]: How to write a long live watching programm.

### ISSUE THREAD

**Issue by cnmade** [microsoft/playwright-dotnet#1695]
### Your question

The purpose is for watching some data change on the target webpage.
for example, i want to write a script to watching the target Stock price changes. if the price change, i can handle the price change , and know the event.
https://finance.yahoo.com/quote/AAPL/

We do not need close the webpage, just let it running .the price change will auto update instantly.

**Comment by avodovnik** [comment]
This isn't really something Playwright is built for. We are focused on web testing, so this scenario is not, nor will it be, supported.

**Comment by cnmade** [comment]
@avodovnik thanks for reply. I just find the way to do it .

a simple for loop save me .
Hope this can help other who need the same purpose.

playwright is good framework to do anything, feel free to use it as well.
