### ISSUE TITLE
[Question]: Is Playwright Test Runner coming to playwright-dotnet?

### ISSUE THREAD

**Issue by ChristianMay21** [microsoft/playwright-dotnet#1716]
### Your question

Hi! I saw the recent release of "Playwright Test"/"Playwright Test Runner" (I've seen it referred to by both of those names), but on the docs page it looks like there's only Javascript documentation.

Will a C# binding for Playwright Test be coming at some point? Sooner or later? Unknown?

Thanks,

Christian

**Comment by ChristianMay21** [comment]
I've been running into some into some issues with NUnit's TestCaseSource method of building tests from lists/collections and was just curious if an alternative would be available on the horizon. I can open a separate issue for that if I can't figure out a good workaround though.

When you say "we do have support for [our custom test runner in .NET]", are you referring to Playwright Test or Microsoft.Playwright.NUnit? In other words, are you saying you currently support the custom test runner in .NET?

**Comment by avodovnik** [comment]
Playwright for .NET is generally not opinionated on the runner is what I'm trying to say :-) , i.e., we won't _not_ work on them, but we do have varying degrees of integration with frameworks on top of them (i.e. NUnit, xUnit, MSTest). 

I believe your issue wrt the `TestCaseSource` was addressed in #1721. As for a custom test runner/framework, we'd need to see a more concrete feature request/scenario for it to be considered.

**Comment by ChristianMay21** [comment]
Ah I understand :) And yes you are correct, my core issue was addressed - thanks so much for all your help and I think we can consider this one closed.
