### ISSUE TITLE
[BUG] Package Microsoft.Playwright.CLI 1.0.2 is not compatible with net50 (.NETFramework,Version=v5.0) / any

### ISSUE THREAD

**Issue by kt-dm** [microsoft/playwright-dotnet#1724]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows 10
- Node.js version: 14.17.0
- Browser: N/A
- Extra: [any specific details about your environment]

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 11.48 GB / 31.69 GB
## Binaries:
 - Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
 - npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

**Describe the bug**

```bash
dotnet tool install --global Microsoft.Playwright.CLI

error NU1202: Package Microsoft.Playwright.CLI 1.0.2 is not compatible with net50 (.NETFramework,Version=v5.0) / any. Package Microsoft.Playwright.CLI 1.0.2 supports:
error NU1202:   - net5.0 (.NETCoreApp,Version=v5.0) / any
error NU1202:   - netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
```

Hi team, this is a installation related issue. I'm following the documents to install the CLI so that I can get started with a test project found [here](https://playwright.dev/dotnet/docs/intro).. and am hitting a snag with the CLI installer.

I've modified my project to `netcoreapp2.1` and can get it to install, but when continue with adding the 1.14.1 Nuget package to my project:

```bash
dotnet add package Microsoft.Playwright
dotnet build
playwright install

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 75

```

Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0 is listed as an installed dependency of my project so unsure what's going on here.

Ideally I want to be using 3.1 as that's the LTS... but .net50 doesn't seem to work because it's selecting the framework sdk over the coreapp sdk which is odd because I'm not sure how to select the coreapp5.0 from the Target Framework dropdown in Visual Studio.

Any ideas?

**Comment by Jojoshua** [comment]
> ```shell
> playwright install
> 
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load the specified file.
>    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
>    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
>    --- End of inner exception stack trace ---
>    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
>    at System.Reflection.RuntimeAssembly.GetExportedTypes()
>    at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 75
> ```

Same error as my 4.8 install attempt (https://github.com/microsoft/playwright-dotnet/issues/1694)

**Comment by ChristianMay21** [comment]
I had the same issue when installing on a project using .net core 2.1 - the 'fix' for me was changing the TargetFramework in my csproj file to "<TargetFramework>net5.0</TargetFramework>", which seems almost like the opposite issue that you were having. 

Honestly the single most discouraging bug I hit with Playwright, and I've seen some other issues open with similar errors so I know that we're not alone.

**Comment by avodovnik** [comment]
Sorry for the delay.

(1) we know about #1694 but that's a separate issue and should get addressed soon

(2) I'm trying to wrap my head around this particular issue. There's a couple things that are confusing, so let's take it step by step, if you're able to help, so we can figure out what's going on.

Can you run:

```powershell
dotnet --version

# and

dotnet --list-sdks
```

Just to be sure, is there any `global.json` file in your project directory or somewhere in the path above?

**Comment by avodovnik** [comment]
This report has not seen a reply from the original author in a while, so I'm closing it.

In the original error message, it also references `net50 (.NETFramework,Version=v5.0)`, which implies a "weird" .NET Framework version (i.e. **not** .NET Core 5.0) which leads me to believe this is a problem in the specific configuration. 

If you have additional information you can provide, and/or a reproducible example, please feel free to open a new issue.

**Comment by kt-dm** [comment]
```bash
dotnet --version
5.0.303
```

```bash
 dotnet --list-sdks
2.1.818 [C:\Program Files\dotnet\sdk]
3.1.412 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
```
