### ISSUE TITLE
[Feature]: complier native

### ISSUE THREAD

**Issue by nguyentuan3691** [microsoft/playwright-dotnet#1727]
### Playwright version

1.14.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### What happened? / Describe the bug

Can't run success browser when complier native.
Exception when control element

**Comment by avodovnik** [comment]
Please provide more information about what it is you're trying to do, what exception you get, and/or an exception stack trace.

**Comment by nguyentuan3691** [comment]
> Please provide more information about what it is you're trying to do, what exception you get, and/or an exception stack trace.

Hello. Thanks for fast reply

This is full my code 
`var playwright = Playwright.CreateAsync().Result;
            var browser = playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false }).Result;
            var context = browser.NewContextAsync().Result;
            var page = context.NewPageAsync().Result;
            page.GotoAsync("https://www.google.com/").Wait();
            page.WaitForSelectorAsync("//input[@maxlength='2048']").Wait();
            page.Keyboard.TypeAsync("playwright").Wait();
            page.Keyboard.PressAsync("Enter");
            Console.ReadLine();`

I build on step this link https://secanablog.wordpress.com/2018/06/08/compile-a-net-core-app-to-a-single-native-binary/
Build success
When run then show exception
Unhandled Exception: System.AggregateException: One or more errors occurred. (The path is empty. Parameter name: path)
 ---> System.ArgumentException: The path is empty. Parameter name: path
   at System.IO.Path.GetFullPath(String) + 0xe0
   at System.IO.FileInfo..ctor(String, String, String, Boolean) + 0x46
   at Microsoft.Playwright.Helpers.Paths.GetExecutablePath() + 0xb7
   at Microsoft.Playwright.Transport.Connection.GetProcess() + 0x2d
   at Microsoft.Playwright.Transport.Connection..ctor() + 0x14b
   at Microsoft.Playwright.Playwright.<CreateAsync>d__0.MoveNext() + 0x4c
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean) + 0x74
   at NativeConsoleApp.Program.Main(String[]) + 0x23
   at NativeConsoleApp!<BaseAddress>+0x522ce5

Thanks for read

**Comment by avodovnik** [comment]
Playwright doesn't support running in a single native binary. 

As a workaround, you might be able to get away with copying the `.playwright` folder next to the binary, but as I've said, this is **unsupported**.
