### ISSUE TITLE
[Question]: Connection closed

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright-dotnet#1728]
### Your question

Hello! I am using .net core with mstest I want to add generic function to create the page to reuse in multiple pages

Sample generic function
```
        public async Task<IPage> GetPageAsync()
        {
            using var playwright = await Playwright.CreateAsync();
            _browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false });
            var page = await _browser.NewPageAsync();
            return page;
        }
```

and I am trying to use like here

```
       [TestMethod]
        [DataRow("standard_user", "secret_sauce")]
        public async Task Login_WithValidUser_NavigatesToProductPageAsync(string user, string password)
        {
            //Arrange
            var page = await GetPageAsync();
            LoginPage loginTests = new LoginPage(page);
```

but I got an exception

Test method sauceDemo.Pages.LoginTests.Login_WithValidUser_NavigatesToProductPageAsync threw exception: 
Microsoft.Playwright.PlaywrightException: Connection closed (Connection disposed) when I tried to access any element in the page

**Comment by avodovnik** [comment]
That's not going to work, as you're disposing `playwright` after leaving the `GetPageAsync` method. 

We haven't provided the docs for it yet, but I'd strongly recommend using the [Playwright.MSTest](https://www.nuget.org/packages/Microsoft.Playwright.MsTest) package. Here's an example of how to use it: https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright.TestingHarnessTest/SimpleSmokeTests.MSTest.cs

If you ~want~ need to roll your own, you can follow our pattern https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright.MSTest/PlaywrightTest.cs#L56

**Comment by apis3445** [comment]
Do you have a sample with the POM? with the samples is not clear for me how setup the test with different browsers, and is different to the POM sample

**Comment by pavelfeldman** [comment]
https://playwright.dev/dotnet/docs/test-runners#creating-an-nunit-project
