### ISSUE TITLE
[Question]: Why couldn't some methods be used in nUnit's OneTimeSetup?

### ISSUE THREAD

**Issue by jevgenijusmarinuskinas** [microsoft/playwright-dotnet#1729]
### Your question

Hello,

I have a question. Why is it so that I could not use some methods, for example, `Context.NewPageAsync()` in a method, which is marked with `[OneTimeSetup]` attribute in nUnit? In this case, I am getting a Null reference exception. In case of usual `[SetUp]` there is no such issue. 

Is it a bug, or by design? If it is the latter, how then should I correctly setup objects which should be executed before all tests?

Thank you.

**Comment by Ducatel** [comment]
@jevgenijusmarinuskinas did you solve this ? I face the same issue.
