### ISSUE TITLE
[BUG] ResponseEnd value of 0ms

### ISSUE THREAD

**Issue by hakito** [microsoft/playwright-dotnet#1731]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: using .net nuget package
- Browser: Chromium
- Extra: .net environment

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```csharp
browserContext.Response += (sender, response) =>

{
    if (response == null || response.Status < 400)
        return;

    var request = response.Request;

    Debug.WriteLine($"HTTP {response.Status} after {request.Timing.ResponseEnd}ms for {request.Url}");
};
```

**Describe the bug**

In this case I get always a ResponseEnd time of 0ms (although the ResponseStart is greater than zero). The [documentation ](https://github.com/microsoft/playwright/blob/master/docs/src/api/class-request.md#method-requesttiming)describes it as a relative value to StartTime. So I'd expect a value of -1 here in case the response value is not yet available or a value greater than ResponseStart.

**Comment by avodovnik** [comment]
You should never use `.Result` in your code unless you're absolutely sure you know what's going on.

Can you try changing your code, to do:

```csharp
browserContext.RequestFinished += async (sender, request) =>
{
    var response = await request.ResponseAsync();
    if (response == null || response.Status < 400 || request.Timing.ResponseEnd < 100)
        return;

    Debug.WriteLine($"HTTP {response.Status} after {request.Timing.ResponseEnd}ms for {request.Url}");
};
```

IF you're still seeing the deadlock at that point, we need to see a bit more info on what you're doing around it.

**Comment by hakito** [comment]
Yes this works.
