### ISSUE TITLE
[Feature]: Chrome Devtools Protocol

### ISSUE THREAD

**Issue by mikesisti** [microsoft/playwright-dotnet#1735]
### Feature request

Hi Microsoft- are there plans to add this feature in the future?

https://playwright.dev/dotnet/docs/api/class-browsercontext

Thanks in advance

**Comment by avodovnik** [comment]
Do you mean .NET support for https://playwright.dev/docs/api/class-cdpsession ?

**Comment by avodovnik** [comment]
Looks like a duplicate of #1291, closing in favour of that one. 

If this isn't a duplicate, please provide more clarity on what the request is for, and we'll be happy to revisit and/or reopen.
