### ISSUE TITLE
[Question]: How can I observe network activity?

### ISSUE THREAD

**Issue by hakito** [microsoft/playwright-dotnet#1741]
### Your question

My intention is to write a of network activity observer class that fires events when the activity switches between active and idle.

Request.ResponseAsync is documented to return the corresponding Response for a Request or null in case of an error. But it seems it never returns when navigation request occurs while other requests are still running.

Guess the following code: 
```csharp
browserContext.RequestFinished += async (sender, request) =>
{
    ++requests;
    var response = await request.ResponseAsync();
    --requests;
};
```

I'd expect the request counter to count down to zero after all requests have finished. To make it work correctly I have to cancel awaiting previous requests in case of a navigation request somehow like this:

```csharp
var observation = new TaskCompletionSource();

browserContext.RequestFinished += async (sender, request) =>
{
    ++requests;
    if (request.IsNavigationRequest)
    {
          observation.Cancel();
          observation = new CancellationTokenSource();
    }
    var response = await request.ResponseAsync().ContinueWith(_ => {}, observation.Token);
    --requests;
};
```

Is there a better way to do that? Shouldn't ResponseAsync at least return null for the abandoned requests?

**Comment by pavelfeldman** [comment]
https://playwright.dev/dotnet/docs/network#network-events would be a good start.

**Comment by hakito** [comment]
The thing I am asking for was: What is the proper way to await ALL responses of requests? Playwright never returns from the await when a navigation request comes in between.

**Comment by mxschmitt** [comment]
It's a web limitation that you can't wait until all requests are complete. What are **all** requests? What if the web-application makes a request every 100ms? Or if they are used in combination with polling and slow by design?

Usually you wait for text or elements to appear on the screen which makes them less flaky compared to waiting for requests to complete.

**Comment by hakito** [comment]
Sorry for replying so late.

I know that there might come time triggered requests at any time. But what I need is just the information: Are there pending requests or not? (Is the browser downloading something or not?)

In my current implementation this is only possible with a workaround as some requests are never completed.
