### ISSUE TITLE
[Question]: Not able to launch Firebox error because of Microsoft.Playwright.PlaywrightException: 'SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by anunay1** [microsoft/playwright-dotnet#1742]
### Your question

I am trying to launch Firefox but receive the error in the subject line. how to I use the option IgnoreHTTPSErrors = true. 

if I try to use, I get the below error: 

![image](https://user-images.githubusercontent.com/7989610/133264476-9e1bead9-637a-4f87-9ac1-a6c1b8a8bf1c.png)

**Comment by mxschmitt** [comment]
IgnoreHTTPSErrors is a context option, you can pass it in NewPageAsync which internally creates a context. See here: https://playwright.dev/dotnet/docs/next/api/class-browser#browser-new-context-option-ignore-https-errors

**Comment by anunay1** [comment]
Thanks @mxschmitt 
Then I get a different set of error: 

![image](https://user-images.githubusercontent.com/7989610/133390281-ef4a0fe7-ba87-43ab-9e19-8f0833c957a6.png)

**Comment by mxschmitt** [comment]
You need to call context.NewPageAsync() to get the page. Currently you only have a context.

See here: https://playwright.dev/dotnet/docs/core-concepts/#browser-contexts
