### ISSUE TITLE
[Question]: Is there a way to attach to a existing browser

### ISSUE THREAD

**Issue by anunay1** [microsoft/playwright-dotnet#1746]
### Your question

Hi, 

I have a scenario to automate wherein I have a word document and then I click on wikipedia, I have automated the opening of the word document and want to use playwright to automated the wikipedia part. Is there a way to attach a existing browser?

**Comment by avodovnik** [comment]
Not at the moment, but it's something we're working on porting over to .NET.

Are you specifically looking for CDP or WebSocket connections?

**Comment by anunay1** [comment]
Yes

**Comment by avodovnik** [comment]
In that case, this is likely a duplicate of #1291
