### ISSUE TITLE
[Bug]: Could not load file or assembly Microsoft.Bcl.AsyncInterface

### ISSUE THREAD

**Issue by mrwensveen** [microsoft/playwright-dotnet#1747]
### Playwright version

1.14.1

### Operating system

Windows

### Other information

This is a duplicate of bug #1531 which was closed by the reporter on the same day it was opened. There was no mention of a resolution and multiple people still encounter this issue including me.

### What happened? / Describe the bug

When running the playwright install command, I get an error message complaining about Microsoft.Bcl.AsyncInterfaces not being installed.

### Code snippet to reproduce your bug

```shell
playwright install
```

### Relevant log output

```shell
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 75
```

**Comment by avodovnik** [comment]
This sounds like the same issue that was fixed with https://github.com/microsoft/playwright-dotnet/pull/1740. The fix should be available in 1.15.

**Comment by avodovnik** [comment]
Also, please feel free to look at https://github.com/microsoft/playwright-dotnet/issues/1694 for workaround suggestions.

**Comment by mrwensveen** [comment]
Thanks @avodovnik, that looks like the same issue.
