### ISSUE TITLE
[Bug]: Provide HTTP Response Code on net::ERR_HTTP_RESPONSE_CODE_FAILURE.

### ISSUE THREAD

**Issue by corygehr** [microsoft/playwright-dotnet#1751]
### Feature request

Per the title, I'd like to be able to understand specifically which HTTP status code was thrown when Chromium returns this error message. It looks like this could represent anything from HTTP 400-599 and there's a wide spectrum of possibilities, and legitimate test cases to look for - especially if trying to determine whether the issue is client or server error.

Right now, it just returns a `PlaywrightException` with the message, and that's about it.

**Comment by pavelfeldman** [comment]
What's your use case? We do provide the status code when there is one. But sometimes there is a lower level connection error.

**Comment by corygehr** [comment]
I should, but there are certain URLs which are returning HTTP 500 but somehow, they're not getting detected as such by Playwright (v1.14.1). I will send you an example URL offline which repros this on Windows - it's a URL with an actual vuln so I don't want to share publicly :)

**Comment by pavelfeldman** [comment]
This prints `500` for me:

```cs
using Microsoft.Playwright;
using System;
using System.Threading.Tasks;

class Program
{
    public static async Task Main()
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
        var response = await page.GotoAsync("http://httpstat.us/500");
        Console.WriteLine(response.Status);
    }
}
```

**Comment by corygehr** [comment]
Did you get the same `PlaywrightException` with the URL I sent you privately? Many URLs handle the HTTP 500 correctly. I'm not sure why the one I shared does not, despite that Chromium reports it as an HTTP 500.

**Comment by pavelfeldman** [comment]
Yes, I get the same with your long URL. HTTP is well-specced, 500 is 500.

**Comment by kudgit** [comment]
I observe the following related/same/inconsistent/not_understood_by_me behavior:

Running an **xUnit.net** Test with a **Playwright "var response = page.GotoAsync(orderNewUrl)"**.
Where orderNewUrl does not exist (http status 404).

# **Observation Summary**

Case 1: If I run the test **headless in Visual Studio 2019** (Community)
- **No Exception is thrown**
- I thus reach the next statement **Assert.Equal(200, response.Status);** which will fail as expected
-  This is the **expected and specified behavior**: https://playwright.dev/docs/api/class-page#page-goto
   - "The method will not throw an error when any valid HTTP status code is returned by the remote server, including 404 ..."

Case 2: If I run the test **headed in **Visual Studio 2019** (Community)** 
Case 3: Or if I run the test **headed in (git) bash with 'dotnet test'**
Case 4: Or if I run the test **headless in (git) bash with 'dotnet test'**
- An **Exception is thrown** and I thus do never reach the next statement **Assert.Equal(200, response.Status);**
- **This is not the expected and specified behavior**: https://playwright.dev/docs/api/class-page#page-goto

# **Observation Details**
(Test code not provided / I guess it is not relevant)

## Case 1 **Headless** test run in **Visual Studio 2019** (Community)
- **No Exception and Assert.Equal(200, response.Status) fails** 
- Visual Studio Test Explorer Output:

```
Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId
   Source: CreateNewOrder_Should_Succeed.cs line 21
   Duration: 2.6 sec

  Message: 
Assert.Equal() Failure
Expected: 200
Actual:   404

  Stack Trace: 
CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId() line 39
--- End of stack trace from previous location ---

  Standard Output: 
headed: False
slowMo: 1000
```

## Case 2 **Headed** test run with **Visual Studio 2019** (Community)
- Exception and thus Assert.Equal(200, response.Status) is never reached
- Visual Studio Test Explorer Output:

```
Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId
   Source: CreateNewOrder_Should_Succeed.cs line 21
   Duration: 2.3 sec

  Message: 
Microsoft.Playwright.PlaywrightException : net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://localhost:5001/orders/new
=========================== logs ===========================
navigating to "https://localhost:5001/orders/new", waiting until "load"
============================================================

  Stack Trace: 
Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
Frame.GotoAsync(String url, FrameGotoOptions options)
CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId() line 38
--- End of stack trace from previous location ---

  Standard Output: 
headed: True
slowMo: 1000
```

## Case 3 **Headless** test run in bash with '**dotnet test**' 
- Exception and thus Assert.Equal(200, response.Status) is never reached
- (git) bash output:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:06.73]     Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId [FAIL]
  Failed Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId [6 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Protocol error (Page.navigate): Cannot navigate to invalid URL
=========================== logs ===========================
navigating to "/orders/new", waiting until "load"
============================================================
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)
   at Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId() in D:\rebus\Services\CustomerOrders\Tests\Acceptance\Orders\CreateNewOrder_Should_Succeed.cs:line 38
--- End of stack trace from previous location ---
  Standard Output Messages:
 headed: False
 slowMo: 0
```

## Case 4 **Headed** test run in bash with '**dotnet test**'
- Exception and thus Assert.Equal(200, response.Status) is never reached
- (git) bash output:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:05.59]     Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId [FAIL]
  Failed Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId [4 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Protocol error (Page.navigate): Cannot navigate to invalid URL
=========================== logs ===========================
navigating to "/orders/new", waiting until "load"
============================================================
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)
   at Dkzhch.Rebus.Services.CustomerOrdersMsc.Tests.Acceptance.Orders.CreateNewOrder_Should_Succeed.Should_HaveOrderNotesAndOrderId() in D:\rebus\Services\CustomerOrders\Tests\Acceptance\Orders\CreateNewOrder_Should_Succeed.cs:line 38
--- End of stack trace from previous location ---
  Standard Output Messages:
 headed: True
 slowMo: 0
```

**Comment by mxschmitt** [comment]
Closing for now since the issue seems stale and we need a repro to act on this.
