### ISSUE TITLE
[BUG] : Timeout exception in WaitForSelectorAsync() when timeout is specified

### ISSUE THREAD

**Issue by vivekvasu** [microsoft/playwright-dotnet#1757]
**Context:**
- Playwright Version: [V1.14.1]
- Operating System: [Windows]
- Node.js version: [v14.16.1]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

```c#
protected async Task<IElementHandle> GetElementAsync()
        {
            return await Frame.WaitForSelectorAsync(Selector, new FrameWaitForSelectorOptions { State = WaitForSelectorState.Attached });
        }

        protected async Task<IElementHandle> GetElementWithoutWaitAsync()
        {
            return await Frame.WaitForSelectorAsync(Selector, new FrameWaitForSelectorOptions { State = WaitForSelectorState.Attached, Timeout = 2 });
        }
```

**Describe the bug**
GetElementAsync() method is returning the element whereas the GetElementWithoutWaitAsync() with a timeout is returning Timeout exception eventhough the element is present in page.

**Comment by valyagolev** [comment]
very similar situation for me – 

```
1) tests/register_and_confirm_and_test.spec.js:11:1 › basic test =================================

    Timeout of 30000ms exceeded.

    Pending operations:
      - page.waitForSelector at tests/register_and_confirm_and_test.spec.js:96:33

    page.waitForSelector: Target closed
    =========================== logs ===========================
    waiting for selector "text=..." to be visible
    ============================================================

      94 |   console.log("waiting for the confirmation of the email...");
      95 |   page1.setDefaultTimeout(240000);
    > 96 |   const emailLink = await page1.waitForSelector(
         |                                 ^
      97 |     "text=...",
      98 |     { timeout: 240000 }
      99 |   );
```

**Comment by pavelfeldman** [comment]
These use cases seem to be different. In the first case, 2 milliseconds is too short. In the second case, email link is not found on the page.

**Comment by valyagolev** [comment]
it's not found because it only appears after a few minutes. should i open a new bug?

**Comment by vivekvasu** [comment]
> These use cases seem to be different. In the first case, 2 milliseconds is too short. In the second case, email link is not found on the page.

I tried debugging it. Its throwing exception even the element is present.
