### ISSUE TITLE
[Bug]: Call to ContentAsync deadlocks and won't return.

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright-dotnet#1759]
### Playwright version

1.14.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Win 10: 10.0.19043 Build 19043 
VS 2019: Community 2019 Version 16.10.2 
Code: .Net 5.0 C# (5.0.20.56312)
Chrome is up to date -- Version 94.0.4606.54 (Official Build) (64-bit)

### What happened? / Describe the bug

Seems like the code is running into a deadlock.   Having just spun up Playwright, registered a callback for the PageLoad event,  navigating to a page, calling ContentAsync from the PageLoad callback function it appears the code is deadlocks and won't return.

Expected no deadlock and the respective page source returned. 

Would think you have all what is needed, if any more info is needed, will provide it.

### Code snippet to reproduce your bug

```shell
//
//  Init code
//
...
this.browser = await browserInfo.browserType.LaunchAsync(browserOptions);

this.Page = await this.context.NewPageAsync();
this.Page.Load += this.Page_Load;
await this.Page.GotoAsync( WebSiteUrl );
return ;  // construction/init finished...
} 

//
//  PageLoad callback handler
//
private void Page_Load( object sender, IPage e )
{
    var pageSource = Utils.GetPageContent(e);
}

//
//   Utility method for page source...
//
public static string GetPageContent( IPage page) 
{
    return Task.Run<string>(async() =>
    {
        try
        {
            return await page.ContentAsync(); // never returns from here...
        }
        catch(Exception ex)
        {
            Console.WriteLine( $"{ex.Message}" );
            return null;
        }
   }).Result;         
}
```

### Relevant log output

```shell
No log to speak of, just appears a deadlock will occur and never returns once.
```

**Comment by avodovnik** [comment]
This is expected - you're mixing `async` code with a `.Result`, which is *never* a good idea. In this case, when the event is triggered, on the main thread, it also blocks that same thread and never yields, hence causing a deadlock. I suggest you redo your logic so that it's all proper async.

Is something like this not an option?

```csharp
            await Page.GotoAsync(WebSiteUrl);
            await Page.WaitForLoadStateAsync();
            // do you asserts here
```

**Comment by ZooDoo4U** [comment]
Thanks @avodovnik, interesting this is the first time running into an issue doing this.   Honestly, the only reason i've been doing this was trying to be lazy and avoid needing to put await all over my code and wanted various utility methods, so the subtle allure sent me down the wrong path.   Just read a number of articles saying what i'm doing is bad...  Just wish the pages on the web where i found doing this made comments "DON"T DO THIS".   

Again Thanks for the help :)
