### ISSUE TITLE
[Bug]: Powershell-Script not working

### ISSUE THREAD

**Issue by greuelpirat** [microsoft/playwright-dotnet#1764]
### Playwright version

1.15

### Operating system

Windows

### What happened? / Describe the bug

Playwright can not be started via powershell anymore. Following error comes up

```
error: unknown option '-File'
```

It looks like this issue was introduced with #1653

### Code snippet to reproduce your bug

```shell
powershell -File playwright.ps1 open https://google.com
```

### Relevant log output

```shell
[11:27:28] olli@ZOTAC:net462: powershell -File playwright.ps1 open https://google.com

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\Users\olli\dev\SuxxessoProjects\ToolSuite\SapUtil\bin\Debug\net462/Microsoft.Playwright.dll
error: unknown option '-File'
0


[11:27:45] olli@ZOTAC:net462:
```

**Comment by pavelfeldman** [comment]
This should be fixed on latest Playwright.
