### ISSUE TITLE
[Bug]: Microsoft.Playwright.Program.Main arguments broken.

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-dotnet#1765]
### Playwright version

1.15

### Other information

Dotnet 5.0
All OS

### What happened? / Describe the bug

(#1655) fix breaks the from code program arguments like install:
Microsoft.Playwright.Program.Main(new string[] {"install" });

https://github.com/microsoft/playwright-dotnet/commit/98e6bf3d1f66933f97a18412edc277249709e05d

The passed args are overwritten with line 44:
`args = Environment.GetCommandLineArgs();`

Perhaps something like this to give have both options

`string lineArguments = null;`
`if (args.Length > 0)`
`  {`
`    lineArguments = string.Join(" ", args);`
`  }`
`  else`
`  {`
`    args = Environment.GetCommandLineArgs();`
`    lineArguments = Environment.CommandLine.Replace(args[0], string.Empty);`
`  }`

### Code snippet to reproduce your bug

```shell
Microsoft.Playwright.Program.Main(new string[] {"install" });
```

### Relevant log output

```shell
Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  install-deps [browser...]              install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
```

**Comment by pavelfeldman** [comment]
This should be fixed in the latest Playwright and the latest tool.
