### ISSUE TITLE
[Question]: How to change element background/ border or highlighting on page?

### ISSUE THREAD

**Issue by maithanhtan** [microsoft/playwright-dotnet#1769]
### Your question

Hi,
I am using Playwright .NET to automation my website checking.
Is there anyway we can highlight the element or change element background/ border to indicate the element is not passed my test case in the website?

Thanks you

**Comment by kababoom** [comment]
You could highlight it yourself, for example...

`await element.EvaluateAsync<string>("e => e.style.outline='red solid 2px'")`

**Comment by maithanhtan** [comment]
Thank you so much @kababoom . I can do it with your code now
