### ISSUE TITLE
[Bug]: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Ve rsion=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

### ISSUE THREAD

**Issue by srigumm** [microsoft/playwright-dotnet#1771]
### Playwright version

1.15.1

### Operating system

Windows

### Other information

netcoreapp3.1

### What happened? / Describe the bug

Though this issue has been fixed with the below PR, I am still facing this issue with v1.15.1 release
https://github.com/microsoft/playwright-dotnet/pull/1740

Steps to repro:

dotnet new console
dotnet build
dotnet tool install --global Microsoft.Playwright.CLI
playwright install

**targetFramework -- netcoreapp3.1
Output:

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Ve
rsion=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at System.Reflection.RuntimeAssembly.GetExportedTypes()

### Code snippet to reproduce your bug

```shell
dotnet new console
dotnet build
dotnet tool install --global Microsoft.Playwright.CLI
playwright install
```

### Relevant log output

```shell
PS D:\MyFolder> playwright install
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Ve
rsion=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 75
```

**Comment by Jojoshua** [comment]
I thought this was going to be fixed as well but it was reverted by @pavelfeldman just before release without explanation.

**Comment by pavelfeldman** [comment]
The fix was bad, could you try the following?

```bash
dotnet new console
dotnet add package Microsoft.Playwright
dotnet build
bin\Debug\netcoreapp3.1\playwright.ps1 install
```

And let me know if it worked. I.e. don't use the tool, use the ps1 script instead.

**Comment by pavelfeldman** [comment]
Ok, this should now work with the latest playwright tool.
