### ISSUE TITLE
[Bug]: IBrowserType does not have ConnectAsync method

### ISSUE THREAD

**Issue by dvygolov** [microsoft/playwright-dotnet#1783]
### Playwright version

1.15.4

### Operating system

Windows

### What happened? / Describe the bug

Guys, in the BrowserType class you have a method for connecting to an existing browser instance:
`public async Task<IBrowser> ConnectAsync`
but I can't use it, cause the only thing I can get is the IBrowserType interface using:
```
            using var playwright = await Playwright.CreateAsync();
            var chromium = playwright.Chromium;
```
And the IBrowserType interface doesn't have this method. Is it a bug?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/986
