### ISSUE TITLE
[Feature]: Infrastructure to support use of BrowserStack Automate

### ISSUE THREAD

**Issue by martincostello** [microsoft/playwright-dotnet#1789]
### Feature request

BrowserStack have published [information](https://www.browserstack.com/docs/automate/playwright) about how it would be possible to use Playwright with their Automate service and [sample code](https://github.com/browserstack/playwright-browserstack/blob/761b35bf79d79ddbfdf518fa6969b409bc42a941/google_search.js) for doing so. However, this is all using playwright natively in node.js, rather than using the .NET bindings.

Looking at the sample code, using BrowserStack and Playwright together appears to depend on the ability to be able to tell playwright to use a [specific server endpoint](https://github.com/browserstack/playwright-browserstack/blob/761b35bf79d79ddbfdf518fa6969b409bc42a941/google_search.js#L20).

However, the code today has a number issues with using this from .NET as-is:

1. There is no way to create an `IPlaywright` with a custom connection (without reimplementing lots of code oneself) ([code](https://github.com/microsoft/playwright-dotnet/blob/ec7c1ebf93bddea4f621c2d9d069fe8d85440c68/src/Playwright/Playwright.cs#L42)).
2. The command run is always `run-driver` ([code](https://github.com/microsoft/playwright-dotnet/blob/ec7c1ebf93bddea4f621c2d9d069fe8d85440c68/src/Playwright/Transport/StdIOTransport.cs#L45)) and there is no option to proxy to an external service (i.e. not just run a local server).

While Playwright doesn't need to be inherently aware of the BrowserStack product itself, especially as it isn't free, appropriately extensibility to allow it to be plumbed in relatively easily from user code (i.e. passing in the `wsEndpoint` endpoint through to Playwright) would allow applications currently using other .NET browser testing technologies (e.g. Selenium) with BrowserStack to switch to using Playwright's .NET libraries to test browser versions they cannot otherwise test locally.

**Comment by mxschmitt** [comment]
It seems like we can fold it into https://github.com/microsoft/playwright-dotnet/issues/986 and create if required a separate issue for our nunit integration to support connect.

**Comment by mxschmitt** [comment]
Folding into #986

**Comment by martincostello** [comment]
For anyone who comes across this, I got Playwright working with BrowserStack Automate with the changes in [v1.18.0](https://github.com/microsoft/playwright-dotnet/releases/tag/v1.18.0) using the code [here](https://github.com/martincostello/dotnet-playwright-tests/blob/648d0f9ad0235a952fa0fc935ff038b1a833f30b/PlaywrightTests/BrowserFixture.cs#L135-L189).
