### ISSUE TITLE
[Feature]: Add rollForward to cli csproj

### ISSUE THREAD

**Issue by vchirikov** [microsoft/playwright-dotnet#1791]
### Feature request

Hi, I want to run `playwright` cli on docker image with 6.0.0-rc.2, but it fails with:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0-rc.2.21480.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK
```

The cli uses 5.0 and 3.1 TFMs and I think we can use rollforward to mitigate issues with next versions.

docs:
https://docs.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior
https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#rollforward

I'll make PR for that.

**Comment by mxschmitt** [comment]
Merging into https://github.com/microsoft/playwright-dotnet/issues/1668
