### ISSUE TITLE
Executable doesn't exist 

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1793]
### Your question

I can't execute playwright install. How can I use code to download automatically?

Microsoft.Playwright.PlaywrightException:“Executable doesn't exist at C:\Users\bin\AppData\Local\ms-playwright\chromium-920619\chrome-win\chrome.exe
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     playwright install                                                  ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝”

**Comment by bbhxwl** [comment]
C:\Users\bin>dotnet tool install  Microsoft.Playwright.CLI
找不到清单文件。
要获取已搜索的位置列表，请在工具名称之前指定 "-d" 选项。
如果你打算安装全局工具，请在命令中添加 `--global`。
如果你想要创建一个清单，请使用 `dotnet new tool-manifest`，通常位于存储库的根目录中。

C:\Users\bin>

**Comment by bbhxwl** [comment]
H:\project\ConsoleApp2\ConsoleApp2>dotnet tool install --global Microsoft.Playwright.CLI
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error : 未能从远程源“https://nuget.pkg.github.com/bbhxwl/download/microsoft.playwright.cli/index.json”检索有关“microsoft.playwright.cli”的信息。 [C:\Users\bin\AppData\Local\Temp\aupxekea.414\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\bin\AppData\Local\Temp\aupxekea.414\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\Users\bin\AppData\Local\Temp\aupxekea.414\restore.csproj]
无法还原工具包。
工具“microsoft.playwright.cli”安装失败。此故障可能由以下原因导致:

* 你尝试安装预览版，但未使用 --version 选项来指定该版本。
* 已找到具有此名称的包，但是它不是 .NET 工具。
* 无法访问所需的 NuGet 源，这可能是由于 Internet 连接问题导致。
* 工具名称输入错误。

有关更多原因(包括强制包命名)，请访问 https://aka.ms/failure-installing-tool

H:\project\ConsoleApp2\ConsoleApp2>

**Comment by fr4gles** [comment]
> From code you can try the following
> 
> `Microsoft.Playwright.Program.Main(new string[] {"install" });`

Or you can prepare/publish offline package with already downloaded browsers with following steps: https://github.com/microsoft/playwright-dotnet/issues/1788#issuecomment-937524114

**Comment by mxschmitt** [comment]
Downloading the Playwright CLI as documented [here](https://playwright.dev/dotnet/docs/intro) and executing `playwright install` should fix it.

**Comment by 304NotModified** [comment]
related https://github.com/microsoft/playwright-dotnet/issues/2239
