### ISSUE TITLE
[Bug]: WebKit jump will never enter the following code.

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1794]
### Playwright version

1.2.0

### Operating system

Windows

### What browsers are you seeing the problem on?

WebKit

### Other information

Most of the following code will not enter. Chrome and Firefox are fine.

```c#
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });


 static   void Main(string[] args)
        {
            Task.Run(async()=> {
                using var playwright = await Playwright.CreateAsync();
                var browser = await playwright.Webkit.LaunchAsync(new BrowserTypeLaunchOptions() { Headless=false });
                var page = await browser.NewPageAsync();
                await page.GotoAsync("https://playwright.dev/dotnet");
                await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
            });
          
            Console.ReadLine();
        }
```
### What happened? / Describe the bug

Most of the following code will not enter. Chrome and Firefox are fine.

await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });

**Comment by bbhxwl** [comment]
> What operating system are you using.
> 
> We have had some bugs with webkit screenshots in the past. Can you try the latest version of playwright, v1.15? Thanks!
I sent the wrong version yesterday. I've been using the latest version.


![image](https://user-images.githubusercontent.com/26525599/138008751-2a02abe3-c54d-4e21-8986-d5d1c67a8e2e.png)

**Comment by mxschmitt** [comment]
Sorry for the late response. I'm closing it for now since it seems stale - please open a new issue if you still encounter any issues with our latest release. Thanks!
