### ISSUE TITLE
[Question]: Playwright install must have a project to install?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1795]
### Your question

If I finish developing the software and want to put it on the server, do I have to create a new project? Then install? How to install offline?

**Comment by fr4gles** [comment]
This would be helpful: https://github.com/microsoft/playwright-dotnet/issues/1788#issuecomment-937524114

**Comment by bbhxwl** [comment]
> This would be helpful: [#1788 (comment)](https://github.com/microsoft/playwright-dotnet/issues/1788#issuecomment-937524114)

How can I judge that I will not reinstall after I have installed it?

**Comment by bbhxwl** [comment]
> We don't support an offline installation. Basically you need to install the browsers via the dotnet tool or `pwsh bin\Debug\netX\playwright.ps1 install` and then it should work. For further issues, please file a new bug why this is not working for you.

Is this the new way of the new version? I've never seen such a step before.

**Comment by mxschmitt** [comment]
Yes, you can either do it via PowerShell or via the tool. Usually the PowerShell script is now recommended, since its bound to the project and the tool is global.

**Comment by bbhxwl** [comment]
> Yes, you can either do it via PowerShell or via the tool. Usually the PowerShell script is now recommended, since its bound to the project and the tool is global.

My current development environment is win10, and the running environment is basically centos7. There should be no PowerShell

Why not consider settings that support offline environments?

**Comment by coader** [comment]
I have to search document of node.js version to install it in server everytime.
