### ISSUE TITLE
[Question]: What is the best way to take a screenshot with Playwright for some long scrollable web pages?

### ISSUE THREAD

**Issue by ScriptBox99** [microsoft/playwright-dotnet#1799]
### Your question

Hello dear Playwright team and community.

I am using Playwright library for my apps.
Many of web pages, I could take actions for my apps with Playwright well.
But also not much and but also not only a few web pages could not take screentshot well and has broken the results always.
Even some of Microsoft's web pages also could not take the screenshot well with Playwright.
Below this link also could not take it, only just long scrollable background images a bit without any actual contents.

For example:
https://blogs.windows.com/windowsexperience/2021/10/06/windows-11-blossoms-with-bloom-a-new-symbol-for-a-new-operating-system/

I am using the library like this code below:  
```cs
var options = new BrowserTypeLaunchOptions(new() { Headless = true, Channel = "msedge"});
var playwright = await Playwright.CreateAsync();
var browser = await playwright.Chromium.LaunchAsync( options );
var page = await browser.NewPageAsync();
await page.GotoAsync(url);
await page.ScreenshotAsync(new() { Path = imgFilePath, FullPage = true, Timeout=0 });
```

Even I tried to change more options and custom scroll before to invoke page.ScreenshotAsync() such efforts for many web pages were tested.
But as I see, it related with web site design with CSS and more.
Anyway Edge browser has offer the web capture tool.
So I would like to call such Edge browser's built-in the web capture tool to take screenshot of some web pages.
I hope to get to know some good ideas how to make sure for such tasks like that.
Thanks.

**Comment by mxschmitt** [comment]
Sorry for the late reply.

> has broken the results always.

What do you mean by that?  

I tried to reproduce and it gave me this image, seems like thats what you mean with broken?

![image](https://user-images.githubusercontent.com/17984549/144723217-8c133986-e21d-4d73-a6bb-31d36a9ab96f.png)
