### ISSUE TITLE
[Question]: Is it possible to build a "lightweight" NuGet package with support for just Linux/Chromium?

### ISSUE THREAD

**Issue by maxmoore14** [microsoft/playwright-dotnet#1803]
### Your question

I had accidentally asked this question on the wrong project, but was referred to this thread: https://github.com/microsoft/playwright/issues/2404

I would like to use Playwright on AWS Lambda with .NET Core but the total package size is too large. I was thinking perhaps I could fork the repo and build a lightweight version, but would appreciate any guidance from the community on how best to do that.

**Comment by brnbs** [comment]
On the NuGet page (https://www.nuget.org/packages/Microsoft.Playwright) it says the package is 96.09 MB. After inspecting the nupkg file, I see the same as @maxmoore14. Can someone please clarify the purpose of this large ".playwright" folder and the included node runtime for all OSes?

**Comment by mxschmitt** [comment]
This should be possible after #1955. (after things change only the driver of the current architecture gets added to the bin directory. Installing single browsers is already possible as of today.)
