### ISSUE TITLE
[BUG]lunch chrome args format error

### ISSUE THREAD

**Issue by tagMatrix4** [microsoft/playwright-dotnet#1810]
pic1
![1635410448(1)](https://user-images.githubusercontent.com/25616829/139220900-1837db29-4503-4d73-aa3a-0fdce2b0bc39.png)

pic2
![1635410751(1)](https://user-images.githubusercontent.com/25616829/139220922-c732d6ba-e652-4ad3-a9c5-426fb554e06d.jpg)

**Comment by tagMatrix4** [comment]
hello?

**Comment by JoelEinbinder** [comment]
From my quick tests this might be working as intended. The correct way to specify the argument would be `-sq-device-name=********` without the quotes. Its fine to have spaces here, because we are not in a shell but rather passing the arguments directly. The same behavior occurs on other operating systems, not just windows.

**Comment by tagMatrix4** [comment]
> From my quick tests this might be working as intended. The correct way to specify the argument would be `-sq-device-name=********` without the quotes. Its fine to have spaces here, because we are not in a shell but rather passing the arguments directly. The same behavior occurs on other operating systems, not just windows.

test url:  https://bot.sannysoft.com/

Webglrender cannot be read correctly here
![image](https://user-images.githubusercontent.com/25616829/140457957-bbe1fa40-9294-4525-92bf-e26c468fd140.png)

![image](https://user-images.githubusercontent.com/25616829/140458443-049a248b-754e-4ce9-9799-59f6a6ae8c17.png)

**Comment by mxschmitt** [comment]
Closing for now since this seems not caused by playwright-dotnet and its stale. Please file an issue on https://github.com/microsoft/playwright if you still encounter issues.
