### ISSUE TITLE
[Bug]: SetInputFilesAsync large Files Error

### ISSUE THREAD

**Issue by mchudie** [microsoft/playwright-dotnet#1814]
### Playwright version

1.16

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

PlaywrightException: Target closed
=========================== logs ===========================
waiting for selector ".updataCoverBox input[type=file]"
  selector resolved to visible <input multiple type="file" accept=".mp4, .mov, .mkv, .…/>
============================================================

### Code snippet to reproduce your bug

```shell
await page.SetContentAsync("<div class=\"updataCoverBox\"><input type=\"file\" multiple=\"\" accept=\".mp4, .mov, .mkv, .avi, .flv, .mpeg, .ogg, .vob, .webm, .wmv, .rmvb\"></div>");
//file 1.mp4 69,737,642 byte
//file 2.mp4 13,291,043 byte
Await Page.SetInputFilesAsync("input[type=file]", new[] { "1.mp4", "2.mp4" });
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/3768
