### ISSUE TITLE
How to use this repo to override JavaScript on some web sites?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-dotnet#1820]
### Feature request

Hello:
From Chrome developer tools, I can replace some web sites’ JavaScript with my own JavaScript in local folder in my Windows 10 PC.
I want to know if I can use this repo to do the same for some web sites?
The detailed steps in Chrome is like this:
I visit one web page: https://www.some_video_sharing.com/, I login with my user name and password.
I visit the first page after I login, there is a few live videos are being played.  I picked the first one to view.
However, every 10, 20 seconds, I saw some pop-up ads show up to block my view, it is boring, and using ad-blocker seems not working.
Then I use Chrome developer tools to find that there are one JavaScript called “detailed.min.js”, which from time to time show some pop-up windows.
So I turned on local override in Chrome developer tools and save the “detailed.min.js” in my local disk folder for overrides, and I changed the JavaScript, replace the pop-up function with a simple return, and reload the web page, then the pop-up is gone.
I want to automate the process, so I don’t have to do this process each time I login to the underlying web page.
And advice if I can do this with the repo or not?
Thanks,

**Comment by mxschmitt** [comment]
You can use Playwright request interception to abort or modify requests, see here: https://playwright.dev/dotnet/docs/next/network/#modify-requests

**Comment by mxschmitt** [comment]
Closing since its answered. Please file a new issue for further questions.
