### ISSUE TITLE
[Question]: Open the web page youku.com and https://v.douyin.com/RftprNy/ Can't play the video.

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1825]
### Your question

Youku prompts that the browser version is too low to play, and Douyin prompts that the audio / video format is not supported. Why? Is automation detected or is the version too low?

**Comment by mxschmitt** [comment]
Not all video/audio codecs are supported by Chromium by default. It you rely on them, you need to use channels with e.g. Google Chrome or Microsoft Edge see here: https://playwright.dev/dotnet/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to
