### ISSUE TITLE
[Bug]: Add deprecation notice to playwright-sharp-tool

### ISSUE THREAD

**Issue by TanayParikh** [microsoft/playwright-dotnet#1829]
### Your question

Hello, I see the [nuget package is still `v0.192.0`](https://www.nuget.org/packages/playwright-sharp-tool), while the latest release in the [repo is `v1.16.1`](https://github.com/microsoft/playwright-dotnet/releases/tag/v1.16.1). Will this be updated, or is there a new package source we should be utilizing?

**Comment by mxschmitt** [comment]
The new package is `Microsoft.Playwright`. The old one is considered deprecated and does not get updated anymore.

See here: https://www.nuget.org/packages/Microsoft.Playwright

And the banner here: https://www.nuget.org/packages/PlaywrightSharp/

**Comment by TanayParikh** [comment]
Ah okay thanks for the clarification. I was just upgrading the package used in `dotnet/aspnetcore`, and was looking for the old package.

https://github.com/dotnet/aspnetcore/blob/c0778f05020f8d99481e479553dc024298c108dd/.config/dotnet-tools.json#L11-L16

> Let us know if the old one is referenced somewhere incorrectly!

Would it be possible to update the README of the [nuget package](https://www.nuget.org/packages/playwright-sharp-tool) to indicate deprecation / new package?

**Comment by mxschmitt** [comment]
> this sounds reasonable to me! lets have this as an action item for this issue.

Thanks!

**Comment by 304NotModified** [comment]
I see the deprecation warning on nuget.org, so this could be closed :)
