### ISSUE TITLE
[Question]: BrowserType Connect

### ISSUE THREAD

**Issue by danielbogatinov13** [microsoft/playwright-dotnet#1833]
### Your question

Hi, 
I was looking into installing Chromium on Azure app service to use it with Playwright. It's simply not possible at the moment without some serious workarounds that cost much more and don't always work as needed. Then I looked into playwright and found the Connect method of BrowserType. I wanted to try it, but guess what? It doesn't exist. Than I saw that you actually have the code for this, but it's not exposed through the Interface. Also while reading through the issues I saw that it was supposed to come out in the 1.15 or 1.17. I really need to know if it's coming soon (or ever). 
Please :).

**Comment by mxschmitt** [comment]
Folding into #986.
