### ISSUE TITLE
Test against .NET 6

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-dotnet#1834]
Currently only 3.1 and 5 are tested. Users already using it with .NET 6 and it seems not working.

**Comment by programatt** [comment]
I've got a PR https://github.com/microsoft/playwright-dotnet/pull/1839 but at least on mac there's a ton of test failures.

**Comment by evgenynazarchuk** [comment]
Hello,
Is it problem? or need create new ticket?

NU1202	
Package Microsoft.Playwright.CLI 1.2.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.Playwright.CLI 1.2.0 supports:
  - net5.0 (.NETCoreApp,Version=v5.0) / any
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any
