### ISSUE TITLE
[Bug]: 1.16.0 Creates Timeouts in Docker

### ISSUE THREAD

**Issue by Shanson90** [microsoft/playwright-dotnet#1837]
### Playwright version

1.16.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

This is in Docker.  

### What happened? / Describe the bug

We use the Microsoft Playwright Docker file as our base, add a couple certs, and publish our own (internally), essentially unchanged.  We have been pulling a specific Docker image version (previously on 1.14.1).  We upgraded to 1.16 and things run, but tons of timeouts (~75% of tests started failing), unable to find elements, only in CI (locally on Windows everything is fine).  Downgraded back to 1.14.1 and everything runs perfectly again in Docker/CI.

Weirdly, it seems someone is removing the ability to use specific Docker image versions.  I can no longer (this seemed to change in the last couple days) find any specific, versioned docker images from Microsoft.  Just a generic one that I assume is the latest version.  This is a bad approach.  Forcing everyone onto only the latest gives us no way to protect ourselves from issues exactly like what I'm experiencing - minor version upgrade is breaking most of our tests in CI. 

Please resume publishing specific versioned images so we have the ability to lock to versions that work without having to create our own new docker image from "scratch" every time Playwright releases a new version.  

As to the timeout issues on 1.16.0, I'm not totally sure how to give a reproducible example since only about 75% of our tests have this issue and it's not yet clear what exactly is the common factor among them.  It's only clear that the upgrade is the issue since downgrading restored all our tests to passing without any additional code changes.

**Comment by mxschmitt** [comment]
Sorry for the late reply. Please try a more recent version like 1.17.2. If I remember correctly we had a regression back then which resulted in timeouts.

> Weirdly, it seems someone is removing the ability

This should not be the case - how do you come to this conclusion? We definitely won't force someone to use the latest version and old tags on Dockerhub stay there forever.

See here how to obtain the image tags: https://playwright.dev/docs/docker#image-tags

**Comment by Shanson90** [comment]
`Step 1/6 : FROM mcr.microsoft.com/playwright:v1.17.2-focal
manifest for mcr.microsoft.com/playwright:v1.17.2-focal not found: manifest unknown: manifest tagged by "v1.17.2-focal" is not found
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1`

**Comment by Shanson90** [comment]
Ok, so I found this page: https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/playwright?P1=1638832974&P2=1&P3=1&P4=LGXBMFNF89fvliYE9E79UhEF%2BJwg74BJ2%2FC10cxJXaA%3D&se=2021-12-06T23%3A22%3A54Z&sig=WuKPQTcjLACPLCiemKWnO3qJad3enKHwdGSxrC8M13Y%3D&sp=r&sr=b&sv=2015-02-21

This seems to indicate 1.17.2 just wasn't a valid tag (yet).  Dropping to 1.17.1 seems to work.  So I guess there's no issue on the Docker front other than that page above seems to be the only place to find the tags now, whereas before it seemed I could find them on Docker hub directly.  Doesn't really matter.

Will report back whether or not 1.17.1 resolves the timeout issues.

**Comment by mxschmitt** [comment]
Closing for now, please create a new issue if you still encounter issues. Thanks!
