### ISSUE TITLE
[Bug]: MacOS Monterey: playwright command not found

### ISSUE THREAD

**Issue by tsmithcad** [microsoft/playwright-dotnet#1840]
### Playwright version

1.17.0

### Operating system

MacOS

### Other information

MacOS Monterey v12.0.1
MacBookPro16,1
8-Core Intel Core i9
2.3 GHz

.NET 5
Visual Studio Community Mac Edition 2019 build 8.10.14 (build 17)

.NET 6
Visual Studio Community Mac Edition 2022 17.0 Preview (17.0 build 4729)

### What happened? / Describe the bug

The "install playwright" command is not recognized by the terminal.

### Code snippet to reproduce your bug

```shell
dotnet tool install --global Microsoft.Playwright.CLI
dotnet new console -n PlaywrightDemo
cd PlaywrightDemo
dotnet add package Microsoft.Playwright
dotnet build

playwright install
```

### Relevant log output

```shell
zsh: command not found: playwright
```

**Comment by bjharo** [comment]
Have you updated your PATH?
`export PATH=/Users/your_username/.dotnet/tools:$PATH`

**Comment by tsmithcad** [comment]
1: Set the terminal to the visual studio active project directory.
2: In terminal run  "export PATH=/Users/your_username/.dotnet/tools:$PATH"
3: Then in terminal run "playwright install" 
Thanks that was successful! 
Do you think that should be referenced in the documentation or do most people know to do that?

**Comment by bjharo** [comment]
I ran into the issue on both Ubuntu (via WSL) and on a Macbook so it may be useful to mention it in the docs for anyone who isn't super familiar with those operating systems.

**Comment by tsmithcad** [comment]
Thank you. You can close this issue. I think adding this note to your documentation would solve this issue and increase user adoption of the .NET implementation for MacOS users.

**Comment by mxschmitt** [comment]
Closing, since Playwright requires a fully working .NET installation, see here about where the `dotnet tool` command will put the built executables: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#description
