### ISSUE TITLE
[Bug]: HAR file not being saved

### ISSUE THREAD

**Issue by StevenDenman** [microsoft/playwright-dotnet#1841]
### Playwright version

1.17.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium, Firefox

### What happened? / Describe the bug

I am trying to record a HAR file with Playwright.

According to the docs, all you need to do is pass RecordHarPath in the BrowserContextOptions and call CloseAsync on the BrowserContext.

With Firefox, this is not creating any HAR file.
With Chromium, it hangs on CloseAsync and never completes.

### Code snippet to reproduce your bug

```shell
static async Task Main()
{
    var playwright = await Playwright.CreateAsync();

    var currentDir = Directory.GetCurrentDirectory();

    Console.WriteLine("Trying Firefox");
    var firefox = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false});
    await TryWith(firefox, Path.Combine(currentDir, "firefoxHar.har"));

    Console.WriteLine("Trying Chromium");
    var chromium = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false });
    await TryWith(chromium, Path.Combine(currentDir, "chromium.har"));
}

static async Task TryWith(IBrowser browser, string harPath)
{
    var context = await browser.NewContextAsync(new BrowserNewContextOptions()
    {
        RecordHarPath = harPath
    });

    var page = await context.NewPageAsync();
    await page.GotoAsync("https://www.microsoft.com");
    var link = await page.QuerySelectorAsync("a#uhf-shopping-cart");
    await link.ClickAsync();

    Console.WriteLine("Closing Context");
    await context.CloseAsync();
    Console.WriteLine("Closing Browser");
    await browser.CloseAsync();
}
```

**Comment by infinitejest69** [comment]
Came to report the same Issue, also not seeing any HAR file, Tried multiple browsers including Chrome and Chromium and tried with and without video recording which does work and saves on CloseAsync. also tried with Dev tools open. would be nice to solve this.
Thanks

**Comment by mxschmitt** [comment]
Was able to repro. Seems like the "HAR saving logic" is missing when the browser context gets closed.
