### ISSUE TITLE
[Question]: What is the method to fetch all the downloaded file names ? 

### ISSUE THREAD

**Issue by vivekvasu** [microsoft/playwright-dotnet#1848]
### Your question

I have a download icon which will download multiple files upon clicking. How can I fetch all the SuggestedFilename ? 
download.SuggestedFilename is returning only one name

**Comment by mxschmitt** [comment]
Multiple download events should then get emitted where you can call the suggested filename, see here: https://playwright.dev/dotnet/docs/api/class-download#download-suggested-filename

**Comment by mxschmitt** [comment]
Closing for now since it seems answered. Please file a new issue if you have further questions.
