### ISSUE TITLE
getting started instructions dont work

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#1865]
### Playwright version

1.17.2

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

net6

### What happened? / Describe the bug

following the getting started failes to install run the install script https://playwright.dev/dotnet/docs/intro/

### Code snippet to reproduce your bug

```shell
PS C:\Code\New folder> dotnet new console -n PlaywrightDemo
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj...
  Determining projects to restore...
  Restored C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj (in 133 ms).
Restore succeeded.

PS C:\Code\New folder> cd .\PlaywrightDemo\
PS C:\Code\New folder\PlaywrightDemo> dotnet add package Microsoft.Playwright
  Determining projects to restore...
  Writing C:\Users\simon\AppData\Local\Temp\tmp3A63.tmp
info : Adding PackageReference for package 'Microsoft.Playwright' into project 'C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.playwright/index.json
info : Restoring packages for C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj...
info : Package 'Microsoft.Playwright' is compatible with all the specified frameworks in project 'C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj'.
info : PackageReference for package 'Microsoft.Playwright' version '1.17.2' added to file 'C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj'.
info : Committing restore...
info : Generating MSBuild file C:\Code\New folder\PlaywrightDemo\obj\PlaywrightDemo.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: C:\Code\New folder\PlaywrightDemo\obj\project.assets.json
log  : Restored C:\Code\New folder\PlaywrightDemo\PlaywrightDemo.csproj (in 176 ms).
PS C:\Code\New folder\PlaywrightDemo> dotnet build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  PlaywrightDemo -> C:\Code\New folder\PlaywrightDemo\bin\Debug\net6.0\PlaywrightDemo.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.62
PS C:\Code\New folder\PlaywrightDemo> bin\Debug\net6.0\playwright.ps1 install
Unable to find type [Microsoft.Playwright.Program].
At C:\Code\New folder\PlaywrightDemo\bin\Debug\net6.0\playwright.ps1:4 char:1
+ [Microsoft.Playwright.Program]::Main($args)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Playwright.Program:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

PS C:\Code\New folder\PlaywrightDemo>
```

**Comment by pavelfeldman** [comment]
It looks like you need to do

```
pwsh bin\Debug\net6.0\playwright.ps1 install
```

I'll investigate why this is necessary.

**Comment by pavelfeldman** [comment]
https://stackoverflow.com/questions/42837447/powershell-unable-to-find-type-when-using-ps-5-classes

**Comment by RiadKatby** [comment]
I have the same problem, any update here in?

**Comment by mxschmitt** [comment]
@RiadKatby which OS/version/PowerShell/.NET version are you using? It would help us to debug this issue further.

**Comment by dariusz-wozniak** [comment]
In addition to @BrandonQA's answer:

`dotnet tool update --global PowerShell`

👆 Helped in my case

**Comment by andrecustodio** [comment]
I had the same issue that OP had. I followed the install and update commands that @BrandonQA and @dariusz-wozniak sent over, but didn't fix it.
I was able to get it working after installing PowerShell Core from the MS website (Latest version in the time of this reply):
https://docs.microsoft.com/pt-br/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2
Cheers!

**Comment by SimonCropp** [comment]
i went with calling this in a ModuleInitializer

```
Microsoft.Playwright.Program.Main(new[] {"install"});
```

**Comment by samayo** [comment]
Eh, still the same issue. When will we ever get something that works outside the box


![image](https://github.com/microsoft/playwright-dotnet/assets/5304093/c11b0bab-1ede-47fa-a952-851feb11430e)

**Comment by mxschmitt** [comment]
> Eh, still the same issue. When will we ever get something that works outside the box
> 
> 
> 
> 
> 
> ![image](https://github.com/microsoft/playwright-dotnet/assets/5304093/c11b0bab-1ede-47fa-a952-851feb11430e)
> 
> 

It needs to be normal slashes instead of backslashes. Please create a new issue instead of reactivating old ones.
