### ISSUE TITLE
[Question]: .NET 6, Playwright CLI,...

### ISSUE THREAD

**Issue by timmkrause** [microsoft/playwright-dotnet#1866]
### Your question

I am a bit confused around the latest changes around #1834 and https://github.com/microsoft/playwright/pull/10796.
My build fails because Playwright CLI seems to require .NET 5.

So for local dev scenario I shouldn't use the .NET Global Tool / Playwright CLI anymore, but instead a PowerShell script within `bin\debug`?

https://playwright.dev/dotnet/docs/intro

Is this seen as a workaround or the final solution?

What is the recommended approach in CI/pipeline scenarios?

https://playwright.dev/dotnet/docs/ci#azure-pipelines

> For Windows or macOS agents, no additional configuration required, just install Playwright and run your tests.

Does not mention that.

Also `playwright.ps1`?

**Comment by pavelfeldman** [comment]
> So for local dev scenario I shouldn't use the .NET Global Tool / Playwright CLI anymore, but instead a PowerShell script within bin\debug?

Correct.

> Is this seen as a workaround or the final solution?

A final solution. You can keep using the tool if it works for you, but we are seeing more trouble than the benefit from it.

> What is the recommended approach in CI/pipeline scenarios?

This is one of the reasons we are stepping away from the tool, invoking a script is easier in CI/CD than installing the tool.

> What is the recommended approach in CI/pipeline scenarios?

It is actually the same as for the local workflow.

**Comment by mxschmitt** [comment]
Closing since its answered. (Also the `Microsoft.Playwright.CLI` tool is fixed now for .NET 6)
