### ISSUE TITLE
[Question]: Click happening before click handler is ready.

### ISSUE THREAD

**Issue by belav** [microsoft/playwright-dotnet#1867]
### Your question

I am working on migrating a large suite of selenium tests over to playwright.
The site being tested is a SPA built with react and redux.
Very often I am running into a test that worked with selenium, but when converted to playwright, the playwright test will click an element and nothing happens. If I introduce a slight delay before clicking, then it works fine. 
Is there some way to say "Wait for the page to stabilize/finish rendering" ? 
I hacked together a quick version which seems to solve the problem but I am wondering if there is a built in way to do this instead.

**Comment by pavelfeldman** [comment]
There is no generic solution to your problem. This is generally considered an application bug - the button should be disabled before the listener is attached to it.

**Comment by belav** [comment]
Yeah there is definitely something odd about a few of there cases, because I am pretty sure the listener should already be attached for at least a few of them. But that is not a playwright issue. Thanks!
