### ISSUE TITLE
[Bug]: .NET Framework 4.8 Driver not found in Temporary ASP.NET Files

### ISSUE THREAD

**Issue by Zephyr-Koo** [microsoft/playwright-dotnet#1872]
### Playwright version

1.17.2

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Project type : ASP.NET Web Application (.NET Framework)
Target framework: .NET Framework 4.8

### Steps to Reproduce
1. Create an ASP.NET Web Application (Web Forms or MVC) on .NET 4.8
2. Install `Microsoft.Playwright` package via NuGet Package Manager
3. Copy sample code from [Getting started](https://playwright.dev/dotnet/docs/intro/) page into default page code-behind (via `Page_Load` event or default controller's action)
4. Visit default page to trigger sample code

### Expected
Screenshot generated successfully with HTTP 200 OK response.

### Actual
Display YSOD with following information:

Source Error:
```csharp
var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
```

Stack Trace:
```
[PlaywrightException: Driver not found: C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\vs\77619d23\815ed4b7\assembly\dl3\.playwright\node\win32_x64\playwright.cmd]
   Microsoft.Playwright.Helpers.Paths.GetExecutablePath() +299
   Microsoft.Playwright.Transport.StdIOTransport.GetProcess() +38
   Microsoft.Playwright.Transport.StdIOTransport..ctor() +77
   Microsoft.Playwright.<CreateAsync>d__0.MoveNext() +61
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +29
   Zephyr.TestDrive.Playwright.Web.<GenerateScreenshot>d__6.MoveNext() in D:\VS\Zephyr.TestDrive.Playwright.Web\Index.aspx.cs:34
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +27
   Zephyr.TestDrive.Playwright.Web.Index.Page_Load(Object sender, EventArgs e) in D:\VS\Zephyr.TestDrive.Playwright.Web\Index.aspx.cs:28
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +85
   System.Web.UI.Control.OnLoad(EventArgs e) +79
   System.Web.UI.Control.LoadRecursive() +130
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2853
```

### Remarks
- `.playwright` folder was not found under `bin` folder after rebuilding project as in Console Application
  - Copying `.playwright` folder to web app `bin` folder didn't help
  - Copying `.playwright` folder to location reported in stack trace will cause page load to wait indefinitely
- Same behaviour was observed when installing browser locally or via custom `ExecutablePath` with `BrowserTypeLaunchOptions`

### Code snippet to reproduce your bug

```shell
// Invoke method in web page with following statement:
GenerateScreenshot().GetAwaiter().GetResult();

private async Task GenerateScreenshot()
{
    var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
    var browser = await playwright.Chromium.LaunchAsync();
    var page = await browser.NewPageAsync();

    await page.GotoAsync("https://playwright.dev/dotnet");
    await page.ScreenshotAsync(new PageScreenshotOptions
    {
        Path = "screenshot.png"
    });
}
```

**Comment by mxschmitt** [comment]
Folding into #1842.
