### ISSUE TITLE
[Question]: Passing cookies

### ISSUE THREAD

**Issue by aw1875** [microsoft/playwright-dotnet#1873]
### Your question

I tried storing cookies so I can pass them back in once I create a new instance. I noticed that the `context.CookiesAsync` function is returning `List<BrowserContextCookiesResult>` type so this is what I've done to store them appropriately. However, when I try to pass them back in to a new context the `context.AddCookiesAsync` function expects a `IEnumerable<Cookie>` type. I haven't been able to successfully pass them back through and wanted to know what I'm doing wrong. Any help is appreciated.

I should note the cookies are being stored in a JSON file so I can access them at ease.

**Comment by aw1875** [comment]
Seems like I was able to do it using this code:

```csharp
account.Cookies.ForEach(async cookie =>
{
    Cookie c = new Cookie();
    c.Name = cookie.Name;
    c.Value = cookie.Value;
    c.Domain = cookie.Domain;
    c.Path = cookie.Path;
    c.Expires = cookie.Expires;
    c.HttpOnly = cookie.HttpOnly;
    c.Secure = cookie.Secure;
    c.SameSite = cookie.SameSite;
    await context.AddCookiesAsync(new[] { c });
});
```

Not sure if this is the best approach but it seems to be working correctly at least! If theres a better way of doing this I'd be open to hearing how.

**Comment by pavelfeldman** [comment]
Are you looking for this: https://playwright.dev/dotnet/docs/auth#reuse-authentication-state ?

**Comment by aw1875** [comment]
@pavelfeldman that will definitely work for what I'm trying to do thank you!
