### ISSUE TITLE
[Question]:  Why is this repo using labels for versions, and not milestones?

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/playwright-dotnet#1875]
### Your question

Why is this repo using labels for versions, and not GitHub milestones?

Just curious, as Microsoft also owns GitHub, I would expect that GitHub would used as by design. 

(there is also a milestone which should be closed? --> [v1.11.0](https://github.com/microsoft/playwright-dotnet/milestone/1))

**Comment by pavelfeldman** [comment]
Seems unrelated to the Playwright functionality!

**Comment by 304NotModified** [comment]
It's related to the open source community...which is an essential part of open source software
