### ISSUE TITLE
I initialize a page and never close it. Will he close it himself?[Bug]: 

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1880]
### Playwright version

1.17.2

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

 arget page, context or browser has been closed
Using the Chrome browser, after jumping to three pages, my program always prompts this error. 
[Target page, context or browser has been closed]

**Comment by mxschmitt** [comment]
This should not be the case. Could you provide us a small repro for this and do you experience this exception all the time?

**Comment by bbhxwl** [comment]
> This should not be the case. Could you provide us a small repro for this and do you experience this exception all the time?

I'll send it to you later. I'm not at home at present. Try hanging up for a few days. This is prompted after several basic visits to the page.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues. Thanks!
