### ISSUE TITLE
[Bug]: Browser is getting closed while uploading large files

### ISSUE THREAD

**Issue by vivekvasu** [microsoft/playwright-dotnet#1894]
### Playwright version

1.12.3

### Operating system

Windows

### What happened? / Describe the bug

Browser is getting closed while uploading a file of 100Mb via element.SetInputFilesAsync() method

### Relevant log output

```shell
Microsoft.Playwright.PlaywrightException: Protocol error (Runtime.callFunctionOn): Target closed.
```

**Comment by mxschmitt** [comment]
Large file uploads are blocked by this upstream issue: https://github.com/microsoft/playwright/issues/3768

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/3768
