### ISSUE TITLE
[Question]: When will ConnectOverCDPAsync be released

### ISSUE THREAD

**Issue by pll1772569001150** [microsoft/playwright-dotnet#1901]
### Your question

I saw ConnectOverCDPAsync in the doc. When will the version with this function be released? I am anxious and have been waiting.

**Comment by mxschmitt** [comment]
In version 1.18 in around one month.

**Comment by deaktomi** [comment]
Hello. It’s been one month since the last update on this issue. Are there any plans for a new revision of 1.18? I really need it, we have a deadline coming up

**Comment by mxschmitt** [comment]
@deaktomi we release it in the upcoming 2-3 days.

**Comment by mxschmitt** [comment]
@deaktomi @pll1772569001150 it's released now!

**Comment by deaktomi** [comment]
Thanks, I think this issue can be closed
