### ISSUE TITLE
[Feature]: Modification of network response

### ISSUE THREAD

**Issue by krokofant** [microsoft/playwright-dotnet#1904]
### Feature request

Follow-up on #1816

This is supported _and _documented__ in the Node.js version of playwright.

Node.js section: https://playwright.dev/docs/network#modify-responses

It does not seem exist for [the .NET version](https://playwright.dev/dotnet/docs/network).

**Comment by mxschmitt** [comment]
Merging into https://github.com/microsoft/playwright-dotnet/issues/1905
