### ISSUE TITLE
[Feature] Add API testing

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-dotnet#1905]
https://playwright.dev/docs/test-api-testing

**Comment by NaZaRKIN123** [comment]
Cool! Any ETA on it?

**Comment by mxschmitt** [comment]
> Cool! Any ETA on it?

Probably 1.23, we unfortunately didn't make it for this (1.22) release.

**Comment by konarx** [comment]
Hi, should we expect this feature in 1.23? And when is the 1.23 release scheduled for? Thank you

**Comment by mxschmitt** [comment]
@konarx yes, we release 1.23 in 1-2 weeks.
