### ISSUE TITLE
Running multiple tests at the same time C#

### ISSUE THREAD

**Issue by BrandonQA** [microsoft/playwright-dotnet#1907]
Hi guys, currently looking for the best way to run multiple tests at the same time using Playwright. I'm not sure if this is possible from the artical i was reading on https://playwright.dev/dotnet/docs/test-runners. 

Thank you for your help and information in advance,
brandon

**Comment by BrandonQA** [comment]
Using  -- NUnit.NumberOfTestWorkers=10 My test still seem to run individually not at the same time.

**Comment by StevenDenman** [comment]
Are you using SpecFlow?

**Comment by BrandonQA** [comment]
> Are you using SpecFlow?

No

**Comment by StevenDenman** [comment]
This worked fine for me, although I noticed that if you were following the instructions [here](https://playwright.dev/dotnet/docs/next/test-runners) then it doesn't state to [setup](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022) your runsettings file, nor to [set the Scope](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022) accordingly (note I have set it to All as his will make the methods run in parallel)

```
using Microsoft.Playwright;
using NUnit.Framework;
using System.Threading.Tasks;

namespace PlaywrightParallel
{
    [TestFixture]
    [Parallelizable(ParallelScope.All)]
    public class Tests
    {
        private static IBrowserContext Context;

        [SetUp]
        public async Task Setup()
        {
            var pw = await Playwright.CreateAsync();

            var chromium = await pw.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false
            });

            Context = await chromium.NewContextAsync();
        }

        [Test]
        public async Task Test1()
        {
            var page = await Context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet/docs");
            await Task.Delay(5000);
        }

        [Test]
        public async Task Test2()
        {
            var page = await Context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet/docs");
            await Task.Delay(5000);
        }

        [Test]
        public async Task Test3()
        {
            var page = await Context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet/docs");
            await Task.Delay(5000);
        }

        [Test]
        public async Task Test4()
        {
            var page = await Context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet/docs");
            await Task.Delay(5000);
        }

        [Test]
        public async Task Test5()
        {
            var page = await Context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet/docs");
            await Task.Delay(5000);
        }
    }
}
```

**Comment by mxschmitt** [comment]
Closing since it works with nunit and multiple test-runners / setups are mixed here. For a guide for nunit, please refer to the docs [here](https://playwright.dev/dotnet/docs/intro#first-test) and use the latest version.
