### ISSUE TITLE
[Question]: Can't seem to find much Documentation on Multiple Page Object model 

### ISSUE THREAD

**Issue by BrandonQA** [microsoft/playwright-dotnet#1910]
### Your question

I'm currently setting up multiple pages and would like to reference all of them within a single test so that i can use all elements and methods i have stored in each page object. 
The current code i have wrote is incorret and every time ran opens up a new page instead of finding the element on the exisiting page

Please find my example below i'm new to .net framework and was wondering if you guys have any guidence within this area.

```csharp
        [Test]
        public async Task ExampleTest()
        {
            using var playwright = await Playwright.CreateAsync();
            var chromium = playwright.Chromium;
            var browser = await chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false, SlowMo = 100, });
            var loginPage = new loginPage(await browser.NewPageAsync());
            var homePage = new homePage(await browser.NewPageAsync());  


            //Run Tests
            await loginPage.Goto("https://ddt-rt5-testing-app-uat.azurewebsites.net/");
            await loginPage.loginIntoCRS("Host", "samplePassword1bb23!");
            await homePage.SelectHomeIcon();
        }
```

**Comment by StevenDenman** [comment]
`await browser.NewPageAsync()` <-- this is what is opening a new page each time.

you want to call that once, store that IPage and pass that in as a parameter to both the loginPage and homePage

**Comment by BrandonQA** [comment]
> re that IPage

Woul it be possible to provide an example on this please?

**Comment by StevenDenman** [comment]
Not tested but something like this?

```
[Test]
public async Task ExampleTest()
{

    using var playwright = await Playwright.CreateAsync();
    chromium = playwright.Chromium;
    browser = await chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false, SlowMo = 100, });
    var page = await browser.NewPageAsync();
    loginPage = new loginPage(page);
    homePage = new homePage(page);

    //Run Tests
    await loginPage.Goto("https://ddt-rt5-testing-app-uat.azurewebsites.net/");
    await loginPage.loginIntoCRS("Host", "samplePassword1bb23!");
    await homePage.SelectHomeIcon();
}
```

**Comment by mxschmitt** [comment]
Page object models are usually just classes which accept a `IPage` instance in their constructor. Then you can put your page logic into dedicated methods inside this class and call it from outside. If you want to have multiple page object models, you can decide if you want to either have them sharing state (using the same underlying browser context) or keep them separated (create separate browser contexts for them).

Keep in mind that `browser.NewPageAsync` is a wrapper for `browser.NewContextAsync` + `context.NewPageAsync`.

Closing since it's answered.
