### ISSUE TITLE
[Question]: How does the new TAB get the page object?

### ISSUE THREAD

**Issue by xiao71781** [microsoft/playwright-dotnet#1911]
### Your question

hi, Tab1 "duplicate Tab" gets Tab2, how do I get Tab2 page object?
My English is poor, I hope I can express myself clearly. thank you

**Comment by mxschmitt** [comment]
What do you mean with duplicate tab?

You can create multiple page instances which share their local storage and cookie state.

If you want isolation, you need to create multiple browser context instances, they are fully isolated from each-other.

**Comment by xiao71781** [comment]
> What do you mean with duplicate tab?
> 
> You can create multiple page instances which share their local storage and cookie state.
> 
> If you want isolation, you need to create multiple browser context instances, they are fully isolated from each-other.

thank you!
