### ISSUE TITLE
[Question]: How to install next version?

### ISSUE THREAD

**Issue by adrmnv** [microsoft/playwright-dotnet#1912]
### Your question

I need to use this function:
`BrowserType.ConnectOverCDPAsync function (endpointURL, options)`
How do I install the latest version described in the documentation?

**Comment by StevenDenman** [comment]
According to [issue 1901](https://github.com/microsoft/playwright-dotnet/issues/1901), this is in 1.18 which is [not yet released](https://github.com/microsoft/playwright-dotnet/releases).

**Comment by mxschmitt** [comment]
As @StevenDenman pointed out. It gets released in 1.18 which is scheduled for the next few weeks.
