### ISSUE TITLE
`RouteAsync` doesn't take async delegates

### ISSUE THREAD

**Issue by slang25** [microsoft/playwright-dotnet#1913]
### Feature request

`RouteAsync` currently accepts an `Action<IRoute>`, however it is expected we call methods on the `IRoute` instance such as `route.FulfillAsync()`. As a .NET developer, it seems like I should await the result of `FulfillAsync`, but the delegate we are in is synchronous.

We could not await it, like in the tests, or make the delegate async, which would feel wrong because we cannot assume the implementation will know to handle a sync vs async delegate at runtime.

It seems to me that the methods on `IRoute` should be synchronous to match their usage in the tests:
https://github.com/microsoft/playwright-dotnet/blob/bf25fc707bbf54746134b7de78edfe08bf67d01b/src/Playwright.Tests/PageRouteTests.cs#L628-L640

Can you clarify?

**Comment by mxschmitt** [comment]
Usually its fine to call these methods in the background and ignore their return values / errors, thats what we do in Node.js/JavaScript too. We might revisit it when we add the response interception in one of the next .NET releases where we need to await things, then we can see how it works out.
