### ISSUE TITLE
[Question]: Driver not found after package a WPF in msix.

### ISSUE THREAD

**Issue by kuyeduwu** [microsoft/playwright-dotnet#1915]
### Your question

**Environment:**
**OS:** Win 10 20H2 19042.1415
**IDE:** Visual Studio Pro 2019
**SDK:** .Net Core 3.1
**Playwright:** Microsoft.Playwright 1.16.1

**Issues:**
I'm trying to build a WPF application with Playwright, everything works perfectly until I tried to package the WPF.

I followed the instruction here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5
to package my WPF app into MSIX, then after deploying it, I got the "Driver not found" error.

Then when checking the App folder, the `.playwright` directory is missing, but in the original WPF app, the `.playwright` folder does exist in the `bin` path.

From my understanding, the packaging process should package all content within the `bin` path, and release them once deployed, but why the `.playwright` folder is missed?

I would like the WPF app could be packaged well so that it could be deployed to other machines easily, so manually installing the playwright on the target machine is not a good choice.

Any idea about this?

**Comment by kaidoatgit** [comment]
> ### Your question
> **Environment:** **OS:** Win 10 20H2 19042.1415 **IDE:** Visual Studio Pro 2019 **SDK:** .Net Core 3.1 **Playwright:** Microsoft.Playwright 1.16.1
> 
> **Issues:** I'm trying to build a WPF application with Playwright, everything works perfectly until I tried to package the WPF.
> 
> I followed the instruction here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5 to package my WPF app into MSIX, then after deploying it, I got the "Driver not found" error.
> 
> Then when checking the App folder, the `.playwright` directory is missing, but in the original WPF app, the `.playwright` folder does exist in the `bin` path.
> 
> From my understanding, the packaging process should package all content within the `bin` path, and release them once deployed, but why the `.playwright` folder is missed?
> 
> I would like the WPF app could be packaged well so that it could be deployed to other machines easily, so manually installing the playwright on the target machine is not a good choice.
> 
> Any idea about this?

Hello sir did u manage to run msix packaged playwright from your wpf? Im having the same problem if you done it let me know sir thanks
