### ISSUE TITLE
[Question]: how to open inspector? 

### ISSUE THREAD

**Issue by coader** [microsoft/playwright-dotnet#1920]
### Your question

only run script in vscode?

**Comment by coader** [comment]
https://playwright.dev/dotnet/docs/inspector

those sample code is not use c#, only vscode+node.js can show inspector?

**Comment by mxschmitt** [comment]
The example image does only show Node.js, but the codegen and debugging functionality is also available in .NET (also Java and Python).

You can open it via `await page.PauseAsync();` or set the `PWDEBUG` environment variable. 

Relates https://github.com/microsoft/playwright.dev/issues/288

**Comment by coader** [comment]
I  use await page.PauseAsync(), but nothing happens
it is running in test expolorer with debug
