### ISSUE TITLE
[Feature] Make IFrame and IPage implement the same interface.

### ISSUE THREAD

**Issue by belav** [microsoft/playwright-dotnet#1923]
We have an existing set of selenium tests that is being migrated to playwright.
We have an abstraction around interactions with playwright/selenium. It would benefit from having a common interface between IFrame and IPage.

A simplified version of how our abstraction works.
```c#
this.Host.NavigateToUrl("test.com")
    .FillField("#field", "value")
    .Click("#button")
```

And in the abstraction, the Click method looks like this.
```c#
public IHost Click(string selector)
{
    this.page.ClickAsync(selector).GetAwaiter().GetResult();
    return this;
}
```

We have a number of tests that deal with iframes, they look something like this
```c#
this.Host.NavigateToUrl("test.com")
    .SwitchToIFrame("#iframe")
    .Click("#button")
```

Because there is no common interface between IFrame and IPage, the Click method needs to change to
```c#
public IHost Click(string selector)
{
    if (this.selectedFrame != null) 
    {
        this.selectedFrame.ClickAsync(selector).GetAwaiter().GetResult();
    }
    else 
    {
        this.page.ClickAsync(selector).GetAwaiter().GetResult();
    }
    return this;
}
```

And this same conditional logic needs to be added to a number of other methods.

With a common interface the click method could be simplified to
```c#
public IHost Click(string selector)
{
    this.pageOrFrame.ClickAsync(selector).GetAwaiter().GetResult();
    return this;
}
```

And could easily support ClickOptions
```c#
public IHost Click(string selector, IClickOptions? clickOptions = null)
{
    this.pageOrFrame.ClickAsync(selector, clickOptions).GetAwaiter().GetResult();
    return this;
}

**Comment by mxschmitt** [comment]
We have a common abstraction between those which is called `Locator` and `FrameLocator`. They both work in-depended of the frame on which they operate on, see here a few examples and resources:

```csharp
var locator = page.Locator("text=Submit");
await locator.ClickAsync();
// --------------------------------
var locator = page.FrameLocator("#my-frame").Locator("text=Submit");
await locator.ClickAsync();
``` 

- https://playwright.dev/dotnet/docs/api/class-locator
- https://playwright.dev/dotnet/docs/api/class-framelocator

**Comment by belav** [comment]
Ah yeah I missed that! We aren't using Locator everywhere yet, but I can see a path forward for us using them. Thanks!
