### ISSUE TITLE
[Feature] Separate Video from Context

### ISSUE THREAD

**Issue by brettwinters** [microsoft/playwright-dotnet#1927]
I'm using Playwright to test a static WASM Blazor app with NUnit.

The provided NUnit fixtures are based on the assumption that the `Browser`, `Page`, `Context` are recreated for each test, but with Blazor this is unworkable due to the loading speed. 

So I've had to re-use the `Page` and therefore the `Context` for the tests via a `[OneTimeSetup]` and then `page.GotoAsync("home")` for each test. Unfortunately this screws up the video. Actually I'd expect the video to start when the context is created and run until the browser is closed in the `[OneTimeTearDown]` but in fact it only shows the login steps and then quits when the page redirects (OIDC code-flow) back to the app. 

My feature request therefore is to link the video with the `Page` (not the `Context`) - in the same way as the screenshot function but perhaps with the ability to start video at an arbitrary time and stop/save as follows: `page.StartVideo()` --> run test -> `page.StopVideo()`. Saving can occur when the context is closed as before.

**Comment by mxschmitt** [comment]
> The provided NUnit fixtures are based on the assumption that the Browser, Page, Context are recreated for each test

It should only re-create the context and page instance for each test, this is a very fast operation and takes in chrome just a few milliseconds. Launching a whole browser is the operation which slows test executions down which should only happen per worker.

> with Blazor this is unworkable due to the loading speed.

So you want to keep the same page instance open and re-use it over and over again?

I expect that `page.GotoAsync("home")` is also then slowing down the test execution in the same way if its slow because of JavaScript.

> but in fact it only shows the login steps and then quits when the page redirects (OIDC code-flow) back to the app.

Video recording is per page instance, it should not stop when navigating to a different page, reloading it or interacting with it in some way. If you have a repro, this would be very helpful to debug it further.

**Comment by brettwinters** [comment]
Hi Max - thanks for getting back to me

I've enclosed two "fake" tests (1) using your suggestion of creating the context and page for each test, and (2) my current practice:

```c#
public class ReinitContextAndPage
{
    private IPlaywright _playwright;
    private IBrowser _browser;
    private IPage _page;

    [OneTimeSetUp]
    public async Task OneTimeSetup() => _playwright = await Playwright.CreateAsync();

    [OneTimeTearDown]
    public async Task OneTimeTearDown() => _playwright.Dispose();

    [SetUp]
    public async Task Setup()
    {
        _browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions{ Headless = false });

        var context = await _browser.NewContextAsync(
            new BrowserNewContextOptions()
            {
                RecordVideoDir = "c:/users/brettwinters/desktop/"
            }
        );
        _page = await context.NewPageAsync();
        await _page.GotoAsync("https://pablofrommars.github.io/");
    }

    [TearDown]
    public async Task TearDown() => await _browser.CloseAsync();

    [Test]
    public async Task ShouldAdd() => await _page.ClickAsync("a:text('Get Started')");

    [Test]
    public async Task ShouldMultiply() => await _page.ClickAsync("a:text('Documentation')");
}

[TestFixture]
public class ResuseContextAndPage
{
    private IPlaywright _playwright;
    private IBrowser _browser;
    private IPage _page;

    [OneTimeSetUp]
    public async Task OneTimeSetup()
    {
        _playwright = await Playwright.CreateAsync();
        _browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false });

        var context = await _browser.NewContextAsync(
            new BrowserNewContextOptions()
            {
                RecordVideoDir = "c:/users/brettwinters/desktop/"
            }
        );
        _page = await context.NewPageAsync();
        await _page.GotoAsync("https://pablofrommars.github.io/");
    }

    [OneTimeTearDown]
    public async Task OneTimeTearDown()
    {
        _browser.CloseAsync();
        _playwright.Dispose();
    }

    [SetUp]
    public async Task Setup()        => await _page.ClickAsync("a.navbar-brand");

    [Test]
    public async Task ShouldAdd() => await _page.ClickAsync("a:text('Get Started')");

    [Test]
    public async Task ShouldMultiply() => await _page.ClickAsync("a:text('Documentation')");
}
```
Notes 

(a) This is a relatively small WASM app, but note that 12MB is downloaded in (1) for each test. I'm unable to host my app locally since I'm using subdomains (for a multitenant portal). I also have the extra delay caused by authentication - even though I'm persisting the authentication state between tests. 

(b) I've also attached the video files generated from (1) and (2). All are cut short, the 1(b) briefly only shows loading.

https://user-images.githubusercontent.com/26474006/149386352-4bdf935a-5ae3-45c6-9523-d4987ae17df6.mp4
https://user-images.githubusercontent.com/26474006/149386356-dc54e89a-dde3-4620-9986-14cbf1489abd.mp4

In the case of (2) only one file is generated (correctly since context is only created once), but this file only shows loading.
https://user-images.githubusercontent.com/26474006/149388900-3edc5a88-b6d7-4a7d-8f7b-114f6d448b1a.mp4

**Comment by mxschmitt** [comment]
Closing then since there are no further questions. We often see re-using the context/page when large apps e.g. due JS/WASM are tested. This is since browsers have to run these web applications - so its nothing which we can fix on our side. Sometimes we saw that instead of using debug builds, using release builds makes it slower, e.g. due the browser interprets the JS source maps.
