### ISSUE TITLE
[Feature] Base NUnit classes do not allow setting Headless = false

### ISSUE THREAD

**Issue by brettwinters** [microsoft/playwright-dotnet#1931]
In the same way that `BrowserTest` allows user's to override `public virtual BrowserNewContextOptions ContextOptions();` I'd like the `PlaywrightTest` to expose the `BrowserTypeLaunchOptions` so that we can set the `Headless` property in tests as follows:

```c#
public override BrowserTypeLaunchOptions()
{
    return new BrowserNewContextOptions
    {
         Headless = false,
         //etc
    };
}
```

or is there another way?

**Comment by brettwinters** [comment]
drilling down, I just noticed this `Headless = Environment.GetEnvironmentVariable("HEADED") != "1"` in the `BrowserService`. I guess that is workable

**Comment by Prinsn** [comment]
Okay, but drilling down into what?
