### ISSUE TITLE
[BUG] Can't download browsers on new machines

### ISSUE THREAD

**Issue by zenntenn** [microsoft/playwright-dotnet#1933]
**Context:**
- Playwright Version: 1.2.2
- Operating System: Windows
- .NET version: .Net Core 3.1
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```
playwright install
```

**Describe the bug**

When installing on a machine that does not have chromium in %USERPROFILE%\AppData\Local\ms-playwright I get the error:

```
Failed to install browsers
Error: Failed to download chromium v930007, caused by
Error: connect ETIMEDOUT 13.107.213.36:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

13.107.213.36 is a Microsoft IP address, and it gives an error page when I browse to there.

**Comment by zenntenn** [comment]
Same happens with firefox, from the same IP address

**Comment by mxschmitt** [comment]
This seems like either a temporary issue with the Azure CDN or your firewall does not allow access to it.

Is it now working?

**Comment by zenntenn** [comment]
@mxschmitt it's working now, seems it was a CDN issue that is now fixed
