### ISSUE TITLE
[Question]: How to name video and trace file as a test name (NUnit)?

### ISSUE THREAD

**Issue by dariusz-wozniak** [microsoft/playwright-dotnet#1942]
### Your question

Is there any way to pass a test name from NUnit to?:
* Trace file: `TracingStopOptions.Path`
* Video file: `BrowserNewContextOptions.RecordVideoDir`

**Comment by mxschmitt** [comment]
It's not possible by default, you'd have to add your own teardown like Bryan said and call e.g. Page.VideoAsync().SaveAsAsync("./asfa") there or pass the right value to Context.Tracing.StopAsync(new () {Path = ".."}).

**Comment by martincostello** [comment]
I do a similar thing, but with xunit, by leveraging [`[CallerMemberName]`](https://github.com/martincostello/dotnet-playwright-tests/blob/0547ca47d143655d8045239b26ec077c0a29f5ce/PlaywrightTests/BrowserFixture.cs#L31) to have the test method name passed through into my browser test fixture. That's then used to generate the file name for screenshots, traces and videos [here](https://github.com/martincostello/dotnet-playwright-tests/blob/0547ca47d143655d8045239b26ec077c0a29f5ce/PlaywrightTests/BrowserFixture.cs#L246).
