### ISSUE TITLE
[Question]: How to attach video / trace file to Azure DevOps (Test Results > Attachments)

### ISSUE THREAD

**Issue by dariusz-wozniak** [microsoft/playwright-dotnet#1943]
### Your question

I'd like to attach the video and trace file as an attachment to the Azure DevOps for passing and failing tests [NUnit]. Is there any way to do that?

In Azure DevOps, Attachments are under Tests > Result Details > Attachments menu:

![image](https://user-images.githubusercontent.com/5969160/149818777-f197ca9e-596c-43c1-b505-7dc2abaa072b.png)

**Comment by infinitejest69** [comment]
I am not sure i can be of help really there is an API you can use but not sure you would be able to call that with the right details until after uploading your test results to get run id etc. not used it much
[](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/attachments/create-test-run-attachment?view=azure-devops-rest-6.0)

I can go over what i do as its similar area.
we store all trace files, videos and screenshots in folders normally named after failing test in a results folder, we have some custom methods to determining is a test is failed or passed and move it to folder with a rename action, should be easy enough to find on google.

as part of the build pipeline we publish build artefacts which is a results folder and it grabs the folder and attaches it to a build pipeline in devops so you can see results there.

we additionally use extent reporting frameworks to make a nice HTML report with pass and fails and embeded Base64 screenshots. we also have log4Net to output any additional loggings we would not want in stakeholder facing reports .

Tech used
NUNIT
Specflow
Log4NET
Playwright
Extent Reporting
Azure Devops

**Comment by puagarwa** [comment]
which ADO task you are using in your pipeline, is it publish test result or vs test task ? if its publish test result task, then its left to your test report file on whether it contain test attachment in right format or not, i suggest you share your ADO pipeline detail for better help.

**Comment by krokofant** [comment]
I've wondered how exactly the `publishRunAttachments` field of the [VSTest@2](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops) works, but haven't come around to testing it. I wonder if this supports [NUnit attachments (`TestContext.AddTestAttachment()`)](https://docs.nunit.org/articles/nunit/writing-tests/TestContext.html#addtestattachment-37) and if that can be used to automatically upload things like videos and logs as part of the test run. If you try it out, please let me know how it works out.

**Comment by krokofant** [comment]
Okay, I couldn't help myself. The `TestContext.AddTestAttachment` works great with `VSTest@2`. It should work with `PublishTestResults@2` as well.

The logic of when to record and which files to save needs to be implemented ofc...

**Comment by puagarwa** [comment]
I havent used NUnit from quite some time but as per thier documentation, it does support NUnit2 and 3 and they mentioned they do support auto attachment upload for NUnit3 https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=nunit2%2Cyaml#nunit-3-1
