### ISSUE TITLE
[Feature] Add port forwarding support in dotnet client

### ISSUE THREAD

**Issue by puagarwa** [microsoft/playwright-dotnet#1950]
Let us know what functionality you'd like to see in Playwright and what your use case is.
JS/TS playwright has recently introduced port forwarding using socks proxy, but its not yet integrated it in dotnet client. if we could include those changes in dotnet client, it will be great for dotnet developers.
https://github.com/microsoft/playwright/pull/8315/files

Do you think others might benefit from this as well?
yes, it could help other dotnet developers.

**Comment by mxschmitt** [comment]
This is an experimental feature which was not yet released to the public. Such experimental features are not ported to language bindings until they reach stable. Closing for now and we can re-consider once it's an announced feature.

**Comment by dgozman** [comment]
Tentatively assigning to 1.19.

**Comment by mxschmitt** [comment]
Closing for now since it seems done via launchServer.
