### ISSUE TITLE
[Question]: How to start a .net 6 WebApplication from the Test Project

### ISSUE THREAD

**Issue by steinbachio** [microsoft/playwright-dotnet#1982]
### Your question

I know, this is probably more a question for either the Testing Framework (NUnit, xUnit or similar) or asp.net itself but it would probably find a good place in your documentation as people will use it as their entrypoint when creating a new test project. With .net 6 StartUp.cs is not used by default and therefore most of the existing documentation is not working.

Most of the existing documentation from asp.net or the testing frameworks is for integration tests and uses WebApplicationFactory which is skipping real HTTP and the application under test is not reachable from a browser used by Playwright.

**Comment by mxschmitt** [comment]
Playwright recommends NUnit as a test-runner and provides a getting-started for it: https://playwright.dev/dotnet/docs/test-runners

No StartUp.cs is required there. What are you planning to do?

**Comment by ShaharM7** [comment]
[](url)@mxschmitt 
With your example, we can see that you want to use a pom design pattern: https://playwright.dev/docs/pom
You are using a di design pattern to inject the page, so you need to initialize and add the page to the container.
You can initialize like in your example, and you must use the inject: "services.AddSingleton(page); for example so you have to inject also the: playwright -> browser -> browserContext and then the page.
![image](https://user-images.githubusercontent.com/44533369/209782661-b29a6484-e19b-4aa6-9d8a-93d771fd620b.png)
