### ISSUE TITLE
[Question]: Ability to set the Url on the Page ?

### ISSUE THREAD

**Issue by thomaschanneladvisor** [microsoft/playwright-dotnet#1985]
### Your question

Hi. I would like to be able to set a Page to a certain Url. I do not want to navigate to this Url.
Instead I would call SetContentAsync to add html.
I don't see a way to do this currently. Is it possible and if not any plans to allow it ?

**Comment by mxschmitt** [comment]
That's not how browsers are working, you cannot just set the URL. For your use-case network mocking might be a good fit.

So you mock the http://microsoft.com response and respond there with your custom content, see here: https://playwright.dev/dotnet/docs/network#handle-requests

**Comment by thomaschanneladvisor** [comment]
I see. Thanks for the quick response. Yeah I will look into using request interception instead.
