### ISSUE TITLE
[Question]: Azure Functions v4 Compatibility

### ISSUE THREAD

**Issue by danielbichuetti** [microsoft/playwright-dotnet#1996]
### Your question

Hi,

Is there anyone running Playwright .NET on Azure Functions v4 without the need to download browser on every run by running Main(args[]) install ? 

OS version is Debian, which miss some deps from the current version. Are there any solution ?

Best regards,

**Comment by danielbichuetti** [comment]
Also I would like to know if there is anyway of installing to a choosen directory using the parameters passed to Main of Microsoft.Playwright. Like installing to /var/tmp or anything like this.

Best regards

**Comment by mxschmitt** [comment]
You can specify a custom browser directory via environment variables: https://playwright.dev/dotnet/docs/browsers

Keep in mind that Debian is not officially supported, WebKit won't work there e.g. Only Ubuntu is supported (linux distribution): https://playwright.dev/dotnet/docs/next/intro#linux

I'd recommend Azure Container apps, this should work flawless with Playwright: https://azure.microsoft.com/de-de/services/container-apps/

**Comment by danielbichuetti** [comment]
Thanks @mxschmitt !

I've made some local tests and  used C# Parallel.ForEachAsync for spawning multiple pages. I could achieve great results with Playwright. It's a great work.

Now I'm looking on a way to implement on a serverless scenario, where hundreds of instances could be started at once. I've taken a look over Azure Functions and AWS Lambda, now based on your guidance I'll look Container Apps.

**Comment by danielbichuetti** [comment]
Using AWS Lambda I got one error saying there are missing dependencies. Is it possible to use install-deps from the assembly itself like the browsers ? Probably it isn't because of user permissions. But maybe you got some workaround for it. 

`Host system is missing a few dependencies to run browsers. `

**Comment by danielbichuetti** [comment]
> Using AWS Lambda I got one error saying there are missing dependencies. Is it possible to use install-deps from the assembly itself like the browsers ? Probably it isn't because of user permissions. But maybe you got some workaround for it.
> 
> `Host system is missing a few dependencies to run browsers. `

Looking further I could dig up solution:

`Microsoft.Playwright.Program.Main(new[] { "install-deps", "firefox" });`

Just like I imagined, root user issues:

`Switching to root user to install dependencies...`

I'll take a look over your dockerfile to grab dependencies.

**Comment by danielbichuetti** [comment]
Hey @mxschmitt , I must say that your words regarding Container Apps made me hold on tests for some hours more (finishing then now). I just made Playwright .NET work on AWS Lambda. Start time is fantastic. Just had to fine tune on custom runtime and use some flags on Chromium startup.

Thanks for the great product!

BTW: AWS Lambda .NET container image use Amazon Linux 2, which is based on RHEL. Dependencies had to be manually installed because package manager is different. But the project code made me find easily all deps.

Project is great!

Thank you!

**Comment by mxschmitt** [comment]
Awesome! I think you can also pick a custom container image which is Ubuntu based so npx playwright --install-deps will work.

Feel free to write a blog article about it, mention us and we can share it on Twitter. 🙂

Closing since it seems working.

**Comment by rhyek** [comment]
@danielbichuetti could you share your custom dockerfile for the AWS Lambda .NET based container image?

**Comment by danielbichuetti** [comment]
@rhyek Hello ! I'm sorry for the delay. It's not hard. I used one of their base images and installed the necessary software. You will need to fine tune on your code the handling of temporary files, if you don't do this (removing as per your design) the default 512 MB ephemeral storage won't be enough.

```
FROM public.ecr.aws/lambda/dotnet:6

RUN yum install -y tar gzip curl && \
    yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y nodejs npm && \
    yum install -y chromium

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npm i -D @playwright/test && \
    npx playwright install chromium && \
    chmod -R 777 /ms-playwright

WORKDIR /var/task


COPY "bin/Release/lambda-publish"  .
```

Oh, last line is lambda package directory generated using dotnet lambda tool. But for other runtime is the same idea. Remember to change to your runtime version the base image on first line.

You may find me here or on Twitter. Have a great time !

**Comment by danbasszeti** [comment]
Hi, I'm really struggling to get the .playwright folder into the right place for Azure Functions V4 to work and find the driver. Playwright keeps looking in /home/site/.playwright/node/linux-x64 etc.  I've managed to sort out my MSBuild/.csproj so that it copies it as high as possible so it works locally, but not on the server(less). 

I'm running dotnet 6 linux azure functions. Mention is made above of getting it working without having to install each time - frankly I'd be happy just having that working! Does anyone have any example code?

**Comment by cjgaspari** [comment]
> Hi, I'm really struggling to get the .playwright folder into the right place for Azure Functions V4 to work and find the driver. Playwright keeps looking in /home/site/.playwright/node/linux-x64 etc. I've managed to sort out my MSBuild/.csproj so that it copies it as high as possible so it works locally, but not on the server(less).
> 
> I'm running dotnet 6 linux azure functions. Mention is made above of getting it working without having to install each time - frankly I'd be happy just having that working! Does anyone have any example code?

were you ever able to get this working in Azure Functions v4? I am trying to also get this working in Functions, and having the exact same issue

**Comment by danbasszeti** [comment]
> > Hi, I'm really struggling to get the .playwright folder into the right place for Azure Functions V4 to work and find the driver. Playwright keeps looking in /home/site/.playwright/node/linux-x64 etc. I've managed to sort out my MSBuild/.csproj so that it copies it as high as possible so it works locally, but not on the server(less).
> 
> > 
> 
> > I'm running dotnet 6 linux azure functions. Mention is made above of getting it working without having to install each time - frankly I'd be happy just having that working! Does anyone have any example code?
> 
> 
> 
> were you ever able to get this working in Azure Functions v4? I am trying to also get this working in Functions, and having the exact same issue 

Sorry no: I eventually plumped for separating out that part of the app and running it on a Node function app instead then communicating over HTTP triggers. Can't remember if it's running puppeteer or playwright on there now.

**Comment by cjgaspari** [comment]
Oh, appreciate the quick reply! thanks so much.
