### ISSUE TITLE
[BUG] Chromium crash with bad parameters configuration

### ISSUE THREAD

**Issue by danielbichuetti** [microsoft/playwright-dotnet#2003]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Linux
- .NET version: .NET 6
- Browser: Chromium
- Extra: AWS Lambda Custom Image

**Code Snippet**
```cs
var _playwright = await Playwright.CreateAsync();

var _browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions()
            {
                Args = new []
                {
                    "--disable-gpu",
                    "",
                    "--no-sandbox",
                    "--single-process"
                },
                Timeout = 30000,
                Headless = true
            });
```

**Describe the bug**

When sending empty arg (after disable GPU line) on the string array from BrowserTypeLauncheOptions Args variable, it causes Chromium to crash.

**Comment by mxschmitt** [comment]
> AWS Lambda Custom Image

Thats not officially supported, for the official supported operating systems see here: https://playwright.dev/dotnet/docs/intro#linux

You could try setting the `DEBUG=pw:api,pw:browser` environment variable, this should give you more hints whats actually crashing and on which side its crashing (Chromium vs. Playwright).
