### ISSUE TITLE
[BUG] Playwright does not work with packages.config (.NET 4.8)

### ISSUE THREAD

**Issue by Jojoshua** [microsoft/playwright-dotnet#2004]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Win 10
- .NET version: 4.8
- Browser: N/A

**Code Snippet**

```cs
 static async Task Main(string[] args)
        {
            await Go().ConfigureAwait(false);
        }

        public static async Task Go()
        {
            using (var playwright = await Playwright.CreateAsync())
            {
                var browser = await playwright.Chromium.LaunchAsync();
                var page = await browser.NewPageAsync();
                await page.GotoAsync("https://playwright.dev/dotnet");
                await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
                await browser.DisposeAsync();
            }
        }
```

**Describe the bug**
Driver is not found upon load. Clone this project for complete reproduction

https://github.com/Jojoshua/Playwright4.8InstallIssue

**Comment by mxschmitt** [comment]
I'd recommend to migrate to PackageReference, then it should work as expected: https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

**Comment by Jojoshua** [comment]
> I'd recommend to migrate to PackageReference, then it should work as expected: https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

This worked for my plain console app but it did not work for my asp.net project. When I tried to convert it to package references an error said my project was not eligible for upgrading.

**Comment by campersau** [comment]
@Jojoshua These resources might help you with the migration:
https://github.com/NuGet/docs.microsoft.com-nuget/issues/860#issuecomment-409207305
https://stackoverflow.com/questions/57581514/vs-2015-to-2017-migrate-to-package-reference-failed/65701746

Looks like https://github.com/NuGet/Home/issues/5877 is still not completely implemented...

**Comment by Jojoshua** [comment]
> @Jojoshua These resources might help you with the migration: [NuGet/docs.microsoft.com-nuget#860 (comment)](https://github.com/NuGet/docs.microsoft.com-nuget/issues/860#issuecomment-409207305) https://stackoverflow.com/questions/57581514/vs-2015-to-2017-migrate-to-package-reference-failed/65701746
> 
> Looks like [NuGet/Home#5877](https://github.com/NuGet/Home/issues/5877) is still not completely implemented...

Thanks I will check that out and see if it works. My preference would be to migrate but it looks flaky for rebuilds. 

However migration aside, does playwright-dotnet not intend to support existing projects using packages.config?

**Comment by Jojoshua** [comment]
There are a slew of net 4.8 issues related to getting started and path drivers. This has been a blocker moving from puppeteer. Can we get a round of 4.8 fixes please?
