### ISSUE TITLE
[BUG] Microsoft.Playwright.PlaywrightException: Executable doesn't exist at ~\AppData\Local\ms-playwright\ffmpeg-1007\ffmpeg-win64.exe

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#2006]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- .NET version: 6
- Browser: Chrome / All
- Extra:

**Code Snippet**
```cs
              //BrowserContext
                BrowserNewContextOptions browserNewContextOptions = new();
                browserNewContextOptions.StorageStatePath = "state.json";
                if (!String.IsNullOrEmpty(BaseConfig.Device))
                {
                    browserNewContextOptions = _playwright.Devices[BaseConfig.Device];
                }
                if (BaseConfig.Video)
                {
                    browserNewContextOptions.RecordVideoDir = VideoPath;
                    browserNewContextOptions.RecordVideoSize = new RecordVideoSize() { Height = 720, Width = 1280 };
                }
                if (BaseConfig.HAR)
                {
                    browserNewContextOptions.RecordHarPath = ResultsPath + $@"{ResultsPath}/HAR/{_scenarioContext.ScenarioInfo.Title}.har";
                }
                browserNewContextOptions.ViewportSize = new ViewportSize() { Height = 720, Width = 1280 };
                var browserContext = await _browser.NewContextAsync(browserNewContextOptions);
```

**Describe the bug**

After updating and running playwright install it appears to be looking for a different folder name for ffmpeg
if i rename the folder in appdata it works
for some reason even deleting all browsers and re-running playwright install still downloads 1006 and we need 1007

Microsoft.Playwright.PlaywrightException: 'Executable doesn't exist at C:\Users\<myusername>\AppData\Local\ms-playwright\ffmpeg-1007\ffmpeg-win64.exe
╔═════════════════════════════════════════════════════════════════════════╗

**Comment by mxschmitt** [comment]
Try installing the browsers and dependencies with: `pwsh bin\Debug\net6.0\playwright.ps1 install`.

**Comment by infinitejest69** [comment]
No luck, 
i added .dotnet\tools and rebooted.

.\bin\Debug\net6.0\playwright.ps1
Unable to find type [Microsoft.Playwright.Program].
At C:\Users\<myusername>\source\repos\Test_UI\TestUI\bin\Debug\net6.0\playwright.ps1:5 char:6
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Playwright.Program:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by infinitejest69** [comment]
> Try this:
> 
> ```
> # If the pwsh command does not work (throws TypeNotFound), make sure to use an up-to-date version of PowerShell.
> dotnet tool update --global PowerShell
> ```
> 
> (we have it soon in the docs)

This Solved the issue, updating PowerShell. is the CLI not the preferred method for downloading the browsers now ?
Happy to close this issue

**Comment by mxschmitt** [comment]
Yes, we did not continue with advertising the CLI because the CLI injects itself into the global PATH and the PowerShell approach is not global and more relative to the project.

**Comment by 304NotModified** [comment]
related https://github.com/microsoft/playwright-dotnet/issues/2239
