### ISSUE TITLE
[Feature] Add CDPSession

### ISSUE THREAD

**Issue by chenzanyu** [microsoft/playwright-dotnet#2009]
Node.js and Python have CDPSession implementations, can this function in DOTNET?
https://playwright.dev/docs/api/class-cdpsession

**Comment by namilkimfree** [comment]
I want that feature.

**Comment by 304NotModified** [comment]
Correct link: https://playwright.dev/docs/api/class-cdpsession

**Comment by wY1k** [comment]
I want that feature.

**Comment by namilkimfree** [comment]
with stealth function

This function is required to use capture events, etc.

@mxschmitt
