### ISSUE TITLE
Remove package dependency on Macross.Json.Extensions

### ISSUE THREAD

**Issue by jgilbert2017** [microsoft/playwright-dotnet#2019]
package v1.18.1 seems to have an unnecessary dependency on `Macross.Json.Extensions` which seems to be a non-microsoft third party package that is not used.

the reference is suspect and hopefully not a supply chain attack of some sort.

**Comment by kblok** [comment]
My two cents here. It's internally use to convert enums using the `JsonStringEnumMemberConverter` class.

**Comment by jgilbert2017** [comment]
ah, i didn't see the usage because the package adds classes to the `System.Text.Json.Serialization` namespace.

still, it seems like a bad idea to ship a dependency to a third-party library like this if it can be avoided.

**Comment by jgilbert2017** [comment]
the code is MIT licencse.  perhaps just lift the class?
