### ISSUE TITLE
[Question]: How to install browsers based on published artifacts?

### ISSUE THREAD

**Issue by timmkrause** [microsoft/playwright-dotnet#2027]
### Your question

I `dotnet publish` test project(s) and package them as pipeline artifacts which are (re)used to run tests in later stages within the pipeline.

How should `playwright install` be executed in this scenario?

**Comment by timmkrause** [comment]
playwright.ps1 is not part of dotnet publish.

**Comment by mxschmitt** [comment]
You can install the browser programatically, see here: https://playwright.dev/dotnet/docs/intro#install-browsers-via-api

Let us know if this works for you!

**Comment by timmkrause** [comment]
Works like a charm. Thank you @mxschmitt.
