### ISSUE TITLE
[Question]: Setup path to driver in azure function

### ISSUE THREAD

**Issue by 12masta** [microsoft/playwright-dotnet#2032]
### Your question

I have Azure Function app on dotnet bindings. Locally everything works perfectly. After deploy I am unable to run it because of error:

_2022-02-28T13:42:06.482 [Error] Executed 'SignUpForTraining-QA' (Failed, Id=1d16ae56-cd75-4d45-aff1-c0f4c2786b4c, Duration=11ms)Driver not found: C:\home\site\.playwright\node\win32_x64\playwright.cmd_

As you see driver is not found. I found a way to make it as part of deploy package. playwright.cmd is on place but on the different path:

<img width="562" alt="Screenshot 2022-02-28 at 14 43 45" src="https://user-images.githubusercontent.com/12436120/155993342-28eb4077-03e6-417a-b8ca-a2fd051791cf.png">

Is there is a way to set the path for driver manually? Maybe by some environment variable?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/1842

We recommend Azure Container Apps instead.
