### ISSUE TITLE
[BUG]NullReferenceException after upgrade 1.18.0 to 1.19.1

### ISSUE THREAD

**Issue by coader** [microsoft/playwright-dotnet#2046]
Message: 
Test method ...  threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

  Stack Trace: 
Browser.NewContextAsync(BrowserNewContextOptions options)

**Comment by coader** [comment]
at Microsoft.Playwright.Core.Browser.<NewContextAsync>d__33.MoveNext()

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/156975362-6349f026-234e-4fb9-b703-a2dff779ecba.png)

**Comment by campersau** [comment]
Can you please try to rebuild the project?
See https://github.com/microsoft/playwright-dotnet/issues/2045#issuecomment-1059725597

**Comment by coader** [comment]
i have restored back to 1.18, show not find driver, and rebuild, it's ok.
now i'll try 1.19 again

**Comment by coader** [comment]
tks, everything is ok after rebuild, got it.
