### ISSUE TITLE
[BUG] No Assert.AreEqual available

### ISSUE THREAD

**Issue by Northimus** [microsoft/playwright-dotnet#2047]
Using:
- Microsoft.Playwright Version 1.19.1
- Windows
- .NET 6
- Browser: Chromium

Seems that documentation is outdated? I cant find "Assert.AreEqual"
![image](https://user-images.githubusercontent.com/100562706/157034127-854cd0f0-08af-4cc3-85ff-6365e9804ceb.png)
![image](https://user-images.githubusercontent.com/100562706/157034218-47064f4c-d25e-40fa-9744-7f9e23bea409.png)
There is "Assert.Equal" though, probably the same?

![image](https://user-images.githubusercontent.com/100562706/157034340-006c244a-ef3a-472c-870c-bec78f37050e.png)

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/dotnet/docs/test-runners#xunit-support

We strongly discourage using xunit.

**Comment by Northimus** [comment]
> See here: https://playwright.dev/dotnet/docs/test-runners#xunit-support
> 
> We strongly discourage using xunit.

Ok but Assert itself is from Playwright, not xunit?
