### ISSUE TITLE
[BUG] LaunchPersistentContextAsync Initialization

### ISSUE THREAD

**Issue by renerlemes** [microsoft/playwright-dotnet#2048]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Windows
- .NET version: .NET 6
- Browser: Chromium

**Code Snippet**

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
       using IPlaywright playwright = await Playwright.CreateAsync();

       BrowserTypeLaunchPersistentContextOptions browserTypeLaunchOptions = new BrowserTypeLaunchPersistentContextOptions()
       {
             Channel = "chrome"
       };

       await using var browser = await playwright.Chromium.LaunchPersistentContextAsync("chromiumData", browserTypeLaunchOptions);
    }
}
```

**Describe the bug**

When I try to use the LaunchPersistentContextAsync method to initialize the Browser, it gives the message **object reference not set to an instance of an object**. This only occurs in version 1.19.0 and 1.19.1, in version 1.18.1 this problem does not occur.

**Comment by mxschmitt** [comment]
Works for me! Could you try to provide the entire stack trace? Try rebuilding the project.

**Comment by renerlemes** [comment]
@mxschmitt the problemn is the same of this issue #2045, even being in different methods, the problem was solved to clean and rebuild the project.
