### ISSUE TITLE
Ship with embedded symbols so we get line numbers

### ISSUE THREAD

**Issue by SimonCropp** [microsoft/playwright-dotnet#2050]
so stuff like this is easier to debug

```
System.NullReferenceException: Object reference not set to an instance of an object.

System.NullReferenceException
Object reference not set to an instance of an object.
   at Microsoft.Playwright.Core.Browser.NewContextAsync(BrowserNewContextOptions options)
   at Microsoft.Playwright.Core.Browser.NewPageAsync(BrowserNewPageOptions options)
```

**Comment by mxschmitt** [comment]
Are you interested in contributing this to the project?

**Comment by SimonCropp** [comment]
side note. what branch should PRs target. main seems to target only netstandard https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Playwright.csproj#L10 but the current release also targets net5 https://github.com/microsoft/playwright-dotnet/blob/release-1.19/src/Playwright/Playwright.csproj#L10

**Comment by mxschmitt** [comment]
main is up2date, we recently changed the TFM to netstandard. It gets released released as stable in a few days.
