### ISSUE TITLE
[Question]: document.activeElement always return null

### ISSUE THREAD

**Issue by coader** [microsoft/playwright-dotnet#2054]
### Your question

I use await page.EvaluateAsync("document.activeElement") when headless=false
click input control in browser by manual, then use method above to fetch, but got null
then I have tried document.body and document.activeElement?.outerHTML, also got null

**Comment by mxschmitt** [comment]
do you have a full repro by any chance? Something like that should work: `page.EvaluateAsync("document.activeElement.tagName")`

**Comment by coader** [comment]
now I  use document.activeElement?.outerHTML, it works for me
I hope to get elementhandle of activeelement, how can I get it?
