### ISSUE TITLE
[Question] How to execute a Promisse using EvaluateAsync

### ISSUE THREAD

**Issue by renerlemes** [microsoft/playwright-dotnet#2056]
I´m trying to execute a function that is a Promisse.

The function is WPP.chat.getMessages('556492015016@c.us', { count: 3 })
https://wppconnect-team.github.io/wa-js/modules/chat.html#getMessages

How to use to get the result in Playwright. I tried to use:
...EvaluateAsync<object>("WPP.chat.getMessages('NUMBER@c.us', { count: 3 })");

It doesn't have to be exactly this function, but how to use it to get the return of a Promise function

**Comment by renerlemes** [comment]
@yury-s this example is the same as the one I reported. It always return null

**Comment by mxschmitt** [comment]
Do you have by any chance a full repro? So we can try it locally.

**Comment by renerlemes** [comment]
https://github.com/wppconnect-team/wppconnect-csharp

But for you to be able to use it, you need to have WhatsApp installed on your cell phone, authenticate and then use the Test() method

There is an example folder that has a Test Console project that you can use

**Comment by mxschmitt** [comment]
Do you have by any chance a smaller repro? Maybe the return value is not JSON serialisable?

I'd recommend to call: `page.PauseAsync()`, open DevTools of the browser and try the call manually.

**Comment by renerlemes** [comment]
Running the following code below

![image](https://user-images.githubusercontent.com/2191533/157858506-17023a42-0bff-4693-bad9-32e926c09f0e.png)

The return will be an Array with the content

![image](https://user-images.githubusercontent.com/2191533/157858455-941ac715-2a24-428d-8dd7-a006ff5ab5d1.png)

I managed to return a string Array(3), in that same format. But having the object I couldn't. 

I don't have the smallest and simplest repository.

**Comment by renerlemes** [comment]
I think that the problemn is when Playwright will make the JSON parse.
                 
```
var messages = await instance.Connection.BrowserPage.EvaluateHandleAsync("WPP.chat.getMessages().then(messages => JSON.stringify(messages));");
                    
string messagesJSON = await messages.JsonValueAsync<string>();
```
I make the JSON.stringify inside my function so I could get the string of json then use the JsonValueAsync method of Playwright  and I managed to get the array.

When I don't use JSON.stringify inside my function, it returns a JHandle and I can't use JsonValueAsync because it gives a circular reference error. So most likely it's a problem in the return of my JSON and not in Playwright
