### ISSUE TITLE
[Question]: Has anyone used Page.RouteAsync()?, i need some help

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#2066]
### Your question

Hi all, My current aim is to usepage.RouteAsync(); with route.FulfillAsync() to essentially Change the Date Time of an object in the response.
The front end has some logic that after n months a different icon would appear.
i have a POCO for my object.
so a simplified method looks like this (method simplified to remove anything related to production code.)

```
myPaginatedObject pageobject= new();
pageobject.Created = DateTime.Now.AddMonths(-1);
var body = pageobject.ToJson();

            await _page.RouteAsync("**/endpoint", async route =>
            {
                await route.FulfillAsync(new RouteFulfillOptions()
                {
                    Body = body
                });
            });

```

so my issue is the front end does a preflight call (CORS) and as soon as i step past the routeAsync Part while debugging the preflight fails with 204 and the GET just shows Pending Forever

i also tried replicating the headers with same result. any working examples or help is greatly appreciated

**Comment by infinitejest69** [comment]
Just doing some browsing and looks similar or related to this
https://github.com/microsoft/playwright/issues/12148

**Comment by mxschmitt** [comment]
Closing as per above. Please upvote the upstream issue (https://github.com/microsoft/playwright/issues/12148) which helps to prioritise.
