### ISSUE TITLE
[BUG] NullReferenceException in Connection.WrapApiCallAsync 

### ISSUE THREAD

**Issue by limbsc** [microsoft/playwright-dotnet#2074]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows
- .NET version: net6.0
- Browser: Firefox

**Related pull request**
[ check namespace for null #2067 ](https://github.com/microsoft/playwright-dotnet/pull/2067)

**Describe the bug**
If ReflectedType is null a NullReferenceException is thrown
Line in question at https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Transport/Connection.cs#L442
```
                string cSharpNamespace = sf.GetMethod().ReflectedType.Namespace;
                bool playwrightInternal = cSharpNamespace != null &&
                                          (cSharpNamespace == "Microsoft.Playwright" ||
                                          cSharpNamespace.StartsWith("Microsoft.Playwright.Core", StringComparison.InvariantCultureIgnoreCase) ||
                                          cSharpNamespace.StartsWith("Microsoft.Playwright.Transport", StringComparison.InvariantCultureIgnoreCase) ||
                                          cSharpNamespace.StartsWith("Microsoft.Playwright.Helpers", StringComparison.InvariantCultureIgnoreCase));
```
![screenshot](https://user-images.githubusercontent.com/17699776/159032483-f17b8dfe-4ad0-40de-961f-2619ca907eb8.png)

**Fix**
```
                string cSharpNamespace = sf.GetMethod().ReflectedType?.Namespace;
```

**Comment by mxschmitt** [comment]
@limbsc are you interested in creating a PR with the fix?
