### ISSUE TITLE
[Question]: how to set userAgentData in playwright C#

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright-dotnet#2080]
### Your question

Hi team,

How we can set userAgentData in playwright C#, so far we have set the UserAgent string, but the UA client hits still we are not able to change it , is there any sample or feature for that?

Many thanks

**Comment by rwoll** [comment]
Here's an example in the docs https://playwright.dev/dotnet/docs/emulation#user-agent and another as a test case https://github.com/microsoft/playwright-dotnet/blob/93bb3842a712bbd1374e5375aef6ec68bc1cfd6a/src/Playwright.Tests/BrowserContextUserAgentTests.cs#L42.

Let me know if that helps!

**Comment by rwoll** [comment]
Thanks for the clarification!

Try https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-add-init-script where your script contains something along the lines of:

```
Object.defineProperty(navigator, 'userAgentData', …)
```

This is similar to if you want to spoof `navigator.platform` concurrency return value:

```
Object.defineProperty(navigator, 'platform', { get: () => "Linux x86_64" });
```

**Comment by ahmwai** [comment]
Thanks,

Yea thats what we did already, and we are able to set the value for userAgentData , thank you for your advice
