### ISSUE TITLE
[BUG] Extra Pages in LaunchPeristentContext

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright-dotnet#2083]
Hello Team,

there is a bug, we have a code as below :

```
   string osp = @"Object.defineProperty(navigator, 'platform', {get: () => 'MacIntel', configurable: false, enumerable: true});";

  var userDataDir1 = "c:\\vcbg";

  string uu = @"Mozilla / 5.0(Macintosh; Intel Mac OS X 10_15_7) AppleWebKit / 537.36(KHTML, like Gecko) Chrome / 98.0.4758.109 Safari / 537.36";

 var browser = await playwright.Chromium.LaunchPersistentContextAsync(userDataDir1, new 
 BrowserTypeLaunchPersistentContextOptions
            {
         
                Locale = "de-DE",
                  
             
                Args = new List<string>() {  "--disable-blink-features=AutomationControlled", "--disable-blink-features", "--user-agent=" + uu, "--use-fake-ui-for-media-stream" },
                ViewportSize = null,
                IgnoreDefaultArgs = new List<string>() {  "--enable-automation" },
                IgnoreAllDefaultArgs = false,
                IgnoreHTTPSErrors = true,
                Headless = false,
                Channel = "chrome",
                TimezoneId = "Europe/Berlin",
                Timeout = 0
               
                ExecutablePath = "C:\\Users\\user\\Downloads\\ungoogled-chromium_97.0.4692.71-1.1_windows-x64\\ungoogled-chromium_97.0.4692.71-1.1_windows\\chrome.exe"


            }); ;



        
             await  browser.AddInitScriptAsync(  osp  );

            var page = await browser.NewPageAsync();
```
when you run the above code Playwright is opening 2 new tabs instated of only one new tab for the page, as we can see **await  browser.AddInitScriptAsync**, is launching a blank tab beside the page one, which we think it should not, kindly let us know why it's like that, and how we can solve this problem 

Thank you

**Comment by rwoll** [comment]
If you remove `await  browser.AddInitScriptAsync(  osp  );`, is the "extra" page still there?

It looks like you are using persistent context (`LaunchPersistentContextAsync`), so it'll startup with a new page, regardless of the addInitScript. This is different from the behavior of [`LaunchAsync`](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch).

For `LaunchPersistentContextAsync`, you can access that already pre-launched page by getting the first page in the context https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-pages.

In your script:
```
 var browser = await playwright.Chromium.LaunchPersistentContextAsync(userDataDir1,
```

`var browser` is a bit misleading here. Since you are using [`LaunchPersistentContextAsync`](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-persistent-context), you're actually getting back a [`context`](https://playwright.dev/dotnet/docs/api/class-browsercontext), not a browser.

NB: Unless you have a strong need for a persistent context, I don't recommend using it as it's stateful between runs.

**Comment by ahmwai** [comment]
thanks for the clarifications,

my question if we are going to use playwright.Chromium.LaunchAsync(), how we can set chrome command line ARG ? and how we can set binary executable path?

the reason we have used LaunchPersistentContextAsync , because we can set a command line for chrome and also use our own chrome.exe file in the ExecutablePath.

so if you can guide us on how to use it in LaunchAsync(), it will be really great

thank you

**Comment by ahmwai** [comment]
Thanks for clarifications,

we have followed your advice and we use LaunchAsync(), but here we have questioned how we can set user-data-dir , so we can let the browser save all the sessions, and storage in the specific dir, when we tried to set it as ARG we got the following error.

Pass userDataDir parameter to `browserType.launchPersistentContext(userDataDir, ...)` instead of specifying --user-data-dir argument'

at the same time, each time we launch the browser, the page opens and then closed in an auto way here is our full code


`using var playwright = await Playwright.CreateAsync();
            string uu = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36";

            var list = new List<KeyValuePair<string, string>>();
        
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA", "\"Chromium\";v=\"98\",\" Not A ;Brand\";v=\"99\",\"Google Chrome\";v=\"98\""));
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA-Mobile", "?0"));
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA-Platform", "\"macOS\""));
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA-Full-Version", "\"98.0.4758.109\""));
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA-Platform-Version", "\"10.15.7\""));
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA-Arch", "\"x86\""));
            list.Add(new KeyValuePair<string, string>("Sec-CH-UA-Bitness", "\"64\""));
            list.Add(new KeyValuePair<string, string>("Sec-CH-Device-Memory", "8"));
            list.Add(new KeyValuePair<string, string>("SSec-CH-UA-Model", "\"\"\""));
            var proxy = new Microsoft.Playwright.Proxy
            {
                Server = "http://154.21.0.0",
                Username = "xxx",
                Password = "xxxx"
            };
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
               
                Args = new List<string>() { "--user-data-dir=c:\\fgghhooo",
                       "--disable-blink-features=AutomationControlled", "--user-agent=" + uu, "--use-fake-ui-for-media-stream" },
             
                IgnoreDefaultArgs = new List<string>() { "--user-data-dir","--enable-automation" },
                IgnoreAllDefaultArgs = false,
              
                Headless = false,
                Channel = "chrome",
              
                Timeout = 0,
              
                ChromiumSandbox = false,
                // Proxy = proxy,
                ExecutablePath = "C:\\Users\\user\\Downloads\\ungoogled-chromium_97.0.4692.71-1.1_windows-x64\\ungoogled-chromium_97.0.4692.71-1.1_windows\\chrome.exe"
            }) ;
           
               var options = new BrowserNewContextOptions
            {
              
            
               
                Locale = "de-DE",
                
                ExtraHTTPHeaders=list

                
            
            };

          
                await using var context = await browser.NewContextAsync(options);

          
                  var page = await browser.NewPageAsync();
                  await  page.GotoAsync("https://google.com");
`

**Comment by rwoll** [comment]
Gotcha—if your use case requires a custom userDataDir, you must use persistent context. What's in the userDataDir that you require? Some state is available to dump/restore via the Playwright API so you might not need to manage that dir.

See https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-storage-state regarding dumping storage state (as well https://playwright.dev/dotnet/docs/auth#session-storage depending on which storage you're after).

**Comment by ahmwai** [comment]
The last question, if used playwright.Chromium.LaunchAsync,  the Chromium always launching in Incognito mode, how we cant disable Incognito mode to normal mode?

**Comment by rwoll** [comment]
> The last question, if used playwright.Chromium.LaunchAsync, the Chromium always launching in Incognito mode, how we cant disable Incognito mode to normal mode?

You can't disable the ephemeral profile/contexts with LaunchAsync; the isolation is its core feature 😄 

If this is an issue for you, then you will need to stick with [LaunchPersistentContextAsync](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-persistent-context). The "extra" page will be there on launch; it should be in https://playwright.dev/docs/api/class-browsercontext#browser-context-pages, so you can access it without creating an additional page.

**Comment by ahmwai** [comment]
Thanks, can you provide a sample of how to access the first tab which has been created by default? 

As the doc  https://playwright.dev/docs/api/class-browsercontext#browser-context-pages , not clear to access the first tab

**Comment by rwoll** [comment]
Oops—I linked the Node.js doc! Here's the .NET version: https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-pages

So something along the lines of:

```c#
        using var playwright = await Playwright.CreateAsync();
        await using var context = await playwright.Chromium.LaunchPersistentContextAsync(userDataDir, …);
        var pages = await browser.Pages();
        var page = pages.First(); // This line is the workaround for your use case. However, for best results—assuming you can allow the extra initial tab—do: var page = await browser.NewPageAsync(); there's no guarantee that first tab will be there in the future using the workaround. Use at your own risk!
```
