### ISSUE TITLE
[BUG] Project Setup / Installation

### ISSUE THREAD

**Issue by zhouyapengzi** [microsoft/playwright-dotnet#2086]
**Context:**
- Playwright Version: [1.19.1]
- Operating System: [Windows]
- .net core version: [3.1]
- Browser: [All, Chromium, Firefox, WebKit]

**Describe the bug**
The project only generates mac and Linux folder in .playwright when build in windows VM.

In my dotnet core playwright project property, I set
```
<PropertyGroup>
	<PlaywrightPlatform>win</PlaywrightPlatform>
</PropertyGroup>
 ```
However, when I build the playwright project in windows, there were only mac and Linux generated in the .playwright folder. 
 ![image](https://user-images.githubusercontent.com/32387778/161276607-f3d85cd6-1ce3-4a2c-9029-1bd013b40b2f.png)

any idea why win folder was missing and how can I prevent it happen?

**Comment by mxschmitt** [comment]
I tried to reproduce it but it works for me. Could you share a repro repository with us?
