### ISSUE TITLE
[Question]: Top-level statements

### ISSUE THREAD

**Issue by Sa1Gur** [microsoft/playwright-dotnet#2088]
### Your question

Would it be beneficial to change documentation examples to top-level statements? A would gladly make PR

**Comment by mxschmitt** [comment]
Sure, this would simplify it a lot I guess!

The docs are located here: https://github.com/microsoft/playwright/tree/main/docs/src

**Comment by Sa1Gur** [comment]
I created PR https://github.com/microsoft/playwright/pull/13559.
