### ISSUE TITLE
[BUG] Release notes link to wrong place in docs

### ISSUE THREAD

**Issue by midgleyc** [microsoft/playwright-dotnet#2097]
The release notes for [v1.21.0](https://github.com/microsoft/playwright-dotnet/releases/tag/v1.21.0) link to "https://playwright.dev/dotnet/dotnet" for the dotnet docker changes. I think this should be https://playwright.dev/dotnet/docs/docker.

**Comment by mxschmitt** [comment]
Fixed, thanks!
