### ISSUE TITLE
[BUG] CreateReadStreamAsync returns stream with System.NotImplementedException

### ISSUE THREAD

**Issue by GianHodgson** [microsoft/playwright-dotnet#2106]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Windows
- .NET version:NET 6
- Browser: Chromium
- Extra:

**Code Snippet**

```cs
using Microsoft.Playwright;

namespace CsvHelperTests
{
    class Program
    {
        static async Task Main(string[] args)
        {
            
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync();
            var page = await browser.NewPageAsync();

            await page.GotoAsync("https://www.mockaroo.com/");

            var waitForDownloadTask = page.WaitForDownloadAsync();

            await page.ClickAsync("text=Download Data");

            var download = await waitForDownloadTask;
            var stream = await download.CreateReadStreamAsync();

            if (stream != null)
            {
                Console.WriteLine(stream.Length);
                
            }
            
        }   
    }
   
}
```

**Describe the bug**

Downloading a stream of a csv and then accessing the stream gives a System.NotImplementedException. I tried downloading different csv files from different websites with same result.

**Comment by mxschmitt** [comment]
This is expected since Length is not implemented. You can do `var content = await new StreamReader(stream).ReadToEndAsync());` which should work as well as `await download.SaveAsAsync('./foo.csv');`.

does this work for you?

**Comment by GianHodgson** [comment]
That works, but for my use case I wanted to consume the stream itself. In 1.15.0 this was possible:

```
using Microsoft.Playwright;

namespace PlaywrightStreamTest
{
    class Program
    {

        static async Task Main(string[] args)
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync();

            var contextOption = new BrowserNewContextOptions()
            {
                AcceptDownloads = true
            };
            var context = await browser.NewContextAsync(contextOption);
            var page = await context.NewPageAsync();

            await page.GotoAsync("https://www.mockaroo.com/");

            var waitForDownloadTask = page.WaitForDownloadAsync();

            await page.ClickAsync("text=Download Data");

            var download = await waitForDownloadTask;
            var stream = await download.CreateReadStreamAsync();
            
                        
            Console.WriteLine(stream.Length);
                      
        }   
    }
```

Is there any way to still do this?

**Comment by mxschmitt** [comment]
In 1.15 the stream implementation was not really a stream implementation internally - we fixed that but this has as a drawback that it does not support reading the length.

why do you rely on reading the length? If so, we can create probably a feature request out of it.

**Comment by GianHodgson** [comment]
I don't specifically rely on the length. That was just an example. I use the library  [CsvHelper](https://github.com/JoshClose/CsvHelper) to parse csv files. It can read csv files from a stream. I used to be able to pass it the stream from CreateReadStreamAsync and it would parse it.

I will close this since it's not a bug. Thanks for the explanation.
