### ISSUE TITLE
[Question] Is the raw CDP socket exposed like in the javascript library?

### ISSUE THREAD

**Issue by craysiii** [microsoft/playwright-dotnet#2107]
### Your question

I am trying to replicate this: https://github.com/microsoft/playwright/issues/592 is the C# library. 

Is it currently possible? I wasn't able to find a way to perform a raw send over CDP to Chrome.

Thanks in advance.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2009
