### ISSUE TITLE
[BUG] All Tests run into Timeout Exception

### ISSUE THREAD

**Issue by MrEdHardy** [microsoft/playwright-dotnet#2112]
**Context:**
- Playwright Version: .net Version 1.21.0
- Operating System: Windows 10 20H2 (Build 19042.1645)
- .NET version: .Net 5.0
- Browser: All
- Extra: Nothing special

**Code Snippet**

(essentially the Getting Started-Example)
```cs
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace Test
{
    public class Tests: PageTest
    {
        [Test]
        public async Task ShouldAdd()
        {
            int result = await Page.EvaluateAsync<int>("() => 7 + 3");
            Assert.AreEqual(10, result);
        }

        [Test]
        public async Task ShouldMultiply()
        {
            int result = await Page.EvaluateAsync<int>("() => 7 * 3");
            Assert.AreEqual(21, result);
        }

    }
}
```

**Describe the bug**
Initially all tests worked fine, but they stopped working entirely at an unseemingly random point throwing a timeout exception every time I run these tests. During execution I noticed that the node.exe process always sat at 0% cpu usage.
*What I already tried:*
 - Tried in various unrelated new Test-Projects, all with the same issue
 - uninstalling and reinstalling the nuget package
 - manually killed the node process 
 - manually deleted and reinstalled all browsers from appdata/local/ms-playwright
 - manually deleted the node-cache folder
 - rebuilt the project assemblies/project files multiple times 
 
**The Stacktrace I got in VS2019:**
Message: 
    System.TimeoutException : Timeout 30000ms exceeded.
  Stacktrace: 
    Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) Zeile 164
    Connection.WrapApiCallAsync[T](Func\`1 action, Boolean isInternal)
    BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) Zeile 61
    <<Register>b__0>d.MoveNext() Zeile 36
    --- End of stack trace from previous location ---
    WorkerAwareTest.RegisterService[T](String name, Func\`1 factory) Zeile 53
    BrowserTest.BrowserSetup() Zeile 46
    GenericAdapter\`1.BlockUntilCompleted()
    NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
    AsyncToSyncAdapter.Await(Func\`1 invoke)
    SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, MethodInfo method)
    SetUpTearDownItem.RunSetUp(TestExecutionContext context)
    <.ctor>b__0(TestExecutionContext context)
    <>c__DisplayClass1_0.<Execute>b__0()
    BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

**Stracktrace when run from Powershell with Verbose Debugging enabled:**
![error_playwright](https://user-images.githubusercontent.com/56278644/165099435-675f6923-2eb2-4d70-b36b-a2dc04a209ed.png)

**Comment by mxschmitt** [comment]
So the launch is timing out, could you set the following environment variable to see if the actual browser launch was successful?

`DEBUG=pw:browser`

if this does not show anything useful, protocol logs might help: `DEBUG=pw:protocol`

**Comment by MrEdHardy** [comment]
Problem seems to have fixed itself. Thanks for your help anyways!
