### ISSUE TITLE
[Question]: How to enable and use HTML report

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#2114]
### Your question

The 1.17 release note lists the HTML reporter but i cant see anywhere else in the documentation to enable or config the report

https://playwright.dev/dotnet/docs/release-notes#version-117

is this report only in the JS version test runner ?

**Comment by akshaysarode31** [comment]
@mxschmitt Can I add Node.js code to a C# framework to generate a HTML report or convert .zip to HTML?
