### ISSUE TITLE
[Feature] Support Ubuntu 22.x jammy

### ISSUE THREAD

**Issue by jgilbert2017** [microsoft/playwright-dotnet#2117]
ubuntu 22.x install-deps fails.  it seems as some packages were renamed:

ttf-unifont -> fonts-unifont
ttf-ubuntu-font-family -> fonts-freefont-ttf

that's as far as i get before the script aborts.

(perhaps an options to keep chugging along even if one step fails so the user can manually install any failed deps?)

edit: looks like an upstream issue
https://github.com/microsoft/playwright/issues/13738

**Comment by mxschmitt** [comment]
Yup, folding into https://github.com/microsoft/playwright/issues/13738 we try to implement it for 1.22
