### ISSUE TITLE
[Feature] Ship native macos/arm driver

### ISSUE THREAD

**Issue by bjharo** [microsoft/playwright-dotnet#2122]
**Context:**
- Playwright Version: 1.21.0
- Operating System: macOS
- .NET version: .NET 6
- Browser: Chrome, Edge
- Extra: M1 processor using the ARM version of the .NET SDK

**Code Snippet**

There's no real example here. Just run any Playwright UI tests on a MacBook with an M1 processor and target either Chrome or Edge.

**Describe the bug**

I do the majority of my test development on a MacBook with an M1 processor and I've noticed that the version of node that gets pulled down whenever I build my testing projects is an x86_64 (Intel) executable.

![image](https://user-images.githubusercontent.com/3472778/166253115-728873ff-88ba-4a82-9f02-c15588dbabe7.png)

Obviously this means that as my tests execute, any calls that go through node have to go through the Rosetta translation layer.  Normally, this not a problem if I'm targeting Chromium, Webkit or Firefox. When I install those browsers with playwright.ps1, the executables are ARM binaries. So, I start a test run, node starts then the browsers running native ARM code and the tests execute relatively fast.

The problem comes in when I want to target Chrome or Edge. Both Chrome and Edge are universal binaries so they include code for both x86_64 and ARM. If I just start up Chrome or Edge from Launchpad, the ARM version executes. When running tests, though, the x86_64 versions of these browsers run. I'm assuming it's because node is starting the browser process. From what I can tell, when a parent process is x86_64 and it spawns child processes, Rosetta will prefer the parent process's architecture for the child. So in this case, Chrome and Edge are universal. Node (x86_64) starts them and Rosetta chooses to use the x86_64 versions of the browsers instead of ARM.

As a test, I replaced node with the ARM equivalent an re-ran my test suite (without rebuilding the code). When running with x86_64 node, my tests took a little over 8 minutes to run with Chrome. With the ARM native version of node, they tests took a little under 4.5 minutes.

**Comment by rhyek** [comment]
Just noticed this myself. Recently purchased a macbook with m1 and am trying to avoid installing Rosetta. I symlinked the node file to my globally installed arm64 version and everything seems to be working fine.

**Comment by mxschmitt** [comment]
Looks like this was done in https://github.com/microsoft/playwright-dotnet/pull/2500.
