### ISSUE TITLE
[Question]: Browser install Fail

### ISSUE THREAD

**Issue by poulhoecherl** [microsoft/playwright-dotnet#2131]
### Your question

**Context:**

Playwright Version: NuGet package version of playwright 1.21.0
Operating System: Windows 10 Ent v10.0.19042
.NET version:  .Net 6
Browser: All
Environment: Visual Studio 2022 Ent, Dev Prompt Console

**Issue Description**

Working in Visual Studio (Dev Command console) I am getting the following errors when executing 
  '**_pwsh .\playwright.ps1 install_**' : 

==================================>
  Failed to install browsers
  Error: Failed to download chromium v1000, caused by
  Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
      at TLSSocket.emit (node:events:390:28)
      at TLSSocket._finishInit (node:_tls_wrap:944:8)
      at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
==================================<

The same behavior occurs when running the command outside Visual Studio in a Developer Command console (via Windows Terminal).

I can hit the download server fine from my network and download a browser zip file (like chromium-win64) from a browser. 

Is this a known issue or am I missing a configuration step perhaps?

**Comment by mxschmitt** [comment]
Most likely this is an issue with your environment, some certificate might be missing in your OS certificate storage e.g. not include the https certificate for https://playwright.azureedge.net/builds/index.html.
