### ISSUE TITLE
[Question]:   resizeTo() and moveTo()  not working in Chromium

### ISSUE THREAD

**Issue by akblissweb** [microsoft/playwright-dotnet#2137]
### Your question

resizeTo(w,h)   moveTo(x,y) 

Any reason why these functions silently fail in Playwright (Chromium)  but not in the normal browser ?

They work ok in Playwright (Firefox).   

I have also tried a non-playwright Chromium incognito and they also still work.

**Comment by mxschmitt** [comment]
Probably because Playwright spawns Chromium with a fixed window size. You can prevent that from doing by creating the context with `ViewportSize = ViewportSize.NoViewport`
