### ISSUE TITLE
[Feature] Provide support for CDPSession in .NET

### ISSUE THREAD

**Issue by architgarg95** [microsoft/playwright-dotnet#2147]

**Comment by rwoll** [comment]
To set expectations, it's unlikely we'd do this in the near-term as accessing CDP directly is generally discouraged. Can you elaborate more on your use case?

**Comment by architgarg95** [comment]
need to know like which cookies are being set by which script, basically checking the call stack of all requests and determining the origin point.

**Comment by architgarg95** [comment]
> To set expectations, it's unlikely we'd do this in the near-term as accessing CDP directly is generally discouraged. Can you elaborate more on your use case?

need to know like which cookies are being set by which script, basically checking the call stack of all requests and determining the origin point.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2009
