### ISSUE TITLE
How to connect with running browser using Playwright with ConnectOverCDPAsync?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-dotnet#2152]
### Your question

Hello:
I want to connect with a running browser, like Chrome to visit some web site, like bing.com, and then change the web page, like google and trying to type some text to search.
I have the following C# code to launch Chrome browser:

```c#
            Process proc = new();
            proc.StartInfo.FileName = Chrome_Binary;
            string remote_chrome_browser = string.Format("{0} {1}",
                “https://www.bing.com/”, " --new-window --remote-debugging-port=9222");
            proc.StartInfo.Arguments = remote_chrome_browser;
            proc.Start();
```

I can see the Chrome browser is launched and home page of Bing is opened.
I have the following C# trying to connect with the running Chrome browser, and I want to connect with the Bing home page, the first tab.  The following code works:

```c#
        private async Task ConnectChrome()
        {
            int Port = 9222;
            using HttpClient httpClient = new ();
            string? url = null;
            while (url == null)
            {
                try
                {
                    var version = 
                        await httpClient.GetFromJsonAsync<JsonElement>($"http://localhost:{Port}/json/version/");
                    url = version.GetProperty("webSocketDebuggerUrl").GetString();
                    Debug.Print(url);
                }
                catch
                {
                    await Task.Delay(1000);
                }
            }
            using IPlaywright? playwright = await Playwright.CreateAsync();
            await using IBrowser? browser = 
            await playwright.Chromium.ConnectOverCDPAsync(url);
            var page = browser.Contexts[0].Pages[0];
            await page.GotoAsync("https://www.google.com/");
        }

However, I want to add some delay in typing the searching text, so it more like a human.  So I want to change my code, so it looks like this:
        private async Task ConnectChrome()
        {
            int Port = 9222;
            using HttpClient httpClient = new ();
            string? url = null;
            while (url == null)
            {
                try
                {
                    var version = 
                        await httpClient.GetFromJsonAsync<JsonElement>($"http://localhost:{Port}/json/version/");
                    url = version.GetProperty("webSocketDebuggerUrl").GetString();
                    Debug.Print(url);
                }
                catch
                {
                    await Task.Delay(1000);
                }
            }
            BrowserTypeLaunchOptions browser_options =
            new() { Headless = false, Channel = "chrome", SlowMo = 100 };
            IPlaywright? playwright = await Playwright.CreateAsync();
            IBrowser? browser =
                await playwright.Chromium.LaunchAsync(browser_options);
            await playwright.Chromium.ConnectOverCDPAsync(url);
            IPage? page = browser.Contexts[0].Pages[0];
            await page.GotoAsync("https://www.google.com/");
        }
```
But the above code did NOT work, I got run time error:
Inner Exception 1:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name.
I want to know how I can fix this, I think there is at least one tab opening, showing Bing home page now, why I get such error.
Please advise,
Thanks,

**Comment by mxschmitt** [comment]
Playwright does the `http://localhost:{Port}/json/version/");` for you already internally. So you can just pass `http://localhost:9222` it will just work.

This is expected, because you run on one hand your browser manually (lets call it browser1) and on the other hand you start another browser via Playwright (browser2). But you only connect to your manual launched browser (browser1), so the slowMo does not apply there. You can pass the slowo to the ConnectOverCDPAsync method, as a second parameter and then it should work as expected.

Can you share a full repro with us where the pages don't get correctly added again? I added a test and it passes for me.

**Comment by zydjohnHotmail** [comment]
The fact is: I searched quite a lot on line, but I didn't see any real example for using ConnectOverCDPAsync  with slowMo parameter.
If you can give me an example using my above code, then I will give you the whole project, if I can finish the test with a success!
Thanks,

**Comment by mxschmitt** [comment]
```c#
BrowserType.ConnectOverCDPAsync($"ws://localhost:{Server.Port}/ws", new()
            {
                SlowMo = 1000,
            })
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  I give you the C# form1.cs, it is almost all the code in my project.
My IDE is Visual Studio 2022 Version 17.2.2, C# project for WinForms, target .NET 6.0 on X64 CPU.
The following is the form1.cs:
using Microsoft.Playwright;
using System.Diagnostics;
using System.Net.Http.Json;
using System.Text.Json;

namespace PlaywrightRunningChromeForm
{
    public partial class Form1 : Form
    {
        public const int Debug_Port = 9222;
        public const string Chrome_Binary =
            @"C:\Program Files\Google\Chrome\Application\chrome.exe";
        public const string Chrome_Running_Parameter =
            @" --new-window --remote-debugging-port=9222";

        public Form1()
        {
            InitializeComponent();
            StartPosition = FormStartPosition.CenterScreen;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            Process proc = new();
            proc.StartInfo.FileName = Chrome_Binary;
            string remote_chrome_browser = string.Format("{0} {1}",
                "https://bing.com/", Chrome_Running_Parameter);
            proc.StartInfo.Arguments = remote_chrome_browser;
            proc.Start();
        }

        private async Task BTN_ConnectChrome()
        {
            int Port = 9222;
            using HttpClient httpClient = new ();
            string? url = null;
            while (url == null)
            {
                try
                {
                    var version = 
                        await httpClient.GetFromJsonAsync<JsonElement>($"http://localhost:{Port}/json/version/");
                    url = version.GetProperty("webSocketDebuggerUrl").GetString();
                    Debug.Print(url);
                }
                catch
                {
                    await Task.Delay(1000);
                }
            }
            using IPlaywright? playwright = await Playwright.CreateAsync();
            await using IBrowser? browser =
            await playwright.Chromium.ConnectOverCDPAsync(url, new() { SlowMo = 100 });
            var page = browser.Contexts[0].Pages[0];
            await page.GotoAsync("https://www.google.com/");
        }


        private async Task BTN_LoginTikTok()
        {
            string ws_version =
                $"http://localhost:{Debug_Port}/json/version/";
            using HttpClient httpClient = new();
            string? url = null;
            while (url == null)
            {
                try
                {
                    JsonElement version =
                        await httpClient.GetFromJsonAsync<JsonElement>(ws_version);
                    url = version.GetProperty("webSocketDebuggerUrl").GetString();
                }
                catch
                {
                    await Task.Delay(1000);
                }
            }
            using IPlaywright? playwright = await Playwright.CreateAsync();
            await using IBrowser? browser =
            await playwright.Chromium.ConnectOverCDPAsync(url, new() { SlowMo = 100 });
            var page = browser.Contexts[0].Pages[0];
            await page.GotoAsync(TikTok_Login_Url);
            await page.TypeAsync("input >> nth=0", "zydjohn@hotmail.com");
            await Task.Delay(1000);
            await page.TypeAsync("input >> nth=1", "Video@2022");
            await Task.Delay(10000);
            await page.Locator(TikTok_Submit_Login_From_Xpath).ClickAsync();
            Console.ReadLine();
            Console.Beep();
            await Task.Delay(1000000);
        }

        private async void BTNConnectChrome_Click(object sender, EventArgs e)
        {
            await BTN_ConnectChrome();
        }

        private async void BTNLoginTikTok_Click(object sender, EventArgs e)
        {
            await BTN_LoginTikTok();
        }
    }
}
