### ISSUE TITLE
How to use proxy with ConnectOverCDPAsync?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-dotnet#2167]
### Your question

Hello:
I can use the following C# code to connect with running Chrome browser:

    private void Form1_Load(object sender, EventArgs e)
    {
        Process proc = new();
        proc.StartInfo.FileName = Chrome_Binary;
        string remote_chrome_browser = string.Format("{0} {1}",
            "https://bing.com/", Chrome_Running_Parameter);
        proc.StartInfo.Arguments = remote_chrome_browser;
        proc.Start();
    }

    private async Task BTN_ConnectChrome()
    {
        int Port = 9222;
        using HttpClient httpClient = new ();
        string? url = null;
        while (url == null)
        {
            try
            {
                var version = 
                    await httpClient.GetFromJsonAsync<JsonElement>($"http://localhost:{Port}/json/version/");
                url = version.GetProperty("webSocketDebuggerUrl").GetString();
                Debug.Print(url);
            }
            catch
            {
                await Task.Delay(1000);
            }
        }
        using IPlaywright? playwright = await Playwright.CreateAsync();
        await using IBrowser? browser =
        await playwright.Chromium.ConnectOverCDPAsync(url, new() { SlowMo = 100 });
        var page = browser.Contexts[0].Pages[0];
        await page.GotoAsync("https://www.google.com/");
    }
But for some web site, I have to use proxy due to geographic limits.
So I want to launch browser to visit https://bing.com/ first, then attach playwright to the running Chrome browser with proxy, which needs user name, password to login to the proxy.  Finally, I want to let Chrome browser to visit https://www.google.com/ with proxy settings.
I can’t find helpful example.
Please advise,
Thanks,

**Comment by mxschmitt** [comment]
You can either set the proxy when launching the browser, as a CLI argument, see [here](https://peter.sh/experiments/chromium-command-line-switches/): `--proxy-server`.

or when connecting to a the browser via CDP, you create a new context, there you can also pass the proxy options in the context options.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  I studied the first advice, but I can't see any user name/password for Windows.  Do I have to input user name, password by hand if I use CLI argument?
For the second advice, do you have any code example or some web page with detailed information?
Thanks,

**Comment by mxschmitt** [comment]
This is not supported by Chromium, see here: https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#proxy-credentials-in-manual-proxy-settings

Instead of using CDP, you can use Node.js and browserType.launchServer({proxy: {...}}) which supports credentials. There you can connect using BrowserType.ConnectAsync then see here: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server

**Comment by zydjohnHotmail** [comment]
Hello:
Let me know if it is supported by MS edge, if yes, then I can use MS edge, I don't care if I can use Chromium.
Thanks,

**Comment by mxschmitt** [comment]
yes, you can use any browser there, for edge you can use the edge channel.
