### ISSUE TITLE
HTML reporter

### ISSUE THREAD

**Issue by anandjaisy** [microsoft/playwright-dotnet#2172]
These features are available for node.js applications. Is there any possibility to make this available for .NET core applications

HTML reporter
[Using reporters](https://playwright.dev/docs/test-reporters#using-reporters)
[Built-in reporters](https://playwright.dev/docs/test-reporters#built-in-reporters)
[Custom reporters](https://playwright.dev/docs/test-reporters#custom-reporters)
[Third party reporter showcase](https://playwright.dev/docs/test-reporters#third-party-reporter-showcase)

**Comment by mxschmitt** [comment]
These are test-runner exclusive features. For .NET you can use reporters which are available for nunit or mstest.

**Comment by kolpav** [comment]
@mxschmitt By quickly skimming through html-reporter code it seems it wouldn't be that hard to make it take trace files from alternative source 

https://github.com/microsoft/playwright/blob/8c416653f9a6e32202f156880f171d5db3ec9537/packages/html-reporter/src/index.tsx#L48-L53

Even better make it into PWA same as trace viewer where you can point it to url containing traces or something like that. Please reconsider making this great feature available to users from other languages even as long term goal.
