### ISSUE TITLE
How to use the repo to upload files in parallel?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-dotnet#2183]
### Your question

Hello:
I have 2 channels with social media (like Youtube), I want to upload some video files (.mp4 format) to my accounts.
For each account, I have to login, then upload files one by one, then after all files uploaded, I will logout. For total files more than 10, but less than 20, then upload the first half (less than 10) to the first channel; upload the second half (from 10 to 20) to the second channel.
I can do this one by one in a loop.  However, uploading even one file takes a long time, esp. when there are some SRT files to be uploaded.
I want to know if I can upload videos files in parallel, that is upload video files to 2 channels at the same time, each channel has its different user name, password.
From my testing, if I use ConfigureAwait(true); for each channle, then the loop control will wait until one channel finishes then go to the next channel.
But if I change it to use ConfigureAwait(false); then the upload mix up, I mean the files should go to channel one, they also go to channel two.
Please advise on how I can do this at the same time without mixing up files.
Thanks,

**Comment by techpro8791** [comment]
@zydjohnHotmail 
NUnit Project - In the fixture life cycle, you will need to run your test using a different instance per case "LifeCycle.InstancePerTestCase". 

```
[TestFixture]
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
[Parallelizable(ParallelScope.All)]
```

SpecFlow Project -  You may have to employ the use of Context to inject each page instance

**Comment by mxschmitt** [comment]
Playwright only recommends ConfigureAwait(false). Uploading can be done using SetInputFiles as usual, see here: https://playwright.dev/dotnet/docs/input#upload-files

**Comment by techpro8791** [comment]
> Playwright only recommends ConfigureAwait(false). Uploading can be done using SetInputFiles as usual, see here: https://playwright.dev/dotnet/docs/input#upload-files

I think he requested a help with parallel run. He already had mentioned that he could upload files. I have faced same problems with parallel run in the past that was why I suggested he use “InstancePerTestcase” for NUnit project or “Contex” on SpecFlow project. I think all he needs is to run separate threads and avoid a clash which in turn evoke a test failure.

**Comment by zydjohnHotmail** [comment]
Hello:
As I can't find useful example for what you said.  Can you show me if you have similar project for such thing.  Like you have to login to someweb sites with multiple accounts, and upload some things at the same time?  Youtube put limit to upload only 10 videos per day, but I can have sometime 100+ videos, and each video could have 5 different language subtitle files.  In order to upload all videos, I may need to have around 10 accounts, but uploading video one by one will take more than 24 hours in the current situation.
