### ISSUE TITLE
[BUG] Wrong docker manifest

### ISSUE THREAD

**Issue by shaibarlev** [microsoft/playwright-dotnet#2195]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.23
- Operating System: [e.g. Windows, Linux or Mac]Windows 11 insider
- .NET version: [e.g. .NET 6] .Net 6.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
Docker desktop 4.10

**Describe the bug**
Try to pull docker image :
docker pull mcr.microsoft.com/playwright/dotnet:v1.23.0-focal
Error response from daemon: manifest for mcr.microsoft.com/playwright/dotnet:v1.23.0-focal not found: manifest unknown: manifest tagged by "v1.23.0-focal" is not found

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
We are currently publishing v1.23, should be good in ~30 minutes!
