### ISSUE TITLE
[BUG] Chromium browser channel not set when run in docker

### ISSUE THREAD

**Issue by bloodgang94** [microsoft/playwright-dotnet#2198]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Docker
- .NET version: NET 6
- Browser: Chrome, MSEdge

**Code Snippet**

```cs
 public static async Task<IBrowser> CreateDriverAsync(PlaywrightConfig pwDto)
        {
            var playwright = await Playwright.CreateAsync();
            var browser = pwDto.Browser switch
            {
                Browser.Chrome => playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions() { Channel = "chrome"}),
                Browser.Firefox => playwright.Firefox.LaunchAsync(),
                Browser.Chromium => playwright.Chromium.LaunchAsync(),
                Browser.WebKit => playwright.Webkit.LaunchAsync(),
                _ => throw new NotImplementedException(nameof(pwDto.Browser))
            };

            return await browser;
        }
```

`
```
ARG PLAYWRIGHT_VERSION=1.23.0

FROM mcr.microsoft.com/playwright/dotnet:v${PLAYWRIGHT_VERSION}-focal

WORKDIR /src
COPY ["PwSpecFlowDemoTest/PwSpecFlowDemoTest.csproj", "PwSpecFlowDemoTest/"]
RUN dotnet restore "PwSpecFlowDemoTest/PwSpecFlowDemoTest.csproj"
COPY . .

WORKDIR /src/PwSpecFlowDemoTest
RUN dotnet build "PwSpecFlowDemoTest.csproj" -c Release -o /app/build

CMD dotnet test PwSpecFlowDemoTest.csproj
```
`

**Describe the bug**

Hello! I'm using the official docker image mcr.microsoft.com/playwright/dotnet:v1.23.0-focal.
Faced with the problem of launching the browser chrome and msedge

```
Error:
   error message:
    System.AggregateException : One or more errors occurred. (Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "pwsh bin\Debug\netX\playwright.ps1 install chrome") (Object reference not set to an instance of an object.)
---- Microsoft.Playwright.PlaywrightException : Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
```

I set the channel like this `playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions() { Channel = "chrome"})`
Locally everything works fine.

**Comment by bloodgang94** [comment]
UPD
if you add a link
RUN pwsh /app/build/playwright.ps1 install chrome
That is no error.

**Comment by mxschmitt** [comment]
This is expected. Only chromium, Firefox and webkit are baked inside the Docker image.

Since most of the users only test on them.

**Comment by bloodgang94** [comment]
> Это ожидаемо. Только хром, Firefox и webkit запекаются внутри образа Docker.
> 
> Так как большинство пользователей тестируют только на них.

Ok
`Why pwsh bin\Debug\netX\playwright.ps1 install`
does not install chrome browser?
But only
`pwsh bin\Debug\netX\playwright.ps1 chrome`

**Comment by mxschmitt** [comment]
The Playwright Docker image only contains the basic browser, chromium, firefox, and webkit.

The branded browsers, like Google Chrome or Microsoft Edge, you need to install manually via the CLI like you showed in your previous message.

**Comment by 304NotModified** [comment]
Related https://github.com/microsoft/playwright/issues/14743
