### ISSUE TITLE
[Feature] Create a template to be used with dotnet new/vs/vsc

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-dotnet#2213]
the ability to create a new playwright tests project using the dotnet cli command [`dotnet new`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)

with some options:
- having an argument to specify which testing library to use [nunit / mstest]
- adding a github actions configuration file
- bundle drivers? (https://playwright.dev/dotnet/docs/intro#bundle-drivers-for-different-platforms)

**Comment by mxschmitt** [comment]
Very good suggestion! Once our testing harness story is done in 1-2 release we'll do it!

**Comment by mxschmitt** [comment]
This seems done, there is `dotnet new mstest-playwright` and `dotnet new nunit-playwright`
