### ISSUE TITLE
[Question]: How can I specify the storageState in the context when using "Microsoft.Playwright.NUnit.PageTest" ?

### ISSUE THREAD

**Issue by j-meds** [microsoft/playwright-dotnet#2216]
### Your question

Hello I have two test that are used to login and logout a user. The first method works fine and stores the storageState. My second method opens a new tab without having anything in the storageState which then fails. Is there something I can do to use the storageState with this setup ?

namespace PlaywrightTests
{
    [Parallelizable(ParallelScope.Self)]
    public class LoginAndLoginTests : PageTest

    // 1. test, used for login and storing state
    [Test]
    public async Task LoginToApplication()
    {

        //var page = await browser.NewPageAsync();
        await Page.GotoAsync(_appUrl);
        await Page.WaitForLoadStateAsync(state: LoadState.DOMContentLoaded);
        await Page.ClickAsync(".btn.btn-primary");
        await Page.FillAsync("input[type=email]", _adminUserEmail);
        await Page.FillAsync("input[type=password]", _testUserPassword);
        await Page.ClickAsync("button[type=submit]");

        var title = await Page.WaitForSelectorAsync("#admin-dashboard-page");
        string titleText = await title.InnerTextAsync();

        // Putting a manual sleep so the browser has time to update the storage states
        Thread.Sleep(3000);
        // Save storage state into the file.
        var storageState = await Page.Context.StorageStateAsync(new BrowserContextStorageStateOptions
        {
            Path = "state.json"
        });

        Assert.AreEqual("Dashboard", titleText);
    }

    // 2. user should be logged in. ISSUE: The default functionality of PageTest is to open a new window and create a context which I'm unable to modify 
    [Test]
    public async Task LogoutFromApplication()
    {
        // Go to the homepage
        await Page.GotoAsync(_appUrl);
        await Page.WaitForLoadStateAsync(state: LoadState.DOMContentLoaded);
        await Page.ClickAsync("#nav-user-details");
        await Page.ClickAsync("#logout-btn");
        await Page.WaitForSelectorAsync("#loginbtn", new PageWaitForSelectorOptions { Timeout = 10 });

        // User should be redirected to login page
        Assert.AreEqual(_appUrl + "/login", Page.Url);
    }

}
`

I have to add the code below for it to pass the test, but this opens a new browser context with the storageState. I'm wondering if it's even possible to keep using the same context for multiple test in the same file or to specify an auth without it creating a new context.

`// Create a new context with the saved storage state.
var context = await Browser.NewContextAsync(new BrowserNewContextOptions
{
    StorageStatePath = "state.json"
});

var Page = await context.NewPageAsync();`

**Comment by mxschmitt** [comment]
The reason for having a new page/context per test is to ensure test isolation between the tests. So if one test is failing, it does not end up that the other tests are failing when e.g. the login did not work.

You can use `BrowserTest` instead and create your page/context yourself in the beginning of all the tests and re-use if you want to re-use the context/page instance.

Would that work for you?

**Comment by j-meds** [comment]
@mxschmitt All my test required authentication, so if the login does fail it won't run any other test. Overriding the context option works perfectly, I'm also using a onetime setup to login generate the storage state. Thanks!

**Comment by j-meds** [comment]
@mxschmitt would be helpful if this was documented as well.

**Comment by no-coffee305** [comment]
@j-meds @mxschmitt I have found this post and it was a long time ago but can you able to share your solution code as I am having the exactly same problem. I am new to C# and not sure best way to implement the context override when using POM. My existing code is below.

At start of my test I would like to create POM instance but also reuse stored state before navigating to the URL of the app. i understand "Browser.NewContextAsync" is the wrong thing to use in this case.

```
 [SetUp]
    public async Task SetUp()
    {
        DashboardPage _dashboardPage = new DashboardPage(Page);
        ReportPage _reportPage = new ReportPage(Page);
        var url = TestContext.Parameters["webAppUrl"];
        var context = await Browser.NewContextAsync(new()
        {
            StorageStatePath = "state.json"
        });
        //var Page = await context.NewPageAsync();
        await Page.GotoAsync(url);
    }
```

I really would appreciate your help. Thank you
