### ISSUE TITLE
[Feature] IBrowser only implements IAsyncDisposable and not IDisposable

### ISSUE THREAD

**Issue by mathiasi** [microsoft/playwright-dotnet#2221]
Seeing that Playwright is a Microsoft product I thought it would be right if it would follow the recommendations from the Microsoft Doc.

> It is typical when implementing the [IAsyncDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable) interface that classes will also implement the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface. A good implementation pattern of the [IAsyncDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable) interface is to be prepared for either synchronous or asynchronous dispose.

https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync

**Comment by akamud** [comment]
Hi, is this still planned for 1.26 release? I just bumped into this issue in my code too.

**Comment by mxschmitt** [comment]
Disposing `APIRequestContext`, `APIResponse`, `Browser`, `BrowserContext`, and `JSHandle` are asyncronous, since they either interact with the browser itself to shutdown them gracefully or interact also with the file-system / Playwright driver to shut them down, cleanup files etc. It's discouraged to either ignore the exception so it runs in the background or force it to be sync by using `GetAwaiter().GetResult()` since it might be ending up being blocking.

Closing by that as a won't fix.

**Comment by akamud** [comment]
Adding more context to the discussion, it isn't a case of being a "best practice", it can literally cause leaks in users' applications:

> Caution
> If you implement the [IAsyncDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable) interface but not the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface, your app can potentially leak resources. If a class implements [IAsyncDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable), but not [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable), and a consumer only calls Dispose, your implementation would never call DisposeAsync. This would result in a resource leak.

As stated here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync

From my understanding, anyone using an old hosting model or any disposing mechanism that wasn't designed when `IAsyncDisposable` was available **will** have leaks unless the user explicitly call this async disposable with sync-over-async.

So, as much as I understand that all those APIs are async, In my opinion this should be handled on Playwright's side, or at the very least be explicitly documented as a warning. It seems to me that simply expecting the user to know about this and do a workaround is a recipe for leaks happening.
What do you think? Is there something else that can be done on Playwright's side to avoid pitfalls?

**Comment by kblok** [comment]
IMHO. Playwright is a **new**, **end-to-end testing library**, async by nature. I don't think we need investments in **old hosting models**.

**Comment by akamud** [comment]
> IMHO. Playwright is a **new**, **end-to-end testing library**, async by nature. I don't think we need investments in **old hosting models**.

That's a fair point, but is there something that can be done documentation-wise?

**Comment by mxschmitt** [comment]
We updated the Microsoft docs to reflect the change best practices - should be live soon!: https://github.com/dotnet/docs/pull/30852

cc @akamud @kblok
