### ISSUE TITLE
[Question]: Upload Folder in C#

### ISSUE THREAD

**Issue by MarkoNaumovic** [microsoft/playwright-dotnet#2229]
### Your question

Hi, I try to find a way to upload folded in my test but something is not working. This is my example of a method ...

public async Task UploadFolderAsync(string folder)
{
var folderChooser = _page.RunAndWaitForFileChooserAsync(async () =>
{
await _page.ClickAsync("button span:has-text('Select folder')");
});
await folderChooser.Result.SetFilesAsync(folder.Select(f => $"../../../UploadFolders/{f}"));
await folderChooser.Result.Page.WaitForRequestFinishedAsync();
}

Somting RunAndWaitForFolderChooserAsync maybe

**Comment by mxschmitt** [comment]
Do you receive any error message or exception which gets thrown?

Can you share with us a a reproducible?

[Folder uploads are not yet supported](https://github.com/microsoft/playwright/issues/6854) but you should be able to upload individual files.

**Comment by MarkoNaumovic** [comment]
When  click on open folder button he don't open path which I set. He opens on local machine C:\Document folder. Then he stops and I get an error that my path has not found.

**Comment by mxschmitt** [comment]
who is he? can you share a repro with us?
