### ISSUE TITLE
[BUG] Unable to force install MSEdge

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#2232]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Windows
- .NET version: [e.g. .NET 6]
- Browser: Chrome, MSEdge, chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
**Attempt to force:**
pwsh playwright.ps1 install --force msedge
Failed to install browsers
TypeError: Cannot read properties of undefined (reading 'Releases')

**No Force:**
pwsh playwright.ps1 install msedge
Failed to install browsers
Error:
╔═════════════════════════════════════════════════════════════════╗
║ ATTENTION: "msedge" is already installed on the system!         ║
║                                                                 ║
║ "msedge" installation is not hermetic; installing newer version ║
║ requires *removal* of a current installation first.             ║
║                                                                 ║
║ To *uninstall* current version and re-install latest "msedge":  ║
║                                                                 ║
║ - Close all running instances of "msedge", if any               ║
║ - Use "--force" to install browser:                             ║
║                                                                 ║
║     pwsh bin\Debug\netX\playwright.ps1 install --force msedge   ║
║                                                                 ║
║ <3 Playwright Team                                              ║
╚═════════════════════════════════════════════════════════════════╝
```

**Describe the bug**
Unable to force install MSEdge. that was working until recently. it part of the pipline for edge we make sure its installed on the agent.
it also normally outputs the version number. i have tried locally but same issue which makes me thing its not environmental

**Comment by mxschmitt** [comment]
Microsoft Edge changed something in their installation API, which broke all the installations, we'll push an update shortly with a fix.

**Comment by mxschmitt** [comment]
v1.24.1 gets published right now, should be fixed then.
