### ISSUE TITLE
Configuring context properly at the beginning of test suite

### ISSUE THREAD

**Issue by mkgn** [microsoft/playwright-dotnet#2233]
I am using Playwright with MSTest. As of now my test cases tries to follow page object pattern. So I have

    public class BasePage: PageTest
    {
        [TestInitialize]
        public async Task TestSetup()
        {
            Page.Context.Browser.NewContextAsync(new BrowserNewContextOptions
            {
                
            })
            await Context.Tracing.StartAsync(new TracingStartOptions
            {
                Title = TestContext.TestName, //Note this is for MSTest only. 
                Screenshots = true,
                //Snapshots = true,
                //Sources = true,
            });
        }
        [TestCleanup]
        public async Task TestCleanup()
        {
            await Context.Tracing.StopAsync(new TracingStopOptions
            {
                Path = TestContext.TestName + ".zip"
            });
        }
    }

Other pages will inherit from the base page and do there work. My issue is I want to parameterize the whole setup so that at the begining I should be able to setup;

 - Run headless or not
 - For tracing include video or image (as above example)
 - share session storage so once logged in, that session will be used with the rest of the tests so it speed up things 

I am not sure how to wire above 3 options within the [TestInitialize]

**Comment by mxschmitt** [comment]
> Run headless or not

You can set headless e.g. via runsettings or via the `HEADED` env var (currently [not working ](https://github.com/microsoft/playwright-dotnet/issues/2231)on 1.24.0 will be fixed soon) see here:
- https://playwright.dev/dotnet/docs/test-runners#customizing-browserlaunch-options-1

> For tracing include video or image (as above example)

We have a [tracking issue](https://github.com/microsoft/playwright-dotnet/issues/2214) to provide screenshot, video, tracing out of the box, no eta on that one, but we're working on it. As of today you manually need to start it inside SetUp and TearDown.

> share session storage so once logged in, that session will be used with the rest of the tests so it speed up things

I'm not super familiar with MSTest, but I think if you run something before, you can generate the storageState, and then reference it back inside the ContextOptions: https://playwright.dev/dotnet/docs/test-runners#customizing-browsercontext-options. Let me file an issue for it so we add it to the docs or figure out a story for reusable auth state in .NET. https://github.com/microsoft/playwright-dotnet/issues/2235

**Comment by sturlath** [comment]
I´m trying this out with 1.25 and the tests are not opened when trying to use .runsettings but I can use the CLI

This doesn't work
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <Playwright>
    <BrowserName>chromium</BrowserName>
    <LaunchOptions>
      <Headless>false</Headless>
      <Channel>msedge</Channel>
    </LaunchOptions>
  </Playwright>
</RunSettings>
```
and neither does this

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <EnvironmentVariables>
	<HEADED>1</HEADED>
    </EnvironmentVariables>
  </RunConfiguration>
</RunSettings>
```

But I can run this and see the browser pop up

```powershell
dotnet test -- Playwright.BrowserName=chromium Playwright.LaunchOptions.Headless=false Playwright.LaunchOptions.Channel=msedge
```

My test if that matters

```csharp
namespace PlaywrightTests
{
    public class FirstTest: PageTest
    {
        [SetUp]
        public async Task Setup()
        {
            await Page.GotoAsync(url: "http://www.eaapp.somee.com");
        }

        [Test]
        public async Task Super_simple_test()
        {
            // Act
            await Page.ClickAsync(selector: "text=Login");
            await Page.FillAsync(selector: "#UserName", value: "admin");
            await Page.FillAsync(selector: "#Password", value: "password");
            await Page.ClickAsync(selector: "text=Log in");

            // Assert
            await Expect(Page.Locator(selector: "text='Employee Details'")).ToBeVisibleAsync();
        }
    }
}
```

**Comment by mxschmitt** [comment]
Do you pass the name of your runsettings file to dotnet test? `dotnet test --settings:test.runsettings` if your runsettings file is called `test.runsettings`.

**Comment by sturlath** [comment]
OK I was just using the Test Explorer in Visual Studio and then just running `dotnet test` thinking the `.runsettings `file would be automatically picked up (btw I just named the file` .runsettings` (no test prefix)

This works with `dotnet test --settings:test.runsettings` but would be great if the Test Explorer would also pick it up.

**Comment by preiius** [comment]
In Test Explorer, see Options > Configure Run Settings

**Comment by sonsuh** [comment]
@sturlath how were you able to resolve this? I have explicitly chosen the file using Options > Configure run settings but it still doesn't work
