### ISSUE TITLE
[Feature] Custom timeout for Expect()

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-dotnet#2237]

**Comment by JesperRisager** [comment]
Any news on when this has been completed?

Currently Expect has a 5 sec timeout using .Net which makes pure usage of Expect flaky when running in the cloud.

**Comment by mxschmitt** [comment]
This is completed, you can set a custom timeout via a runsettings file: https://playwright.dev/dotnet/docs/test-runners#using-the-runsettings-file

**Comment by JesperRisager** [comment]
It seems like this requires Visual Studio and MSTest?

I use xUnit and Rider for development and it needs to be able to run in CI in Github also.

**Comment by mxschmitt** [comment]
It does not. `dotnet test` supports it too: https://playwright.dev/dotnet/docs/running-tests

**Comment by JesperRisager** [comment]
Thanks :)

**Comment by tesar-tech** [comment]
Is it possible to set the custom default timeout for Expect() outside of the `.runsettings`? Somewhere in my code when creating browser context or a page...
