### ISSUE TITLE
[Question]: Issue when Deploy Playwright PDF application on Azure App Service

### ISSUE THREAD

**Issue by akashlimbani** [microsoft/playwright-dotnet#2238]
### I already deployed the app on the azure service but when running the Playwright operation that time got an error like this

> 2022-08-03 09:13:38.205 +00:00 [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.Microsoft.Playwright.PlaywrightException: Executable doesn't exist at C:\local\LocalAppData\ms-playwright\chromium-1015\chrome-win\chrome.exe╔════════════════════════════════════════════════════════════╗║ Looks like Playwright was just installed or updated. ║║ Please run the following command to download new browsers: ║║ ║║ pwsh bin\Debug\netX\playwright.ps1 install ║║ ║║ <3 Playwright Team ║╚════════════════════════════════════════════════════════════╝at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in //src/Playwright/Transport/Connection.cs:line 167at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func1 action, Boolean isInternal) in //src/Playwright/Transport/Connection.cs:line 477at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) in //src/Playwright/Core/BrowserType.cs:line 61at impdfengine.Helpers.PDFGeneratorHelper.GetPDF(GetPDFRequest request) in D:\Projects\P\impdfengine\impdfengine\impdfengine\Helpers\PDFGeneratorHelper.cs:line 8at impdfengine.Controllers.ReportController.DownloadPdf(PDFRequest request) in D:\Projects\P\impdfengine\impdfengine\impdfengine\Controllers\ReportController.cs:line 19at lambda_method20(Closure , Object )at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>gAwaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.gAwaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.gAwaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g_Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

**Comment by mxschmitt** [comment]
Like the exception says, you need to run `pwsh bin\Debug\netX\playwright.ps1 install chromium` after you deployed your application so Chromium gets downloaded.

**Comment by akashlimbani** [comment]
But how I can run it on Azure app service @mxschmitt

**Comment by mxschmitt** [comment]
You can either execute the command somehow or use this api: https://playwright.dev/dotnet/docs/browsers#install-browsers-via-api

**Comment by 304NotModified** [comment]
Related https://github.com/microsoft/playwright/issues/14743
