### ISSUE TITLE
[Question]: How to upload multiple files via Playwright in C# for Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-dotnet#2253]
### Your question

Hello:
I have to upload multiple files to one web site, actually, I created one facebook page, and I can use creator studio to upload multiple files at one shot.  Otherwise, if you upload files one by one, then quite often you can upload only a few files (less than 5), but if you use creator studio, you can upload more than 20 files at one shot.
So I did some testing, I can use Playwright to upload files one by one, but the performance is very bad, so I want to try to upload multiple files at once using creator studio.
I created one folder in C:\Uploads\, and add 2 videos files: 1.mp4 and 2.mp4.
I wrote some C# code trying to upload the 2 videos files in one folder (C:\Uploads) to facebook:

public static async Task Bulk_Upload_Videos_Facebook_My_Page()
{ 
    string upload_hold_button_xpath =
@"//html/body/div[1]/div[1]/div/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div/div/div[1]/div/div/div/div[1]/div[2]/div[3]/div[1]/div/div/div/span";
    string upload_many_files_button_xpath =
@"//html/body/div[1]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[1]/div/div/ul/li[2]/div/div/div[2]";
    await Facebook_Page.GotoAsync("https://business.facebook.com/creatorstudio/home?reference=search_facebook");
    await Task.Delay(5000);
    ILocator? upload_hold_button =
Facebook_Page.Locator(upload_hold_button_xpath);
    await upload_hold_button.ClickAsync();
    await Task.Delay(5000);
    ILocator? upload_many_files_button =
Facebook_Page.Locator(upload_many_files_button_xpath);
    await upload_many_files_button.ClickAsync();
    await Task.Delay(5000);
    List<string> set_to_upload_files = 
Directory.GetFiles("C:\Uploads\").Select(x => x.Replace(@"\", "/")).ToList();
    string bulk_files =
string.Join("', '", set_to_upload_files);
    string upload_bulk_files =
"['" + bulk_files + "']";
    Debug.Print(upload_bulk_files);
    await Facebook_Page.Locator("input[type='file']")
       .SetInputFilesAsync(upload_bulk_files);
    await Task.Delay(5000);
}

Of course, I have to login to facebook first, then run the above code, most part of the above code seems working, but I got error when trying to input multiple file names, I want to use this format like:
await page.setInputFiles("input[type='file']", ['file1.txt', 'file2.txt']);
In my case: I want to do something like: 
await page.setInputFiles("input[type='file']", ['C:\Uploads\1.mp4', 'C:\Uploads\2.mp4']);
But I got run time error:
Inner Exception 1:
IOException: The filename, directory name, or volume label syntax is incorrect. : 
'C:\Facebook\bin\Debug\net6.0-windows\['C:\Uploads\1.mp4', 'C:\Uploads\2.mp4']'
So I changed my C# code, I am trying to upload files like this:
await page.setInputFiles("input[type='file']", ['C:/Uploads/1.mp4', 'C:/Uploads/2.mp4']);
I think the error seems to me that Playwright prefers the file name like Unix style name, however, I still got the same error after I changed my code.
Please advise how I can get my code running to upload multiple files to facebook using creator studio in Windows 10?
Thanks,

**Comment by mxschmitt** [comment]
You need to escape the slashes inside your path, otherwise it won't work:

-> `await page.setInputFiles("input[type='file']", ['C:\\Uploads\\1.mp4']);`

**Comment by zydjohnHotmail** [comment]
Hello:
I will try again later, but if I didn't change anything for each file in the folder, then in C#, each file has the format like: 'C:\\Uploads\\1.mp4'
However, the above file format didn't work, that was the reason why I changed my code.
If you can create one facebook page and use creator studio to upload 2 files (any format like: MP4, JPEG, PNG, GIF), you will know.

**Comment by mxschmitt** [comment]
Closings as per above and since its answered.

**Comment by zydjohnHotmail** [comment]
Hello:
Your answer is totally wrong!
