### ISSUE TITLE
[Feature] Expose Ability to Set Expect Timeout

### ISSUE THREAD

**Issue by bjharo** [microsoft/playwright-dotnet#2259]
With 1.25, we have the ability to set the default timeout for web-first assertions (Expect) via the runsettings file but only if your testing project is using the Microsoft.Playwright.NUnit package. You can see in `WorkerAwareTest` where the timeout is getting set in the SetUp method:
```
        [SetUp]
        public void WorkerSetup()
        {
            if (!_allWorkers.TryPop(out _currentWorker))
            {
                _currentWorker = new();
            }
            WorkerIndex = _currentWorker.WorkerIndex;
            if (PlaywrightSettingsProvider.ExpectTimeout.HasValue)
            {
                AssertionsBase.SetDefaultTimeout(PlaywrightSettingsProvider.ExpectTimeout.Value);
            }
        }
```

The call to AssertionsBase.SetDefaultTimeout seems to set the default timeout. I've been wanting to set a default timeout for Expect assertions since they first came to Playwright.NET but unfortunately, our testing project doesn't use Microsoft.Playwright.NUnit and it appears that AssertionsBase is an internal class so there is no way we can set the timeout.

It would be great if this functionality was exposed in some way so that those of use not using Microsoft.Playwright.NUnit can set a default.

**Comment by marcuskrahl** [comment]
This setting is not only exposed to Microsoft.Playwright.NUnit. 

We have a .runsettings file like:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<!-- Playwright specific parameters -->
	<Playwright>
		<ExpectTimeout>30000</ExpectTimeout>
	</Playwright>
</RunSettings>
```
The timeout is then correctly applied even for MSTest in our case by running the tests via `dotnet test -s .runsettings`.

So the scope of this issue is probably just to expose this property via C# like `Context.SetDefaultTimeout`

**Comment by bryanh-bloomerang** [comment]
I've tried placing this setting in my .runsettings file as you suggest @marcuskrahl but the timeout for my Expect calls still defaults to 5000ms regardless of what value I put in the setting.

**Comment by Philip-DeLuca** [comment]
I second this.  I have been trying to figure this out for 3 full days now.  When I apply the ExpectTimout parameter to my .runsettings file, I am still getting error messages that say "5000ms" for Expect calls.  My problem may be slightly different though- as I am using only Microsoft.Playwright.NUnit for the projects.

**Comment by bryanh-bloomerang** [comment]
I did find a way around this issue. It uses reflection and it's not pretty but it works.

```
public static void SetDefaultWebFirstAssertionTimeout(float timeout)
    {
        Guard.Against.NegativeOrZero(timeout, nameof(timeout),
            "The default timeout for web-first assertions must be greater than zero.");

        var assembly = Assembly.LoadFrom("Microsoft.Playwright.dll");
        var type = assembly.GetType("Microsoft.Playwright.Core.AssertionsBase");

        if (type is null)
        {
            throw new InvalidOperationException(
                "Unable to set the default web first assertion timeout because the proper Playwright type, " +
                "AssertionsBase, could not be found.");
        }

        var method = type.GetMethods(BindingFlags.NonPublic | BindingFlags.Static)
            .SingleOrDefault(m => m.Name is "SetDefaultTimeout");

        if (method is null)
        {
            throw new InvalidOperationException(
                "Unable to set the default web first assertion timeout because the proper method could not be found.");
        }

        method.Invoke(null, new object[] { timeout });
    }
```

**Comment by batlicka** [comment]
@bryanh-bloomerang or @mxschmitt I am using NUnit together with playwright.  Where I should place the method SetDefaultWebFirstAssertionTimeout in structure of my project? I try add it directly into file with my tests, but Visual Studio marked me "Aganist" in first row and says: 
![image](https://github.com/microsoft/playwright-dotnet/assets/46314552/1de5d496-217a-4321-bcfe-a18c648c0128)
