### ISSUE TITLE
[BUG] - Behaviour difference after upgrading to a nuget package version >= 1.24.0

### ISSUE THREAD

**Issue by adrianwright109** [microsoft/playwright-dotnet#2262]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Windows
- .NET version: .NET 6
- Browser: Chromium

I have a console app that I use to login to my bank's online banking website which then collects transactions, serializes them into JSON.  The JSON data is then used to update an Excel spreadsheet.

I have a created a minimal repro console app here: [https://github.com/adrianwright109/PlaywrightUpgrade](https://github.com/adrianwright109/PlaywrightUpgrade) which can be used to reproduce the issue.

It works as expected if I use `Microsoft.Playwright` nuget package version(s) `<= 1.23.0`.

If however I upgrade the `Microsoft.Playwright` nuget package to a version `>= 1.24.0` then it stops working as expected.

When the login form is submitted it should remain on the login form with validation errors, which it does using `Microsoft.Playwright` nuget package version(s) `<= 1.23.0`.
![image](https://user-images.githubusercontent.com/47532258/185475111-9fac78ee-c7a7-4c14-a351-c69af3e4688f.png)

However using `Microsoft.Playwright` nuget package version(s) `>= 1.24.0` it goes to an error page and I'm not sure why it does this?
![image](https://user-images.githubusercontent.com/47532258/185474646-ae461996-efd7-489a-a1f6-1091909e028a.png)

**Comment by mxschmitt** [comment]
For me when I try to repro it with v1.23 I get 
<img width="937" alt="image" src="https://user-images.githubusercontent.com/17984549/185562467-7e818f45-e9cf-4721-9e3c-a2570aa92a2f.png">

so it seems like there is something phishy with the repro? Maybe its bot protection on their end?

**Comment by adrianwright109** [comment]
Strange!  It was consistently reproducing for me using `>= 1.24.0` and always worked with `1.23.0`.

Are there any tricks/switches I could try to make it think this wasn't software automation but a real browser with a user?

**Comment by mxschmitt** [comment]
Unfortunately not. Since this is not an end-to-end testing use-case we can't act on this, so I'm closing it.
