### ISSUE TITLE
[Question]: Query elements based on style

### ISSUE THREAD

**Issue by Markz878** [microsoft/playwright-dotnet#2277]
How can I query elements based on style property? Meaning if my html has an element like this:
``
div style="margin-bottom:5px; box-shadow:0px 0px 2px 4px red;"
``
How can I get all instances of it with QuerySelectorAllAsync method?

**Comment by mxschmitt** [comment]
You can do e.g. `div[style*="margin-bottom:5px;"]` see above and [here](https://stackoverflow.com/questions/34303423/is-it-possible-to-have-a-css-selector-based-on-a-css-property-and-its-value).
