### ISSUE TITLE
[Feature] Add Overloaded FIllAsync() and TypeAsync() Methods That Take int, double, float, ect.

### ISSUE THREAD

**Issue by KaelinStephens** [microsoft/playwright-dotnet#2285]
Right now, FillAsync() and TypeAsync() only accept string inputs. There are many times the data input needs to be an int, double, float, etc. and Playwright for .NET does not support this. Changing the input data to a string is not difficult, but then the page being tested often throws an error as it is expecting some form of number as input rather than a string.

I can't be the only one running into this problem.

**Comment by mxschmitt** [comment]
We have this feature request upstream: https://github.com/microsoft/playwright/issues/16660

Internally inside the web, an input is always a string, so it would do ToString() internally anyways.
