### ISSUE TITLE
How to Take a Screenshot at failed step in Nunit Framework

### ISSUE THREAD

**Issue by dbhimar** [microsoft/playwright-dotnet#2296]
Can someone help me how to take screenshot at failed step in Nunit Framework test case
Currently I can take screenshot at the given line

**Comment by RuaanKruger** [comment]
Hi @dbhimar, 

Not part of this project but I recently needed to do something very similar and looking at the following URLs helped :

https://docs.nunit.org/articles/nunit/writing-tests/TestContext.html
https://docs.nunit.org/articles/nunit/writing-tests/setup-teardown/index.html

Here is a pretty straightforward example:


```
public class Tests : PageTest
{
    [TearDown]
    public async Task TakeScreenshotOnFailure()
    {
        if (TestContext.CurrentContext.Result.Outcome == ResultState.Error)
        {
            await Page.ScreenshotAsync(new()
            {
                Path = "screenshot.png",
            });
        }
    }

    [Test]
    public async Task RandomlyCaptureScreenshot()
    {
        await Page.GotoAsync("https://playwright.dev");
        
        if (TestContext.CurrentContext.Random.Next(1, 100) % 3 == 0)
        {
            throw new Exception("This will happen randomly");
        }
    }
}

```

**Comment by mxschmitt** [comment]
Thank you @RuaanKruger, we're working on supporting this feature natively and its tracked in this issue: https://github.com/microsoft/playwright-dotnet/issues/2214

**Comment by dbhimar** [comment]
@RuaanKruger  Thanks, but I want to take screenshot at failure statement only

**Comment by dbhimar** [comment]
@mxschmitt Thank you for the headsup

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2214 since it includes screenshot on failure. (I can't make promises, but I hope to be able to ship this feature in 1.27)
