### ISSUE TITLE
[Feature]LocatorAssertions support for .ToBeGreaterThan .GreaterThanOrEqual .LessThan .LessThanOrEqual

### ISSUE THREAD

**Issue by gibman** [microsoft/playwright-dotnet#2313]
It would be great if you could adapt and support the Assertion helpers (LocatorAssertions) for the following.. 

 .ToBeGreaterThan 
.GreaterThanOrEqual 
.LessThan 
.LessThanOrEqual

It should already be supported here =>
https://github.com/microsoft/playwright/issues/10367

**Comment by mxschmitt** [comment]
The upstream issue is different, it's about adding [Expect.Poll](https://playwright.dev/docs/test-assertions#polling). The assertions which you mentioned, are normal integer based assertions, so you can use the existing nunit/mstest assertions for it.

I filed a feature request for it here: https://github.com/microsoft/playwright-dotnet/issues/2314
