### ISSUE TITLE
[Question]: How to best get auth context before tests run

### ISSUE THREAD

**Issue by bzuillsmith** [microsoft/playwright-dotnet#2322]
### Your question

Is there a way to save an auth context before all tests, and then reuse it in all the tests? Using MSTest for example -- [TestInitialize] is run for every test so I can't perform the steps of authenticating there or it will run for every test. [ClassInitialize] is too early as the whole test object is not available to perform actions with and sign in. Is this supported?

The [docs on auth context](https://playwright.dev/dotnet/docs/auth#reuse-authentication-state) very vague about how to achieve this.

**Comment by mxschmitt** [comment]
We'll have to follow-up with docs for it, but something like that in ClassInitialize should work:

```csharp
   using Microsoft.Playwright;

   [ClassInitialize]
   public async static Task ClassInitialize(TestContext context)
   {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
        await page.GotoAsync("https://playwright.dev/dotnet");
        // ... do your auth
        await page.Context. StorageStateAsync(new()
        {
            Path = "storageState.json"
        });
   }
```

And then inside your test:

```csharp
    public override BrowserNewContextOptions ContextOptions()
    {
        return new BrowserNewContextOptions()
        {
            StorageState = "storageState.json",
        };
    }
```
