### ISSUE TITLE
Soft assertion - not possible in .net?

### ISSUE THREAD

**Issue by benjamin-inspectly** [microsoft/playwright-dotnet#2327]
Hi ! :)
Great library this far!

I have a question about soft assertions. I can see them in Node JS documentation but not in the .NET version.
I'm using the MSTest version of the framework.

Do you have plans to add it in the .NET version as well or is it just me who cannot find it? :)

Thank you for a good testing framework. Easy to get started!

**Comment by mxschmitt** [comment]
I created a dedicated feature request for it: https://github.com/microsoft/playwright-dotnet/issues/2328
