### ISSUE TITLE
Getting "Unable to find type" Error when trying to install playwright

### ISSUE THREAD

**Issue by cdaoud** [microsoft/playwright-dotnet#2329]
While following these set up steps trying to install Playwright on my Mac: https://playwright.dev/dotnet/docs/intro#installing-playwright 

I'm getting the following error when executing this command:  `pwsh bin/Debug/net6.0/playwright.ps1 install`

**Error:** 
InvalidOperation: /Users/--/--/Test/bin/Debug/net6.0/playwright.ps1:5:6
Line |
   5 |  exit [Microsoft.Playwright.Program]::Main($args)
     |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [Microsoft.Playwright.Program].

Has anyone been able to overcome this issue?

**Comment by cdaoud** [comment]
> Do you have PowerShell 7+?
> 
> See here for installing it: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2

I have powershell version 7.2.6

**Comment by mxschmitt** [comment]
did you build your project before? This error is very weird, seeing it the first time!

**Comment by cdaoud** [comment]
> did you build your project before? This error is very weird, seeing it the first time!

Yes

**Comment by mxschmitt** [comment]
Which version of Windows are you using? We were unfortunately not able to reproduce and this is the first time this error occurs, so most likely something is off on your end.

**Comment by mxschmitt** [comment]
What's inside the `bin/Debug/net6.0/` directory?

Since you follow the instructions, its probably not not worth sharing a repro repository. This is the first time we seeing this error, so its most likely something off on your end.

**Comment by mxschmitt** [comment]
Closing since we can't repro and it seems stale. If you find something useful why this is happening, let us know and we're happy to adjust documentation, since this is the first time this issue is occuring for our users.

**Comment by NatElkins** [comment]
Want to report that uninstalling my current version of pwsh and installing the latest fixed this issue for me.  Went from 7.0.0 to 7.3.2.
