### ISSUE TITLE
[BUG] CS0103	The name 'Expect' does not exist in the current context

### ISSUE THREAD

**Issue by sankarbha** [microsoft/playwright-dotnet#2331]
**Context:**
- Playwright Version: 1.14 (file version)
- Operating System: Windows
- .NET version: .NET 6
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: Visual Studio 2022 Community Edition

Followed line by line as mentioned [here](https://playwright.dev/dotnet/docs/intro) to try my first test using Playwright but got this error when I tried to build.
`CS0103	The name 'Expect' does not exist in the current context`

Code:
```
using Microsoft.Playwright.MSTest;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Admin.UIAutomationTests
{
    [TestClass]
    public class UnitTest1 : PageTest
    {
        [TestMethod]
        public async Task HomepageHasPlaywrightInTitleAndGetStartedLinkLinkingtoTheIntroPage()
        {
            await Page.GotoAsync("https://playwright.dev");

            // Expect a title "to contain" a substring.
            await Expect(Page).ToHaveTitleAsync(new Regex("Playwright"));

            // create a locator
            var getStarted = Page.Locator("text=Get Started");

            // Expect an attribute "to be strictly equal" to the value.
            await Expect(getStarted).ToHaveAttributeAsync("href", "/docs/intro");

            // Click the get started link.
            await getStarted.ClickAsync();

            // Expects the URL to contain intro.
            await Expect(Page).ToHaveURLAsync(new Regex(".*intro"));
        }
    }
}

```

Am I missing something?

Please throw some light on this.

Thanks.

**Comment by mxschmitt** [comment]
Looks like your Playwright version is quite old! Try updating it to 1.26 Expect() is a relatively new method exposed on the PageTest class.

**Comment by sankarbha** [comment]
Thanks. I am able to upgrade, build and run my first test.

**Comment by tmvsivakumar** [comment]
Hi,
I am getting same error though I have latest Playwright (1.52) installed:

![Image](https://github.com/user-attachments/assets/fcd47ad4-ff18-4962-bbeb-84adbd5725c2)
