### ISSUE TITLE
[BUG]no  Name   prop in  class  PageGetByRoleOptions 

### ISSUE THREAD

**Issue by gitlsl** [microsoft/playwright-dotnet#2345]
**Context:**
- Playwright Version1.27.1
- Operating System: win11
- .NET version: .net 6
- Browser: Chromium
- Extra: [any specific details about your environment]

codegen will  gen  next code

` page.GetByRole(AriaRole.Heading, new() { Name = "xxxxxxx" });`

`Name` should be replace with `NameString`  ？（no `Name`  prop in  class `PageGetByRoleOptions`)

**Comment by mxschmitt** [comment]
Looks like the same as https://github.com/microsoft/playwright/issues/17960
