### ISSUE TITLE
[BUG] Playwright throws "Unknown platform" from standard Android app using .NET Standard 6.0

### ISSUE THREAD

**Issue by hammondreg** [microsoft/playwright-dotnet#2347]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.27.1
- Operating System: [e.g. Windows, Linux or Mac] Windows 11
- Node.js version: [e.g. 12.22, 14.6] No idea
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment] Visual Studio 2022 - Android Application template using .NET Standard 6.0

**Code Snippet**

```csharp
namespace AndroidApp1
{
    [Activity(Label = "@string/app_name", MainLauncher = true)]
    public class MainActivity : Activity
    {
        protected async override void OnCreate(Bundle? savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            IPlaywright playwright = null;
            try
            {
                playwright = await Playwright.CreateAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

           // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.activity_main);
        }
    }
}
```

**Describe the bug**

The CreateAsync() statement throws an "Unknown platform" exception

Add any other details about the problem here.

**Comment by yury-s** [comment]
Are there any other details on the exception, stack trace maybe?

**Comment by hammondreg** [comment]
Well ... I could provide one if you think it would be useful - but the exception is very simple to reproduce:
1. Create a standard Android .NET app using Visual Studio 2022
2. Install Playwright from NuGet
3. Add in the call to CreateAsync from the code snippet I provided
4. The bug will appear!

**Comment by mxschmitt** [comment]
This seems expected, do you want to run Playwright on an Android device in the end?

This is not supported only Linux/Windows/macOS is supported see [here](https://playwright.dev/docs/troubleshooting#system-requirements).

**Comment by hammondreg** [comment]
Thank you Max, you are perfectly correct; I mistakenly thought that because I was using an emulator on a WIndows device, then the platform would be supported.

One final question (if you can help): Do you have any idea if/when Playwright will EVER be supported on an Android platorm?

Thanks

**Comment by mxschmitt** [comment]
Unfortunately running Playwright on an Android device is not supported, the host device needs to be mac/linux/windows.

But on these platforms you can connect to an Android device from these host operating systems (only supported on Node.js tho as of today since its an experimental feature).
