### ISSUE TITLE
[Question]: The verification code fails to pass

### ISSUE THREAD

**Issue by hanfeige** [microsoft/playwright-dotnet#2357]
### Your question

When I was in use playwright testing a website, found the site click on the verification code has been returned failure information, but I by opening the path of chromium to access this page, where authentication code is through properly, suspect that the default configuration of a led to this problem, This problem is resolved when IgnoreAllDefaultArgs=true is used. But this creates some other problems that I don't want, and how do I know which configuration is affecting it? To ignore using IgnoreDefaultArgs alone
`

>                 Context = await playwright.Chromium.LaunchPersistentContextAsync(path, new()
>                 {
>                     Headless = false,
>                     Args = browserArgs,
>                     ColorScheme = ColorScheme.Dark,
>                     IgnoreHTTPSErrors=true,
>                     //IgnoreAllDefaultArgs = true,
>                     IgnoreDefaultArgs =new string[] { "--disable-extensions", "--no-sandbox", "--no-initial-navigation", "--enable-automation", "--no-default-browser-check" },
>                     ViewportSize = ViewportSize.NoViewport
>                 });

`
Verification code picture
![image](https://user-images.githubusercontent.com/17940219/198449986-397e7e76-5e3a-4d05-91fb-fdd64f5b91f8.png)

**Comment by mxschmitt** [comment]
Most likely they do bot protection, since Playwright is targeting end-to-end testing we expect users to have control over the site they are testing.
