### ISSUE TITLE
[Question]: Is it possible to configure a different node.exe path outside of the compiled Playwright DLL?

### ISSUE THREAD

**Issue by cmeyer001** [microsoft/playwright-dotnet#2363]
### Your question

In Driver.CS, the GetExecutablePath returns the path of the playwright.cmd file. The playwright.cmd file starts node runtime.

If I leave the playwright.cmd file in its original folder and update the playwright.cmd file to open node.exe from a different folder path such as a centralized location that is not within the app folder, I assumed that this would allow playwright to start with a centralized path to node.exe, However, this doesn't work so there must be other circumstances preventing this.

**I left this path/file in place and modified the cmd file to point to a centralized .playwright folder that contains node.exe**
C:\Users\userID\source\repos\MsPlaywrightTestHarness\\.playwright\node\win32_x64\playwright.cmd

**An example of a centralized folder that contains the node files that I pointed to is below -** 
C:\Users\userID\AppData\Roaming\automations\\.playwright

Is it possible to configure a different node.exe path outside of the compiled Playwright DLL? If so, what other file needs to be updated other than playwright.cmd?

From previous questions/responses on this topic, I know this issue isn't on the radar to be addressed, I'm just trying to find options that I can use to change the path where node is launched from so that we don't have multiple instances of this node folder for every playwright automation that we install on an end-user desktop. Currently we decompile the playwright DLL, make changes to allow that path of our choice (a customized "GetExecutablePath") then recompile the DLL which has been a pain to manage. 

Playwright has been a great automation tool for us compared to other tools, we'd just like to streamline the installation process while removing multiple instances of node.

Thanks

**Comment by cmeyer001** [comment]
I have this working now - closing question

**Comment by zubairkhakwani** [comment]
> I have this working now - closing question

Can you please mention how to make it work?
