### ISSUE TITLE
[Question]: Azure Function Custom Docker Image - how to add Playwright

### ISSUE THREAD

**Issue by adrianwright109** [microsoft/playwright-dotnet#2365]
### Your question

Hi,

I have an existing .NET 6 worker service application which I've created as a Windows service and runs on my local machine.

The application uses `Microsoft.Playwright` version `1.27.1` to automate a Firefox browser.

This application installs `Microsoft.Playwright` at runtime if required e.g.
```csharp
  Console.WriteLine("Installing browsers");

  // The following line installs the default browsers. If you only need a subset of browsers,
  // you can specify the list of browsers you want to install among: chromium, chrome,
  // chrome-beta, msedge, msedge-beta, msedge-dev, firefox, and webkit.
  // var exitCode = Microsoft.Playwright.Program.Main(new[] { "install", "webkit", "chrome" });
  // If you need to install dependencies, you can add "--with-deps"
  var exitCode = Microsoft.Playwright.Program.Main(new[] { "install", "firefox" });
  if (exitCode != 0)
  {
      Console.WriteLine("Failed to install browsers");
      Environment.Exit(exitCode);
  }

  Console.WriteLine("Browsers installed");
```

I now want to move this application into Azure as an Azure function that can be triggered on a timer trigger.

My first attempt was to create an Azure Function and use the existing application code, but this fails with various errors around Playwright and folder paths etc.

I did some googling and it appears that other people have had success by using `Linux` rather than `Windows` Azure functions and specifically with a docker container.

I am very new to the world of containers and docker so would appreciate some help.  I see that `Playwright` publish a docker image: [https://playwright.dev/docs/docker](https://playwright.dev/docs/docker)

I followed [this tutorial](https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=isolated-process%2Cbash%2Cazure-cli&pivots=programming-language-csharp]) from Microsoft to create an Azure function from a custom docker image.

The `Dockerfile` it creates looks like this:
```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env

# Build requires 3.1 SDK
COPY --from=mcr.microsoft.com/dotnet/core/sdk:3.1 /usr/share/dotnet /usr/share/dotnet

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0-appservice
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
```

Can someone tell me what I need to add to this `Dockerfile` to install `Playwright` and to be able to run a `Firefox` browser using my existing C# application code.

Thanks.

**Comment by feiyun0112** [comment]
Copy all exclude the first line from `https://github.com/microsoft/playwright-dotnet/blob/main/utils/docker/Dockerfile.focal` to your Dockerfiel

**Comment by adrianwright109** [comment]
Does it matter where I paste this into my docker file?

**Comment by feiyun0112** [comment]
https://github.com/microsoft/playwright-dotnet/issues/1546#issuecomment-881361130

**Comment by mxschmitt** [comment]
There is an official .NET Docker image, would that work for you? https://playwright.dev/dotnet/docs/docker

Alternatively you can use the Playwright CLI to install the dependencies which are required to run the browsers, see [here](https://playwright.dev/dotnet/docs/cli) for that.
