### ISSUE TITLE
Is page.screenshotAsync working on .NET frameworks?

### ISSUE THREAD

**Issue by RCJONESNXT** [microsoft/playwright-dotnet#2370]
I have tried on 3 separate .NET frameworks, one with POM and one without, and a fresh one based on the installation guides on playwright.dev. 

using the standard: 

`await _page.ScreenshotAsync(new()
        {
            Path = "screenshot.png",
            FullPage = true,
        });`

However no screenshot file is produced. Am I missing something?

**Comment by feiyun0112** [comment]
I can run the demo code after removing `using' keyword in Console App (.NET Framework 4.8)

Can you provide us a repro which we can run locally?

**Comment by RCJONESNXT** [comment]
Appreciate the reply, here's is a repo which essentially has the same code but in an NUnit project, as opposed to a Console App.

https://github.com/RCJONESNXT/NUnitTest2

**Comment by feiyun0112** [comment]
![image](https://user-images.githubusercontent.com/10190938/200595869-902b41ff-e847-4568-a274-aa688d44df8f.png)

it's work

**Comment by RCJONESNXT** [comment]
@feiyun0112 Yes it passes, but I'm guessing there was no screenshot.png file generated?

**Comment by mxschmitt** [comment]
NUnit using using afaik the bin directory or bin/net6.0 as a CWD (current working directory). Which `page.ScreenshotAsync` is using if you are using relative paths.

We recommend passing absolute paths, then the file will be put to the path you specify.

**Comment by feiyun0112** [comment]
![image](https://user-images.githubusercontent.com/10190938/200716841-a46a4ec1-16f0-4eb4-b735-63294a160e0b.png)

generated

**Comment by RCJONESNXT** [comment]
Ok just a pathing problem then, thank you both for your help!
