### ISSUE TITLE
[Question]: Installing an application(wpf) including playwright by Visual Studio option: Create Package

### ISSUE THREAD

**Issue by kaidoatgit** [microsoft/playwright-dotnet#2373]
Hello,

Im currently trying to publish a desktop application that uses Playwright to automate few task, however it seems that im missing something...
So after creating a windows package project in visual studio to package my application (Publish > Create Package > ...) I ended up with an installer:
![image](https://user-images.githubusercontent.com/117680565/200398412-8c7fe356-7829-4cdd-a7a9-8c7332ae29d5.png)
The application installs correctly and all other dependencies such as API and Database are working correctly but Playwright is not working for some reason. 

For testing purpose I've created a Mock project that has a simple button that calls playwright:
```
try
{
    var exitCode = Microsoft.Playwright.Program.Main(new[] { "install" });
    if (exitCode != 0)
    {
        Console.WriteLine("Failed to install browsers");
    }

    using var playwright = await Playwright.CreateAsync();
    await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions() { Headless = false });
    await using var browserContext = await browser.NewContextAsync();
    var page = await browserContext.NewPageAsync();
    await page.GotoAsync("https://www.google.com");
    await page.WaitForTimeoutAsync(10000f);
}
catch (Exception exception)
{
    output.Text = exception.Message + Environment.NewLine + exception.StackTrace + Environment.NewLine;
}
```
**The package installation details:
.NET CORE 6
Playwright package version: 1.27.2
Windows 10 x64**

After the package is installed I run the application that looks like this:
![image](https://user-images.githubusercontent.com/117680565/200401858-daad3e10-850b-4b75-98e6-a332bae622d3.png)

When the Test button is pressed, the above code runs and this is the final output:
![image](https://user-images.githubusercontent.com/117680565/200401778-5abde4c1-17d2-4feb-8367-95cdb0a5d675.png)

Playwright is not installing and therefore the launching/creation not working which I believe the exception is pointing to.

I've searched on google and other places but there is not an answer to this problem, could you guys help me out?

Thanks.

**Comment by kaidoatgit** [comment]
So I found out that MSIX Installer is installing the application in C:\Program Files\WindowsApps. WindowsApps is hidden and a privileged folder that not even the admin has access therefore Playwright is not being installed while installing the package. Did someone had this problem in the past?

**Comment by feiyun0112** [comment]
Please check if the `.playwright` folder exists in the installation directory

you should throw exception when Playwright is not installing 
`if (exitCode != 0)
    {
        throw new Exception("Failed to install browsers");
    }`

**Comment by kaidoatgit** [comment]
> Please check if the `.playwright` folder exists in the installation directory

thats the thing .playwright does not exist because WindowsApps does not allow to install for some reason, this is a problem for me because I dont want to ask my client to manually change the security of this folder...

> you should throw exception when Playwright is not installing `if (exitCode != 0) { throw new Exception("Failed to install browsers"); }`

I just didnt because I wanted to get the error from LaunchAsync since it is a "Mock" Project for testing purpose, thanks for the tip

**Comment by feiyun0112** [comment]
> > Please check if the `.playwright` folder exists in the installation directory
> 
> thats the thing .playwright does not exist because WindowsApps does not allow to install for some reason, this is a problem for me because I dont want to ask my client to manually change the security of this folder...
> 
> > you should throw exception when Playwright is not installing `if (exitCode != 0) { throw new Exception("Failed to install browsers"); }`
> 
> I just didnt because I wanted to get the error from CreateAsync since it is a "Mock" Project for testing purpose, thanks for the tip

maybe you can include .playwright folder in the resource file , and extract when first run

**Comment by kaidoatgit** [comment]
> maybe you can include .playwright folder in the resource file , and extract when first run

sorry for the ignorance how can you do that? do you have example?

**Comment by kaidoatgit** [comment]
So .playwright folder actually exist my bad...
![image](https://user-images.githubusercontent.com/117680565/200697687-4e4f3806-c8a1-4d6a-ba2a-191b3e9d7ebd.png)

It seems I cant execute any kind of action in this C:\Program Files\WindowsApps ... which means that I cant install playwright. 
All MSIX (package installers generated by Visual studio) are installed in this particular folder with high security. 

Any clue how to solve this problem without getting access to this folder? Clients shouldnt unsecure this folder

**Comment by feiyun0112** [comment]
you can manually copy browser binaries to client and set environment variable

https://playwright.dev/dotnet/docs/browsers#managing-browser-binaries

**Comment by kaidoatgit** [comment]
Someone knows how to run the installer of playwright from the application that was installed by MSIX?
Is there a way to pack the application to MSIX and change the reference for the Library of Microsoft.Playwright?

**Comment by mxschmitt** [comment]
Using Playwright inside WPF is not supported, Playwright is focusing end-to-end testing rather than being embedded inside a Windows application. Shipping browsers and a driver makes it not easily portable as of today.

Closing since this is out of scope for Playwright.

**Comment by kaidoatgit** [comment]
> Using Playwright inside WPF is not supported, Playwright is focusing end-to-end testing rather than being embedded inside a Windows application. Shipping browsers and a driver makes it not easily portable as of today.
> 
> Closing since this is out of scope for Playwright.

Hello sir, if I want to package playwright and install using the package it should work there must a workaround
