### ISSUE TITLE
[Bug] [Regression] [since 1.23] Parsing Guid values (IPage.EvaluateAsync<Guid>) using System.Convert class throws

### ISSUE THREAD

**Issue by maw136** [microsoft/playwright-dotnet#2374]
This created very problematic regression for parsing Guid values.
`Convert.ChangeType("{08d15efd-bd4f-4244-b46e-2238964e0e36}", typeof(Guid), System.Globalization.CultureInfo.InvariantCulture)` throws

_Originally posted by @maw136 in https://github.com/microsoft/playwright-dotnet/issues/2178#issuecomment-1306371464_

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally?

**Comment by maw136** [comment]
I have discovered the issue with the usage of `IPage.EvaluateAsync<Guid>` method with a JS script body that returns proper Guid string.

**Comment by maw136** [comment]
This then calls `ScriptsHelper` which calls the changed `EvaluateArgumentValueConverter`
Previously I have used 1.22 and today I upgraded to 1.27.2 and then I have analyzed the repo to find when the change in the implementation happened.

**Comment by maw136** [comment]
Full repro:

`
using System;
using System.Threading.Tasks;
using Microsoft.Playwright;
					
public class Program
{
	public static async Task Main()
	{
		using var playwright = await Playwright.CreateAsync();
		await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions{ Channel = "msedge", Headless = true});
		var page = await browser.NewPageAsync();
		await page.GotoAsync("https://www.microsoft.com/en-us");
		var guid = await page.EvaluateAsync<Guid>("{ document.evaluate('/html/body/div[5]/div/div/main/div/div[2]/div/div/a', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.id }");
	}
}


`
