### ISSUE TITLE
[BUG] locator.EvaluateAsync timeout 

### ISSUE THREAD

**Issue by kababoom** [microsoft/playwright-dotnet#2375]
**Context:**
- Playwright Version: 1.27.2
- Operating System: Windows + Mac
- .NET version: .NET 6
- Browser: All
- Extra: None

**Code Snippet**

```
using Microsoft.Playwright;

global::Microsoft.Playwright.Program.Main(new string[] { "install" });

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
var page = await browser.NewPageAsync();

await page.GotoAsync("https://www.google.com/");

var locator = page.Locator("button:has-text(\"NOTAccept all\")");

// Click button:has-text("Accept all")

await locator.EvaluateAsync<string>("e => e.click()", new LocatorEvaluateOptions() { Timeout = 1000 });

```

**Describe the bug**

Timeout value is not honoured when using EvaluateAsync, the above snippet demonstrates this with a simple element click. 

System.TimeoutException: 'Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button:has-text("NOTAccept all")"
============================================================'

**Comment by mxschmitt** [comment]
As per Interface:

`    Task<T> EvaluateAsync<T>(string expression, object? arg = default, LocatorEvaluateOptions? options = default);`

The second parameter is treated as the [argument](https://playwright.dev/dotnet/docs/evaluating) to `EvaluateAsync` which gets passed to the browser JS runtime.

If you want to specify a custom timeout, then you need to do: `await locator.EvaluateAsync<string>("e => e.click()", null, new LocatorEvaluateOptions() { Timeout = 1000 });
`

**Comment by kababoom** [comment]
Thank you Max...
