### ISSUE TITLE
[BUG] codegen scripts for Microsoft SSO/TFA do not generate useable code

### ISSUE THREAD

**Issue by Prinsn** [microsoft/playwright-dotnet#2382]
**Context:**
- Playwright Version: 1.27.2
- Operating System: Windows 10
- .NET version: NET 6.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
Generated Code
```cs
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
        {
            Headless = false,
        });
        var context = await browser.NewContextAsync();
        var page = await context.NewPageAsync();
        await Page.GotoAsync("https://<theurl>.com/");
        await Page.Locator("input[type=\"number\"]").FillAsync("11");
        
        await Page.WaitForURLAsync(new Regex("https://login.microsoftonline.com/<unique login string>");
        
        await Page.GetByPlaceholder("Email, phone, or Skype").ClickAsync();
        //This line never appears to be executed
        await Page.GetByPlaceholder("Email, phone, or Skype").FillAsync("name@domain.com");
        await Page.GetByPlaceholder("Email, phone, or Skype").PressAsync("Enter");
        
        await Page.WaitForURLAsync("https://login.microsoftonline.com/login.srf");
        await Page.GotoAsync("https://<theurl>.com/signin-oidc#access_token=<unique token>);
        
        await Page.Locator("input[type=\"number\"]").FillAsync("11");
```

**Describe the bug**

Upon rerunning the test, it fails to ever `FillAsync`, presumably because the `WaitForUrlAsync` is unique every execution.

**Comment by Prinsn** [comment]
Further testing appears to show that it actually gets to 
`        await Page.Locator("input[type=\"number\"]").FillAsync("11");`

and times out waiting for the field, despite never doing

`        await Page.GetByPlaceholder("Email, phone, or Skype").FillAsync("name@domain.com");`

**Comment by Prinsn** [comment]
![image](https://user-images.githubusercontent.com/3219355/200934590-83d73b77-5dc1-47dd-9c54-e4b094055de8.png)
This is the context in which it's failing.  

I've honestly got to ask if I'm doing something wrong here because I'm looking into this because the claims of the suite are that it is more robust than Selenium but these are literally the exact same flaws we experienced with Katalon Recorder.

**Comment by Prinsn** [comment]
Trying to extract any information whatsoever out of this, the locator in question that's failing is the first
`        await page.Locator("input[type=\"number\"]").FillAsync("11");`
which I overlooked, because there was no user action at that step.

That just shows up between the initial url and the direct to `login.microsoft.com`

Removing it causes the execution to fail IMMEDIATELY instead of getting to the above screen and timing out.

**Comment by Prinsn** [comment]
Apparently the above -1ms failure appears to come from trying to ameliorate the issue with `Timeout = Timeout.Infinite` which was an VS2022 autocomplete suggestion, so that was fun.

**Comment by Prinsn** [comment]
Related to #2380 the generated code single clicks appear to be insufficient, I have to duplicate these, but otherwise the code gen for the case works so long as I manually extract dead code and update the auth stuff to use regex instead of raw URL copy.

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally? Seems like this issue is mixing a few different things. If the WaitForURL links are dynamic, you can either make them work with your random URLs, aka. Regex or you remove them.

(Next Playwright will not add WaitForURL anymore, since it has auto-waiting by default.)
