### ISSUE TITLE
[Question] test run aborted.

### ISSUE THREAD

**Issue by joshmar** [microsoft/playwright-dotnet#2386]
Heey Playwrighters,

## Goal
I'm trying to setup a net for 500 status codes during tests. The goal is to preemptively stop the current test whenever a 500 request response has been returned. 

## Issue 1
Sadly I have a bit of a hardship setting this up. The code I've got written down so far is working, however, it comes with a side effect; it makes the test host process crash. This means that if the 500 code is received in the first test it stops all other tests who may not be faulty at all.

## Issue 2
Further more, I've also noticed that enabling the EventHandler for anything context related "clocks up" the trace log file.

## Code
```cs
    [SetUp]
    public async Task BasePageSetup()
    {
        Context = await NewContext(ContextOptions).ConfigureAwait(continueOnCapturedContext: false);
        Page = await Context.NewPageAsync().ConfigureAwait(continueOnCapturedContext: false);
        Page.Response += Page_Response;
    }

    private void Page_Response(object? sender, IResponse e)
    {
        try
        {
            if (e.Status >= 500 && e.Status <= 599)
            {
                throw new InternalServerErrorException();
            }
        }
        catch (PlaywrightException ex)
        {
            if (!ex.Message.Contains("Response body is unavailable for redirect responses", StringComparison.InvariantCultureIgnoreCase))
            {
                if (!ex.Message.Contains("No resource with given identifier found", StringComparison.InvariantCultureIgnoreCase))
                {
                    if (!ex.Message.Contains("Target closed"))
                    {
                        throw;
                    }
                }
            }
        }
    }
```
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Testing._Technology.Extensions.Exceptions.InternalServerErrorException: Exception of type 'Testing._Technology.Extensions.Exceptions.InternalServerErrorException' was thrown.
   at Testing.BasePageTest.Page_Response(Object sender, IResponse e) in ***\BasePageTest.cs:line 57
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
### Clogged trace viewer log
![image](https://user-images.githubusercontent.com/19995485/201870948-398893de-edeb-41f7-b25f-2e9ba4615105.png)

### Expected trace viewer log
![image](https://user-images.githubusercontent.com/19995485/201871520-dfca062b-c5fe-4bef-9b68-aa07bcbe9631.png)

**Comment by joshmar** [comment]
Little update; I've found the reason for the crashes, a rookie mistake on my part... I used a [async void](https://github.com/microsoft/vstest/issues/2261#issuecomment-1034018644) method for the EventHandler. I had some other refactors that needed to be done, so I'm not quite sure yet about "Issue 2". I'll update again when I do.

**Comment by joshmar** [comment]
Figured out the issue lays in failing a test through the `EventHandler` directly. Whenever an exception is thrown in a test case its fine, but when the exact same is done through the `EventHandler` it crashes all tests.

To be fair I'm not quite sure as to how this came to be, however I now do know it is because of that.


Could anyone shed some more light onto why this happens, and what - most likely - I'm doing wrong?

**Comment by VictorYakushenko** [comment]
I created a similar problem in selenium https://github.com/SeleniumHQ/selenium/issues/11207

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally? So far this sounds not like an issue in Playwright.

**Comment by joshmar** [comment]
I've made a very basic version of my code.
Do keep in mind the tests will probably run into a timeout exception at some point, depending on your culture.

https://github.com/joshmar/playwright-examples.git

**Comment by mxschmitt** [comment]
Closing for now since its stale, please re-file if you still encounter this issue.
