### ISSUE TITLE
[Question]: Test reports

### ISSUE THREAD

**Issue by mr0406** [microsoft/playwright-dotnet#2401]
### Your question

Is .NET Playwright capable of producing a report like this?
https://playwright.dev/docs/test-reporters#html-reporter

If so, could you give a few examples?
If not, is there any intention to implement that feature?
Do you know of any existing libraries for this? I am using NUnit as a testing framework.

**Comment by mxschmitt** [comment]
HTML reporter is not available for Playwright for .NET.

You can use existing nunit/mstest reporters which will produce html, but they will have less functionality.

**Comment by dikili** [comment]
Has this issue been addressed? it wd be have been great to see these enhancement in playwright c# too.
