### ISSUE TITLE
[Feature] .NET7 docker image

### ISSUE THREAD

**Issue by ikesnowy** [microsoft/playwright-dotnet#2403]
here is my `Dockerfile`, maybe we can publish a separate image tagged `-jammy` with .NET7 SDK?

```Dockerfile
FROM mcr.microsoft.com/playwright/dotnet:v1.27.2-focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy AS build
WORKDIR /src
# COPY projects...
RUN dotnet restore "src/Test.Worker/Test.Worker.csproj"
COPY . .
WORKDIR "/src/src/Test.Worker"
RUN dotnet build "Test.csproj" -c Release --no-restore

FROM build AS publish
RUN dotnet publish "Test.Worker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Test.Worker.dll"]
```

**Comment by mxschmitt** [comment]
If you want to pick different .NET SDK versions we recommend building either your own Docker image or to use the existing one and inherit from it via the `FROM` keyword. After that you have all the flexibility to install your different .NET version on top of it.

We use the .NET LTS for our base image, so once a new LTS gets selected, we'll pick the new one.
