### ISSUE TITLE
[Question]: Docker linux/amd64 support

### ISSUE THREAD

**Issue by n3nikita** [microsoft/playwright-dotnet#2406]
### Your question

I'm trying to deploy my playwright app to Azure. My app is working fine with Docker ARM container; however, Azure's **Web App for Containers** requires linux/amd64. Here is my Dockerfile for linux/amd64:

```Dockerfile
FROM mcr.microsoft.com/playwright/dotnet:v1.28.0-focal-amd64

WORKDIR /src
COPY . .
RUN dotnet restore "./src/MyApp.API/MyApp.API.csproj"
RUN dotnet publish "./src/MyApp.API/MyApp.API.csproj" -c Release -o /app/publish

WORKDIR /app/publish
EXPOSE 80

ENTRYPOINT ["dotnet", "MyApp.API.dll"]
```
I build it using this command: `docker buildx build --platform linux/amd64 -t myapp:latest .`

```c#
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions
{
    Headless = true
});
```
Chromium doesn't seem to work. Firefox is working but JavaScript is not rendering. 

I have this error when I try to use `Chromium`: 
<img width="789" alt="CleanShot 2022-11-23 at 08 26 38@2x" src="https://user-images.githubusercontent.com/22433209/203491988-56f40dba-026f-49a9-8896-2ff45503bc8a.png">

**Comment by n3nikita** [comment]
Error on the screenshot is coming from the Docker image on my M1 but my app is not working on Azure either

**Comment by mxschmitt** [comment]
What error do you get on Azure? I imagine its a different error which you get there. 

We recommend to not pass the `-amd64` then the tag gets selected automatically and it will work locally.

**Comment by mxschmitt** [comment]
Closing since its stale.
