### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by maFrekt** [microsoft/playwright-dotnet#2412]
**Context:**
- Playwright Version: 1.28
- Operating System: Windows 10
- .NET version: NET 6
- Browser: All

**Code Snippet**

```
    using var playwright = await Playwright.CreateAsync();
    await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
    await using var browserContext = await browser.NewContextAsync();
    var page = await browserContext.NewPageAsync();
    await page.GotoAsync("https://playwright.dev/docs/test-reporters", new PageGotoOptions(){ Timeout = 240000});
    await page.WaitForLoadStateAsync(LoadState.NetworkIdle);
    await page.ClickAsync(".tabItem_LNqP");
```
```

Microsoft.Playwright.PlaywrightException: selector is not defined
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 163
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 482
```

Playwright starts the browser, loads the corresponding web page and as soon as an element is tried to be addressed, I get this error message.

Typescript playwright works fine.
DotNet just breaks since friday.

**Comment by mxschmitt** [comment]
I tried to reproduce it with the example above and it was working for me.

Does this reproduce for you on https://playwright.dev/docs/test-reporters?

**Comment by maFrekt** [comment]
![image](https://user-images.githubusercontent.com/24719925/204522294-edeb1490-379e-4de4-a59b-709e5b365b40.png)

Just created a fresh project and run the test again.
The issue remains the same. I did debug into it and saw that the dictionary key "selector" was filled with the correct value, but I dont know what happens after the send message where it throws the error.

**Comment by feiyun0112** [comment]
i can run it in VS2022, maybe do not use rider, try to run in dotnet CLI

**Comment by maFrekt** [comment]
I think you are on the right track here. 
It does run with VS2022, but I cannot get it to work with Rider.

**Comment by mxschmitt** [comment]
Looks like an issue with your environment and not with Playwright. We recommend re-installing .NET and/or VS/VSC.
