### ISSUE TITLE
[Question]: Can I use current Edge browser without using pwsh download

### ISSUE THREAD

**Issue by jonswaino** [microsoft/playwright-dotnet#2414]
### How can I make use of the currently up-to-date browser installed in an Enterprise Environment?

First time using the framework in an Enterprise environment using VS.
Problem is we can't run a test due to the:  "Looks like Playwright was just installed", please run pwsh bin/debug/netX... to download latest browsers, error being raised.

I understand this is to download the latest browsers.
However, pwsh is not installed on our systems in our locked down environment.
Also there is an issue with winget being broken so it is not downloading the "Microsoft.Powershell" package.  [https://github.com/microsoft/winget-cli/issues/1826](url)

So the question is, is there a way to circumvent winget's issue/downloading pwsh, can we not simply use it with the latest Edge browser installed (V107.0.1418.62)?

**Comment by mxschmitt** [comment]
If you want to use Firefox or WebKit then you need to leverage the `pwsh` script to install the Playwright browsers.

If you want to use your existing Microsoft Edge, then you can pass `Channel="msedge"` when launching the browser via [BrowserType.LaunchAsync](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-option-channel).

I guess that answers your question?

**Comment by jonswaino** [comment]
So should I inherit from PageTest to set this up?  I can't see from the intro docs how to intercept with Browser config.
Thanks again.

**Comment by mxschmitt** [comment]
Yes, you can pass it like this or in your runsettings file: `dotnet test -- Playwright.LaunchOptions.Channel=msedge` there is currently no way to set it inside the class.

**Comment by jonswaino** [comment]
Ah ok.  It would have been nice to run from the VS test runner.  But no problem.  Thanks for your help.
