### ISSUE TITLE
[Question]: How to set global tracing options for playwright on .net?

### ISSUE THREAD

**Issue by markoueis** [microsoft/playwright-dotnet#2415]
### Your question

I'm setting up CI with playwright and looking to make trace information available for all tests/failed tests to easily allow debugging. I need a way to do this globally for all tests. We are using nunit as per document recommendations. 

The "Recording a trace on CI" documentation for .net does not appear to be accurate, or I am missing something: see link
https://playwright.dev/dotnet/docs/trace-viewer#recording-a-trace-on-ci

I like what the instructions in that link state, but they appear to be for node and not .net (though they are in the .net section)

Thank you

**Comment by mxschmitt** [comment]
This is not possible as of today, folding into https://github.com/microsoft/playwright-dotnet/issues/2214.
