### ISSUE TITLE
[Question]: Can golang version be updated in base image?

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright-dotnet#2416]
### Your question

In my dockerfile I'm pulling the image version "playwright/dotnet:v1.28.0-focal". But our security scan says the golang version 1.13.8 has some vulnerabilities. Is it possible to update that in your base image to latest golang version?

**Comment by mxschmitt** [comment]
Can you help us pointing out where in this Docker image Go is installed? Playwright does not use Go.

**Comment by quldude** [comment]
Figured out that go is being installed when running below command in dockerfile:
```
RUN apt install chromium-browser -y
```
