### ISSUE TITLE
Does C # have no launchServer?[Feature]

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2422]
Does C # have no launchServer?

**Comment by mxschmitt** [comment]
Language ports don't have the launchServer feature, you can manually launch the server via Node.js: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server

**Comment by bbhxwl** [comment]
> Language ports don't have the launchServer feature, you can manually launch the server via Node.js: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server

Would you consider increasing it in the future? I want to create it automatically with C #.

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright/issues/19267.
