### ISSUE TITLE
[BUG] 401 error when calling rest api methods when setting StorageState in BrowserContext

### ISSUE THREAD

**Issue by bloodgang94** [microsoft/playwright-dotnet#2423]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows 10
- .NET version: NET 6
- Browser: All
- Extra: Authorization via UI keycloak

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```cs
      public async Task CreateRequestApiAsync()
        {
            var browserStorageState= await _browserContext.StorageStateAsync();

            var api = await _playwright.APIRequest.NewContextAsync(new APIRequestNewContextOptions
            {
                StorageState = browserStorageState
            });
            var response = await api.PostAsync("https://page.com/api/request",

                new() { DataObject = new Fixture().Create<RequestDto>() });
        }
```
![image](https://user-images.githubusercontent.com/63465285/206525699-16dd6b63-b2e8-4f18-90ee-53618f2c9726.png)

**Describe the bug**

Good day! Our company uses keycloak as a single entry point.
I'm trying to use browser context for authorization on the backend side.
The code I provided above always returns 401 errors, although the documentation says:
Storage state is interchangeable between BrowserContext and APIRequestContext

Any ideas how to get this to work? I have a workaround to get token from localstorage
(vuex:tokenInfo:access_token)

**Comment by mxschmitt** [comment]
Could you provide us a repro which we can run locally? Yes this should work out of the box see here:

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
await using var browserContext = await browser.NewContextAsync();
var page = await browserContext.NewPageAsync();
await browserContext.AddCookiesAsync(new []
{
    new Cookie
    {
        Name = "cookie1",
        Value = "value1",
        Url = "https://postman-echo.com/headers",
        HttpOnly = false,
        Secure = true,
        SameSite = SameSiteAttribute.None,
    }
});

var storageState = await browserContext.StorageStateAsync();

Console.WriteLine("storage state: " + storageState);

var request = await playwright.APIRequest.NewContextAsync(new ()
{
    StorageState = storageState,
});
var response = await request.GetAsync("https://postman-echo.com/headers");
Console.WriteLine(await response.TextAsync());

```

**Comment by bloodgang94** [comment]
@mxschmitt  There is definitely time for this. I can give a snapshot of storageState for now
[storageState.txt](https://github.com/microsoft/playwright-dotnet/files/10220227/storageState.txt)

As I understand it, the problem is that the bearer token is in KEYCLOAK_IDENTITY

**Comment by mxschmitt** [comment]
Looks stale and we don't have a repro so we cannot act on it. Closing as part of the triage process. Please re-file with a clear repro.
