### ISSUE TITLE
[BUG] Control+C throws an error

### ISSUE THREAD

**Issue by RenderMichael** [microsoft/playwright-dotnet#2426]
**Context:**
- Playwright Version: 1.28.0
- .NET version: .NET 7
- OS/Browser: Windows 10 + Chromium, Windows 10 + Firefox, MacOS Ventura + webkit
- Extra: I'm connecting to a remote browser with `IBrowserType.ConnectAsync()`

**Code Snippet**

```cs
Page.Keyboard.DownAsync("Control+C").Wait();
```

**Describe the bug**
The above line throws `PlaywrightException: Unknown key: "Control+C"`

**Comment by RenderMichael** [comment]
The same thing happens with `Control+V`

**Comment by mxschmitt** [comment]
Shortcuts are not supported in DownAsync, only in PressAsync: https://playwright.dev/dotnet/docs/api/class-keyboard#keyboard-down

**Comment by RenderMichael** [comment]
Got it, thanks
