### ISSUE TITLE
[Feature] Add an option or a method to set global Timeout on `Expect()`

### ISSUE THREAD

**Issue by konarx** [microsoft/playwright-dotnet#2428]
At browser's initialization, there are the `BrowserTypeLaunchOptions` passing the `Timeout` property. eg:
`var browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions{Timeout = 25000});`

After page initialization, there are methods:
`_page.SetDefaultTimeout(25000);`
`_page.SetDefaultNavigationTimeout(25000);`

But the `Expect()` method persists its default timeout, which is 5000ms.

There should also be a way to set this specific timeout globally, for example:
`_page.SetAssertionTimeout(25000);`

_PS: I know about the `new LocatorAssertionsOptions{Timeout = 25000}` and pass it in every single `Expect()` method but It would much more useful to set it globally._

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2259.

Please upvote it there.
