### ISSUE TITLE
[Question]: How to reduce image size?

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright-dotnet#2429]
### Your question

Currently the base image "playwright/dotnet:v1.28.0-focal" has a size of 2.75GB. Are there ways I can reduce it?

**Comment by mxschmitt** [comment]
You can manually build the Docker image that it does not contain all the 3 browsers and their dependencies. Other than that there is no way as of today.

See here the build script: https://github.com/microsoft/playwright-dotnet/blob/main/utils/docker/build.sh
