### ISSUE TITLE
[Question]: ToHaveScreenshot in .net API

### ISSUE THREAD

**Issue by vmachacek** [microsoft/playwright-dotnet#2433]
### Your question

Hello I went thru the code in this repo but couldn't find ToHaveScreenshot equivalent of what is mentioned here https://playwright.dev/docs/test-snapshots is there any plant to add it in the future? I guess I can use Verify for this if C# lib does no support it or there are no plans to add it

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/1854

**Comment by infinitejest69** [comment]
@vmachacek Thank you for the Verify suggestion. i raised issue #1854 and you suggestion helped my find this
[Verify.HeadlessBrowsers](https://github.com/VerifyTests/Verify.HeadlessBrowsers)
and this blog that show how easy it is to use
[snapshot-testing-with-verify](https://www.danclarke.com/snapshot-testing-with-verify)
