### ISSUE TITLE
[Question]: Is there a way to trace only on failure in dotnet

### ISSUE THREAD

**Issue by markoueis** [microsoft/playwright-dotnet#2446]
### Your question

We are using the Trace Chunking feature. We only want to trace the failing chunks. Is there a way to do that or do we have to trace everything and then delete the files of the successful chunks. We just don't want to clutter things with hundreds of files when maybe just 1 file is needed.

```
page.Context.Tracing.StartChunkAsync().Wait();
try
{
    //Do something with page
}
finally
{                
    page.Context.Tracing.StopChunkAsync(new TracingStopChunkOptions() { Path = $"{chunkId}.zip" }).Wait();
}    
```

Would it work for example if I put empty Path on the TracingStopChunkOptions?

Thanks

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2214.

There is no out of the box solution yet for .NET like we have in Node.js
