### ISSUE TITLE
[Question]:  Invalid browser name: ms edge

### ISSUE THREAD

**Issue by dens3122** [microsoft/playwright-dotnet#2449]
### Your question

**Context:**
- Playwright Version: v1.27.1
- Operating System: Windows
- .NET version: .NET 6
- Browser: Chromium
- Extra: Jenkins slave (Windows server 2019) 

**Code Snippet**

```cs
using System.Net;
using Microsoft.Playwright.NUnit;
using Microsoft.Playwright;
using NUnit.Framework;
using System.Threading.Tasks;
using Paz.Autotests.RunSettings;

namespace Paz.Autotests;

public class BrowserContextCredentialsTests : BrowserTest
{
    static string URL = Configuration.WebAppUrl;
    static string USERNAME = Configuration.WebAppUserName;
    static string PASSWORD = Configuration.WebAppPassword;

    [Test]
    public async Task ShouldWorkWithCorrectCredentials()
    {
        await using var context = await Browser.NewContextAsync(new()
        {
            HttpCredentials = new()
            {
                Username = USERNAME,
                Password = PASSWORD
            },
        });

        var page = await context.NewPageAsync();
        var response = await page.GotoAsync(URL);
        Assert.AreEqual((int)HttpStatusCode.OK, response.Status);
    }

    [Test]
    public async Task ShouldFailIfWrongCredentials()
    {
        await using var context = await Browser.NewContextAsync(new()
        {
            HttpCredentials = new()
            {
                Username = "foo",
                Password = "bar"
            },
        });

        var page = await context.NewPageAsync();
        var response = await page.GotoAsync(URL);
        Assert.AreEqual((int)HttpStatusCode.Unauthorized, response.Status);
    }

    [Test]
    public async Task ShouldReturnResourceBody()
    {
        await using var context = await Browser.NewContextAsync(new()
        {
            HttpCredentials = new()
            {
                Username = USERNAME,
                Password = PASSWORD
            },
        });

        var page = await context.NewPageAsync();
        var response = await page.GotoAsync(URL);
        Assert.AreEqual((int)HttpStatusCode.OK, response.Status);
        Assert.AreEqual("PAZ", await page.TitleAsync());
        StringAssert.Contains("PAZ", await response.TextAsync());
    }
}
```

**Question**

Hello. I'm trying to run autotests in Jenkins, but they fall with an error. The launch takes place under a technical domain account with policies set by my organization. No matter what browser i choose this error occurs. At the same time, when I log into this server via RDP under my own domain account and run the same command, the tests are successful. What could be wrong?

**chromium.runsettings**

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<RunConfiguration>
		<EnvironmentVariables>
			<DEBUG>pw:api</DEBUG> <!-- Логгирование в консоли. "0" - нет логгирования -->
			<PWDEBUG>0</PWDEBUG><!-- Отладка тестов в браузере, подробнее: https://playwright.dev/dotnet/docs/debug -->
		</EnvironmentVariables>
	</RunConfiguration>
	<Playwright>
		<BrowserName>chromium</BrowserName> <!-- Движок браузера, который будет использоваться при тестировании: "chromium", "firefox", "webkit"-->
		<ExpectTimeout>1000</ExpectTimeout> <!-- Таймаут для тестов в мс, подробнее: https://playwright.dev/docs/test-timeouts -->
		<LaunchOptions>
			<Headless>true</Headless> <!-- Запускать браузер (режим headed) - "false", не запускать (режим headless) - "true" -->
			<Devtools>false</Devtools> <!-- Инструменты разработчика в браузере -->
			<ExecutablePath>C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe</ExecutablePath> <!-- Путь до исполняемого файла браузера, в котором выполнять автотесты -->
		</LaunchOptions>
	</Playwright>
	<TestRunParameters>
		<Parameter name="webAppUrl" value="***" /> <!-- URL для тестирования -->
		<Parameter name="webAppUserName" value="lol" />
		<Parameter name="webAppPassword" value="kek" />
	</TestRunParameters>
</RunSettings>
```

**Run command**
dotnet test autotests_bin\Paz.Autotests.Smoke.dll -s ..\chromium.runsettings -- TestRunParameters.Parameter(name=\"webAppUrl\", value=\"******\")  Playwright.BrowserName=chromium Playwright.LaunchOptions.ExecutablePath="C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" 

**LOG**
09:40:42  Microsoft (R) Test Execution Command Line Tool Version 17.0.0
09:40:42  Copyright (c) Microsoft Corporation.  All rights reserved.
09:40:42  
09:40:42  Starting test execution, please wait...
09:40:42  A total of 1 test files matched the specified pattern.
09:40:42    Failed ShouldFailIfWrongCredentials [3 s]
09:40:42    Error Message:
09:40:42     System.ArgumentException : Invalid browser name: ms edge
09:40:42    Stack Trace:
09:40:42       at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.ValidateBrowserName(String browserName) in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 102
09:40:42     at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.get_BrowserName() in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 45
09:40:42     at Microsoft.Playwright.NUnit.PlaywrightTest.PlaywrightSetup() in /_/src/Playwright.NUnit/PlaywrightTest.cs:line 44
09:40:42     at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
09:40:42     at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
09:40:42     at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
09:40:42     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
09:40:42     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
09:40:42    Failed ShouldReturnResourceBody [< 1 ms]
09:40:42    Error Message:
09:40:42     System.ArgumentException : Invalid browser name: ms edge
09:40:42    Stack Trace:
09:40:42       at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.ValidateBrowserName(String browserName) in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 102
09:40:42     at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.get_BrowserName() in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 45
09:40:42     at Microsoft.Playwright.NUnit.PlaywrightTest.PlaywrightSetup() in /_/src/Playwright.NUnit/PlaywrightTest.cs:line 44
09:40:42     at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
09:40:42     at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
09:40:42     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
09:40:42     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
09:40:42    Failed ShouldWorkWithCorrectCredentials [< 1 ms]
09:40:42    Error Message:
09:40:42     System.ArgumentException : Invalid browser name: ms edge
09:40:42    Stack Trace:
09:40:42       at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.ValidateBrowserName(String browserName) in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 102
09:40:42     at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.get_BrowserName() in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 45
09:40:42     at Microsoft.Playwright.NUnit.PlaywrightTest.PlaywrightSetup() in /_/src/Playwright.NUnit/PlaywrightTest.cs:line 44
09:40:42     at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
09:40:42     at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
09:40:42     at NUnit.Framework.Internal.Commands.SetUpTearDownCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
09:40:42     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
09:40:42     at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
09:40:42  
09:40:42  Failed!  - Failed:     3, Passed:     0, Skipped:     0, Total:     3, Duration: 3 s - Paz.Autotests.Smoke.dll (net6.0)

**Comment by mxschmitt** [comment]
I unfortunately can't reproduce, could you provide a minimal repro which we can run locally? I already have tried your runsettings file + the command you supplied.

**Comment by dens3122** [comment]
what exactly is needed?
I repeat - the error occurs when running the jenkins job. Can you reproduce the launch in jenkins?
This is how you can run it in jenkins, if all the parameters are written in the .runsettings file:

**jenkins stage**
``` groovy
stage('Run tests') {
            steps {
                script {
                    try {
                                bat("""dotnet test autotests_bin\\${dll} -s autotests_bin\\${runSettings}  """)
                    }
                    catch (Throwable ignore) { }
                }
            }
        }
```

**Comment by mxschmitt** [comment]
We are not familiar with Jenkins, so I would appreciate a reproduction without Jenkins. So something which we can run locally which demonstrates the issue.
