### ISSUE TITLE
[Question] Test retries and HTML reporter for .Net?

### ISSUE THREAD

**Issue by jgraber** [microsoft/playwright-dotnet#2455]
Hi,
Are there any plans to add the 2 Node.js features **[test retries](https://playwright.dev/docs/test-retries)** and the **[HTML reporter](https://playwright.dev/docs/test-reporters#html-reporter)** to .Net? Or do you have a work around to create something similar when you run Playwright in .Net?

Regards,
Johnny

**Comment by yury-s** [comment]
HTML reporter is only available in Playwright Node.js test runner. @mxschmitt would now better about test retries.

**Comment by mxschmitt** [comment]
Test retries feature request is here: https://github.com/microsoft/playwright-dotnet/issues/2316
