### ISSUE TITLE
[Question]: How to check if each element is empty in locator which resolves to multiple elements.

### ISSUE THREAD

**Issue by groogiam** [microsoft/playwright-dotnet#2458]
### Your question

I have a locator that resolves to multiple elements which I want to assert are empty. When using the Expect.ToBeEmptyAsync I get a strictness exception. Is there a way to perform this check on multiple elements? Thanks.

**Comment by mxschmitt** [comment]
```csharp
foreach (var element in await page.GetByRole(AriaRole.Listitem).AllAsync())
  Expect(element).ToBeEmptyAsync();
```

You can do something like that, would that work for you? Instead of GetByRole you can use any locator. See [here](https://playwright.dev/dotnet/docs/locators#rare-use-cases).

**Comment by groogiam** [comment]
That works! Looks like `ILocator.AllAsync` was very recently added to the API. Thanks for your help.
