### ISSUE TITLE
[Question]: switch to new tab not working in headless mode

### ISSUE THREAD

**Issue by firdausng** [microsoft/playwright-dotnet#2459]
### Your question

I am using PW with .Net - xUnit specflow.
I am working on a test where clicking a button will open new tab

I am using this code
`var newPage = await context.RunAndWaitForPageAsync(async () =>
            {
                await Page.ClickAsync("div[data-behavior-analytics-feature='tenantDrawer-app1']");
            });
        await newPage.WaitForLoadStateAsync();
`
this work on headful but not in headless mode. it will just return timeout after 30 second

Any suggestions what I might be doing wrong here?

**Comment by mxschmitt** [comment]
We recommend tracing to find out why its not working as expected: https://playwright.dev/dotnet/docs/trace-viewer-intro

Without a repro we cannot act on it, so I'm closing it for now, feel free to re-file with a repro.
