### ISSUE TITLE
[BUG] Console window appearing over WPF Application v1.30

### ISSUE THREAD

**Issue by FutureTD** [microsoft/playwright-dotnet#2462]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- .NET version: [e.g. .NET 7]
- Browser: FireFox
- Extra: [any specific details about your environment]

**Code Snippet**

```cs
Microsoft.Playwright.Program.Main(new[] {"install", "firefox"});
```

**Describe the bug**

I'm currently using playwright in my WPF application and upon my application startup I have be running the code on startup:

Microsoft.Playwright.Program.Main(new[] {"install", "firefox"});

Everything has been working great. However, with the latest update playwright version (1.30.0), when that code is run it now pops up a console window cmd.exe when the other versions previously were silent. 

Even if the browser is already installed that window pops up for a few seconds over my application. I was wondering if there was a way to revert back to the old behavior especially for a WPF Application as I prefer not to have a console window popping up in front of my application.

I reported this issue before from a previous version https://github.com/microsoft/playwright-dotnet/issues/2103#issue-1206735789

**Comment by mxschmitt** [comment]
I'm curious why this happens with WPF but not with a normal .NET console app. Having a repro would also be quite nice, then we can dig more into it.

Definitely its caused by https://github.com/microsoft/playwright-dotnet/pull/2451 but also the previously implementation had side effects since `CreateNoWindow=true` does not forward the stdout/stderr anymore.

**Comment by mxschmitt** [comment]
I was able to reproduce it with a WPF application as well with a normal Windows forms application. Maybe @nohwnd knows why this happens, or if this is normal Windows behavior.

**Comment by FutureTD** [comment]
Has their been any progress on a fix for this issue?

**Comment by nohwnd** [comment]
@FutureTD  I tried to fix it, but that would revert back an issue with progress not being reported, unless progress stops requiring interactive prompt,  there is no solution currently.
