### ISSUE TITLE
[BUG] Expect.ToContainTextAsync Fails to Match Regex

### ISSUE THREAD

**Issue by groogiam** [microsoft/playwright-dotnet#2467]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Window 10
- .NET version: .NET 6
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;
using System.Text.RegularExpressions;

class Program
{
    public static async Task Main()
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
        var l = page.Locator("#my-element");
        await Assertions.Expect(l).ToContainTextAsync(new Regex(@"^(Id:\s)[1-9]\d*$");
    }
}
```

**Describe the bug**
The above snipped fails when the input element text is `Id: 5`

**Comment by mxschmitt** [comment]
The reason for this is since you have `^` and `$` in your regex, which means it does not allow whitespaces and does not act like contains. Thereby you'd have to get rid of the whitespace before your text like this:

```csharp
await page.SetContentAsync(@"
    <div id=""my-element"">Id: 123</div>
");
var l = page.Locator("#my-element");
await Assertions.Expect(l).ToContainTextAsync(new Regex(@"^(Id:\s)[1-9]\d*$"));
```

Alternatively remove the `^` and `$` (starts and ends with).

**Comment by groogiam** [comment]
That fixes the issue. Thanks for your help.
