### ISSUE TITLE
[Question]: Where are the 1.30 release notes?

### ISSUE THREAD

**Issue by slang25** [microsoft/playwright-dotnet#2470]
### Your question

It looks like 1.30 was released to nuget, but there are usually a release added to the GH repo and release notes, but I can't find them this time:
https://github.com/microsoft/playwright-dotnet/releases

**Comment by slang25** [comment]
That said, I've just looked at the playwright repo and [seen that](https://github.com/microsoft/playwright/releases/tag/v1.30.0) it was a maintenance release + browser update. It would still be nice to know that from the release notes here too.

**Comment by mxschmitt** [comment]
I updated it for the .NET release as well, its a maintenance release.

>
