### ISSUE TITLE
[BUG] add IgnoreDefaultArgs and set IgnoreAllDefaultArgs =true  LaunchPersistentContextAsync  time out

### ISSUE THREAD

**Issue by wang3156** [microsoft/playwright-dotnet#2477]
![image](https://user-images.githubusercontent.com/18094713/217766629-eaf70af0-11b9-41d6-b4d6-ed684e5bf7fa.png)
Yellow part after an execution LaunchPersistentContextAsync tip timeout

      var playwright = await Playwright.CreateAsync();
            BrowserTypeLaunchPersistentContextOptions bto = new BrowserTypeLaunchPersistentContextOptions { Headless = false, ExecutablePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "chromedriver_win32", "chrome-win", "chrome.exe") };
            //bto.IgnoreDefaultArgs = new[] { "--enable-automation" };
            //bto.IgnoreAllDefaultArgs = true;
            var browser = await playwright.Chromium.LaunchPersistentContextAsync(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "chromedriver_win32", "webDir"), bto);

**Comment by mxschmitt** [comment]
This is expected, as per documentation:

> Dangerous option; use with care.

If you skip all arguments, then you need to supply your own ones with the necessary ones, from [here](https://github.com/microsoft/playwright/blob/6b0a7003c4e2d155fdb04301dd8e6b2e52646a85/packages/playwright-core/src/server/chromium/chromiumSwitches.ts#L20) and [here](https://github.com/microsoft/playwright/blob/df143031e7eac11460bcd658dc3bb5a8951ccd64/packages/playwright-core/src/server/chromium/chromium.ts#L262).

What are you trying to achieve?
