### ISSUE TITLE
[Feature] Video of a whole BrowserContext

### ISSUE THREAD

**Issue by PeterHevesi** [microsoft/playwright-dotnet#2482]
Hi guys,
Please, I need a feature, in which it would be possible to instruct Playwright to create 1 video for a whole BrowserContext rather than videos for each Page.
I have a multipage scenario, where I open some pages in a new tab to verify some informations, but I can open a lot of them. And then I have a lot of videos, which is not really that helpful to see what was happening. I would rather want to have 1 continous video of a whole BrowserContext, to see exactly how the test went all in 1 video.
Thanks sooo much, if you decide to implement this feature, I will greatly appreciate 🙂

**Comment by mxschmitt** [comment]
Having a single video would not work since multiple things will happen at the same in multiple pages. For multi page debugging scenarios we recommend the trace viewer, see here: https://playwright.dev/dotnet/docs/trace-viewer-intro

(much more powerful than videos or screenshots!)
