### ISSUE TITLE
[Feature] Add support Page.WaitForEvent

### ISSUE THREAD

**Issue by MartinStrbak** [microsoft/playwright-dotnet#2488]
I have React web component
    <o2-select id="multi-standalone" label="Select label" class="hydrated"></o2-select>

and it emits this custom event
o2ScrollToEnd
Emitted from o2-select when options scrollbar has reached the most bottom position.

type Event = {
  detail: {
    value: string;
  };
};

I need to wait for this event, but in playwright-dotnet is no page.WaitForEvent  (Node.js version of Playwright supports it).
Is there any other way/workaround how to catch custom page/component events in playwright-dotnet?

**Comment by mxschmitt** [comment]
Node.js waitForEvent also would not work for this, since it only allows waiting for Playwright events see [here](https://playwright.dev/docs/api/class-page#page-wait-for-event).

In your scenario I'd do the following:

```csharp
var waitForo2ScrollToEndTask = page.WaitForFunctionAsync(@
"() => new Promise(resolve => {
  ...
  resolve();
})")
...
await waitForo2ScrollToEndTask;
```
