### ISSUE TITLE
[Question]: How to use saved state.json file for next set of test cases

### ISSUE THREAD

**Issue by AmolPatil250792** [microsoft/playwright-dotnet#2490]
### Your question

I have saved state into state.json now i want to leverage that saved state for next test cases. How can i use that into playwright using dotnet.

**Comment by mxschmitt** [comment]
You can configure custom context options on file level but not yet on test level, would that work for you? https://playwright.dev/dotnet/docs/test-runners#customizing-browsercontext-options-1
