### ISSUE TITLE
[BUG] Desktop windows popping up since update to 1.31.0

### ISSUE THREAD

**Issue by martincostello** [microsoft/playwright-dotnet#2491]
**Context:**
- Playwright Version: 1.31.0
- Operating System: Windows
- .NET version: .NET 7
- Browser: Chrome

**Code Snippet**

Standard usage.

**Describe the bug**

Since updating to Playwright 1.31.0, I've noticed that when UI tests are run, Chrome terminal-looking windows pop up when tests are run where they didn't used to.

![image](https://user-images.githubusercontent.com/1439341/220887678-2bd26f5f-2fe9-4086-aba1-e2e5d2d02a96.png)

I would expect the previous headless behaviour to reduce noise/clutter on the desktop when running UI tests locally.

**Comment by mxschmitt** [comment]
This is a dupe of https://github.com/microsoft/playwright/issues/21093 and is already fixed in Node.js. Gets rolled out to .NET soonish.
