### ISSUE TITLE
[Question]: Hello, I use ConnectOverCDPAsync to open the browser. How do I open codegen for Test Generator

### ISSUE THREAD

**Issue by joinevans** [microsoft/playwright-dotnet#2495]
### Your question

Hello, I use ConnectOverCDPAsync to open the browser. How do I open codegen for Test Generator

```
 await using var browser = await playwright.Chromium.ConnectOverCDPAsync(url);
            var context = browser.Contexts[0];
            var page = context.Pages[0];
            //Open Codegen ?
```

**Comment by mxschmitt** [comment]
You can call [`await page.PauseAsync()`](https://playwright.dev/dotnet/docs/api/class-page#page-pause).

**Comment by joinevans** [comment]
> 您可以调用[`等待页面。暂停异步（）。`](https://playwright.dev/dotnet/docs/api/class-page#page-pause)

thank you very much

**Comment by joinevans** [comment]
> You can call [`await page.PauseAsync()`](https://playwright.dev/dotnet/docs/api/class-page#page-pause).

thank you very much
