### ISSUE TITLE
[BUG] Unable to read download stream into byte[]. 

### ISSUE THREAD

**Issue by NetworkGithub** [microsoft/playwright-dotnet#2504]
System info
Playwright Version: .NET 1.31.1
Operating System: Windows 11
Browser: All, Chromium
Other info:
Source code

```csharp
foreach (var item in await Page.GetByText("job_sheet").AllAsync())
{
var download = await Page.RunAndWaitForDownloadAsync(async () =>
{
  await item.Locator("xpath=..").GetByTitle("download").ClickAsync();
}, new PageRunAndWaitForDownloadOptions() { Timeout = 10000 });
var stream = await download. CreateReadStreamAsync();
var content = await new StreamReader(stream).ReadToEndAsync();
var content2 = new BinaryReader(stream).ReadBytes(65535);
var path = await download.PathAsync();
var fileFullPath = @$"C:\Users\SpencerThompson(Netw\Downloads\{download.SuggestedFilename}";
await download.SaveAsAsync(fileFullPath);
var bytes = Encoding.Latin1.GetBytes(content);
filePayload.Add(new FilePayload() { Name = $"FromStream5_{download.SuggestedFilename}", MimeType = "application/pdf", Buffer = bytes });
var fileBytes = File.ReadAllBytes(fileFullPath);
 filePayload.Add(new FilePayload() { Name = $"FromFile5_{download.SuggestedFilename}", MimeType = "application/pdf", Buffer = fileBytes });
}
```

Steps
If a pdf file is downloaded then it is only possible to save it to a disk. This application will run as a service so disk will not be relevant, and the only purpose of downloading the file is to upload it again also using Playwright.
The other option is to CreateReadStreamAsync(). This doesn't actually create a Readable Stream as reading the stream causes NotImplementedException. 
On another bug report https://github.com/microsoft/playwright-dotnet/issues/2106 it stated to await new StreamReader(stream).ReadToEndAsync(); This produces a string[], not a usable byte[]
Using a BinaryReader(Stream).Read(... instead of StreamReader gives NotImplementedException.

Expected
It is expected that it would be possible to be able to binary read the stream to get the bytes to put into a FilePayload which can be used to upload. Other than saving to disk there doesn't seem to be a way of doing that because the stream doesn't support read / binaryRead

Actual
ReadToEnd produces ASCII that is shorter than the saved file. In this case content.Length = 59408 but fileBytes = 62104.

**Comment by mxschmitt** [comment]
We unfortunately need to stay in the asynchronous world, which means like instead of Read() what your BinaryReader uses, we need to use ReadAsync.

I used the following which was working for me:

```csharp
    public async Task<byte[]> ReadAllBytes(Stream stream)
    {
        using (var ms = new MemoryStream())
        {
            await stream.CopyToAsync(ms);
            return ms.ToArray();
        }
    }
```

and then

```csharp
var stream = await download.CreateReadStreamAsync();
var bytes = await ReadAllBytes(stream);

```

**Comment by NetworkGithub** [comment]
Yes, that works.

Many thanks.
