### ISSUE TITLE
Playwright docker image with ubuntu jammy version.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright-dotnet#2515]
When will the jammy version of playwright dotnet be published? ref: https://playwright.dev/dotnet/docs/docker#base-images

**Comment by mxschmitt** [comment]
There was actually a bug which prevented publishing Jammy images, I fixed it. For the next release on you'll have versioned images, or for now you can stick with the next version:

```
docker pull mcr.microsoft.com/playwright/dotnet:next-focal
```

We'll update the docs shortly.

**Comment by quldude** [comment]
@mxschmitt is there a timeline on when the new version will be released?

**Comment by mxschmitt** [comment]
Beginning of next week I think.
