### ISSUE TITLE
[Question]: RouteAsync does not work with google.com

### ISSUE THREAD

**Issue by niwes** [microsoft/playwright-dotnet#2520]
### Your question

When I try to block images with routeAsync and go to google.com, in 9 out of 10 cases the site loads infinitely, all other sites block images successfully. When I go to google.com it doesn't even enter the lambda expression. But if I press shift + enter, the site successfully opens in a new window and blocks images, after that also works in the main window

```
var pw = await Playwright.CreateAsync();
var br = await pw.Chromium.ConnectOverCDPAsync(resp.ws_endpoint.ToString(), new BrowserTypeConnectOverCDPOptions());
                context = br.Contexts[0];
                await context.RouteAsync("**/*.{png,jpg,jpeg}", r =>
                {
                    r.AbortAsync();
                });
```

**Comment by mxschmitt** [comment]
Could you provide us a full script which we can run locally? The snippet above does not compile.
