### ISSUE TITLE
[Question]: "Save As" does not work

### ISSUE THREAD

**Issue by niwes** [microsoft/playwright-dotnet#2521]
### Your question

When I connect to the browser, the shortcut ctrl + s does not work. "Save as" also does not work, while everything else works, such as ctrl + p.
`var pw = await Playwright.CreateAsync();`
`var br = await pw.Chromium.ConnectOverCDPAsync(resp.ws_endpoint.ToString(), new BrowserTypeConnectOverCDPOptions());`
All I do is connect to the browser. The save window just does not appear

**Comment by mxschmitt** [comment]
This is unfortunately out of scope for Playwright. Playwright is for automating browsers and not for getting automated by users.
