### ISSUE TITLE
[BUG] Tracing.StopAsync() never completes when called from the BrowserContext Close event

### ISSUE THREAD

**Issue by Zero3** [microsoft/playwright-dotnet#2522]
**Context:**
- Playwright Version: 1.28
- Operating System: Windows
- .NET version: .NET 6
- Browser: Chromium

**Describe the bug**

The task returned by `Tracing.StopAsync()` seemingly never completes when the method is called from the `BrowserContext` `Close` event, causing the consuming application to freeze.

It seems to me like this should be a valid and useful thing to do. I was not able to find anything in the docs that says this is not supposed to work.

**Comment by Zero3** [comment]
Hi @mxschmitt

Thanks for your reply. That explains the behaviour I am seeing.

I see that you already closed this issue, but I would like to add the feedback that this is not very intuitive behaviour or discoverable information.

To improve Playwright for .NET I would like to suggest 2 improvements in relation to this:

1. Either change things so the operstion becomes valid OR throw an exception instead of not completing the task and leaving the consumer hanging.

2. Document the behaviour either way.

**Comment by mxschmitt** [comment]
This is fair! I'll keep it open to do 1)

**Comment by mxschmitt** [comment]
I tried the following which threw an exception that the context has been closed for me - what are you doing differently?

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
context.Close += async (_, _) =>
{
    try
    {
        Console.WriteLine("Context is closing");
        await context.Tracing.StopAsync();
        Console.WriteLine("Tracing stopped");
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
};
await context.CloseAsync();
await browser.CloseAsync();

```

**Comment by Zero3** [comment]
Aha. I see the issue now. When using a normal non-async event handler, the `Task` returned by `context.Tracing.StopAsync()` will never complete when waiting on it in the event handler. Probably because Playwright cannot process the trace stop request while still executing the close operation (which the event handler is part of here).

With an "async" event handler, however, like in your example, the Task will complete. This is because `context.Tracing.StopAsync()` doesn't actually complete while inside the event handler, as one would expect when seeing the code in your example, with the `await` on the call and everything. This is because there are actually no async event handlers in C#. The `async` keyword in your example just causes the event handler to complete as soon as an `await` is met, instead of actually awaiting. The trace stop request then executes after the close operation is done, in a background thread instead.

So to make a long story short: One cannot make calls like `Tracing.StopAsync()` on the context during its `Close` event. This makes somewhat sense, though I still wish this was documented, and that an exception was thrown instead of the application freezing.

**Comment by mxschmitt** [comment]
Our Async methods are not intended to be consumed in a non-async manner - since you then never know when they get executed. If I follow this rule, this looks intended or at least a possible side effect which we are unfortunately not able to address I feel like.

We can make it clear that when the Close event has fired, no further actions on the Context can be performed, but the hanging, seems a reasonable side effect of not awaiting.

**Comment by Zero3** [comment]
> Our Async methods are not intended to be consumed in a non-async manner - since you then never know when they get executed.

Could you elaborate on what you mean with "since you then never know when they get executed"?

---

Anyway, to backtrack back to my intention with calling `Tracing.StopAsync()` from the `Close` event, which caused me to run into this issue:

In my use case, the code disposing the browser context cannot/should not be responsible for for determining the path to the trace file, and thus cannot be the one calling `Tracing.StopAsync()`. It should not even know/care about whether tracing was started or not. Instead, I would like the code that creates the browser context to be responsible for this. One way to solve this issue could perhaps be the addition of an `OnClosing` event, or similar, where one can call `Tracing.StopAsync()` before it is too late.

**Comment by mxschmitt** [comment]
> Could you elaborate on what you mean with "since you then never know when they get executed"?

If you execute an async function without await, it can complete immediately but also 10 seconds later since it does not await.

> One way to solve this issue could perhaps be the addition of an OnClosing event, or similar, where one can call Tracing.StopAsync() before it is too late.

Playwright's event handlers are all synchronous, even if we introduce this event, it would never wait for the event handlers to be executed. We recommend putting Tracing.StopAsync in the place where you actually close the context.

Closing as per above.
