### ISSUE TITLE
[Question]:  Get the content of an HTML tag with a specific class ?

### ISSUE THREAD

**Issue by lkskfs1235** [microsoft/playwright-dotnet#2524]
### Your question

i use uncorrect code and can't output correct result.

`var content = page.Locator("intro");`
`var attri = content.GetAttributeAsync("href")`
`var text = content.InnerTextAsync();`
`WriteLine(text);`
`WriteLine(attri);`

this is html.
`<a class="intro" href="/page/google ">today is good </a>`

and  i have 3 questions:
1. how do i locate a element by specifying class?
2. how do i get   content   of attribute?
i want to get  url of  href-attribute like "www.google.com" form above html.
3. how do i get  text of element?
i want to get content of html like "today is good"  from above html.

What kind of code is correct?
Can someone correct my code?

**Comment by mxschmitt** [comment]
Closing as per above.
