### ISSUE TITLE
[BUG] PlaywrightPlatform seems broken

### ISSUE THREAD

**Issue by jgilbert2017** [microsoft/playwright-dotnet#2525]
Context:

Playwright Version: 1.31.1
Operating System: Windows 10

Setting PlaywrightPlatform to linux-arm64 gets linux-arm64,linux-x64 and win32_x64 node installations in the output dir.
Setting PlaywrightPlatform to linux-x64 gets linux-x64 and win32_x64 node installations in the output dir.

**Comment by mxschmitt** [comment]
I experienced similar behaviour. @campersau, do you mind taking a look?

**Comment by campersau** [comment]
For me it looks like that the platform folders don't get removed when you change the `PlaywrightPlatform` but they will be empty if you check their contents. You can also remove the `.playwright` folder and build again, then you should only get the expected folders.
Maybe we need some additional logic for the `clean` target to actually remove these folders.

**Comment by jgilbert2017** [comment]
@campersau i manually deleted the node folders and did a rebuild on my project and i hit the bug as described in the original report.

**Comment by campersau** [comment]
@jgilbert2017 Could you please run `dotnet build /bl` or `msbuild /bl` to build you project? This will create a [`msbuild.binlog`](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md) file which you can zip and upload here so I can take a look at it as I am unable to reproduce the issue on my side.

**Comment by jgilbert2017** [comment]
@campersau ok, i got a binlog and figured out the problem (btw binlog->wow!).

My target *.exe project has a dependecy on a *.dll library project that uses playwright but does not have `PlaywrightPlatform` defined.  I was only setting the property in the exe project.  This causes `PlaywrightPlatform` to use the default value.

After including `<PlaywrightPlatform>none</PlaywrightPlatform>` in my dll project things work mostly as expected.

However, this does seem to be an issue that `linux-arm64` causes both linux-arm64 and linux-x86 node binaries to be copied to the output dir.

**Comment by campersau** [comment]
@jgilbert2017 Great you figured it out!

---

> However, there does seem to be an issue that linux-arm64 causes both linux-arm64 and linux-x86 node binaries to be copied to the output dir.

Yes, that is currently expected.
https://github.com/microsoft/playwright-dotnet/blob/eb9a43bd66842799711f725d166036f2358c9950/src/Playwright/build/Microsoft.Playwright.targets#L16
For backward compatibility this also checks for `$(PlaywrightPlatform.Contains('linux'))` which is true for `linux-x86` as well as `linux-arm64` which is why you get both...

Maybe we can split the `PlaywrightPlatform` value first by `;` and check then with contains.

**Comment by jgilbert2017** [comment]
yes, i think splitting is a good idea.
