### ISSUE TITLE
[BUG] Upkeep of code tree - src/Playwright.Tests.TestServer/assets/

### ISSUE THREAD

**Issue by maw136** [microsoft/playwright-dotnet#2534]
**Summary**
Given the path `src/Playwright.Tests.TestServer/assets/` is maintained by `build.sh` script by first removing and then copying the entiriety of it form the upstream Playwright repo that must be checkout somewhere on devs machine,
I made a PR that adds appropriate entry to `.gitignore`

**Comment by maw136** [comment]
The PR: https://github.com/microsoft/playwright-dotnet/pull/2533

**Comment by mxschmitt** [comment]
We experimented with this in the past and found that this is counterintuitive for us, since it requires us on the CI and locally to always have two repros checked out.

Closing by that.
