### ISSUE TITLE
[Feature] Playwright image for .NET 7.0

### ISSUE THREAD

**Issue by polymerase** [microsoft/playwright-dotnet#2544]
Title says it all, any plans to release a .net 7.0 image?

Love the framework!

**Comment by mxschmitt** [comment]
Playwright Docker image will use the latest .NET LTS version, which is is as of today 6.0 see [here](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). If you want to have a different version, we recommend using ours as a base image and then installing your preferred version on top of it. Alternatively you can create your own, see [here](https://github.com/microsoft/playwright-dotnet/blob/main/utils/docker/Dockerfile.jammy).

**Comment by gaelj** [comment]
@mxschmitt once again, this is not acceptable. Microsoft tooling MUST support the latest Microsoft frameworks. Doing differently is a BIG red flag on your and Microsoft's behalf.

**Comment by mxschmitt** [comment]
Just to be clear, we support the latest .NET version framework wise. You can install net7 easily on top of our image see here: https://github.com/microsoft/playwright-dotnet/issues/2553#issuecomment-1511099995 to use it inside your tests.
