### ISSUE TITLE
[Feature] IAPIResponse.JsonAsync should support JsonSerializerOptions

### ISSUE THREAD

**Issue by heavenwing** [microsoft/playwright-dotnet#2550]
In [this code]( https://github.com/microsoft/playwright-dotnet/blob/a1713bb4d3274024ee98175b18bd54d37ddf213a/src/Playwright/Core/APIResponse.cs#L79)
If response body use camel case convention, but my .NET DTO class use pascal case , my dto's properties will be empty or null.

**Comment by Exoow** [comment]
Isn't this being fixed by #2818 ?
