### ISSUE TITLE
[Question]: Any plan to move up on NET7 and soon NET8?

### ISSUE THREAD

**Issue by UtopleMan** [microsoft/playwright-dotnet#2553]
### Your question

We are currently stuck on NET6 because of our dependency to Playwright. I was wondering if you guys are planning to move up on NET7 and eventually NET8?

**Comment by mxschmitt** [comment]
Once a new LTS version gets released, we'll switch to it. For now we recommend installing you preferred .NET version on-top of our base Docker image: https://playwright.dev/docs/docker

You can do this with a single line by using the dotnet-install.sh: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

```bash
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --version 7.0.0
```

**Comment by BC89** [comment]
Hello. Hope all is well. Now that .Net8 is officially LTS, when should we expect to see a maintained container?

**Comment by mxschmitt** [comment]
> Hello. Hope all is well. Now that .Net8 is officially LTS, when should we expect to see a maintained container?  

In the next version 1.40
