### ISSUE TITLE
chore: update nuget dependencies in .Tests and ..TestingHarnessTest

### ISSUE THREAD

**Issue by maw136** [microsoft/playwright-dotnet#2557]
Chore, update nugets in Tests and TestHarness.
Should have no impact on main dependencies of generated nugets.

fix: https://github.com/microsoft/playwright-dotnet/pull/2556
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/playwright-dotnet/issues/2592
- [ ] https://github.com/microsoft/playwright-dotnet/issues/2590
```

**Comment by maw136** [comment]
Added small changes necessitated by failing tests after nuget update.

**Comment by maw136** [comment]
Extracted code changes to separate PRs

**Comment by mxschmitt** [comment]
Closing for now since we upgrade packages as we have to instead of regularly in chunks.
