### ISSUE TITLE
[BUG] GetAttributeAsync("X") on element without attribute "X"

### ISSUE THREAD

**Issue by verdickta** [microsoft/playwright-dotnet#2566]
**Context:**
Im on playwright version 1.32.0
Im using macOS Ventura 13.2.1
The .NET version Im using is 7.0.203
Using Chrome

**Code Snippet**
```cs
using Microsoft.Playwright;
using PlaywrightTests;

class Model
{
    public async Task Main(string id)
    {
        _tabs = Page.GetByTestId($"{id}");
        var elementHandle = await _tabs.ElementHandleAsync();
        _tabList = (await elementHandle.QuerySelectorAllAsync("a[href][role='tab']")).ToArray();
    }

    public async Task Second()
    {
        if (_tabList != null)
        {
            foreach (var tab in _tabList)
            {
                var test = await tab.GetAttributeAsync("tabindex");
        }
    }
}
```

**Describe the bug**
Hello
Im very new to dotnet, c# and playwright so Im learning a lot of new stuff and I might be making a mistake but I got a problem with the GetAttributeAsync method.

So im using a QuerySelector to get an Array of all the tab elements. I loop over the array and on every tab I want to run the GetAttributeAsync method to check the value of tabindex. Sometimes this will be 0, this can be -1 but sometimes there is no attribute tabindex. So Im expecting the GetAttributeAsync method to return null in that case.

When Im running this code and the attribute exists everything is fine and it displays the value, but when the attribute does not exist the code seems to crash on the "var test = await tab.GetAttributeAsync("tabindex");" line.

The error Im getting is as followed:
"System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
Result message:
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary."

I looked into it but the fixes I found didnt really apply for me. 
Could this be a bug or am I doing something horribly wrong? 

Thanks in advance :)

**Comment by mxschmitt** [comment]
Hey!

Thanks for filing this issue, this is a bug on our side and gets fixed in the next release.

We strongly recommend using Locators instead of ElementHandles, see [here](https://playwright.dev/dotnet/docs/handles#locator-vs-elementhandle). They are much more reliable and are compatible with our [web-first assertions](https://playwright.dev/dotnet/docs/test-assertions).
