### ISSUE TITLE
Microsoft.Playwright.dll Isn't Digitally Signed

### ISSUE THREAD

**Issue by arpavan** [microsoft/playwright-dotnet#2569]
**Context**
- Playwright Version: [1.22.0](https://www.nuget.org/packages/Microsoft.Playwright/1.22.0)
- Operating System: Windows, Linux, OSX
- .NET version: .NET 6.0
- Browser: Not Applicable

**Code Snippet**
Not Applicable

**Description**
It appears in any of the stable released versions of the Playwright-dotnet library, the artifacts are not digitally signed. Specifically the Microsoft.Playwright.dll artifact included in the NuGet package. Versions  [1.32.0](https://www.nuget.org/packages/Microsoft.Playwright/1.32.0) (current latest),  [1.22.0](https://www.nuget.org/packages/Microsoft.Playwright/1.22.0) (the one we use) and [1.12.0](https://www.nuget.org/packages/Microsoft.Playwright/1.12.0) (the first stable) were examined and it has been observed that the signing is absent in all of these versions. Please see screenshot below - 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/1485950/235754911-81879108-0294-4b4d-90af-53c9a22addb8.png">

Below is a screenshot of the properties page of a signed binary from a different library - 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1485950/235755131-7ec27511-0a80-4173-afce-7954aff3fd2d.png">

The expectation is that the Microsoft.Playwright.dll binary itself should be digitally signed in addition to the NuGet package (which is already signed). Due to the missing digital signature for Microsoft.Playwright.dll we're unable to consume this version in our application project as this is impacting our release process where certain checks in the pipeline that require binaries to be signed are failing.

**Comment by mxschmitt** [comment]
I published version 1.33.0-beta-1 which has now a digital signature. Could you verify if this works for you? Then I'll merge it into the normal main branch.

![image](https://user-images.githubusercontent.com/17984549/236279766-09f9e4bf-5e7a-4d46-940a-e05055a674dd.png)
