### ISSUE TITLE
[Feature] Improve Playwright.CLI to allow to specify directory of Microsoft.Playwright.dll

### ISSUE THREAD

**Issue by coenm** [microsoft/playwright-dotnet#2584]
I'm using the dotnet tool `Microsoft.Playwright.CLI` to install Playwright in my azure devops build agent like this:

```
dotnet tool install --global Microsoft.Playwright.CLI
playwright install
```

This executes the following [program](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright.CLI/Program.cs) which only runs when `*.csproj` or `*.sln` files exist.

My pipeline setup however first builds all applications, libraries and test projects and makes artifacts of relevant output.
Then, in an other step, it downloads the artifacts and tries to execute E2E tests by directly referencing the test dlls. 

The problem is that I don't have the original `.csproj` files in the artifact and therefore have some trouble with installing Playwright.

My proposed solution is to add an new argument (or extend the `-p` argument) in the [program](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright.CLI/Program.cs) to allow to specify the location of the `Microsoft.Playwright.dll` directly.

At this moment, my workaround is

```
dotnet new nunit -n PlaywrightTests
cd PlaywrightTests
dotnet add package Microsoft.Playwright.NUnit
dotnet build

dotnet tool install --global Microsoft.Playwright.CLI
playwright install
```

**Comment by mxschmitt** [comment]
Playwright CLI is the deprecated way of interacting with the CLI. We recommend running the PowerShell file instead: `pwsh bin/Debug/netX/playwright.ps1 install`. Would that work for you?

**Comment by coenm** [comment]
Okay, thanks for your response. 

Just curious, what is the benefit of using the powershell script instead of just calling  `bin/Debug/netx/Microsoft.Playwright.dll install`?

**Comment by mxschmitt** [comment]
This is the same in the end, the PowerShell script is just a bit more convenient, I think on Windows we were required to have this pwsh wrapper if I remember correctly.
