### ISSUE TITLE
[BUG] IsEnabledAsync() return Null value for Playwright's .NET library

### ISSUE THREAD

**Issue by padhibibaswan** [microsoft/playwright-dotnet#2585]
**Context:**
- Playwright Version: 1.33.0
- Operating System: Windows
- .NET version: 7
- Browser: Chromium 

**Code Snippet**

// The below code : doesnot work . The execution reaches to Exception block for the IsEnabledAsync method
Boolean enabled = await page.GetByRole(AriaRole.Button).IsEnabledAsync();
// However Boolean isVisible = page.GetByRole(AriaRole.Button).IsVisibleAsync(); thsi works perfectly fine and return True or False .
 

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
        var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
       Boolean enabled = await page.GetByRole(AriaRole.Button).IsEnabledAsync();  // Fails and reaches the Exception block
       Boolean isVisible = page.GetByRole(AriaRole.Button).IsVisibleAsync(); / This works perfectly fine

    }
}
```

**Describe the bug**

As stated in the documentation : https://playwright.dev/dotnet/docs/api/class-locator#locator-is-enabled , This method does not return Bool value , and it waits for the default timeut and if does not succeed , it reaches Exception block .
My question is How I can check if an element is enabled or disabled and based on that perform some action in my Test .

**Comment by feiyun0112** [comment]
IsEnabledAsync and IsVisibleAsync are implemented differently, IsEnabledAsync base on  Locator can be accessible

you can avoid errors by checking for the existence of DOM element first

```
var button = await page.GetByRole(AriaRole.Button).ElementHandlesAsync( );
if (button!=null && button.Any())
{
    Boolean enabled = await button.First().IsEnabledAsync();  // Fails and reaches the Exception block
    Console.WriteLine(enabled);
}
```

**Comment by mxschmitt** [comment]
Looks reasonable that IsEnabled throws when the element is not there.

```csharp
// Can be used to wait for the element to appear on the page
await page.GetByRole(AriaRole.Button).WaitForAsync();
// Then IsEnabledAsync won't throw
var enabled = await page.GetByRole(AriaRole.Button).IsEnabledAsync()
```

What we recommend instead tho are our web-first assertions which automatically retry: https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-enabled

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
