### ISSUE TITLE
chore: small refinements string constants extraction and use more readable String.Equals implementation

### ISSUE THREAD

**Issue by maw136** [microsoft/playwright-dotnet#2595]
chore: string constants extraction and use more readable String.Equals implementation)

- extracted some strings to constants on top of classes and methods
- use more readable Equals with regard to comparing constant strings with input

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright-dotnet/pull/2594#issuecomment-1570616282.
