### ISSUE TITLE
[Feature] External cancellation of `...WaitFor...` methods where feasible

### ISSUE THREAD

**Issue by maw136** [microsoft/playwright-dotnet#2596]
Add external cancellation of `...WaitFor...` methods where feasible.

Reasoning:
Wait for style methods have a timeout, but there are circumstances where external events could be the cause to cancel specific waits.
The current solution doesn't provide any cancellation except default/custom timouts.

**Comment by mxschmitt** [comment]
Thanks for the feature request, unfortunately this is not compatible with the way Playwright, the driver and calls to the browser are working. If you sent once something to the browser, it can't be canceled. Since we don't plan on implementing this, I will close it for now.

**Comment by pavelfeldman** [comment]
Could you provide a complete example where you benefit from the cancellation token? I'd like to understand the use case better.
