### ISSUE TITLE
[BUG]pwsh bin/Debug/net7.0/playwright.ps1 install

### ISSUE THREAD

**Issue by azbo** [microsoft/playwright-dotnet#2599]
**Context:**
- Playwright Version: [1.34.0]
- Operating System: [Linux]
- .NET version: [.NET 7]
- Browser: [All]
- 
/var/datedu/net/web2pdf/playwright_unit/PlaywrightTests/bin/Debug/net7.0/.playwright/node/linux-x64/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /var/datedu/net/web2pdf/playwright_unit/PlaywrightTests/bin/Debug/net7.0/.playwright/node/linux-x64/node)

**Comment by mxschmitt** [comment]
Which Linux distribution are you using? Only Ubuntu 20/22, Debian 11 are supported.

**Comment by mxschmitt** [comment]
Closing since you are most likely not using an official supported linux distribution. See here for the system requirements: https://playwright.dev/dotnet/docs/intro#system-requirements
