### ISSUE TITLE
[Feature] Set Default global LocatorAssertions in .NET.

### ISSUE THREAD

**Issue by MWRAUTO** [microsoft/playwright-dotnet#2603]
Hello! as we spoke in this issue: https://github.com/microsoft/playwright/issues/23471

I would like to request for a posibility to set expect global timeout while we're setting up browser context, same as we have default timeout & default navigation timeout in screenshot below.

![image](https://github.com/microsoft/playwright-dotnet/assets/128363781/63dc0c16-ecc8-4062-ab6f-53582140313c)

![image](https://github.com/microsoft/playwright-dotnet/assets/128363781/480e4332-c6f4-436a-a6f0-f07e82ddba78)

**Comment by Materix** [comment]
As workaround I use:
```
        typeof(Playwright).Assembly.GetType("Microsoft.Playwright.Core.AssertionsBase")!
            .GetMethod("SetDefaultTimeout", BindingFlags.Static | BindingFlags.NonPublic)!
            .Invoke(null, new object[] { _defaultTimeout });
```

in any static ctor which are always loaded

**Comment by SephVin** [comment]
Thanks for workaround! I really don't understand why we can't set default timeout for Assertions without using runsettings. This  file works only in VS

**Comment by Melkor972** [comment]
Totally on the same page. Unless the workaround above is applied, Playwright makes pretty much obliges users to use runsettings file while configuration from code/custom config sources might be preferable to someone

**Comment by mxschmitt** [comment]
Folding into #2259
