### ISSUE TITLE
[BUG] Locator.Filter has extra properties

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-dotnet#2606]
I think we have a bug in the code generator. The [LocatorFilterOptions](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/API/Generated/Options/LocatorFilterOptions.cs) has 3 properties: `HasText`, `HasTextString` and `HasTextRegex` to represent `hasText?: string | RegExp,`.  I think we don't need `HasText`. And if this is expected it's [confusing for some users](https://stackoverflow.com/questions/76411920/difference-between-the-filter-options-in-playwright).

**Comment by mxschmitt** [comment]
Hi Dario!

This is actually expected and was introduces in https://github.com/microsoft/playwright-dotnet/pull/2387.

**Comment by kblok** [comment]
Maybe we could say that in the doc?

**Comment by mxschmitt** [comment]
Hard to find a place for it!

**Comment by EgoPingvina** [comment]
So what is the difference between them?

**Comment by mxschmitt** [comment]
There is no difference, they are the same and there for connivence.
