### ISSUE TITLE
[Question]: Clear working example for setting up an Azure Pipeline for Playwright E2E Tests

### ISSUE THREAD

**Issue by bluntspoon** [microsoft/playwright-dotnet#2609]
### Your question

I'm in the process of configuring our CICD Pipeline in Azure Devops to build and run our Playwright Tests. I attempted the approach using the jammy container running on a self-hosted ubuntu vm, but seemed to keep hit issues, first permissions and then tests ended up just hanging. 

Looking for clean simple example to follow, is there anything available?

**Comment by mxschmitt** [comment]
We reworked the examples for CI for the next release. Let me know if it helps: https://playwright.dev/dotnet/docs/next/ci

(Added full azure pipelines examples)

**Comment by mxschmitt** [comment]
Of course! And if you spot bugs, feel free to create a PR here: https://github.com/microsoft/playwright/blob/main/docs/src/ci.md

**Comment by bluntspoon** [comment]
Quick update: I got the non-containerised flow working. Thanks for the help. 👍🏻
_NB: I'll feedback on containerised and suggestions soon._

**Comment by mxschmitt** [comment]
I'll close this issue for now since there are no action items from our side. Thanks for testing the new CI/CD docs and feel free to follow up with some fixes, thanks!
