### ISSUE TITLE
[Question]: Should we support `RegexOptions.Compiled`?

### ISSUE THREAD

**Issue by jjshao-ms** [microsoft/playwright-dotnet#2615]
### Your question

I use `context.RouteAsync(RouteFilterRegex, route => {...})` API, and I create `RouteFilterRegex` with option `RegexOptions.Compiled` in order to have better performance. But looks like, the following code https://github.com/microsoft/playwright-dotnet/blob/ca7b02ac910e573666f48d502bfabb1c17639e68/src/Playwright/Helpers/RegexOptionsExtensions.cs#L35-L55 refuse to accept compiled regex.
To me, I would expect that we can set a compiled regex in `RouteAsync`, could you show me why you do not support that, or maybe fix it?

And this is actually a **regression**, at least I could do this in 1.24.0.

**Comment by kblok** [comment]
The regex is being passed to the playwright driver (node.js app). So it doesn't make much sense to pass that .NET flag to the driver.

**Comment by jjshao-ms** [comment]
> The regex is being passed to the playwright driver (node.js app). So it doesn't make much sense to pass that .NET flag to the driver.

I agree we should not pass that flag to the driver, but could we allow that flag by ignore it when transfer (to me, I don't think compile flag will change the regex behavior, so I think ignore is acceptable?) More specifically, can we just change this line: `if ((options & ~(RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Multiline)) != 0) ` ?

**Comment by mxschmitt** [comment]
Allowing this option sounds good to me. If someone wants to create a PR with a fix for it (and potentially test), I'm happy to review it. Thanks!
