### ISSUE TITLE
[Question]: is the .NET implementation of Playwright limited in terms of features?

### ISSUE THREAD

**Issue by KikoUK** [microsoft/playwright-dotnet#2633]
### Your question

Hello, we are looking to migrating our tests to Playwright from Selenium and currently evaluating whether to move forward with the Node.js or .NET implementation. 

We would prefer to use .NET as our product and knowledge is .NET based; however, Node.js (TypeScript) implementation seem to have many more features, for example, the whole Playwright Test section is missing in the .NET versions of the docs. For instance, in our case, Annotations, Fixtures, Global Setup, Parallelism and so fort are very important, but missing from the .NET docs. Are the related Playwright Test missing in the docs only or is it a case where some features are only available in Node.js (Typescript) since PW is mainly a Node.js tool? 

Similar story with the API section of PW docs.

Also, seems like the .NET implementation relies on third party frameworks such as NUnit for it to work, whereas Node.js works "out of the box". Is that correct?

**Comment by mxschmitt** [comment]
Closing as per above then.
