### ISSUE TITLE
[Question]:  how to select svg ? like document.querySelectorAll('svg')

### ISSUE THREAD

**Issue by billpeace** [microsoft/playwright-dotnet#2651]
how to select svg ? like document.querySelectorAll('svg')

var item = await page.WaitForSelectorAsync("svg");  // item is null  how to ?
                        await item.ScreenshotAsync(new ElementHandleScreenshotOptions()
                        {
                            Path = "document.png",
                            OmitBackground = true
                        });

 how to select svg ? like document.querySelectorAll('svg')

thanks

[mml-svg.zip](https://github.com/microsoft/playwright-dotnet/files/12192665/mml-svg.zip)

**Comment by mxschmitt** [comment]
Never use WaitForSelector, always use Locators. See e.g. this which works for me:

```cs
using Microsoft.Playwright;

var playwright = await Playwright.CreateAsync();
var browser = await playwright.Chromium.LaunchAsync();
var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();

var path = "/Users/maxschmitt/Downloads/mml-svg.html";
await page.GotoAsync(new Uri(path).AbsoluteUri);
var element = page.Locator("svg");
await element.ScreenshotAsync(new() { Path = "screenshot.png" });
```
