### ISSUE TITLE
[BUG] ReferenceError: user is not defined at eval

### ISSUE THREAD

**Issue by arpitjainms** [microsoft/playwright-dotnet#2652]
### System info
- Playwright Version: [v1.23]
- Operating System: Windows 10
- Browser: Chromium

### Source code

getting following error intermittently from playwright dotnet
```Caller = <GetHtmlAttributeAsync>d__86.MoveNext, L0, Details = Microsoft.Playwright.PlaywrightException: ReferenceError: user is not defined at eval (eval at evaluate (:178:30), <anonymous>:1:15) at UtilityScript.evaluate (<anonymous>:185:19) at UtilityScript.<anonymous> (<anonymous>:1:44) at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 167 at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 489 at Microsoft.Playwright.Core.Frame.EvalOnSelectorAsync[T](String selector, String expression, Object arg, FrameEvalOnSelectorOptions options) in /_/src/Playwright/Core/Frame.cs:line 523 at Turanga.SessionManager.Providers.PlaywrightElement.GetHtmlAttributeAsync(String attribute)```

Although, the xpath and attribute exists on the page
![image](https://github.com/microsoft/playwright-dotnet/assets/125344449/4be4862a-d560-42fa-8a7c-d3976639304e)

Code where error is being thrown
Frame.cs line:523
```
522        public async Task<T> EvalOnSelectorAsync<T>(string selector, string expression, object arg = null, FrameEvalOnSelectorOptions options = null)
523            => ScriptsHelper.ParseEvaluateResult<T>(await _channel.EvalOnSelectorAsync(
524                selector: selector,
525                expression,
526                arg: ScriptsHelper.SerializedArgument(arg),
527                strict: options?.Strict).ConfigureAwait(false));
```

Calling code
```
var elementLocator= /* get locator for xpath = "//*[@id='testHook']"      */
var jsonElement = await elementLocator.EvaluateAsync($"el => el.{attribute}");  /*  where attribute = "data-user"   */ 
```

Can you please help me understand when is this error thrown?

**Comment by mxschmitt** [comment]
Can you share a reproducible? Most likely the website you are testing overrides some globals which end up in that error constellation.

**Comment by arpitjainms** [comment]
Sure, we are upgrading the playwright version at our end. Will get back if the issue persists.

**Comment by mxschmitt** [comment]
Closing for now then, please re-file if you still experience issues.
