### ISSUE TITLE
[BUG] Instability after migrating from WaitForNavigation to WaitForUrl

### ISSUE THREAD

**Issue by mathiasi** [microsoft/playwright-dotnet#2654]
### System info
- Playwright Version: 1.35.0
- Operating System: All
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Test file (self-contained) (partial)**

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
await using var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();

await page.ClickAsync(".btn-primary");
await page.WaitForURLAsync($"https://my.website.com/*");
```

**Steps**
- [Run the test]

**Expected**

That the url is correctly awaited.

**Actual**
We see various TimeoutExceptions with different events being fired but this one I found peculiar since it actually lists the Load event as being fired and the URL seems to match exactly.
```
System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://my.website.com/*" until "Load"
navigated to "https://my.website.com/"
"NetworkIdle" event fired
"DOMContentLoaded" event fired
"Load" event fired
```

**Comment by mxschmitt** [comment]
We need a working reproducible in order to act on this. Are you able to supply us a full reproduction?

**Comment by mathiasi** [comment]
I'm afraid it is for an internal system - isn't there any logs I can provide that might help?

**Comment by mxschmitt** [comment]
Unfortunately we need a repro, but looking at your logs I can already see that you use:

`glob: https://my.website.com/*`

and navigate to a URL which is:

`https://my.website.com/`

this means like glob wise it does not match. You need to change your glob to `https://my.website.com*` or `https://my.website.com/**` so it matches.

**Comment by mathiasi** [comment]
Thanks that is actually very useful input! I was not aware of the differences. Not sure why it isn't consistent but I will try it out! :)

**Comment by mxschmitt** [comment]
Cool, closing for now then, please re-file if you still experience issues.
