### ISSUE TITLE
[BUG] null values in body are not serialised into json

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-dotnet#2657]
### System info
- Playwright Version: [v1.36.0]
-  .NET 7.0
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]

I am trying to send a post request with the following body 

`{
    "projectId": null,
    "companyCode": null
}`

In my code I am doing the following:

```
data.Add("projectId", null!);
data.Add("companyCode", null!);
```

```
_context.Response!.Value = await _context.Page!.APIRequest.PostAsync($"{TestContext.Parameters["BaseUrlApi"]!}{url}", new APIRequestContextOptions()
                    {
                        Headers = Header(headerType),
                        DataObject = data
                    });
```

Unfortunatelly those above are not sent as null, and are excluded from the request.

When trying to pass a class object as the request to be sent in Playwright, nulls are excluded from the request.

**Comment by mxschmitt** [comment]
I tried the following which was working for me, what do you do differently?

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();

var myDict = new Dictionary<string, string?>();
myDict.Add("foo", null);

var response = await page.APIRequest.PostAsync("https://httpbin.org/post", new () {
    DataObject = myDict,
});
Console.WriteLine(await response.TextAsync());

```

Make sure to use v1.36, since we had some related fixes in previous versions if I remember correctly.

**Comment by NikkTod** [comment]
Thanks for the quick help @mxschmitt, you are totally right, there was a bug in our application, which kind of mislead me. 
I checked the trace viewer and saw the expected response body, closing the ticket.

![image](https://github.com/microsoft/playwright-dotnet/assets/94455079/be33b404-4867-4798-847b-f9536e67aa88)
