### ISSUE TITLE
[BUG] playwright 1.36 gpu memory leak

### ISSUE THREAD

**Issue by bba2022** [microsoft/playwright-dotnet#2661]
### System info
- Playwright Version: [v1.36]
- Operating System: [Windows 10]
- Browser: [Chromium,]
- Other info: cdp connect chrome

### Source code
BrowserTypeLaunchPersistentContextOptions persistentContextOptions = new BrowserTypeLaunchPersistentContextOptions();
                persistentContextOptions.Locale = "zh-CN";
                persistentContextOptions.Headless = false;
                persistentContextOptions.IsMobile = true;
                    persistentContextOptions.UserAgent = BVariable.UserAgent_Mobile;
                    persistentContextOptions.ViewportSize = new ViewportSize() { Width = 375, Height = 812 };
                    persistentContextOptions.BypassCSP = true;
                persistentContextOptions.ExecutablePath = BVariable.chrome_path;
                websiteUser.userAgent = persistentContextOptions.UserAgent;
                persistentContextOptions.IgnoreDefaultArgs = new string[] {"--no-sandbox", "--enable-automation", "--no-default-browser-check", "--disable-gpu", "--disable-gpu-compositing", "--disable-gpu-vsync", "--disable-background-timer-throttling", "--disable-renderer-backgrounding", "--disable-breakpad", "--disable-features", "--disable-accelerated-2d-canvas", "--disable-dev-shm-usage", "--no-zygote", "--disable-gpu-rasterization", "--ignore-urlfetcher-cert-requests", "--ignore-certificate-errors", "--disable-web-security" };
                persistentContextOptions.Args = new[] { "--disable-gpu", "--disable-gpu-compositing", "--disable-gpu-vsync", "--disable-background-timer-throttling", "--disable-renderer-backgrounding", "--disable-breakpad", "--disable-features", "--disable-accelerated-2d-canvas", "--disable-dev-shm-usage", "--no-zygote", "--disable-gpu-rasterization", "--ignore-urlfetcher-cert-requests", "--ignore-certificate-errors", "--disable-web-security" };
                string rootPath = "D:\\playwright-caches\\"+ websiteUser.websitetype;

                string serviceWorkerPath = rootPath +@"\Default\Service Worker";
                if (Directory.Exists(serviceWorkerPath)) {
                    Directory.Delete(serviceWorkerPath, true);
                }
                IBrowserContext context = await playwright.Chromium.LaunchPersistentContextAsync(rootPath, persistentContextOptions);
                var guidProperty = context.GetType().GetProperty("Guid", BindingFlags.Instance | BindingFlags.NonPublic);
                var pageGuid = (string)guidProperty.GetValue(context);
                contextD = new ContextD(context, persistentContextOptions.UserAgent, true, websiteUser.websitetype, pageGuid);
                ContextDictionary[websiteUser.websitetype] = contextD;
                await new PlaywrightFilter(websiteUser.userAgent, websiteUser).filterAsync(context);
 var page = await contextd.context.NewPageAsync();
                    await page.AddInitScriptAsync(js);
                    var client = await contextd.context.NewCDPSessionAsync(page);
                     await setEmulation(client, websiteUser.userAgent);
                    await page.GotoAsync(website);
public  async Task filterAsync(IBrowserContext context) {
            context.Page += async (sender, e) =>
            {
                try
                {
                    var client = await context.NewCDPSessionAsync(e);
                   await PlaywrightUtils.setEmulation(client, userAgent);
                    string js = @"Object.defineProperty(window, 'navigator', {
                                       value: new Proxy(navigator, {
                                       has: (target, key) => (key === 'webdriver' ? false : key in target),
                                       get: (target, key) =>
                                           key === 'webdriver'
                                           ? undefined
                                           : typeof target[key] === 'function'
                                           ? target[key].bind(target)
                                           : target[key]
                                       })
                                   });";
                    if (websiteUser.userAgent.Contains("Android"))
                    {
                        js = BVariable.mobilewebdriver_js;
                    }
                    else
                    {
                        //js = BVariable.pcdriver_js;
                    }
                    await e.AddInitScriptAsync(js);
                }
                catch (Exception ee) { 
                
                }
            };
            context.Request += async (_, request) =>
            {
                string url = request.Url;
                Uri uri = new Uri(url);
                try
                {
                    if (1==1)
                            {
                                websiteUser.headers = new Dictionary<string, string>( request.Headers);

                                if (websiteUser.headers.ContainsKey("cookie"))
                                {
                                    string rootHost = UTILS.Utils.getRootHost(uri.Host);
                                    websiteUser.host = uri.Host;
                                    websiteUser.schme = uri.Scheme;
                                    websiteUser.port = uri.Port;
                                    websiteUser.origin = rootHost;
                                    websiteUser.cookies = websiteUser.headers["cookie"];
                                    websiteUser.updateTime = nowTime + jiange;
                                }
                            }

                }
                catch (Exception ee)
                {

                }
            };
            context.Response += async (_, response) =>
            {
                try
                {
                    string url = response.Url;
                    
                }
                catch (Exception ee) { 
                
                }
            };
            context.Close += async (_, e) =>
            {
                try
                {
                    var guidProperty = e.GetType().GetProperty("Guid", BindingFlags.Instance | BindingFlags.NonPublic);
                    var pageGuid = (string)guidProperty.GetValue(e);
                    //Console.WriteLine(pageGuid);
                    ContextD resultCtx = PlaywrightUtils.ContextDictionary.Values.FirstOrDefault(x => x.guid == pageGuid);

                    if (resultCtx != null && PlaywrightUtils.ContextDictionary.ContainsKey(resultCtx.type))
                    {
                        PlaywrightUtils.ContextDictionary.Remove(resultCtx.type);
                    }
                }
                catch (Exception ee) { 
                
                }

            };

[Describe actual behavior]
![11111](https://github.com/microsoft/playwright-dotnet/assets/89675020/7cc46f7e-e60d-4556-9d6e-f82ffd2ac6eb)

**Comment by mxschmitt** [comment]
We need a clear repro to be able to act on it. This seems very convoluted and just a few code snippets rather than a project we can clone and run. Please re-file with clear repro steps and a repository we can clone.

**Comment by bba2022** [comment]
The request and response events caused a memory leak, and the memory leak scenario will reappear 30 minutes after opening the browser

**Comment by mxschmitt** [comment]
This is expected, we recommended recreating the context after each test, this flushes the memory.

https://github.com/microsoft/playwright/issues/6319
