### ISSUE TITLE
[BUG] Exception When Making A Request With A Multi-Part Form File

### ISSUE THREAD

**Issue by Xen0byte** [microsoft/playwright-dotnet#2662]
### System Info
- Playwright Version: 1.36.0
- Operating System: Windows 11
- Browser: N/A
- Other Info: The code is fairly specific, but the easy repro is to just fire a POST multi-part form request with a file against (I suspect) any endpoint that supports that. In fact, the endpoint probably doesn't even matter, because this exception occurs before even making the request.

### Source code

```cs
  using SixLabors.ImageSharp;

  public async Task GenerateImageAsync(string format, int width, int height)
  {
      Image<Rgba32> image = new(width, height);

      byte GetRandomByte() => Convert.ToByte(Random.Shared.Next(Convert.ToInt32(byte.MaxValue).IncrementBy(1)));

      for (int x = 0; x < width; x++)
          for (int y = 0; y < height; y++)
              image[x, y] = new Rgba32(GetRandomByte(), GetRandomByte(), GetRandomByte(), GetRandomByte());

      string name = $"IMAGE.TEMP.{format.ToUpper()}";

      Models.API.Media.Image data = new()
      {
          Name = name,
          Format = format.ToUpper(),
          ParentID = Guid.Parse(ScenarioContext.Get<string>("Media Folder GUID")),
          Properties = new[] { new ImageProperties() { Alias = "description", Value = $"Programmatically Generated @ {DateTime.UtcNow.ToString("O")}" } }
      };

      switch (format.ToUpper())
      {
          case "GIF":  await image.SaveAsGifAsync(name);  break;
          case "JPEG": await image.SaveAsJpegAsync(name); break;
          case "PNG":  await image.SaveAsPngAsync(name);  break;

          default: Assert.Fail($@"Unsupported Image Format ""{format}""; Supported Formats Are: GIF, JPEG, PNG"); break;
      };

      IFormData form = HTTPCallContext.CreateFormData();

      form.Set("file", new FilePayload() { Buffer = await File.ReadAllBytesAsync(name), Name = name, MimeType = $"image/{format.ToLower()}" }); // TODO: Just Use A MemoryStream And Don't Create The File Locally
      form.Set("data", JsonSerializer.Serialize(data));

      // HTTPCallContext is an IAPIRequestContext
      IAPIResponse response = await HTTPCallContext.PostAsync(ImagesEndpoint, new APIRequestContextOptions() { Form = form });

      File.Delete(name);

      if (response.Status is 200)
          ScenarioContext.Set("Generated Image", image);

      else Assert.Fail($"[{response.Status}] {await response.TextAsync()}");
  }
```

**Steps**
1. Execute an API request along the lines of the above code.
2. Observe that a Playwright exception occurs.

**Expected**
I expect that I can attach a file to a multi-part form request and succesfully issue the request, however that does not seem to be possible.

**Actual**

`Microsoft.Playwright.PlaywrightException: 'formData[0].value: expected string, got undefined'`
```
   at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__39`1.MoveNext()
   at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__49`1.MoveNext()
   at Microsoft.Playwright.Transport.Channels.APIRequestContextChannel.<FetchAsync>d__2.MoveNext()
   at Microsoft.Playwright.Core.APIRequestContext.<FetchAsync>d__11.MoveNext()
   at ...
```

**Comment by Xen0byte** [comment]
Hi @mxschmitt, any thoughts on this one? In my mind the issue should be fairly straight-forward, but if the somewhat specific code is not good enough for a repro on your end I can replace it with a more concrete code that targets some public endpoint. Please let me know.

**Comment by mxschmitt** [comment]
The issue in your case is that you want to have:

    new APIRequestContextOptions() { Multipart = form });

and not:

    new APIRequestContextOptions() { Form = form });

we should definitely make the error more readable here!

**Comment by Xen0byte** [comment]
> The issue in your case is that you want to have:
> 
> ```
> new APIRequestContextOptions() { Multipart = form });
> ```
> 
> and not:
> 
> ```
> new APIRequestContextOptions() { Form = form });
> ```
> 
> we should definitely make the error more readable here!

Oh, amazing! Thank you so much.
