### ISSUE TITLE
[Feature] Avoid async delegates

### ISSUE THREAD

**Issue by mathiasi** [microsoft/playwright-dotnet#2669]
We are trying to use [Page.RequestFinished](https://playwright.dev/dotnet/docs/api/class-page#page-event-request-finished) however the advocated approach involves async delegates which triggers [this analyzer](https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD101.md) and it does appear to be causing some issues for us but since the `request` only has `ResponseAsync` it is a bit hard to avoid using async inside. It would be if there was a way around this or to have a synchronous way of getting the response. Afterall that is probably what most people are interested in when using `RequestFinished` specifically

**Comment by kblok** [comment]
@mxschmitt I was about to recommend `RunAndWaitForRequestFinishedAsync`. But the problem I found there is that the `Predicate` is a `Func<Request, bool>` and it would be nice to have a `Func<Request, Task<bool>>` option.

**Comment by mxschmitt** [comment]
Sounds like https://github.com/microsoft/playwright-dotnet/issues/2576

**Comment by mathiasi** [comment]
I cannot speak to the similarity as we are interested in specifically the callback. We are using it to keep track of all the API calls that are triggered by the Playwright tests and then know what data to clean up after the tests is complete. We are interested in some response data as it contains ID's and therefore we have to look at the response which unfortunately for us is only available as an async operation.
If only we could it synchronously like this it would serve our needs:
```csharp
page.RequestFinished += (page, request) =>
  {
    _tracking.Save(request.Url, request.Response());
  }
```

**Comment by mxschmitt** [comment]
I see, there is unfortunately no sync way of getting the response. I recommend either listening on "Response" event instead, which is fired after RequestFinished. Would that work for you?

**Comment by mathiasi** [comment]
@mxschmitt Maybe I have misunderstood you but the Response event gives a Response object which is also very async-focused. Did I miss a way to get the response body in a synchronous way on Response? It seems to me that I'll be facing the same problem whether we use Response or RequestFinished events.

**Comment by mxschmitt** [comment]
Oh ok, then there is no way, then maybe collect the Request/Response objects and bulk process them at the end of your tests or before you navigate?

**Comment by mathiasi** [comment]
Yeah I'm contemplating that solution too. Even though that will also have a downside: https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md

**Comment by mxschmitt** [comment]
Sounds then unfortunately a won't fix to me, since we can't change our model to have sync getters.

I'd recommend for now to disable the specific analyzer rules.

**Comment by mxschmitt** [comment]
Closing as per above, since this is more of a linter problem rather than an actual bug/feature request in Playwright.
