### ISSUE TITLE
[BUG] request and response events caused a memory leak

### ISSUE THREAD

**Issue by bba2022** [microsoft/playwright-dotnet#2672]
### System info
- Playwright Version: [v1.37]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

**Actual**

[Describe actual behavior]
The request and response events caused a memory leak, and the memory leak scenario will reappear 30 minutes after opening the browser

**Comment by mxschmitt** [comment]
Can you share a minimal reproducible which we can run locally to replicate your issue?

**Comment by mxschmitt** [comment]
closing as per above. Please re-file with a reproduction, otherwise we can't act on it, thanks!
