### ISSUE TITLE
Please expand the functionality of the .NET feature to match that of Java and Node [Feature]

### ISSUE THREAD

**Issue by jclaudon** [microsoft/playwright-dotnet#2678]
I normally develop my automation in Java/JS, and I love the rich and robust features that are available. I am now having to write my automation in .NET C# and the features are seriously lacking. Please as you continue to develop this amazing tool, develop in parallel for all supported languages.

**Comment by mxschmitt** [comment]
Closing as per above. We learned that most of our customers are most familiar with the Node.js ecosystem, so we invest most of our resources into this language port. I recommend filing individual feature requests for .NET if you are interested there in a particular feature.
