### ISSUE TITLE
[Feature] docker image for debian bookworm

### ISSUE THREAD

**Issue by jgilbert2017** [microsoft/playwright-dotnet#2680]
would it be possible to publish a debian bookworm based docker image since it is an officially supported platform?  

thank you for your hard work on this project, it is amazing!

**Comment by jgilbert2017** [comment]
is there any chance this can be added for dotnet8?  thank you.

**Comment by mxschmitt** [comment]
1.40.0 contains now .NET 8 as per https://playwright.dev/dotnet/docs/docker and https://playwright.dev/dotnet/docs/release-notes.

We'll continue to publish images based on the official ones, so Debian will be out of scope for now.
