### ISSUE TITLE
[Feature] Tracing to Support Multiple Pages

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#2682]
I had a brief look chunking doesn't seem to be support for multiple pages within the same context.

My use Case:
I used Playwright .NET with Spec flow + Nunit, 

I have a before Scenario hook that will run to create a new instance of page and uses dependency Injection to pass it around the step classes, this works fine. there a few scenarios where i run two pages of the same browser context for checking User A Action don't impact user B Etc.
To do this i have a scenario Tag i.e "page2" that i can apply to a scenario to open another page using a different state etc, this will take the current Browser context already running tracing and create a new page also passing that instance of page around using DI.

my issue is when one of these scenarios fail the trace file on shows the first page in the screenshots. the tracing is stopped on the browser context after the scenario is run

```
 await _scenarioContext.ScenarioContainer.Resolve<IBrowserContext>()
  .Tracing.StopAsync(new TracingStopOptions {
      Path = path
      });
```

How can i get a trace for either all pages within one Zip or multiple traces for each page. i guess i could create a whole new browser context and new page within to trace that but that seems excessive just to use tracing on two pages. if there no inbuilt way to trace a muti page browser context?

**Comment by mxschmitt** [comment]
> there a few scenarios where i run two pages of the same browser context for checking User A Action don't impact user B Etc.

A user is logged-in once per context, how do you login twice on the same context? Usually you should create a new context per user, so each user is isolated in its own world.

> my issue is when one of these scenarios fail the trace file on shows the first page in the screenshots. the tracing is stopped on the browser context after the scenario is run

I don't follow that. Could you elaborate? I think what you want is StartChunkAsync and StopChunkAsync.

> How can i get a trace for either all pages within one Zip or multiple traces for each page.

The first you can accomplish by just using StartAsync and StopAsync. Everything between, all the pages then get recorded. To get a trace per each page is not possible as of today.

---

Is your issue that user A and user B page is in the same trace file and you want to have it in a separate trace file?

**Comment by infinitejest69** [comment]
Sorry i was Absent for a few days.

i think this can be closed, i see where i may have mad a mistake in my Specflow Hooks logic creating new browsers contexts. 
Apologies
