### ISSUE TITLE
[Feature] How to setup Tracing with `PageTest` and `BrowserTest`?

### ISSUE THREAD

**Issue by DanielHabenicht** [microsoft/playwright-dotnet#2685]
There is this basic example of how to setup a trace with Playwright: https://playwright.dev/dotnet/docs/trace-viewer#recording-a-trace

However (I would think) most of the developers are extending `PageTest` and `BrowserTest`. But I can't wrap my head around how extend these classes to integrate tracing, as the most important parts are `private`. 

It would be neat if they would support it out of the box (by calling another method or supplying a `: base(tracing=true)` constructor).

**Comment by mxschmitt** [comment]
It's not possible yet to use it with the base classes as per https://github.com/microsoft/playwright-dotnet/issues/2214. Folding into it by that.
