### ISSUE TITLE
[BUG] Getting node platform folder for all platforms even when specifying runtime.

### ISSUE THREAD

**Issue by TheWrightDev** [microsoft/playwright-dotnet#2687]
From #1955 I add the `-r win-x64` paramter to my publish script expecting it to reduce the node platforms added, it does not.

### System info
- Playwright Version: v1.36.0
- Operating System: Windows 11
- Browser: N/A
- Other info:

### Source code

**Test file (self-contained)**

```
dotnet publish TestProject -r win-x64 --configuration Dev --output .\dist
```

**Steps**
- Run publish command.

**Expected**
.playwright\node directory would only contain `win32_x64`  folder.

**Actual**
.playwright\node actually contains `win32_x64`, `darwin-arm64`, `darwin-x64`, `linux-arm64`, `linux-x64` folders.

**Comment by mxschmitt** [comment]
I can reproduce, neither -r nor [`<PlaywrightPlatform>`](https://playwright.dev/dotnet/docs/library#bundle-drivers-for-different-platforms) works anymore.

**Comment by campersau** [comment]
As a workaround you can do `-p:PlaywrightPlatform=win`.
