### ISSUE TITLE
[BUG] No IBrowserContext.Pages/Page event not working in firefox

### ISSUE THREAD

**Issue by coderb** [microsoft/playwright-dotnet#2691]
### System info
- Playwright Version: [v1.37.1
- Operating System: Windows
- Browser: Firefox
- Other info:

### Source code

see below

**Steps**
- create firefox browser context
- manually add a tab
- BrowserContext.Pages.Count == 1 and no Page event is fired

If you require code let me know but is seems like Pages are completely broken in firefox.

Perhaps it is related to https://github.com/microsoft/playwright/issues/21780

**Comment by coderb** [comment]
maybe this
https://bugzilla.mozilla.org/show_bug.cgi?id=1706353

**Comment by mxschmitt** [comment]
> manually add a tab

So you open a new tab in the UI? that's outside of the scope for playwright. It's not expected to update state when the user interacts with it manually.

**Comment by coderb** [comment]
yes, that's right.  too bad it's not supported.  i'm trying to work around the OOPIF issue in firefox and was hoping to get a callback when the iframe was created.  chrome receives the callbacks and updates the Pages collection.

**Comment by mxschmitt** [comment]
If you have a real use-case, which can be purely reproduced with a single script and no user-interaction, we are more than happy to take a look. (so its pure automation) Thanks for your understanding!

**Comment by coderb** [comment]
is there _any_ workaround for not being able to get the IPage for firefox frames that are OOPIF?  the issue has been open for a long time.  my use case is site automation rather than testing.  there are many cases where a site uses a secure iframe and it is unavailable in playwright/firefox.    thank you!
