### ISSUE TITLE
[BUG]Running Chromium missing state compared to Firefox

### ISSUE THREAD

**Issue by czf** [microsoft/playwright-dotnet#2692]
When I run the included test using Chromium the final menu screen is blank.  The network requests for an xhr needed to render the menu return 403 Forbidden.  When I run the same code with Firefox the xhr request that returned 403 in Chromium returns 200 and the menu loads.  What configuration in Chromium is different from Firefox?

### System info
- Playwright Version: [v1.37.1]
- Operating System:  Windows 10
- Browser: Chromium
- Other info: succeeds in FireFox

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```cs
[TestMethod]
public async Task MenuTest()
{
    
    await Page.GotoAsync("https://www.subway.com/en-us/locator", new() { WaitUntil=WaitUntilState.DOMContentLoaded});
    await Page.Locator("#onetrust-reject-all-handler").ClickAsync();

    await Page.Locator("main #subwayLocator").GetByRole(AriaRole.Combobox).WaitForAsync();
    var locatorHandles = await Page.Locator("main #subwayLocator").GetByRole(AriaRole.Combobox).ElementHandlesAsync();
    var locationSearchBox = locatorHandles.First();
    await locationSearchBox.FillAsync("98026");
    await locationSearchBox.PressAsync("Enter");
    await Page.Locator("#subwayLocator .pickupCtaButton.primaryCta").ClickAsync();
    await Page.WaitForURLAsync("**/menu", new() { WaitUntil = WaitUntilState.DOMContentLoaded });
    await Page.Locator("h1.slider__title").GetByText("Best Sellers").WaitForAsync();

}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <Playwright>
    <BrowserName>chromium</BrowserName>
    <LaunchOptions>
      <Headless>false</Headless>
    </LaunchOptions>
  </Playwright>
</RunSettings>
```

**Steps**
- [Run the test]
- [...]

**Expected**

Menu loads xhr request for POST to https://www.subway.com/RemoteOrder/Menu/CategoriesAsync will return 200 running in chromium.

**Actual**
menu page is blank and xhr request for POST to https://www.subway.com/RemoteOrder/Menu/CategoriesAsync returns 403
in chromium but returns 200 in Firefox.

**Comment by czf** [comment]
I do get the expected behavior when I use a regular private window.  I'm assuming the issue is with how playwright starts chromium browsers

**Comment by mxschmitt** [comment]
This unfortunately sounds like the site has some kind of bot protection in place, which prevents Playwright from using the site. This is unfortunately out of our control. If you have a minimal reproducible, that a certain web-api is not behaving how it should be, then we're more than happy to take a look. With this we can't act on it.

(403 = forbidden, forbidden is usually an indicator, that you are blocked).

**Comment by czf** [comment]
@mxschmitt Is the test code I provided not considered minimal repro?  I included the api that isn't working in my notes as well.  I don't think its bot protection because this only happens in Chromium browsers.  I can use firefox via playwright just fine.
