### ISSUE TITLE
[Docs] Add notes on how to change .NET version to the docker guide

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright-dotnet#2698]
There are many requests to upgrade the official container to .NET7; examples: https://github.com/microsoft/playwright-dotnet/issues/2466, https://github.com/microsoft/playwright-dotnet/issues/2544, https://github.com/microsoft/playwright-dotnet/issues/2553, https://github.com/microsoft/playwright-dotnet/issues/2655, https://github.com/microsoft/playwright-dotnet/issues/2403, https://github.com/microsoft/playwright-dotnet/issues/1668. For reasons I don't understand, it's been said that only .NET6 (LTS) is supported and that we must create our own image. (That isn't in line with how it's done for all other MS repos, but ok.)

The advice given [here](https://github.com/microsoft/playwright-dotnet/issues/2553#issuecomment-1511099995) is to upgrade the [official](https://github.com/microsoft/playwright-dotnet/blob/main/utils/docker/Dockerfile.jammy) .NET6 [image](https://playwright.dev/dotnet/docs/docker#image-tags) like this:
```
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --version 7.0.0
```

However that doesn't work:
```
$ docker run -it --rm mcr.microsoft.com/playwright/dotnet:v1.37.1-jammy
$ dotnet --version
6.0.413

$ curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --version 7.0.0
# ...installation

$ dotnet --version
6.0.413
```

Playwright's docker experience is extremely complicated - please provide guidance how to upgrade to .NET7?

Thanks!

**Comment by mxschmitt** [comment]
Turns out you need to pass a custom installation directly, otherwise its not working, also depending on your use-case you might want the SDK, it would then look like this:

```bash
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 7.0.401 --install-dir /usr/share/dotnet
dotnet --list-runtimes
dotnet --list-sdks
```

.NET 8 will be LTS soon in November, then things get changed. Hope that helps!

**Comment by mxschmitt** [comment]
As per [the docs](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=macos), Linux is not supported by the .NET uninstall tool.

> The tool supports Windows and macOS. Linux is currently not supported.

Since a .NET SDK and runtimes are just folders on Linux, you can uninstall like that if I understand it correctly, worked for me:

```
rm -rf /usr/share/dotnet/shared/Microsoft.AspNetCore.App/6*
rm -rf /usr/share/dotnet/shared/Microsoft.NETCore.App/6*
rm -rf /usr/share/dotnet/sdk/6*
```

This should release around 442MB for me with linux/arm64.
