### ISSUE TITLE
Detect whether running in headed/headless mode

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright-dotnet#2705]
Is there a **built-in way** to detect whether Playwright is running in headed/headless mode?

I [asked](https://github.com/microsoft/playwright/discussions/27170#discussioncomment-7042910) on the upstream repo, and apparently for "test mode", it can be done like this:
```js
test('is headless', async ({}, testInfo) => {
    console.log(testInfo.project.use.headless)
});
```

Is it possible to detect when using .NET and in "library mode"?

**Comment by yury-s** [comment]
You can use `PlaywrightSettingsProvider.LaunchOptions` in the tests, will that work for you? When running without the test fixtures there is no direct way to read the option as it is passed by your code to Browser.LaunchAsync and the code is supposed to already know it.
