### ISSUE TITLE
[Feature] Documentation - Add up to date comparison of the dotnet feature set vs the node feature set

### ISSUE THREAD

**Issue by markoueis** [microsoft/playwright-dotnet#2712]
We are trying to decide between going with the dotnet implementation vs the node implementation of Playwright. Our teams are more familiar with c# but it seems like the Nodejs implementation may be quite ahead in terms functionality. Two areas off the top of my head would be global tracing configuration options and reporting options. 

Can we have an up to date page that shows the differences to help us chose between the two options? Do we have this somewhere already? I saw an older post that's 1 year old but was wondering if there was an update on that.

**Comment by yury-s** [comment]
The main difference of Node.js version is that it comes with its own test runner (and its unique features like HTML reporter). Even though Node.js is our primary platform, we strive to maintain parity between all supported languages in terms of library functionality. Also see [this page](https://playwright.dev/docs/languages).
