### ISSUE TITLE
[BUG] Unable to set maxResourceBufferSize and maxTotalBufferSize on C#

### ISSUE THREAD

**Issue by hermesramos** [microsoft/playwright-dotnet#2713]
It doesn't seem to be possible to set the maxResourceBufferSize and maxTotalBufferSize for Chromium on C#.

### System info
- Playwright Version: 1.37.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

```
using Microsoft.Playwright;
using System.Threading.Tasks;

class Program
{
    public static async Task Main()
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var context = await browser.NewContextAsync();
        var page = await context.NewPageAsync();

        var client = await page.Context.NewCDPSessionAsync(page);

        await client.SendAsync("Network.enable", new
        {
            ["maxResourceBufferSize"] = 1024 * 1024 * 50,
            ["maxTotalBufferSize"] = 1024 * 1024 * 100
        });

        // Navigate or perform other actions
        await page.GotoAsync("https://example.com");
    }
}
```

**Expected**

To increase the buffer size and be able to download a 20mb JSON from a response.

**Actual**

Doesn't increase buffer size.

**Comment by yury-s** [comment]
> Doesn't increase buffer size.

If the command succeeded, the new params [should apply](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;l=1951-1961;drc=150d8c7e45daeef094be8ec8852e3486eed8f59d). How do you check that it didn't increase?

**Comment by hermesramos** [comment]
> > Doesn't increase buffer size.
> 
> If the command succeeded, the new params [should apply](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;l=1951-1961;drc=150d8c7e45daeef094be8ec8852e3486eed8f59d). How do you check that it didn't increase?

Here is the updated code, showing that the json is still being evicted and the new params didn't apply.


```
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
        Microsoft.Playwright.Program.Main(new[] { "install", "chromium" });

        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var context = await browser.NewContextAsync();
        var page = await context.NewPageAsync();

        var client = await page.Context.NewCDPSessionAsync(page);

        await client.SendAsync("Network.enable", new()
        {
            ["maxResourceBufferSize"] = 1024 * 1024 * 50,
            ["maxTotalBufferSize"] = 1024 * 1024 * 100
        });

        // Navigate or perform other actions
        var responseTask = page.WaitForResponseAsync("**/large-file.json");
        await page.GotoAsync("https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json");
        var response = await responseTask;
        var json = await response.TextAsync();
    }
}
```

**Comment by yury-s** [comment]
The parameters are updated per CDP session and that one that you create is different from that used by Playwright. It will work as expected if you use bare CDP in the same session where you update the parameters.

Folding this request into https://github.com/microsoft/playwright/issues/13449. If `response.TextAsync()` does not work for some responses work for a large response, feel free to file a separate issue for that.
