### ISSUE TITLE
[Question] Trying to add user-agent setting on runSettings file

### ISSUE THREAD

**Issue by ZhouZhengCarlos** [microsoft/playwright-dotnet#2717]
Hi I want to add user agent to my playwright .net solution as I did in my playwright nodejs solution

Playwright.config.js:
```
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], userAgent: 'Chrome-Playwright-Automation' },
    }
```

I've seen that on .Net there is a .runSettings file and I wanted to add it there instead of this solution https://github.com/microsoft/playwright-dotnet/issues/2080

Tried this approach but doesnt look to work, I might be missing something

.runSettings:

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- NUnit adapter -->  
  <NUnit>
    <NumberOfTestWorkers>24</NumberOfTestWorkers>
  </NUnit>
  <!-- General run configuration -->
  <RunConfiguration>
    <EnvironmentVariables>
      <!-- For debugging selectors, it's recommend to set the following environment variable -->
      <DEBUG>pw:api</DEBUG>
    </EnvironmentVariables>
  </RunConfiguration>
  <!-- Playwright -->  
  <Playwright>
    <BrowserName>chromium</BrowserName>
    <ExpectTimeout>5000</ExpectTimeout>
    <LaunchOptions>
      <Headless>false</Headless>
		<UserAgent>Chrome-Playwright-Automation</UserAgent>
		<!-- <Channel>msedge</Channel> -->
    </LaunchOptions>
  </Playwright>
</RunSettings>
```

Thank you!

**Comment by mxschmitt** [comment]
`UserAgent` is a Context options rather than a Launch options. Context options can't be set in the runsettings file, only inside the class its supported as per https://github.com/microsoft/playwright-dotnet/issues/2555.

Folding into https://github.com/microsoft/playwright-dotnet/issues/2555.
