### ISSUE TITLE
[BUG]: TearDown : Microsoft.Playwright.PlaywrightException : Process exited

### ISSUE THREAD

**Issue by aaron-volosin-tfs** [microsoft/playwright-dotnet#2721]
I wrote a set of tests the using the Nunit framework for Playwright and the tests themselves work fine until I add code into [TearDown] that stops my service I am running against. I can run the tests. They complete without any errors and then when the code specifically hits the myService.Stop(); in [TearDown] then the test fails with "TearDown : Microsoft.Playwright.PlaywrightException : Process exited" I can watch the browser close at this step. Here is the full stack trace.

Message: 
TearDown : Microsoft.Playwright.PlaywrightException : Process exited
TearDown : Microsoft.Playwright.PlaywrightException : Process exited

Stack Trace: 
--TearDown
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary2 dictionary, Boolean keepNulls) line 214 Connection.WrapApiCallAsync[T](Func1 action, Boolean isInternal) line 521
BrowserContext.CloseAsync() line 276
BrowserTest.BrowserTearDown() line 57
GenericAdapter1.GetResult() AsyncToSyncAdapter.Await(Func1 invoke)
SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
SetUpTearDownItem.RunTearDown(TestExecutionContext context)
--TearDown
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary2 dictionary, Boolean keepNulls) line 214 Connection.WrapApiCallAsync[T](Func1 action, Boolean isInternal) line 515
Browser.CloseAsync() line 79
WorkerAwareTest.WorkerTeardown() line 90
GenericAdapter1.GetResult() AsyncToSyncAdapter.Await(Func1 invoke)
SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
SetUpTearDownItem.RunTearDown(TestExecutionContext context)

I would really like to use Setup and TearDown to stop and start my service to make sure all sessions are cleared for the next test. Any Ideas?

### System info
- Playwright Version: [v1.38]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;

```cs
   [TearDown]
   public void TearDown()
   {
       if (myService.Status == ServiceControllerStatus.Running)
       {
           myService.Stop();
           while (myService.Status != ServiceControllerStatus.Stopped)
           {
               Thread.Sleep(250);
               myService.Refresh();
           }
       }
   }
```

**Steps**
- [Run the test]
Run the test with VS running as Administrator ( to access the service ) 
NOTE: if the service is stopped it will start without issues in the [SetUp]
Test completes as expected and browser closes

**Expected**
TearDown will stop the service and the test will be marked as passed in the Test Explorer

**Actual**
Test is marked as failed with the stack trace above

**Comment by mxschmitt** [comment]
Can you provide us a reproducible which we can run locally and clear reproduction steps? the code snippet above is unfortunately not runnable.

**Comment by aaron-volosin-tfs** [comment]
This is looking to be specific to my service.  The service stops and starts as expected but whatever comes to playwright specifically from my service causes it to exit. If I use another service like "Themes" the test passes as expected.  I can''t give you access to my service as its proprietary so I guess this can be closed unless there is a way to get deeper debug logs

**Comment by mxschmitt** [comment]
Please re-file with a repro which we can run locally as per above. Thank you for your understanding.
