### ISSUE TITLE
[Feature] Conditional tracing depending on test outcome

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright-dotnet#2734]
Right now we need to start and stop the tracing manually. However I only want traces of failing tests.

I thought of doing this, but I'm not sure if the Stop isn't called that there won't be a memory leak, for example?
```csharp
[TestCleanup]
public async Task Cleanup()
{
    if (TestContext.CurrentTestOutcome == UnitTestOutcome.Failed)
    {
        await Context.Tracing.StopAsync();
    }
}
```
Ideally like in the Typescript bindings, there would be a high-level setting to automatically trace (retained only for failing tests).

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2214
