### ISSUE TITLE
[Feature] .NET8 docker images

### ISSUE THREAD

**Issue by martinalderson** [microsoft/playwright-dotnet#2737]
Let us know what functionality you'd like to see in Playwright and what your use case is.

Any ETA on providing .NET8 docker images? It would be great to have "preview" ones based on rc2 for example so we can be ready for launch on a couple of weeks, especially given it is an LTS release. 

Do you think others might benefit from this as well?

Yes. We currently build our own .NET7/8 docker images for playwright but this is a quite painful/brittle process to manage. It's also really slow (nearly all our CI time is spent compiling docker images for playwright), and causes our bitbucket docker cache to go over the 1GB limit atlassian has. We did try to have our own layered images but we had problems with it getting stale and causing weird build failures. 

Playwright docker images consistently causes us the most headaches when upgrading .net versions.

**Comment by mxschmitt** [comment]
> Any ETA on providing .NET8 docker images?

We switch to .NET 8 once it got promoted to LTS. This happens around November 14-16, 2023.

> It would be great to have "preview" ones based on rc2 for example so we can be ready for launch

We strongly recommend not using our Docker container with your production apps. Its for end-to-end testing only, so we see not a lot of value in providing a RC version by that.

> It's also really slow (nearly all our CI time is spent compiling docker images for playwright), and causes our bitbucket docker cache to go over the 1GB limit atlassian has. 

Do you push to a custom Docker Registry?  See e.g. [here](https://support.atlassian.com/bitbucket-cloud/docs/build-and-push-a-docker-image-to-a-container-registry/). There are a lot of Registries out there, self hosted, as well as managed ones. Also GitHub has their [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry). Are you doing that already?

**Comment by jgilbert2017** [comment]
@mxschmitt _"We strongly recommend not using our Docker container with your production apps."_

can you please say why that is?  deployment to production is one of the main uses of docker imo.

**Comment by martinalderson** [comment]
@mxschmitt yes I'm aware of that, but we can't update our e2e test project to .net8 (which we run on CI via docker) because of this. well, we can, because we make our own docker images, but it's actually a big blocker. I'm not sure if you guys are considering exactly how people use playwright in development cycles.

for example; we reference our shared project from the e2e test project for various models and classes, and run our e2e tests on docker on ci. when you don't provide out of the box .net7/8 docker images it causes a massive headache, as we can't reference the shared .net7/8 project from a .net6 project. i'm sure many many people are hitting this.

i would really recommend you reassess your playwright docker image policy in general.

but keeping with the actual request, rc2 images would be much appreciated.

**Comment by yury-s** [comment]
Covering .Net releases beyond LTS is out of scope for Playwright. This is the same policy that we apply in Node.js port where we only publish Docker images with current Node.js LTS. All the docker files are open source and you can always tweak them to your liking or just add a layer on top of existing image and push it to a registry of your choice to save resources.

Closing this issue as we are not planning to increase number of published Docker images.

> can you please say why that is? deployment to production is one of the main uses of docker imo.

See the note on [this page](https://playwright.dev/docs/docker#usage), basically our images are supposed to be used for testing in a trusted environment.

**Comment by jgilbert2017** [comment]
@yury-s 

> See the note on [this page](https://playwright.dev/docs/docker#usage), basically our images are supposed to be used for testing in a trusted environment.

i see that it recommends using a non-root user to do scraping, and a note that says the image is not intended to be used against untrusted sites, but what i am asking is _why_?

if i use an untrusted user as recommeneded, is there any reason not to use the docker image for production?  the rationale here seems at best incompletely explained.

**Comment by martinalderson** [comment]
@mxschmitt any update on the docker images?

**Comment by martinalderson** [comment]
@mxschmitt which tag should we be using? the dotnet:v1.39.0-jammy still seems to use .net6?

**Comment by mxschmitt** [comment]
1.40 will contain .NET 8 once 1.40 got released.
