### ISSUE TITLE
[BUG] Download Events

### ISSUE THREAD

**Issue by qq7995516** [microsoft/playwright-dotnet#2755]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [ Windows 10]
- Browser: [Msedge]
- Other info:
- Msedge The download event is not triggered for some files.
This is an intranet website that I cannot share with you.

### Source code

            context.Page += (s1, p) =>
            {
                p.Download += async (s2, d) =>
                {
                    textBox2.Text = $"{textBox1.Text}\\{d.SuggestedFilename} 下载完成";
                };
            };

**Comment by mxschmitt** [comment]
Since this issue is not following the bug template, we unfortunately need to close it.

I recommend looking into the Download API docs, as per here: https://playwright.dev/dotnet/docs/downloads

Feel free to re-file with a repro, thanks for your understanding.

**Comment by qq7995516** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
