### ISSUE TITLE
[Question] I have to keep my current window open and launch a new tab or window with a URL in Playwright.

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2764]
In our application, we stop user on a screen until user   clicks a link which is sent to their Mobile Device or Email. And the screen auto populates the information once user clicks the link.

Here, I would like to launch or open new tab or window with the URL and verify the screen populates  the right information. Could you please let me know . .how can I achieve this using playwright?
**What I want to acheive.**
Window 1 is the place where user is stopped.
Window 2 or tab I want to launch with the URL which is sent to User Email such that Window 1 refresh by itself and populates the information.

**Comment by mxschmitt** [comment]
Sounds like for Window 1 you just use the normal `Page` and for Window 2 you create a new page with `Context.NewPageAsync()` which is like a tab. Have you tried this?

**Comment by kabdul-incomm** [comment]
thank you @mxschmitt - This is what I was looking for hence closing the ticket.

> Sounds like for Window 1 you just use the normal `Page` and for Window 2 you create a new page with `Context.NewPageAsync()` which is like a tab. Have you tried this?
