### ISSUE TITLE
[Question] How do I access Playwright from an MSIX package?

### ISSUE THREAD

**Issue by tpetchel** [microsoft/playwright-dotnet#2773]
Hi!

I’m building an MSIX package that includes a C# app that calls into Playwright (using the NuGet package.) After installation, I get a `PlaywrightException` (“Access is denied”) when the app activates Playwright. My application works as expected in my development environment or if I move my app outside of the installation path (to, say, C:\Temp).

This code example is incomplete, but it's basically what I'm using to start Playwright:

```csharp
playwright = await Playwright.CreateAsync();
browserContext = await playwright.Chromium.LaunchPersistentContextAsync(userDataDir, new()
{
    Headless = headless,
    Channel = browserChannel,
    Args = new[] {
        $"--profile-directory={profileDirectory}"
    }
});
```
 
Does anyone have advice on which capabilities or settings I need to include in my AppxManifest? Thanks so much in advance! 🙇‍♂️

**Comment by mxschmitt** [comment]
We are unfortunately not familiar with MSIX, would it be possible by creating a minimal reproducible and/or following the [bug issue template](https://github.com/microsoft/playwright-dotnet/issues/new?assignees=&labels=&projects=&template=bug.md&title=%5BBUG%5D)?

**Comment by tpetchel** [comment]
I learned from the Playwright team that our scenario - packaging Playwright as part of another application - isn't supported. Closing this and we'll look for another solution.
