### ISSUE TITLE
[BUG] Broken links in Rider

### ISSUE THREAD

**Issue by thatstatsguy** [microsoft/playwright-dotnet#2774]
### System info
- Playwright Version: 1.38.0
- Operating System: Windows
- Browser: n/a
- Other info: IDE - rider

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Steps**
Type the following code into Rider
```
await using var browser = playwright.Chromium.LaunchAsync();
await using var context = await browser.NewContextAsync();
await context.Tracing.StartAsync(new()
{
  Screenshots = true,
  Snapshots = true
});
var page = context.NewPageAsync();
await page.GotoAsync("https://playwright.dev");
await context.Tracing.StopAsync(new()
{
  Path = "trace.zip"
});
```
When hovering over `StopAsync`/`Path`/ etc Rider gives a suggested link which no longer exists. I'm happy to update the links, but I can't find them on this repository although this repo definitely has the code e.g. [StopOptions](https://github.com/microsoft/playwright-dotnet/blob/6e50f17ede858f2ff4955db0661035f7763837ae/src/Playwright/API/Generated/Options/TracingStopOptions.cs) . 

**Expected**

To redirect to this following link
https://playwright.dev/dotnet/docs/api/class-tracing

**Actual**
I'm redirected here which doesn't exist
https://learn.microsoft.com/en-us/dotnet/api/Microsoft.Playwright.TracingStopOptions.Path?view=netstandard-2.0

**Comment by mxschmitt** [comment]
It looks like a Rider bug to me since we don't have the links in our source code / nuget file which we distribute. I tried the following (after adjusting your code since it was not syntactically correct)

```csharp
using var playwright = await Playwright.CreateAsync();
var browser = await playwright.Chromium.LaunchAsync();
var context = await browser.NewContextAsync();
await context.Tracing.StartAsync(new()
{
    Screenshots = true,
    Snapshots = true
});
var page = await context.NewPageAsync();
await page.GotoAsync("https://playwright.dev");
await context.Tracing.StopAsync(new()
{
    Path = "trace.zip"
});
```

I would recommend to reach out to the Rider support tracker.

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by thatstatsguy** [comment]
Thanks @mxschmitt! Will reach out to the peeps at rider. Ironically that code with the syntax issue came straight from the playwright website (wasn't able to use my code). Will make a PR for that.
