### ISSUE TITLE
[Question] Weird behavior (and trace source) when running parallel tests with tracing in Azure Devops

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright-dotnet#2775]
Some context: I have a number of Playwright tests running against a Microsoft Dynamics application.

- running them locally (parallel and with tracing) works fine
- running them in an Azure pipeline (parallel but without tracing) works fine

However, the oddities commence when adding tracing in the pipeline - _see the screenshot_. 

- most tests (but not all) fail because the application's initial navigation to a subpage take 2 minutes
- oddly enough in my tracing source, there's a 404 error page relating to GitHub? I have no idea where this comes from. There is no 404 call in the Network traces.
- this also happens locally: also, there's a console error that's possibly related? _Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set._

![image](https://github.com/microsoft/playwright-dotnet/assets/18096566/b5434460-5eef-490d-aac1-45f3592c85ed)

I have no clue how to further investigate as it's not locally reproducible.

**Comment by pavelfeldman** [comment]
Could you share a trace of a local execution with us privately? Maybe it is huge? Too much stuff happens on the initial navigation, etc...

**Comment by mxschmitt** [comment]
Discord will work, either `pavelfeldman` or `mxschmitt` there.

**Comment by Exoow** [comment]
Files sent to @pavelfeldman

**Comment by mxschmitt** [comment]
Sorry for the late reply, would it be possible to send it to me?

**Comment by Exoow** [comment]
Done (on Discord).

**Comment by mxschmitt** [comment]
Note: We also landed a fix for the sources tab which showed HTML as per the first comment in https://github.com/microsoft/playwright/pull/29192.
