### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2776]
### System info
- Playwright Version: 1.40.0
- Operating System:  Windows 11
- Browser: Chromium
- Other info: nUnit Version 3.13.3

### Source code

 

**Test file (self-contained)**

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

   var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
IBrowser? browser;
  browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
  {
      Headless = true
  });
  _Page = await browser.NewPageAsync();
await _Page.GotoAsync("Some URL");
var prefillPage = await page.Context.NewPageAsync();
```
Actual Result:
An error message Microsoft.Playwright.PlaywrightException : Please use Browser.NewContextAsync()
is returned.
  

**Expected**

User should be allowed to open a new tab. And Perform action.

Note: 
1. The same code works fine when Headless = false. 
2. Their is no object called Browser in Playwright which is mentioned in the error message.
3. I don't have Ibrowser instance available from where I execute var prefillPage = await page.Context.NewPageAsync(); .

**Comment by mxschmitt** [comment]
[`Browser.NewPageAsync()`](https://playwright.dev/docs/api/class-browser#browser-new-page) is a wrapper function which creates a context and a page for you. When using this, its not possible to create a new a new page using the underlying context.

You can fix it by doing the following (create a context first and use it to create your page1 and page2):

```csharp
 var context = await browser.NewContextAsync();
_Page = await context.NewPageAsync();
await _Page.GotoAsync("Some URL");
var prefillPage = await context.NewPageAsync();
```

Let us know if that works for you!

**Comment by kabdul-incomm** [comment]
> [`Browser.NewPageAsync()`](https://playwright.dev/docs/api/class-browser#browser-new-page) is a wrapper function which creates a context and a page for you. When using this, its not possible to create a new a new page using the underlying context.
> 
> You can fix it by doing the following (create a context first and use it to create your page1 and page2):
> 
> ```cs
>  var context = await browser.NewContextAsync();
> _Page = await context.NewPageAsync();
> await _Page.GotoAsync("Some URL");
> var prefillPage = await context.NewPageAsync();
> ```
> 
> Let us know if that works for you!

We don't create context. Is it recommended to create context all the time? And context object is not available in our framework all the time. Is this recommended?

**Comment by kabdul-incomm** [comment]
> Yes it is recommended. `browser.NewContextAsync();` does also create a context for you, you just have no ability to access it. Since you need one, you need to create it from the outside.

Thank you. The above solution works hence closing this issue.

**Comment by kabdul-incomm** [comment]
Thank you. The above solution works hence closing this issue.
