### ISSUE TITLE
[BUG] Microsoft.Playwright.PlaywrightException: spawn UNKNOWN

### ISSUE THREAD

**Issue by DipakTated** [microsoft/playwright-dotnet#2777]
Microsoft.Playwright.PlaywrightException: spawn UNKNOWN
=========================== logs ===========================
C:\Users\jlindt\AppData\Local\ms-playwright\chromium-1045\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\jlindt\AppData\Local\Temp\playwright_chromiumdev_profile-I3S297 --remote-debugging-pipe --no-startup-window
at async Task Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync(string guid, string method, Dictionary<string, object> dictionary)
at async Task Microsoft.Playwright.Transport.Connection.WrapApiCallAsync(Func<Task> action, bool isInternal)
at async Task

**Comment by mxschmitt** [comment]
Could you check if `C:\Users\jlindt\AppData\Local\ms-playwright\chromium-1045\chrome-win\chrome.exe` exists?

Or if the folder `C:\Users\jlindt\AppData\Local\ms-playwright\chromium-1045` exists?

**Comment by DipakTated** [comment]
Yes the folders exists with its contents

**Comment by DipakTated** [comment]
When i try to manually delete these folders which you mentioned, it throws below error:

Executable doesn't exist at C:\Users\dtated\AppData\Local\ms-playwright\chromium-1091\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     pwsh bin/Debug/netX/playwright.ps1 install             ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚══════════════════════════════



So definitely spawn issue is not caused by folder

**Comment by DipakTated** [comment]
Today , i tried running the application as administrator and it works all fine. While if i run from account, which doesnot have administrator rights, it throws access error from Playwright and spawn unknown error. Can we make playwright .net be accessed and working for normal users as well

**Comment by mxschmitt** [comment]
My guess is that since you filed https://github.com/microsoft/playwright-dotnet/issues/2778 its related to some company policies on your system which prevent us from spawning Chromium. I recommend checking with your IT. This would also explain why it works with Administrator permissions and not as a normal user.

**Comment by DipakTated** [comment]
Shell scripting execution policy is unrestricted on all users machine.   Only playwright application is not able to run, cause of this architecture

**Comment by mxschmitt** [comment]
`spawn: UNKNOWN` means that there is an anti-virus or Windows Group Policy preventing running the browsers.

I recommend trying to run the executable via the Terminal manually to see if it works or not. And checking with your IT for further assistance.

Since this is not actionable for us I'm going to close it for now.
