### ISSUE TITLE
[Question] How to use QuerySelectorAllAsync().Select()

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2779]
How to get all the items of Select html element.
I tried below code but its erroring out. The error is mentioned in the screen shot.
` var selector = "#MainContent_BelowMenuContent_lstProgram>option";
 var querySelectorResult = await page.QuerySelectorAllAsync(selector);
 var values = await querySelectorResult.Select(async option => await option.GetAttributeAsync("value")).ToList();`
![QuerySelector](https://github.com/microsoft/playwright-dotnet/assets/51454842/ec4fedc5-80ac-4758-819b-287019c85033)

**Comment by kabdul-incomm** [comment]
> instead

 . Document only shows how to select an item from the drop down. Instead I want to get all the drop down values.

**Comment by mxschmitt** [comment]
If you want to get all the dropdown items `SelectOptionAsync` won't work since its for selecting items. To assert the values you can e.g. do this: 

```csharp
var locator = Page.Locator("select");
await locator.SelectOptionAsync(new string[] { "R", "G" });
await Expect(locator).ToHaveValuesAsync(new string[] { "R", "G" });
```

To get the values you can use: 

```csharp
await Page.EvalOnSelectorAsync<string[]>("select", "select => Array.from(select.options).map(option => option.value)");
```

Would that work for you?

**Comment by mxschmitt** [comment]
In your case you can do one of the following:

```csharp
await Page.EvalOnSelectorAsync<string[]>( "#MainContent_BelowMenuContent_lstProgram>option", "selector => Array.from(selector.options).map(option => option.value)");
await Page.Locator("#MainContent_BelowMenuContent_lstProgram>option").EvalOnSelectorAsync<string[]>("selector => Array.from(selector.options).map(option => option.value)");
```

The latter is preferred, since it ensures that there is only one element with the specific selector on the page.

Does this answer your question?

**Comment by kabdul-incomm** [comment]
> In your case you can do one of the following:
> 
> ```cs
> var allElements = await Page.EvalOnSelectorAsync<string[]>( "#MainContent_BelowMenuContent_lstProgram>option", "selector => Array.from(selector.options).map(option => option.value)");
> var allElements = await Page.Locator("#MainContent_BelowMenuContent_lstProgram>option").EvalOnSelectorAsync<string[]>("selector => Array.from(selector.options).map(option => option.value)");
> ```
> 
> The latter is preferred, since it ensures that there is only one element with the specific selector on the page.
> 
> Does this answer your question?

Sorry to say.. I don't see EvalOnSelectorAsync in 1.40.0 version of Playwright. Instead I see EvaluateAllAsync.

**Comment by mxschmitt** [comment]
I apologise, thats the one I meant.

**Comment by kabdul-incomm** [comment]
> I apologise, thats the one I meant.

Expression = Array.from(selector.options).map(option => option.value) is javascript correct?
