### ISSUE TITLE
[BUG] Playwright won't initialise when console thread blocked

### ISSUE THREAD

**Issue by harryhobson** [microsoft/playwright-dotnet#2783]
### System info
- Playwright Version: [v1.40.0]
- Operating System: Windows 10, Windows Server 2016
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

In addition to playwright, requires:
- [serilog-sinks-console](https://github.com/serilog/serilog-sinks-console)
- [serilog-sinks-async](https://github.com/serilog/serilog-sinks-async)

I have included serilog as this is how I have been able to replicate the issue.

```csharp
using Microsoft.Playwright;
using Serilog;
 
Log.Logger = new LoggerConfiguration()
	.WriteTo.Async(a => a.Console())
	.CreateLogger();
 
int i = 1;
while (true)
{
	File.AppendAllText("./data.txt", DateTime.Now.ToString("hh:mm:ss.fff") + "\n");
	var playwright = await Playwright.CreateAsync();
	//var browser = await playwright.Chromium.ConnectOverCDPAsync("http://localhost:9222");
	//await browser.DisposeAsync();
	Log.Information(i.ToString());
	await Task.Delay(2000);
	playwright.Dispose();
	i++;
}
```

**Steps**
- Run the code as a windows console application (unsure if the occurs on other platforms)
- Select the console screen text to block console IO. This causes serilog to be unable to write logs to console and blocks the background serilog thread. See [this link](https://stackoverflow.com/questions/45275480/console-writeline-gets-stuck/45895662#45895662) for more details.
- `Playwright.CreateAsync()` is unable to run due to the thread being blocked and hangs indefinitely

**Expected**

`Playwright.CreateAsync()` is successful. Code continues to run and write timestamps to file/iterations to console. 

**Actual**

`Playwright.CreateAsync()` hangs indefinitely. Code does not continue to run and timestamps stop being written to file/iterations to console.

**Playwright Thread**

![createasync_issue_playwright](https://github.com/microsoft/playwright-dotnet/assets/21588616/53bbe5cf-6314-4f0d-8859-1f46fee02a52)

**Serilog Thread**
![createasync_issue_serilog](https://github.com/microsoft/playwright-dotnet/assets/21588616/93b96fcb-f608-4b7e-833b-c57afa760965)

**Comment by mxschmitt** [comment]
Seems like the line which hangs is: `Console.OutputEncoding = new UTF8Encoding(false);`. Does this also hang without Playwright - like just executing this line after your use your Serilog log library?

**Comment by harryhobson** [comment]
Yes I see the same hanging behaviour using just your line instead of the Playwright line

**Comment by mxschmitt** [comment]
Sounds like a bug in Serilog or .NET in my opinion. I recommend fing a bug on Serilog side.

**Comment by harryhobson** [comment]
Sure thing, will do. Thanks @mxschmitt

**Comment by mxschmitt** [comment]
Closing as per above then!
