### ISSUE TITLE
[BUG] Playwright is not able to load is page where javascript is injected based on click event by the application

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2791]
Playwright Version: 1.40
Operating System: Windows 11,
Browser: Chromium
Our Application inject javascript based on click event and using the javascript we display some controls and interact with user.
Here. playwright is not able to inject the javascript.

Expected

Playwright should be able to inject the javascript.

Actual

Playwright is not able to inject javascript.

Note: In Firefox the javascript is injected.
![PrivacySettings](https://github.com/microsoft/playwright-dotnet/assets/51454842/1ec27b4f-e988-4545-83de-aef29284022a)

**Comment by kabdul-incomm** [comment]
do you want me to create an application and provide you the steps using Git repository?  Its going to take time.

**Comment by mxschmitt** [comment]
Yes, we are otherwise unfortunately not able to debug such issues.

**Comment by kabdul-incomm** [comment]
Its very easy for me to create a test account which works for US IP address and last long for 30 days only. Let me know if you are fine with this.
