### ISSUE TITLE
How i can use .net 6 in docker container?

### ISSUE THREAD

**Issue by SaveliyShur** [microsoft/playwright-dotnet#2799]
What is tag for docker image?

**Comment by mxschmitt** [comment]
You can e.g. use `mcr.microsoft.com/playwright/dotnet:v1.40.0-focal` which is using Ubuntu 20.04 and .NET 6.

Jammy is using Ubuntu 22.04 and .NET 8.

If you want to use a different .NET version which does not match these, we recommend creating your own Docker image.
