### ISSUE TITLE
[Feature]How to match RouteAsync with a fixed start and a wildcard at the end?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2800]
How to match RouteAsync with a fixed start and a wildcard at the end?
The following code is not working

```
await page.RouteAsync("https://playwright.dev*", async route =>
        {
           
        });
```

**Comment by mxschmitt** [comment]
`*` does not match `/` so you need to do: `**/*`:

`await page.RouteAsync("https://playwright.dev**/*", async route =>`

let us know if it works for you!

**Comment by mxschmitt** [comment]
This feature is called globstar and is part of the [glob syntax](https://en.wikipedia.org/wiki/Glob_(programming)), closing by that.
