### ISSUE TITLE
[BUG]ConnectOverCDPAsync Multiple uses may cause bugs

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2802]
ConnectOverCDPAsync Multiple uses may cause bugs

error  Connection disposed

If I call the following method multiple times, the above exception will occur.

![image](https://github.com/microsoft/playwright-dotnet/assets/26525599/665fe4cf-8dba-432d-aa0f-a563dd877889)

```
page.Request +=
```

**Comment by bbhxwl** [comment]
![image](https://github.com/microsoft/playwright-dotnet/assets/26525599/5ad2b4b8-91c4-4cb7-a3de-d7a0cec9a223)

**Comment by mxschmitt** [comment]
This bug does not follow the bug template, please re-file with a self-contained reproducible which we need in order to triage bugs like this. Thanks for your understanding.
