### ISSUE TITLE
[BUG]Why is the rendering result different from a real browser?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2803]
The following code startup will fix the size of the content, which is different from the real browser, resulting in different rendering effects. Why?

```
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions()
{
    ExecutablePath = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    Headless = false
});
await page.GotoAsync("https://google.com");

```

![image](https://github.com/microsoft/playwright-dotnet/assets/26525599/bb24e7eb-5cfb-4bfd-8e8b-6054adcf18fa)

**Comment by mxschmitt** [comment]
Playwright leverages something called a virtual viewport in the browser. This is controlled by the viewport you pass when [creating a context](https://playwright.dev/dotnet/docs/api/class-browser#browser-new-context-option-viewport) the default for that is 1280x720. See also [here](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-persistent-context-option-viewport) how to deactivate it.

We use this to ensure a consistent behaviour across different machines, especially if they have different monitor resolutions.

**Comment by bbhxwl** [comment]
> Playwright leverages something called a virtual viewport in the browser. This is controlled by the viewport you pass when [creating a context](https://playwright.dev/dotnet/docs/api/class-browser#browser-new-context-option-viewport) the default for that is 1280x720. See also [here](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-persistent-context-option-viewport) how to deactivate it.
> 
> We use this to ensure a consistent behaviour across different machines, especially if they have different monitor resolutions.

Thank you, this is really powerful.
