### ISSUE TITLE
Question: How to add chrome extension

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2804]
How do I extensions in Playwright. I'm using below p;iece of code but not able to add. Please help.

```csharp
 var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
 var headless = Convert.ToBoolean(ConfigurationData.GetAppSetting("HeadlessModeEnabled"));
 var pageDefaultTimeoutInMs = Convert.ToInt32(ConfigurationData.GetAppSetting("PageDefaultTimeoutInMs"));
 IBrowser? browser;
 if (!headless)
 {
     browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
     {
         Headless = headless,
         Args = new[]
         {
             "--start-maximized",
             "--load-extension=C:\\Users\\kabdul\\AppData\\Local\\Google\\Chrome\\User Data\\extensions_crx_cache\\ndgimibanhlabgdgjcpbbndiehljcpfh_1.ae972fbce9ff8459dede10532d16a7eb9927091e112a9e5c0ffe0a51eb6a7496"
         }
     });
     var context = await browser.NewContextAsync(new BrowserNewContextOptions() { ViewportSize = ViewportSize.NoViewport });
     _Page = await context.NewPageAsync();
 }
 else
 {
     browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
     {
         Headless = headless
     });
    
     _Page = await browser.NewPageAsync();
 }

 _Page.SetDefaultTimeout((float)pageDefaultTimeoutInMs);
 return _Page;
```

**Comment by mxschmitt** [comment]
In order to load a Chrome extension, you need a persistent context instead of normal launch. This would then look something like that:

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
var extensionPath = "C:\\Users\\maxschmitt\\development\\playwright-dotnet\\src\\Playwright.Tests.TestServer\\assets\\simple-extension (81)";
await using var context = await playwright.Chromium.LaunchPersistentContextAsync("", new(){
    Headless = false,
    Args = new[] {
        $"--disable-extensions-except={extensionPath}",
        $"--load-extension={extensionPath}",
        "--start-maximized",
    },
    ViewportSize = ViewportSize.NoViewport
});
await context.Pages[0].PauseAsync();
```

**Comment by kabdul-incomm** [comment]
> ```cs
> $"--load-extension={extensionPath}",
> ```

I get this error ---------------------------
Error Loading Extension
---------------------------
Failed to load extension from: C:\Users\kabdul\AppData\Local\Google\Chrome\User Data\extensions_crx_cache\ndgimibanhlabgdgjcpbbndiehljcpfh_1.ae972fbce9ff8459dede10532d16a7eb9927091e112a9e5c0ffe0a51eb6a7496. Manifest file is missing or unreadable
---------------------------
OK   
---------------------------

**Comment by kabdul-incomm** [comment]
@mxschmitt - Sorry to push you, I don't know whether you are working or enjoying your holidays, whenever you find time could you please let me know how to resolve my error.

**Comment by mxschmitt** [comment]
Most likely `C:\Users\kabdul\AppData\Local\Google\Chrome\User Data\extensions_crx_cache\ndgimibanhlabgdgjcpbbndiehljcpfh_1.ae972fbce9ff8459dede10532d16a7eb9927091e112a9e5c0ffe0a51eb6a7496` doesn't contain the unpacked extension, so Chromium can't load it. Have you tried unpacking the crx file directly? (crx can be unpacked using a zip extract tool)

**Comment by kabdul-incomm** [comment]
> Most likely `C:\Users\kabdul\AppData\Local\Google\Chrome\User Data\extensions_crx_cache\ndgimibanhlabgdgjcpbbndiehljcpfh_1.ae972fbce9ff8459dede10532d16a7eb9927091e112a9e5c0ffe0a51eb6a7496` doesn't contain the unpacked extension, so Chromium can't load it. Have you tried unpacking the crx file directly? (crx can be unpacked using a zip extract tool)

 I forgot to mentioned I already tried with .crx and I get the below error Error Loading Extension
---------------------------
Failed to load extension from: C:\Kaleem\SeleniumHubExtensionFile\NDGIMIBANHLABGDGJCPBBNDIEHLJCPFH_5_1_6_0.crx. Manifest file is missing or unreadable
---------------------------
OK   
---------------------------

![FailedToLoadExtension](https://github.com/microsoft/playwright-dotnet/assets/51454842/d4d77ace-0d3d-46a3-8147-602f052787d6)

**Comment by mxschmitt** [comment]
You need to unpack the crx file:

1. rename the file's extension from crx to zip e.g. foo.zip
2. extract it
3. point this folder to the folder which we use in the code in https://github.com/microsoft/playwright-dotnet/issues/2804#issuecomment-1864290596

**Comment by kabdul-incomm** [comment]
> C:\Users\kabdul\AppData\Local\Google\Chrome\User Data\extensions_crx_cache

I still have the same issue. Attaching screen shot which shows all the extract files are there in the folder 
![AllTheExtractFiles](https://github.com/microsoft/playwright-dotnet/assets/51454842/f3f6985c-5296-4b96-ab12-afff59a5806f)

**Comment by mxschmitt** [comment]
Maybe its no extension?

I'm closing this issue for now, since its not actionable for us. Most likely the folder you are using is not an unpacked Chromium extension. Also make sure that you launch your browser headed, or use headless=new, since extensions are [not usable in a headless browser](https://playwright.dev/docs/chrome-extensions#headless-mode).
