### ISSUE TITLE
[Question] How do I maximize Firefox and Webkit while launching 

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright-dotnet#2808]
I want to maximize Firefox and Webkit while launching.

I'm using below piece of code and it doesn't work for Firefox and Webkit. 

I understand the Args is for chromium only.

`var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
var headless = Convert.ToBoolean(ConfigurationData.GetAppSetting("HeadlessModeEnabled"));

var pageDefaultTimeoutInMs = Timeouts.XXLarge;
var browserType = "webkit";

IBrowser? browser = browserType.ToLowerInvariant() switch
{
    "chromium" => await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
    {
        Headless = headless,
        Args = !headless ? new[]
                           {
                                "--start-maximized"
                           }
                         : null
    }),
    "firefox" => await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions
    {
        Headless = headless,
        Args = !headless ? new[]
        {
            "--start-maximized"
            } : null
    }),
    "webkit" => await playwright.Webkit.LaunchAsync(new BrowserTypeLaunchOptions
    {
        Headless = headless,
        Args = !headless ? new[]
        {
            "--start-maximized"
            } : null
    }),
    _ => throw new Exception($"{browserType} is not supported."),
};
if (!headless)
{
    BrowserContext = await browser.NewContextAsync(new BrowserNewContextOptions() { ViewportSize = ViewportSize.NoViewport });
    _Page = await BrowserContext.NewPageAsync();
}

else
{
     
    _Page = await browser.NewPageAsync();
}
  

_Page.SetDefaultTimeout((float)pageDefaultTimeoutInMs);
return _Page;`

I tried this line and it didn't worked.                 await _Page.EvaluateAsync("resizeTo(window.screen.availWidth, window.screen.availHeight)");

**Comment by mxschmitt** [comment]
This is not possible in Firefox and WebKit as of today.

Folding into https://github.com/microsoft/playwright/issues/4046.
