### ISSUE TITLE
I want to request the result, then judge and return it

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2810]
The following code can request normally, but the response has not been restored. How can the response be restored correctly?

 var response = await route.FetchAsync();
                var jsonStr=await  response.TextAsync();
                
                var json = JObject.Parse(jsonStr);
                if (json?["loginFailed"]?.Value<string>()=="true")
                {
                    tcs.SetResult(null);
                    await page.UnrouteAsync("**/*");
                }
               await route.FulfillAsync(new() { Response = response, BodyBytes = await response.BodyAsync()});

**Comment by mxschmitt** [comment]
What do you mean with "response has not been restored"?

There is no need of doing this:

    await route.FulfillAsync(new() { Response = response, BodyBytes = await response.BodyAsync()});

this is enough:

    await route.FulfillAsync(new() { Response = response });

**Comment by bbhxwl** [comment]
> What do you mean with "response has not been restored"?
> 
> There is no need of doing this:
> 
> ```
> await route.FulfillAsync(new() { Response = response, BodyBytes = await response.BodyAsync()});
> ```
> 
> this is enough, we then automatically use the right body from the response you are passing:
> 
> ```
> await route.FulfillAsync(new() { Response = response });
> ```

Is it related to me intercepting a certain message and executing it? Will this make all requests invalid?


page.UnrouteAsync("**/*");

**Comment by mxschmitt** [comment]
`page.UnrouteAsync("**/*");` will remove all the handlers which were registered previously with `"**/*"`, so future requests don't get intercepted again.

What do you mean with "all requests invalid"? Doing `page.UnrouteAsync("**/*");` will not abort the requests, the browser will execute them normally then. If you want to abort them, see [here](https://playwright.dev/dotnet/docs/network#abort-requests).

**Comment by mxschmitt** [comment]
I'll close it in the meantime and per above. Feel free to re-file if you still experience issues.
