### ISSUE TITLE
[BUG]/app/.playwright/node/linux-x64/playwright.sh' with working directory '/app'. Permission denied 

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2812]
![image](https://github.com/microsoft/playwright-dotnet/assets/26525599/2d2267e4-6ca3-422d-beb7-c5c623277d93)

**Comment by bbhxwl** [comment]
```
FROM mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MicroServicesAutoSyncJinMin/MicroServicesAutoSyncJinMin.csproj", "MicroServicesAutoSyncJinMin/"]
RUN dotnet restore "MicroServicesAutoSyncJinMin/MicroServicesAutoSyncJinMin.csproj"
COPY . .
WORKDIR "/src/MicroServicesAutoSyncJinMin"
RUN dotnet build "MicroServicesAutoSyncJinMin.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "MicroServicesAutoSyncJinMin.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN chown -R $APP_UID /app
ENTRYPOINT ["dotnet", "MicroServicesAutoSyncJinMin.dll"]

```

**Comment by mxschmitt** [comment]
Sounds like your user has no permissions of running your `RUN chown -R $APP_UID /app` line. 

You could do `USER $APP_UID` after that instead of in line 2 and then it should work.

**Comment by bbhxwl** [comment]
> Sounds like your user has no permissions of running your `RUN chown -R $APP_UID /app` line.
> 
> You could do `USER $APP_UID` after that instead of in line 2 and then it should work.

It seems that there is no such command, is this related to my use of Windows system?

I can't run without using Docker, the Linux environment is too difficult.


![image](https://github.com/microsoft/playwright-dotnet/assets/26525599/e1267428-1d4a-4e86-b659-7705e9a2da14)

![image](https://github.com/microsoft/playwright-dotnet/assets/26525599/6166e06d-ee5c-49bb-8d6f-99a297d9868a)

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2814.
