### ISSUE TITLE
[Question] How to investigate Azure DevOps pipeline where Playwright tests (sporadically) never end?

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright-dotnet#2813]
I run Playwright with MSTest in an Azure Devops pipeline.
About 1 in 15 times, the pipeline fails due to timeout. When checking the logs of the test step, it appears only 12 out of 15 tests are finished, so there must be a test that is either stuck or never started. (But the other 14 times, all tests run until finished.)

As Playwright tests automatically have timeouts, how can I find out what is wrong (either in the pipeline, or possibly in my test code)?
I don't believe the .trx file is attached because the test step does not finish.

![image](https://github.com/microsoft/playwright-dotnet/assets/18096566/450d802b-a703-4a55-88f2-b2acce7b2242)

**Comment by PandaMagnus** [comment]
Are you doing any sort of setup or teardown between tests? Is it the same 12 tests completing every time? If there are 3 that always don't run, I'd say to add prolific logging to those (or to test setup/teardown) to see if you can isolate where the hang is.

Given Playwright isn't throwing it's timeout error, it's hard to know without more information.

**Comment by Exoow** [comment]
@PandaMagnus The problem with more logging is: if the .TRX file isn't saved at the end (because there is no end), how do I access  any logs (which are test attachments)?

**Comment by PandaMagnus** [comment]
@Exoow If you use MSTest's TestContext.WriteLine it will write out to the pipeline window. So E.G. I have a test (non-Playwright, but using TestContext.WriteLine in MSTest,) that iterates over several items and compares them to an oracle value has a writeout like this in the pipeline logs:

![writeout](https://github.com/microsoft/playwright-dotnet/assets/23488367/9ed9627b-8477-49f5-a7db-1569cd689f92)

That should help. You won't get the same diagnostics you get in the .trx file, which means you'll have to do some guess-and-check, but if you can narrow the hang down to one of three tests, hopefully that won't be too burdensome.

**Comment by mxschmitt** [comment]
@Exoow We unfortunately need a repro in order to act on it. You can try setting the `DEBUG=pw:api` env var, which will give you a bit more output - but not sure if thats helpful. I would try to narrow it down first. Maybe you forgot a missing await, forgot to close a page or wrote some racy test which will end up waiting infinite. Its hard to give advice without seeing the actual code / having a better repro.

I see that one test is failing, is it always hanging when this specific test is failing? Maybe the test is the problem in this case?

**Comment by Exoow** [comment]
@mxschmitt Yes, I will try `TestContext.WriteLine` as suggested to hopefully get immediate feedback even without the .trx file.

Considering the tests usually complete (doesn't matter pass or fail) it's definitely not a missing `await` or such. But I'll investigate with logging and post a new issue if needed.
