### ISSUE TITLE
[BUG] Getting storage state with UTF-16 data fails

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright-dotnet#2819]
### System info
- Playwright Version: v1.40
- Operating System: Windows 11
- Browser: Chromium

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
await using var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
await page.GotoAsync("https://www.close.com/");
await page.WaitForLoadStateAsync(LoadState.Load);
await context.StorageStateAsync();
```

**Steps**
- [Run the test]

**Expected**

The storage state is fetched successfully.

**Actual**

```
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.origins[0].localStorage[1].value | LineNumber: 0 | BytePositionInLine: 4436.
 ---> System.InvalidOperationException: Cannot read incomplete UTF-16 JSON text as string with missing low surrogate.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadIncompleteUTF16()
```

The issue appears related to #2748, except that my problem is with storage state.

**Comment by mxschmitt** [comment]
I tried to reproduce on Windows and macOS with .NET 8, but was not able to. In the snippet you provided was a typo with the goto method: `goToAsync` -> `GotoAsync`.

Does it repro with exactly the snippet from above?

**Comment by shravan2x** [comment]
Hi @mxschmitt sorry for the trouble, I've updated the snippet now (adding a page wait).

**Comment by mxschmitt** [comment]
I was able to repro, thanks!
