### ISSUE TITLE
Can not run JavaScript via Page.EvaluateAsync

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright-dotnet#2835]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Windows 10]
- Browser: [MS Edge version 120]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
        public async Task<string> 
```
Call_JS_Code(string url1, string user1)
        {
            // Get the cookies for the user
            {
                Debug.Print (All_Cookies);
                // Define the JavaScript code
                string script = @"
            new Promise((resolve, reject) => {
                var xhr = new XMLHttpRequest();
                xhr.open('GET', '" + url1 + @"', true);
                xhr.setRequestHeader('Cookie', '" + All_Cookies + @"');
                xhr.onreadystatechange = function () {
                    if (xhr.readyState == 4 && xhr.status == 200) {
                        resolve(xhr.responseText);
                    }
                };
                xhr.onerror = reject;
                xhr.send();
            });
        ";
                // Run the JavaScript code
                string result = await _Page.EvaluateAsync<string>(script);
                return result;
        }
```

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
await using var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]
But what I really want to write some C# code with playwright to store a cookies and headers, around 60 cookies and about 10 headers, and run the first JavaScript from WinForms project.  It should run XHR JavaScript get request and return the fetched data

**Actual**
I got run time errors: 
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Reflection\MethodBaseInvoker.cs:line 125
   at System.Delegate.DynamicInvokeImpl(Object[] args) in System\Delegate.cs:line 55
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 154
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Threading\ExecutionContext.cs:line 154
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   at Windows.Win32.PInvoke.DispatchMessage(MSG* lpMsg)
   at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at PlaywrightJSBalanceForm.Program.Main() in D:\GlaxyBet\1Xbit\PlaywrightJSBalanceForm\PlaywrightJSBalanceForm\Program.cs:line 14

  This exception was originally thrown at this call stack:
    Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync<T>(Microsoft.Playwright.Transport.ChannelOwner, string, System.Collections.Generic.Dictionary<string, object>, bool) in Connection.cs
    Microsoft.Playwright.Transport.Connection.WrapApiCallAsync<T>(System.Func<System.Threading.Tasks.Task<T>>, bool) in Connection.cs
    Microsoft.Playwright.Core.Frame.EvaluateAsync<T>(string, object) in Frame.cs
    PlaywrightJSBalanceForm.Form1.Call_JS_Code(string, string) in Form1.cs
    PlaywrightJSBalanceForm.Form1.BTNBalance_Click(object, System.EventArgs) in Form1.cs
    System.Threading.Tasks.Task.ThrowAsync.AnonymousMethod__128_0(object) in Task.cs
    System.Reflection.MethodBaseInvoker.InvokeWithOneArg(object, System.Reflection.BindingFlags, System.Reflection.Binder, object[], System.Globalization.CultureInfo) in MethodBaseInvoker.cs

Inner Exception 1:
PlaywrightException: Execution context was destroyed, most likely because of a navigation.

[Describe actual behavior]

More explanation what I am doing now: 
I can do the following: I launch MS Edge browser to visit: https://www.bing.com/
Then open developer tools, in the console tab, I can write the following JavaScript:
var xhr = new XMLHttpRequest();
xhr.open('GET', 'https://www.bing.com/search?q=playwright', true);
xhr.onreadystatechange = function () {
    if (xhr.readyState == 4 && xhr.status == 200) {
        console.log(xhr.responseText);
    }
};
xhr.send();

But what I really want to write some C# code with playwright to store a cookies and headers, around 60 cookies and about 10 headers, and run the first JavaScript from WinForms project.  
The All_Cookies are a long string containing many cookies name and values, like this: 
is_rtl=1; v3fr=2; lng=fr; flaglng=fr; view=0; tz=2; _gid=GA1.2.1917113579.1705522091; _ym_uid=1705522091738494561; _ym_d=1705522091; __adm_tid=v1.0.13084392008.12389340447; sh.session.id=2d5dff83-853c-40aa-aa8a; etc...
All those cookies can only be obtained after I login to one web page, and the JavaScript XHR requests need all those cookies to get some data.  After I login to web site, I can open developer tool and find many HTTP GET or post request, as long as I have set the correct cookies and header, the JavaScript will usually work; but from testing in MS Edge console tab in DevTools; it seems, the console doesn’t recognize resolve or reject or even xhr.onerror; but it recognize xhr.send().
But I can not run this JavaScript, when I run my C# code in WinForm project, I always got this error: 
I have to use JavaScript XHR request, because in C# httpclient request, cookies from some domain names are not allowed, as those domain name start with ”.”; like ”.1xbit.com”; but only those domain name like this works: "1xbit.com".  But from some HAR file, I can see all the JavaScript XHR requests used about 1/3 of cookies whose domain name start with ”.”.
Any suggestion on how can I make the _Page.EvaluateAsync works?
By the way, I tried to use the discord channel to report the issue, but I was not allowed to speak!
![PlaywrightCallJSNOK](https://github.com/microsoft/playwright-dotnet/assets/45263518/c3667e21-302f-4113-800e-743c36ac5f90)

**Comment by mxschmitt** [comment]
This issue is not following the issue template, hence I'm closing it for now. If you have a reduced test case, which we can easily run locally e.g. a small script with expected / actual, we can take a look. Thanks for your understanding and feel free to re-file.

**Comment by ToshanP** [comment]
I am having the same issue. Below code use to work on v1.37 but after upgrading to 1.41 it returns wrong locale.

var cultureName = Page.EvaluateAsync<string>(@"() => {
        return window.navigator.languages ? window.navigator.languages[0] : window.navigator.userLanguage || window.navigator.language || navigator.language || navigator.userLanguage || navigator.browserLanguage || navigator.systemLanguage || '';
    }").Result;

1.37 use to return the correct browser culture (en-GB), after upgrading it always returns en-US

Regards

Toshan

**Comment by mxschmitt** [comment]
Looks like a different issue, I recommend filing a new issue.
