### ISSUE TITLE
[BUG] WaitForUrl instability

### ISSUE THREAD

**Issue by mathiasi** [microsoft/playwright-dotnet#2839]
### System info
- Playwright Version: 1.40.0
- Operating System: Ubuntu
- Browser: Chromium
- Other info:

### Source code
Internal system so can't provide source code with reproducible example.

We are using Playwright dotnet to orchestrate tests of an Angular SPA. We have seen cases where it appears that WaitForUrl  is not reliable - sometimes it works and sometimes it does not. I have provided a screenshot where we wait for a URL but judging by the trace, the condition is met but it fails with a timeout. We are seeing `waiting for navigation until "Load"` in the log and I wonder if it is related to the fact it is a SPA.  The URL updates but perhaps the Load event is not fired at that time. 
I'm hoping someone has any idea or can give some input as to whether or not WaitForUrl is even intended to be used with a SPA.

![WaitForUrl](https://github.com/microsoft/playwright-dotnet/assets/2315801/1b3f8dc3-1824-4d8e-9bd7-2b44498f94a3)

**Comment by Exoow** [comment]
You forgot to put `await` before the method call. :)

**Comment by mathiasi** [comment]
Ah I’m sorry it was split for debugging purposes but it is awaited on the next line ☺️

**Comment by Exoow** [comment]
But your code fails on line 73 and you're showing line 51.

**Comment by feiyun0112** [comment]
Maybe you can try the `RunAndWaitForResponseAsync` method

[https://playwright.dev/dotnet/docs/api/class-page#page-wait-for-response](https://playwright.dev/dotnet/docs/api/class-page#page-wait-for-response)

**Comment by mathiasi** [comment]
> But your code fails on line 73 and you're showing line 51.

I believe that's the inner workings of Playwright. This is the stack trace I'm seeing in the output:
```
[at Microsoft.Playwright.Core.Waiter.WaitForPromiseAsync[T](Task`1 task, Action dispose) in /_/src/Playwright/Core/Waiter.cs:line 228]
[at Microsoft.Playwright.Core.Frame.WaitForNavigationInternalAsync(Waiter waiter, String url, Func`2 urlFunc, Regex urlRegex, String urlString, Nullable`1 waitUntil) in /_/src/Playwright/Core/Frame.cs:line 271]
[at Microsoft.Playwright.Core.Frame.RunAndWaitForNavigationAsync(Func`1 action, FrameRunAndWaitForNavigationOptions options) in /_/src/Playwright/Core/Frame.cs:line 239]
[at E2E.UI.Test.Pages.BasePages.PropertiesPage.ClickCreateAndPublishButton(String comment, Boolean expectValidationErrorForCommentField) in /home/vsts/work/1/s/services/E2E/E2E.UI.Test/Pages/BasePages/PropertiesPage.cs:line 52]
```
and line 52 is where the task is awaited.

**Comment by mathiasi** [comment]
> Maybe you can try the `RunAndWaitForResponseAsync` method

I would like to but I'm interested in the URL where it redirects as it will contain a GUID for a newly created entity. Ideally I would like to use RunAndWaitForResponseAsync and capture the GUID in the response but it is part of the body and I can't access that in RunAndWaitForResponseAsync since it only supports synchronous operations (so can't use IResponse.BodyAsync).

**Comment by mxschmitt** [comment]
Would it be possible to provide us a reproduction for the issue you are encountering? Based on the information above it could be caused by a lot of core components Playwrights is using. Having a reproduction is necessary for us to debug this issue further, thanks for your understanding!

**Comment by mathiasi** [comment]
Unfortunately I don't have a reproduceable example. I did however seem to find a workaround. If I start waiting for the URL before I do the action (click a button) then it seems to be more reliable (at least for now). So I moved line 51 to line 40 and kept the await of the task on line 52.
