### ISSUE TITLE
[Feature] Allow proxy for ConnectAsync and ConnectOverCdpAsync

### ISSUE THREAD

**Issue by Refreshmant** [microsoft/playwright-dotnet#2850]
My employer (an enterprise organization) requires most outgoing traffic to use a proxy.
One of our requirements is to connect to an existing browser that hosted outside our network. (i.e. BrowserStack)

Currently it's not possible to configure a proxy when using the [BrowserType.ConnectAsync](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect) and [BrowserType.ConnectOverCdpAsync](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect-over-cdp) methods.
A workaround is available when using node by using a npm package to configure the proxy, but I haven’t found a similar solution for the .net version.

I’ve also found similar issues but these don’t seem to apply to my case.
- [Unable to pass Proxy over ConnectAsync](https://github.com/microsoft/playwright-dotnet/issues/2766)
- [How to use proxy with ConnectOverCDPAsync](https://github.com/microsoft/playwright-dotnet/issues/2167)

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/26985.
