### ISSUE TITLE
[Feature]: Port Android Support To .NET

### ISSUE THREAD

**Issue by Xen0byte** [microsoft/playwright-dotnet#2862]
### 🚀 Feature Request

This is possible on the TS version and it would be usefull to the .NET peeps as well: https://playwright.dev/docs/next/api/class-android.

### Example

```csharp
await Android.Connect(wsEndpoint);
await Android.Connect(wsEndpoint, options);

// ... etc.
```

### Motivation

It should be possible to test mobile browsers with Playwright as well. I am aware that iOS is currently unsupported (hopefully this will be added soon), but support for Android should be implemented on the .NET side too.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/1178

**Comment by mxschmitt** [comment]
As per https://github.com/microsoft/playwright-dotnet/issues/1178 the feature request is still open.
