### ISSUE TITLE
[Docs]: Clarification on best practice for context usage

### ISSUE THREAD

**Issue by thatstatsguy** [microsoft/playwright-dotnet#2868]
### Page(s)

https://playwright.dev/dotnet/docs/browser-contexts#multiple-contexts-in-a-single-test
https://playwright.dev/dotnet/docs/browser-contexts#how-playwright-achieves-test-isolation

### Description

Hi there. Hoping to get clarification on best practice when using contexts in C#.
In the two links below, the way in which contexts are generated are slightly different i.e.

In the first link the using statement is not used in 
```
var context = await browser.NewContextAsync();
```

but in the second link it is
```
await using var userContext = await browser.NewContextAsync();
```
https://playwright.dev/dotnet/docs/browser-contexts#how-playwright-achieves-test-isolation
https://playwright.dev/dotnet/docs/browser-contexts#multiple-contexts-in-a-single-test

I'd like to understand if there's a reason for the difference and if there are any caveats one needs to consider when not using it. Obviously using `using` disposes of the object instance once out of scope, but curious to know if there's more behind it

Cheers

**Comment by thatstatsguy** [comment]
To add to this - what led me to this page was that I was getting warnings in Rider that several node.exe instances were dangling and asked whether I wanted to kill off the processes. Similarly in azure piplines, I'm seeing a scenario where the pipeline just hangs for no apparent reason when reaching a certain point - the second point may be unrelated, but thought it worth mentioning

**Comment by mxschmitt** [comment]
This highly depends on where you are using the context. Using with Playwright is equal of calling [.Close()](https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-close).

Depending on the use-case using might make sense or not, if you pass it around into different functions, dispose the browser afterwards anyways etc. So there is unfortunately not a clear recommendation for this.
