### ISSUE TITLE
Test cases not running after upgrading to 1.42.0 in Azure DevOps

### ISSUE THREAD

**Issue by erenkocyigit** [microsoft/playwright-dotnet#2891]
After upgrading Playwright from version 1.40.0 to 1.42.0, my test cases are no longer running in Azure DevOps. No error codes are displayed, but the test suite simply hangs and does not execute any of the tests.

In my local everything is working as expected

I have checked the Playwright documentation and release notes for any breaking changes between 1.40.0 and 1.42.0, but I could not find anything that seems to be relevant to this issue.

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="coverlet.collector" Version="3.2.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Docker.DotNet" Version="3.125.12" />
      <PackageReference Include="JetBrains.Annotations" Version="2022.3.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
      <PackageReference Include="Microsoft.Playwright" Version="1.42.0" />
      <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.42.0" />
      <PackageReference Include="NUnit.Analyzers" Version="3.5.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Polly" Version="7.2.3" />
      <PackageReference Include="SpecFlow" Version="3.9.74" />
      <PackageReference Include="SpecFlow.Autofac" Version="3.9.74" />
      <PackageReference Include="SpecFlow.Plus.LivingDocPlugin" Version="3.9.57" />
      <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
      <PackageReference Include="SpecFlow.xUnit" Version="3.9.74" />
      <PackageReference Include="xunit" Version="2.7.0" />
      <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>

    </ItemGroup>

    <ItemGroup>
      <None Remove="specflow.json" />
      <Content Include="specflow.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="appsettings.json" />
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="TestScenarios\Features\ApiTokens.feature.cs">
        <DependentUpon>ApiTokens.feature</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>

Additional Information:

Added test output. The output shows that the tests are started and one test file is found, but it hangs without any errors or test results.

Test Output: (1.42.0 version) _TIME OUT_ **FAILED**

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.7+8f2703126a (64-bit .NET 7.0.10)
[xUnit.net 00:00:00.08]   Discovering: Manager.UITests.PW
[xUnit.net 00:00:00.16]   Discovered:  Manager.UITests.PW
[xUnit.net 00:00:00.16]   Starting:    Manager.UITests.PW
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\LivingDoc.SpecFlowPlugin.dll
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\SpecFlow.Autofac.SpecFlowPlugin.dll
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\TechTalk.SpecFlow.xUnit.SpecFlowPlugin.dll
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\Manager.UITests.PW.dll
##[error]The operation was canceled.
```

Test Output: (1.40.0 version) **PASSED**

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.7+8f2703126a (64-bit .NET 7.0.10)
[xUnit.net 00:00:00.09]   Discovering: Manager.UITests.PW
[xUnit.net 00:00:00.18]   Discovered:  Manager.UITests.PW
[xUnit.net 00:00:00.18]   Starting:    Manager.UITests.PW
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\LivingDoc.SpecFlowPlugin.dll
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\SpecFlow.Autofac.SpecFlowPlugin.dll
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\TechTalk.SpecFlow.xUnit.SpecFlowPlugin.dll
-> Loading plugin C:\Users\bcknd-win-bld-agt\buildAgents\agent1\_work\8\s\tests\Manager.UITests.PW\bin\Debug\net7.0\Manager.UITests.PW.dll
-> Using specflow.json
  Passed Hint when regenerating Channel Access [11 s]
  Passed Regenerate PIN Code [10 s]
  Passed Matching stereo input sources(leftInput: "Analog 1 with gain (In 1)", rightInput: "Analog 2 with gain (In 2)", exampleTags: []) [9 s]
  Passed....
```

Possible Causes:
An error is occurring during the tests but no error message is displayed.
There is an issue with a plugin or test library.

I would appreciate any help in diagnosing and resolving this issue. I am happy to provide any additional information that may be helpful.

**Comment by yury-s** [comment]
From the error log it appears to be failing outside of playwright while loading some plugins.

> In my local everything is working as expected

Then it has to do with your environment. Unfortunately we can't help much without a repro. Feel free to file a new bug if you have a reproduction.
