### ISSUE TITLE
[Bug]: FillAsync broke between1.41.2 and 1.42.0

### ISSUE THREAD

**Issue by mpelley** [microsoft/playwright-dotnet#2892]
### Version

1.42.0

### Steps to reproduce

The web page I am testing has an element whose ancestor has `contenteditable="true"`.  In previous versions of Playwright up to 1.41.2, I was able to use the `FillAsync()` to set some text into the element.  But version1.42.0 does not set the text.  It does not throw an exception saying it can't set it.  If the element has some text, it will be successfully replaced, but if it has no content, then the desired text is not entered.

### Expected behavior

I expect `FillAsync()` to set the text in the element.

### Actual behavior

The text in the element is not set.

### Environment

```Text
- Operating System: Windows 10
- CPU: Intel
- Browser: Chromium
- .NET Version: Net 6.0
- Other info:
```

**Comment by mxschmitt** [comment]
Would it be possible to share a reproduction which we can run locally? This is essential for us in order to look into issues like this.

**Comment by mpelley** [comment]
I don't think so.  You need an account on one of our systems, which are time-consuming and hard to get.

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
