### ISSUE TITLE
[Bug]: `IVideo.DeleteAsync()` hangs

### ISSUE THREAD

**Issue by thomhurst** [microsoft/playwright-dotnet#2906]
### Version

1.42.0

### Steps to reproduce

I raised a similar issue before. It looks like `PathAsync` works, but `DeleteAsync` hangs.

I believe it only occurs when the page has not been interacted with, which can happen in our test suite, as we spawn a new browser in a SetUp method, but then the test might execute some logic to realise it doesn't need to run on the current environment, and then the browser closes without any other interaction.

This should be able to replicate it:

```csharp
var pw = await Playwright.CreateAsync();

var browser = await pw.Chromium.LaunchAsync();

var context = await browser.NewContextAsync(new BrowserNewContextOptions
{
    RecordVideoDir = Environment.CurrentDirectory
});

var page = await context.NewPageAsync();

await page.Video!.DeleteAsync();

Console.WriteLine("Finished");
```

### Expected behavior

Video file deletes

### Actual behavior

.NET process hangs indefinitely

### Environment

```Text
.NET 6/7/8

Windows + Linux
```

**Comment by mxschmitt** [comment]
Video.DeleteAsync [will wait](https://playwright.dev/docs/api/class-video#video-delete) until the video processing is done. It's done when the page has been closed, so doing the following works for me:

```csharp
var pw = await Playwright.CreateAsync();

var browser = await pw.Chromium.LaunchAsync();

var context = await browser.NewContextAsync(new BrowserNewContextOptions
{
    RecordVideoDir = Environment.CurrentDirectory
});

var page = await context.NewPageAsync();
await context.CloseAsync();
await page.Video!.DeleteAsync();

Console.WriteLine("Finished");
```

**Comment by thomhurst** [comment]
Ah my bad. Thanks!
