### ISSUE TITLE
[Bug]: `NewContextAsync` on v1.43.0 is not firing up Chromium in Incognito mode

### ISSUE THREAD

**Issue by konarx** [microsoft/playwright-dotnet#2907]
### Version

1.43.0

### Steps to reproduce

Today I updated the NuGet package and (as always after an update) I executed the `playwright.ps1`. But now Chromium is starting in normal mode, not incognito.
I reverted the update, ran the `playwright.ps1` with uninstall, and then again installed with the previous version (v1.42.0), and the Chromium started as expected in incognito mode.
Has something changed in Playwright or in Chromium version? Is there a config that I miss?
As I can see in the [doc](https://playwright.dev/dotnet/docs/api/class-browsercontext), I do not do anything different than
await browser.NewContextAsync();.

### Expected behavior

Chromium should start as expected in incognito mode

### Actual behavior

Chromium starts in normal window mode

### Environment

```Text
- Operating System: Windows 10
- CPU: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
- Browser: Chromium
- .NET Version (TFM): net6.0
```

**Comment by mxschmitt** [comment]
It looks like Chromium has changed the UI, this should not have any affects on the tests. The browser contexts are still in-memory browser profiles which are isolated from each other.

Do you experience any change in the behaviour? Or is it just about that it doesn't say "Incognito" anymore?

**Comment by konarx** [comment]
@mxschmitt I have a scenario with a user who logs in using SSO that is supposed to fail when using incognito Chrome window, but now it does not. That's how I found it, not from the UI label. How sure are we that nothing has changed "under the hood"?

**Comment by mxschmitt** [comment]
There is from my knowledge no notion of Incognito inside the web / JavaScript. How do you check inside your application for it?

The underlying behaviour should not have changed - so curious how you detect it. That would help us to investigate.

**Comment by mxschmitt** [comment]
When checking via https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled it was also `Yes` in `v1.42`. So I don't see a behaviour change. The settings also look the same for me in both versions.

Do you get a difference on your environment?

The browser contexts Playwright has created always "looked" like incognito tabs UI wise, but there were normal browser contexts. So this UI change they are doing is eliminating this confusion.

**Comment by konarx** [comment]
Ok, it looks very strange indeed. I'll have to dive deeper along with our front-end engineers, so let's close this issue for now and if I have any further info I will reference it.
Thank you Max :)
