### ISSUE TITLE
[Bug]: Tests in chromium based browsers halting on chrome-error://chromewebdata/ 

### ISSUE THREAD

**Issue by jaspervanderwoude** [microsoft/playwright-dotnet#2908]
### Version

1.42.0

### Steps to reproduce

Reproduction repository not possible as issue occurs on private URL's (not open from internet). Problem occurs on default `await await Page.GotoAsync("someurl");` call when one of the redirects fails for a short period of time and then succeeds (see behavior below). 

### Expected behavior

When navigating to the url of our app manually in a playwright chromium browser some redirects occur, eventually leading to a login screen. One of these redirects sort of 'fails', for a split second, the browser shortly shows 'This site cannot be reached' (ERR_INVALID_URL). DevTools showing status code ='(failed)' for this request. Milliseconds later this redirect is performed again successfully leading to the login screen. 

Expected behavior when running Playwright tests is the same, login screen should appear (eventually) and app should login.

### Actual behavior

Actual behavior is the test not reaching the login screen and throwing exception because an element on the page cannot be found. Happens headed and headless, but only on chromium based browsers (no problem in Firefox and Webkit). Caused by chromium (under water?) navigating to a `chrome-error://chromewebdata/` page and stopping there? See logging below. Second logging is from a test monitoring http traffic which suffers from the same problem. 

This page / error is not visible when navigating manually in the chromium browser and the ERR_INVALID_URL message is only visible shortly and not the end result of the navigation. 

How to prevent Playwright to stop / throw exception when `chrome-error://chromewebdata/` is encountered as this may be temporary and not the end result of the navigation. Can this be ignored somehow? 

```
2024-04-11T01:35:38.986Z pw:api navigating to "https://<myprivateurl>", waiting until "load"
2024-04-11T01:35:40.900Z pw:api   "commit" event fired
2024-04-11T01:35:40.901Z pw:api   navigated to "https://<redirecturl>"
2024-04-11T01:35:42.362Z pw:api   "domcontentloaded" event fired
2024-04-11T01:35:42.899Z pw:api   "load" event fired
2024-04-11T01:35:42.922Z pw:api waiting for Locator("#userNameInput")
2024-04-11T01:35:43.327Z pw:api   navigated to "<myprivateurlagain>"
2024-04-11T01:35:44.738Z pw:api   "commit" event fired
2024-04-11T01:35:44.738Z pw:api   navigated to "chrome-error://chromewebdata/"
2024-04-11T01:35:44.760Z pw:api   "domcontentloaded" event fired
2024-04-11T01:35:44.807Z pw:api   "load" event fired
2024-04-11T01:35:45.238Z pw:api   "networkidle" event fired
2024-04-11T01:36:13.070Z pw:api taking page screenshot
```

```
Microsoft.Playwright.PlaywrightException : Page URL expected to match regex '.eidas..'
But was: 'chrome-error://chromewebdata/'
Call log:
PageAssertions.ToHaveURLAsync with timeout 10000ms
waiting for Locator(":root")
locator resolved to <html>…</html>
unexpected value "chrome-error://chromewebdata/"
```

### Environment

```Text
- Operating System: [Windows Server 2016 Standard]
- CPU: [Intel Xeon]
- Browser: [Chromium]
- .NET Version (TFM): [net8.0]
- Other info: In private corporate (firewalled) network
```

**Comment by mxschmitt** [comment]
A similar issue was fixed in v1.43, could you try upgrading?

**Comment by jaspervanderwoude** [comment]
O, really? 1.43 was released on april 7th I see  now, I encountered this issue on that same date and been debugging since ; -))))

I will try thanx!

**Comment by jaspervanderwoude** [comment]
Seems to work at first glance! Great! Will do some more testing tomorrow.

**Comment by jaspervanderwoude** [comment]
Everything working as expected now, thanks again!
