### ISSUE TITLE
[Bug]: Custom/Unknown CDP events cause playwright to close

### ISSUE THREAD

**Issue by joelgriffith** [microsoft/playwright-dotnet#2912]
### Version

1.43.0

### Steps to reproduce

Difficult to reproduce as it involves creating a custom server that intercepts WebSocket messages and emits custom events in the CDP protocol. Happy to set up something for reproducing as we have our own custom CDP events.

### Expected behavior

Unknown CDP events should be allowed to propagate through to an event handler if there is one, and ignored if not. The connection shouldn't be closed when unknown CDP events are raised.

### Actual behavior

Any unknown CDP events cause playwright to close the connection when connecting over CDP.

### Additional context

We override the CDP event space with custom ones for browserless: https://docs.browserless.io/open-api#section/The-Browserless-CDP-API, and have noticed that most playwright libraries work flawlessy with this, however, the .NET variation closes anytime an unknown CDP message is sent (even when there's an event handler for it). I'm happy to go over this in further detail or provide temporary environments where this behavior is exhibited. Happy to also to try and provide a PR as well if possible.

### Environment

```Text
- Operating System: [macOS 14.4.1]
- CPU: [arm64]
- Browser: [Chromium]
- .NET Version (TFM): [net8.0]
```

**Comment by mxschmitt** [comment]
Do you know where it crashes?

Feel free to send me a repro, either here if public is fine or on Discord, then we can take a look.

**Comment by joelgriffith** [comment]
@mxschmitt I'll work on a reproduction script for you and get established in your Discord group, I don't necessarily think it's a full-on crash but something is closing the underlying WebSocket connection, rather. Thanks for the response!

**Comment by joelgriffith** [comment]
Is there a preferred person or channel to start? I'm in that discord channel
