### ISSUE TITLE
[Bug]: Driver not found: /var/pkg-cache/project/project/instances/.playwright/node/linux-x64/node

### ISSUE THREAD

**Issue by bhanupalsingh** [microsoft/playwright-dotnet#2915]
### Version

1.42.0

### Steps to reproduce

  var playwright = await Playwright.CreateAsync().Result; Throws exception as 

Driver not found: /var/pkg-cache/project/project/instances/.playwright/node/linux-x64/node . 

I was using playwright dotnet 1.15.0 for long time after updating to 1.42.0 with same set of code throwing above exception . 

### Expected behavior

Expected behavior is to get playwright instance.  

### Actual behavior

Throw exception as Driver not found: /var/pkg-cache/project/project/instances/.playwright/node/linux-x64/node

### Environment

```Text
- Operating System: [debian 11 bullseye] with additional installed system dependencies
- CPU: [arm64]
- Browser: [Chromium]
- .NET Version (TFM): [net8.0]
- Other info:
```

**Comment by mxschmitt** [comment]
Would it be possible to share a reproduction with us? It's essential for us in order to triage issues like this.

**Comment by bhanupalsingh** [comment]
Issue Description:

When deploying a C# project with Playwright 1.42.0 in a Linux-based Docker container, an error occurs. 

Resolution Steps:

The issue was resolved by including the Runtime Identifier <RuntimeIdentifier>linux-x64</RuntimeIdentifier> in the csproj file.
