### ISSUE TITLE
[Bug]: GetByLable/GetByRole and FillAsync is filling text in wrong text box

### ISSUE THREAD

**Issue by dotnetmaniac** [microsoft/playwright-dotnet#2919]
### Version

1.40.0

### Steps to reproduce

I'm trying to write textbox in 6th column of a table:
await Page.GetByRole(AriaRole.Row).GetByRole(AriaRole.Cell).Nth(5).GetByRole(AriaRole.Textbox).FillAsync("FUM");

When I check the trace it has found the right control:
![image](https://github.com/microsoft/playwright-dotnet/assets/99637339/38894c8d-02bc-405d-a950-3e34aea78449)
![image](https://github.com/microsoft/playwright-dotnet/assets/99637339/afaea408-de22-4ef4-935b-359e5f8e3b9a)

However, after this step, when I see snapshot in next step it has inserted text in first textbox available in this row:
![image](https://github.com/microsoft/playwright-dotnet/assets/99637339/9d2d345b-1e7d-4230-a2c0-12f53b77f9ff)

This doesn't always happen, happens randomly in test servers (windows VM's with 8GB RAM) and the website is hosted locally on the same VM.

Another similar issue I've faced is:
I have 3 textboxes in a dialog to change password. I try to fill them:
await Page.GetByLabel("Old Password", new() { Exact = true }).FillAsync("test");
await Page.GetByLabel("New Password", new() { Exact = true }).FillAsync("NewPassword");
await Page.GetByLabel("Confirm New Password", new() { Exact = true }).FillAsync("NewPassword");

Old Password: testNewPassword
New Password: 
Confirm New Password: testNewPassword

Even this happens intermittently.

### Expected behavior

I expected to see the right textbox have the value filled in it reliably.

### Actual behavior

It seems to be filling the first textbox available in the page.

### Environment

```Text
- Operating System: Windows
- Browser: Chromium
- .NET Version (TFM): net4.8
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

In the meantime we suggestion Codegen to generate the right locator for you: https://playwright.dev/dotnet/docs/codegen-intro#running-codegen

**Comment by dotnetmaniac** [comment]
I've given you the lines of code that is causing the issue.
There is no network call or JS execution that/s happening in the background is all I can confirm.

I can't share the code as its happening in an enterprise application, and it doesn't always happen, it happens randomly causing failure of test suite execution.
