### ISSUE TITLE
[Bug]: has-text does not work on input fields

### ISSUE THREAD

**Issue by mathiasi** [microsoft/playwright-dotnet#2930]
### Version

1.43.0

### Steps to reproduce

The docs state that when using `:has-text` then when it comes to input fields it will match by the `value` - https://playwright.dev/dotnet/docs/other-locators#:~:text=Input%20elements%20of%20the%20type%20button%20and%20submit%20are%20matched%20by%20their%20value%20instead%20of%20text%20content.%20For%20example%2C%20%3Atext(%22Log%20in%22)%20matches%20%3Cinput%20type%3Dbutton%20value%3D%22Log%20in%22%3E. 

```csharp
using Microsoft.Playwright;
using System;
using System.Threading.Tasks;
        
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
{
    Headless = false,
});
var context = await browser.NewContextAsync();

var page = await context.NewPageAsync();
await page.GotoAsync("https://material.angular.io/components/input/overview");

await page.Locator(":has-text('Sushi')").ClickAsync();
```

### Expected behavior

Field to be found

### Actual behavior

Field was not found

### Environment

```Text
- Operating System: Windows 11
- CPU: Amd64
- Browser: All
- .NET Version (TFM): net6.0
- Other info:
```

**Comment by mxschmitt** [comment]
This only happens if your `<input>` element has `type=button` or `type=submit`. In your case we recommend the following locator:

    await page.GetByPlaceholder("Ex. Pizza").FillAsync("Hello world");

This is e.g. what codegen gives you, you can trigger codegen by calling `await page.PauseAsync();`.

**Comment by mathiasi** [comment]
Ah I see, sorry about that, I missed it.
