### ISSUE TITLE
[Docs]: Contributing guide

### ISSUE THREAD

**Issue by RenderMichael** [microsoft/playwright-dotnet#2932]
### Page(s)

CONTRIBUTING.md

### Description

I am trying to build Playwright from source to diagnose an issue I've been having, and I was stumped for a while. I followed the [prerequisites](https://github.com/microsoft/playwright-dotnet/blob/main/CONTRIBUTING.md#prerequisites) but still I was getting an error for [each driver copy](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Playwright.csproj#L45-L49), with the build telling me the files did not exist.

It wasn't until I noticed [this line](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Playwright.csproj#L56) (not in any build error, but directly in the file) that I ran that command and everything worked!

Could a note to run the following line be added to the `CONTRIBUTING.md` file, just to jumpstart anyone trying to build from source without any real knowledge of internals yet?

```init
dotnet run --project ./src/tools/Playwright.Tooling/Playwright.Tooling.csproj -- download-drivers --basepath .
```

**Comment by mxschmitt** [comment]
This line is getting executed when running `./build.sh --download-driver` so I'm curious why it didn't work on your system.

**Comment by RenderMichael** [comment]
My bad, I should have dug into the .ps file.

Here is what I get when I try to run `--download-driver`:
![image](https://github.com/microsoft/playwright-dotnet/assets/12619902/1b426de8-2257-4f96-9ce3-26161b2f0941)

**Comment by mxschmitt** [comment]
Looks like your drivers are already up to date and no changes needed to the contributing.md?

**Comment by RenderMichael** [comment]
I deleted the `.drivers` folder and tried again, this time they are successfully being downloaded with the `--download-driver`. Looks like there's no action to take after all. Thanks for the time!
