### ISSUE TITLE
[Bug]: Playwright chain of locators  insert double ">"

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [microsoft/playwright-dotnet#2939]
### Version

Latest

### Steps to reproduce

When I used sequence of Locators specified as css selectors, it was generated with double 
“Greater than” signs >> instead of single >
For the following code

    var rowLocator = Page.Locator(“table.booking-table tbody:nth-child(3) tr:nth-child(1)”);
    var cellLocator = rowLocator.Locator($"td.{columnClass}");

The generated locator was `“table.booking-table tbody:nth-child(3) tr:nth-child(1) >> td.booking-time-to-travel”`, which doesn’t work.
I had to concatenate selectors as strings instead of  call chain of locators.

### Expected behavior

Single > should be generated, e.g. `“table.booking-table tbody:nth-child(3) tr:nth-child(1) > td.booking-time-to-travel”` that does work

### Actual behavior

The generated locator was `“table.booking-table tbody:nth-child(3) tr:nth-child(1) >> td.booking-time-to-travel”`, 

### Environment

```Text
- Operating System: [Windows]
- Browser: [All, Chromium, Firefox, WebKit]
- .NET Version (TFM): [net8.0]
- Other info: .Net Playwright
```

**Comment by mxschmitt** [comment]
How do you use the generated locator - do you call `String()` on it?

The `>>`  is the nesting operator when interacting with e.g. Locators and you click etc. It's part of the Playwright Selector syste.

They are not compatible with e.g. `document.querySelectorAll` in the browser - since they contain [many more features](https://playwright.dev/dotnet/docs/locators) which the web does not support out of the box.

**Comment by michael-freidgeim-webjet** [comment]
Thanks @mxschmitt , you are right. I've confirmed that chain of locators is working. 
I probably had some other error in selector, but in debugger it was shown with ">>" which made me think that it is a reason of mismatch.
Both following tests  work the same way:
using Microsoft.Playwright.MSTest;


namespace PlayWright.Tests;

[TestClass]
public class ChainedLocator : PageTest
{
    [TestMethod]
    public async Task SearchCellInRow2Locators()
    {
         await Page.GotoAsync("https://www.w3schools.com/html/html_tables.asp");
        int rowNumber=3;
        int cellNumber = 3;
        var rowLocator = Page.Locator($"table.ws-table-all tbody tr:nth-child({rowNumber+1})");
        var cellLocator = rowLocator.Locator($"td:nth-child({cellNumber})");
        var text=await cellLocator.TextContentAsync();
         Assert.IsTrue(text== "Austria");
    }
    [TestMethod]
    public async Task SearchCellInRowSingleLocator()
    {
        await Page.GotoAsync("https://www.w3schools.com/html/html_tables.asp");
        int rowNumber = 3;
        int cellNumber = 3;
        var cellLocator = Page.Locator($"table.ws-table-all tbody tr:nth-child({rowNumber+1}) td:nth-child({cellNumber})");
        var text = await cellLocator.TextContentAsync();
        Assert.IsTrue(text == "Austria");
    }
}
