### ISSUE TITLE
[Bug]: Screenshot fails due to timeout on certain pages (repro steps included) 

### ISSUE THREAD

**Issue by MattLangCafe** [microsoft/playwright-dotnet#2946]
### Version

1.44.0

### Steps to reproduce - full steps: https://github.com/MattLangCafe/playright-screenshot-bug-repro/tree/main

1. Create an Nunit test project with the following version 
2. `<PackageReference Include="Microsoft.Playwright.NUnit" Version="1.44.0" />`
3. Copy this code to attempt to screenshot example page
```csharp
[SetUp]  public async Task Setup()
        {
            var playwright = await Playwright.CreateAsync();
            var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                SlowMo = 1000,
                Headless = false // -> Use this option to be able to see your test running
            });

            var context = await browser.NewContextAsync();

            //Initialise a page on the browser context.
            var user = await context.NewPageAsync();

            await user.GotoAsync("https://mattlangcafe.github.io/playwright--screenshot-test/");

            await user.ScreenshotAsync();
        }
```
4. Screenshot will time out at any delay on selected page, tried at 30 seconds

### Expected behavior

Screenshot should be saved, this is the case when I replace my github pages url with, eg, google.com

### Actual behavior

Screenshot times out
Error message:

  Message: 
System.TimeoutException : Timeout 30000ms exceeded.
Call log:
  - taking page screenshot
  - waiting for fonts to load...

Trace:
`  Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) line 206
Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) line 532
Page.ScreenshotAsync(PageScreenshotOptions options) line 675
Tests.Setup() line 24
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await(Func`1 invoke)
SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
SetUpTearDownItem.RunSetUp(TestExecutionContext context)
<.ctor>b__0(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)`

### Environment

```shell
System: Windows 11 22631.3593
net8.0
	 <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.44.0" />
	 <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
```

**Comment by mxschmitt** [comment]
its stuck at `waiting for fonts to load..` so merging into https://github.com/microsoft/playwright/issues/28995

**Comment by MattLangCafe** [comment]
Thanks for taking a look. Just to check, how do I set browser environment variables from a dotnet runtime?

**Comment by mxschmitt** [comment]
You set it from the outside before you run your dotnet app.

**Comment by MattLangCafe** [comment]
BrowserTypeLaunchOptions.Env = {PW_TEST_SCREENSHOT_NO_FONTS_READY, 1} would work right?

**Comment by mxschmitt** [comment]
It would not, since it needs to be set for Playwright, not for the browser.

**Comment by MattLangCafe** [comment]
@mxschmitt Ah, okay I understand what you mean. What I mean to ask then, is how do I configure the playwright environment variables when i'm using the nuget package

**Comment by mxschmitt** [comment]
Before you run dotnet test or dotnet run you set this inside your CI pipeline or local pwsh/batch.

**Comment by MattLangCafe** [comment]
Yes, I understand now what you mean, node will pick up the pipeline variable. Thanks for you help
