### ISSUE TITLE
[Regression]: Update to playwright 1.41+ removed playwright.cmd file from bin\Release\net8.0\.playwright\node\win32_x64

### ISSUE THREAD

**Issue by kchambersmtm** [microsoft/playwright-dotnet#2955]
### Last Good Version

1.40

### First Bad Version

1.41

### Steps to reproduce

I am using C#, visual studio 2022, net8.0 and trying to run playwright tests with NUnit.

With Playwright 1.40 and prior there would be a playwright.cmd file created at <project>\bin\Release\net8.0\.playwright\node\win32_x64\playwright.cmd

So I would have a post build event in my csproj file that would install the browsers and not require to manually run the playwright.ps1 install.

Here is my csproj file with the postbuildevent:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.3" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.40.0" />
    <PackageReference Include="NUnit" Version="4.1.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(TargetDir).playwright\node\win32_x64\playwright.cmd install" />
  </Target>

</Project>`

it's not displaying properly so he's a screenshot:
![image](https://github.com/microsoft/playwright-dotnet/assets/174622264/8f2683ef-7c9b-498e-abab-e9a78a720157)

and the playwright file:
![image](https://github.com/microsoft/playwright-dotnet/assets/174622264/db8b2dc4-4c02-4b42-9084-744e190f9682)

### Expected behavior

When I upgraded to playwright 1.41 or 1.44 I expected to have the same playwright.cmd file

### Actual behavior

However the cmd file disappears
![image](https://github.com/microsoft/playwright-dotnet/assets/174622264/37741165-6ee5-4382-ae19-85b0ef35e31a)

Which then causes an error:
>'C:\Dev\<project folders>\bin\Release\net8.0\.playwright\node\win32_x64\playwright.cmd' is not recognized as an internal or external command, operable program or batch file.

If I remove the post build event then it tells me the executable doesn't exist:
![image](https://github.com/microsoft/playwright-dotnet/assets/174622264/d4846121-0f58-437c-95f5-12320e3cada6)

I can run that and then running the tests locally will work, however I'm using Azure Devops to run the tests in an agent and that fails with the same error message saying playwright is not installed and I can't get it to work to be installed in the yaml file. None of the examples I've seen for yaml work for me. Most are expecting you to be using nodejs but I'm using C#.

### Environment

```Text
- Operating System: Windows 11
- CPU: Intel i7
- Browser: Chromium
- .NET Version (TFM): net8.0
- Other info:
```

**Comment by mxschmitt** [comment]
This is expected, playwright.cmd were implementation details which were never documented. We recommend the ps1 file instead.

See / folding into https://github.com/microsoft/playwright-dotnet/issues/2870#issuecomment-1954987054.
