### ISSUE TITLE
Try to run " dotnet add package Microsoft.Playwright.MSTest" getting error : NU1108: Cycle detected.

### ISSUE THREAD

**Issue by hemanshurana** [microsoft/playwright-dotnet#2963]
Getting error message  NU1108: Cycle detected.

While I run the command " dotnet add package Microsoft.Playwright.MSTest"

![Capture1](https://github.com/user-attachments/assets/bd801b02-38be-425c-951f-55880eea78db)

- [ ] I understand

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
