### ISSUE TITLE
[Bug]: PW:API Output Seems To Include Malformed Characters

### ISSUE THREAD

**Issue by Xen0byte** [microsoft/playwright-dotnet#2967]
### Version

1.43.0-beta-1712646596000

### Steps to reproduce

1. Run both UI and API tests with pw:api enabled.
2. Observe the pw:api output.

### Expected behavior

The output should not contain malformed characters.

### Actual behavior

UI
![image](https://github.com/user-attachments/assets/a6aa61fc-ff9a-462d-b113-889cbd63c719)

API
![image](https://github.com/user-attachments/assets/ef0afcba-25ac-4d1b-90d9-b64faf015573)

### Additional context

Maybe there are some bytes missing?

### Environment

```Text
- Operating System: Windows 10.0
- CPU: x64
- Browser: All
- .NET Version (TFM): net8.0
```

**Comment by Xen0byte** [comment]
Observed in the output of both Visual Studio and Azure DevOps pipelines.

**Comment by mxschmitt** [comment]
Are you using NUnit or MSTest?

Would it be possible to share a reproduction with us?

Ideally something which we can run locally where we can observe this.

**Comment by Xen0byte** [comment]
Hi @mxschmitt, I'm using NUnit, more specifically SpecFlow.NUnit. A repro might be tricky because all the tests set up internal things, but I will try to put together something that I can share.

**Comment by mxschmitt** [comment]
@Xen0byte any updates?

**Comment by Xen0byte** [comment]
Hi @mxschmitt, I tried to create a distilled version of the tests, but the issue does not reproduce, so I need to do more digging. Based on this, there must be a weird interaction with something, but what that something is could be difficult to determine. I suppose that this issue can probably be closed for now, until I have more information.

I'll leave this code here, to be updated when I discover more information about what's causing the problem: [PlaywrightDebug.zip](https://github.com/user-attachments/files/16592346/PlaywrightDebug.zip).

**Comment by mxschmitt** [comment]
Closing for now as per above - don't hesitate to re-file if you have more options. My guess is e.g. that you have a non utf-8 codepage configured, we recommend 1252.
