### ISSUE TITLE
[Bug]: Getting error when running test cases in parallel Microsoft.Playwright.TargetClosedException : Target page, context or browser has been closed and Microsoft.Playwright.PlaywrightException : net::ERR_ABORTED; maybe frame was detached?

### ISSUE THREAD

**Issue by akshaysarode31** [microsoft/playwright-dotnet#2980]
### Version

1.41.1

### Steps to reproduce

Steps to Reproduce:
1. Clone the Repo https://github.com/akshaysarode31/PlaywrightFramework.git (playwright should be installed)
2. Run All the test cases.

### Expected behavior

The level of Parallelism is 3, So 3 test cases should run in parallel without any issues. 

### Actual behavior

When I run all tests, the level of parallelism is 1. All Test cases pass
But When I run all the tests, with level of parallelism is 3. Then random test cases pass and fail, with a 50% passing rate.

I am getting below error on random test cases 
Microsoft.Playwright.PlaywrightException : net::ERR_ABORTED; maybe frame was detached?
Microsoft.Playwright.TargetClosedException : Target page, context or browser has been closed
System.TimeoutException : Timeout 60000ms exceeded.

### Additional context

I have updated the playwright from 1.41.1 to 1.45.1 but still fails with the same issues
Also, In tear down I am calling 
await _page.CloseAsync();
await _context.CloseAsync();
await _browser.CloseAsync();
but still, the browser doesn't close after execution and it closes all the browser instances at the end of the execution. 

### Environment

```shell
- Operating System: [Windows 11]
- CPU: [x64]
- Browser: [Chromium]
- .NET Version (TFM): [net8.0]
- Playwright 1.41.1
```

**Comment by akshaysarode31** [comment]
@yury-s Is this issue transferred out of the playwright?

**Comment by yury-s** [comment]
It is specific to multithreaded implementation in our .Net port, so it was transferred to corresponding language port repo.

**Comment by mxschmitt** [comment]
The issue in your case is that you have the Playwright instances as static members and closing some of them which influences other tests. And by that overriding them. We recommend sticking with our [official harnesses](https://playwright.dev/dotnet/docs/intro) in order to not encounter such issues. Also we recommend re-using the browser for multiple tests and only re-creating the context.

```diff
diff --git a/PlaywrightFramework/Tests/TestSetup.cs b/PlaywrightFramework/Tests/TestSetup.cs
index c22d96d..9486445 100644
--- a/PlaywrightFramework/Tests/TestSetup.cs
+++ b/PlaywrightFramework/Tests/TestSetup.cs
@@ -7,9 +7,9 @@ namespace PlaywrightFramework.Tests
 {
     public class TestSetup
     {
-        public static IConfiguration Configuration { get; private set; }
-        public static BrowserConfiguration BrowserConfig { get; private set; }
-        public static IBrowserWrapper BrowserWrapper { get; set; }
+        public IConfiguration Configuration { get; private set; }
+        public BrowserConfiguration BrowserConfig { get; private set; }
+        public IBrowserWrapper BrowserWrapper { get; set; }
 
 
         [SetUp]

```
