### ISSUE TITLE
[Feature]: Automatically install browsers in .NET test projects

### ISSUE THREAD

**Issue by LarsKemmann** [microsoft/playwright-dotnet#2995]
### 🚀 Feature Request

Show how to add something like the following to the .NET project files, like the NUnit Playwright template:

```csproj
  <!-- Automatically install required browsers for Playwright. -->
  <Target Name="PostBuild" AfterTargets="Build" Condition="'$(TF_BUILD)' != 'True'">
    <Exec Command="pwsh bin/Debug/$(TargetFramework)/playwright.ps1 install" />
  </Target>
```

### Example

This removes one extra step for people who are developing locally. It does make some assumptions about a person's workflow, so it's probably best not to add it to the actual project template files, but including it as guidance (e.g., commented out inside the project file as a suggestion) could be useful.

### Motivation

Automatically installing the required browsers could be a nice quality-of-life improvement for teams -- every new machine setup, every new team member, always has to go through the failed test and figure out that they need to run a command, then figure out _in which directory_ to run the command, etc.

**Comment by mxschmitt** [comment]
Looks like we can fold that into https://github.com/microsoft/playwright-dotnet/issues/2286. You can also do something like that [during runtime](https://playwright.dev/dotnet/docs/browsers#install-browsers-via-api), there you exactly know which browsers you want to run.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2286
