### ISSUE TITLE
[Bug]: Node.exe processes remain despite calling IPlaywright.Dispose()

### ISSUE THREAD

**Issue by AlexSimionCommify** [microsoft/playwright-dotnet#3005]
### Version

1.47.0

### Steps to reproduce

1. Create ApiDriver class as per Driver pattern:

using Microsoft.Playwright;
namespace NodeExeNotDisposed
{
    public class ApiDriver : IDisposable
    {

        private readonly Task<IAPIRequestContext> _context = null;
        public ApiDriver()
        {
            _context = CreateAPIContext();
        }

        public IAPIRequestContext APIRequestContext => _context.GetAwaiter().GetResult();

        private async Task<IAPIRequestContext>? CreateAPIContext()
        {
            var playwright = await Playwright.CreateAsync();
            return await playwright.APIRequest.NewContextAsync();
        }

        public void Dispose()
        {
            _context?.Dispose();
        }
    }
}

2.  Create multiple test classes for Nunit:

using Microsoft.Playwright;

namespace NodeExeNotDisposed
{
    public class MultipleTests1
    {
        private ApiDriver _apidriver;
        private IAPIRequestContext _request;

        public MultipleTests1()
        {
            _apidriver = new ApiDriver();
            _request = _apidriver.APIRequestContext;
        }

        [Test]
        public async Task Test1()
        {
            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests2
    {
        private ApiDriver _apidriver;
        private IAPIRequestContext _request;

        public MultipleTests2()
        {
            _apidriver = new ApiDriver();
            _request = _apidriver.APIRequestContext;
        }

        [Test]
        public async Task Test1()
        {
            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests3
    {
        private ApiDriver _apidriver;
        private IAPIRequestContext _request;

        public MultipleTests3()
        {
            _apidriver = new ApiDriver();
            _request = _apidriver.APIRequestContext;
        }

        [Test]
        public async Task Test1()
        {
            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests4
    {
        private ApiDriver _apidriver;
        private IAPIRequestContext _request;

        public MultipleTests4()
        {
            _apidriver = new ApiDriver();
            _request = _apidriver.APIRequestContext;
        }

        [Test]
        public async Task Test1()
        {
            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests5
    {
        private ApiDriver _apidriver;
        private IAPIRequestContext _request;

        public MultipleTests5()
        {
            _apidriver = new ApiDriver();
            _request = _apidriver.APIRequestContext;
        }

        [Test]
        public async Task Test1()
        {
            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }
}

3. Open Task Manager and check for node.exe processes 

### Expected behavior

To see node.exe process appear and disappear after each class execution

### Actual behavior

node.exe processes remain until end of execution, pilling up all the time (which will become problematic when we run over 200 test classes) 

### Additional context

Related to pre-existing closed bugs:
https://github.com/microsoft/playwright-dotnet/issues/1749
https://github.com/microsoft/playwright-dotnet/pull/1864

### Environment

```Text
- Operating System: Windows 11 Pro 23H2 (but happening also on Linux agents in azure pipelines)
- CPU: 12th Gen Intel(R) Core(TM) i7-1270P   2.20 GHz
- .NET Version (TFM): [net8.0]
- Other info:

Happening with following nuget packages:
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.47.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

but also in own project framework with:
 <PackageReference Include="Microsoft.Playwright" Version="1.44.0" />
 <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.44.0" />
```

**Comment by mxschmitt** [comment]
```
    private async Task<IAPIRequestContext>? CreateAPIContext()
    {
        var playwright = await Playwright.CreateAsync();
        return await playwright.APIRequest.NewContextAsync();
    }
```

This is creating a `node.exe` process. You need to dispose the `playwright` instance when you want to clean it up. Ideally you re-use the Playwright instance over and over again during your test runs. So you could do it inside `OneTimeSetUp`. So you have a single Playwright instance for all your tests and just create a `APIRequestContext` for each test:

    return await playwright.APIRequest.NewContextAsync();

**Comment by AlexSimionCommify** [comment]
Hello, thanks for you fast reply.

I updated the code and tried different ways, but still same issue occurs.

using Microsoft.Playwright;

namespace NodeExeNotDisposed
{
    public class ApiDriver : IDisposable
    {

        private readonly Task<IAPIRequestContext> _context = null;
        private readonly Task<IPlaywright> _playwright = null;
        //private IPlaywright _playwright;

        public ApiDriver()
        {
            //_context = CreateAPIContext();
            _playwright = CreatePwInstance();
        }

        public IAPIRequestContext APIRequestContext => _context.GetAwaiter().GetResult();
        public IPlaywright PlaywrightInstance => _playwright.GetAwaiter().GetResult();

        private async Task<IAPIRequestContext>? CreateAPIContext()
        {
            var playwright = await Playwright.CreateAsync();
            return await playwright.APIRequest.NewContextAsync();
        }

        private async Task<IPlaywright>? CreatePwInstance()
        {
            return await Playwright.CreateAsync();
        }

        public void Dispose()
        {
            _context?.Dispose();
            _playwright?.Dispose();
        }
    }
}


using Microsoft.Playwright;

namespace NodeExeNotDisposed
{
    public class MultipleTests1 : IDisposable
    {
        private ApiDriver _apidriver;
        private IPlaywright _pw;
        private IAPIRequestContext _request;

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _apidriver = new ApiDriver();
            _pw = _apidriver.PlaywrightInstance;
            _request = _pw.APIRequest.NewContextAsync().GetAwaiter().GetResult();
        }

        //public MultipleTests1()
        //{
        //    _apidriver = new ApiDriver();
        //    _pw = _apidriver.PlaywrightInstance;
        //    _request = _pw.APIRequest.NewContextAsync().GetAwaiter().GetResult();
        //}

        public void Dispose()
        {
            _apidriver.Dispose();
            _pw.Dispose();
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            _apidriver.Dispose();
            _pw.Dispose();
        }


        [Test]
        public async Task Test1()
        {

            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests2 : IDisposable
    {
        private readonly ApiDriver _apidriver;
        private IPlaywright _pw;
        private IAPIRequestContext _request;

        public MultipleTests2()
        {
            _apidriver = new ApiDriver();
            _pw = _apidriver.PlaywrightInstance;
            _request = _pw.APIRequest.NewContextAsync().GetAwaiter().GetResult();
        }

        public void Dispose()
        {
            _apidriver.Dispose();
        }

        [Test]
        public async Task Test1()
        {

            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests3 : IDisposable
    {
        private readonly ApiDriver _apidriver;
        private IPlaywright _pw;
        private IAPIRequestContext _request;

        public MultipleTests3()
        {
            _apidriver = new ApiDriver();
            _pw = _apidriver.PlaywrightInstance;
            _request = _pw.APIRequest.NewContextAsync().GetAwaiter().GetResult();
        }

        public void Dispose()
        {
            _apidriver.Dispose();
        }

        [Test]
        public async Task Test1()
        {

            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests4 : IDisposable
    {
        private readonly ApiDriver _apidriver;
        private IPlaywright _pw;
        private IAPIRequestContext _request;

        public MultipleTests4()
        {
            _apidriver = new ApiDriver();
            _pw = _apidriver.PlaywrightInstance;
            _request = _pw.APIRequest.NewContextAsync().GetAwaiter().GetResult();
        }

        public void Dispose()
        {
            _apidriver.Dispose();
        }

        [Test]
        public async Task Test1()
        {

            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }

    public class MultipleTests5 : IDisposable
    {
        private readonly ApiDriver _apidriver;
        private IPlaywright _pw;
        private IAPIRequestContext _request;

        public MultipleTests5()
        {
            _apidriver = new ApiDriver();
            _pw = _apidriver.PlaywrightInstance;
            _request = _pw.APIRequest.NewContextAsync().GetAwaiter().GetResult();
        }

        public void Dispose()
        {
            _apidriver.Dispose();
        }

        [Test]
        public async Task Test1()
        {

            await _request.GetAsync("https://github.com/cmealex/pw2024.git");
        }
    }
}

**Comment by AlexSimionCommify** [comment]
In case I misunderstood, please assist with an example

**Comment by mxschmitt** [comment]
You still only dispose the `APIRequestContext` but never the `IPlaywright` instance. I recommend to stick with our default base classes, we provide there `PageTest`, `ContextTest`, `BrowserTest` or in your case probably helpful: `PlaywrightTest`. See [here](https://playwright.dev/dotnet/docs/intro).

**Comment by AlexSimionCommify** [comment]
Regarding dispose, I thought this was disposing IPlaywright instance:
        _pw.Dispose();

Yes, I can use the PlaywrightTest while using Playwright  NUnit project, but
I am using a Specflow + Playwright  + Nunit project, and I see that:
- when I use PlaywrightTest, the IPlaywright instance is null all the time
- and if I try to use OneTimeSetup, it never passes through 

Is this approach intended to work with also Specflow integration? or only for Nunit?

I can create a repo if necessary
