### ISSUE TITLE
[Feature]: New Test Framework Package

### ISSUE THREAD

**Issue by thomhurst** [microsoft/playwright-dotnet#3007]
### 🚀 Feature Request

Heya, I see you have NUnit and MSTest packages for helping set up playwright tests in those frameworks.

I've written a new testing framework and was wondering on what your policy is for potentially adding a package for it?

The repository can be found here:
https://github.com/thomhurst/TUnit

I'd gladly help if you needed. Thanks!

### Motivation

Easier use of playwright for anyone using TUnit as their testing framework

**Comment by thomhurst** [comment]
> 33.9K total downloads is below our threshold. I recommend creating a `TUnit.Playwright` package until it reached more popularity. See the source code of our current existing integrations which you could probably follow along:
> 
> * https://github.com/microsoft/playwright-dotnet/tree/main/src/Playwright.MSTest
> * https://github.com/microsoft/playwright-dotnet/tree/main/src/Playwright.NUnit

Out of curiosity what's the threshold?

**Comment by LarsKemmann** [comment]
> 33.9K total downloads is below our threshold. I recommend creating a `TUnit.Playwright` package until it reached more popularity.

@mxschmitt Some time has passed, and TUnit now averages 136K downloads _per day_ and has 2.6M total downloads, so it's probably time to revisit this decision. 😊 Can you please share the current popularity threshold for adding official support within Playwright? Supporting TUnit in the Playwright docs and making it available as an output target for the test recorder would be useful for the community.
