### ISSUE TITLE
[Feature]: Add support to run in Azure Playwright Testing

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/playwright-dotnet#3008]
### 🚀 Feature Request

Run dotnet tests using Azure Playwright Testing

### Example

Run dotnet tests using Azure Playwright Testing

### Motivation

Better than using DevOps Agents

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-testing-service/issues/16. There are examples for .NET:

- https://github.com/microsoft/playwright-testing-service/tree/main/samples/.NET
