### ISSUE TITLE
Question on which playwright version supports .NET 8

### ISSUE THREAD

**Issue by mahsadft** [microsoft/playwright-dotnet#3011]
### Please do not submit this issue.

- [x] I understand
```[tasklist]
### Tasks
```

**Comment by mxschmitt** [comment]
Playwright for .NET supports netframework2.0 which includes net6 and net8. Could you help us what you mean with "stopped working"? Ideally an error or a reproduction would help us a ton!

**Comment by mahsadft** [comment]
in our dockerfile we have this and we get build error:
Step 1/6 : FROM mcr.microsoft.com/playwright-dotnet:v1.46.0 AS build
manifest for mcr.microsoft.com/playwright-dotnet:v1.46.0 not found: manifest unknown: manifest tagged by "v1.46.0" is not found

Could you point me out to the most recent playWright version which supports .Net 8?

Thanks

**Comment by mxschmitt** [comment]
It should be `playwright/dotnet` - looks like our release notes on GitHub had a typo and used a `-` instead. I fixed it.

e.g. the following would work:

    docker pull mcr.microsoft.com/playwright/dotnet:v1.46.0
    
I found a bug in our build pipeline for v1.47 (hence I'm using v1.46) - I recommend 1.46 in the meantime until we have it fixed.

**Comment by mahsadft** [comment]
Thank you for your quick and helpful response!

**Comment by mahsadft** [comment]
the issue with the build step got fixed with what you just explained but at run step I get this error now 
<img width="920" alt="image" src="https://github.com/user-attachments/assets/21670bda-7c27-4880-943f-52905d83ad9d">
Have you got any suggestion on how this could be fixed? Thanks

**Comment by mahsadft** [comment]
Thanks
