### ISSUE TITLE
[Feature]:Is it possible to remove the built-in nodejs

### ISSUE THREAD

**Issue by pll177** [microsoft/playwright-dotnet#3019]
### 🚀 Feature Request

Is it possible to remove the built-in nodejs

### Example

Dynamically downloads the corresponding platform's nodejs when I run it

### Motivation

Without removing the nodejs runtime, my packaged programs are too big to migrate.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/1850
