### ISSUE TITLE
[Feature]: Allow ExecutablePath to work in .runsettings

### ISSUE THREAD

**Issue by Jojoshua** [microsoft/playwright-dotnet#3034]
### 🚀 Feature Request

https://playwright.dev/dotnet/docs/test-runners#using-the-runsettings-file-1 shows the supported values but < ExecutablePath > isn't listed nor was I able to get it to work in a net 4.8 Nunit project. The request is to allow ExecutablePath work in the .runsettings file.

### Example

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- NUnit adapter -->  
  <NUnit>
    <NumberOfTestWorkers>24</NumberOfTestWorkers>
  </NUnit>
  <!-- General run configuration -->
  <RunConfiguration>
    <EnvironmentVariables>
      <!-- For debugging selectors, it's recommend to set the following environment variable -->
      <DEBUG>pw:api</DEBUG>
    </EnvironmentVariables>
  </RunConfiguration>
  <!-- Playwright -->  
  <Playwright>
    <ExecutablePath>C:\....chrome.exe</ExecutablePath>
    <ExpectTimeout>5000</ExpectTimeout>
    <LaunchOptions>
      <Headless>false</Headless>
    </LaunchOptions>
  </Playwright>
</RunSettings>
```

### Motivation

Providing the browser path in the .runsettings allows for flexible testing scenarios and bypass any type of install browser script.

**Comment by mxschmitt** [comment]
ExecutablePath needs to be under LaunchOptions, have you tried that?

**Comment by Jojoshua** [comment]
> ExecutablePath needs to be under LaunchOptions, have you tried that?

I didn't know that was possible, will give it a go!

**Comment by Jojoshua** [comment]
> ExecutablePath needs to be under LaunchOptions, have you tried that?

That didn't work. So far all I did was create a new project, installed playwright package. My environment won't allow me to download the browsers automatically. It's still wanting to find a browser under AppData ms-playwright. 

Part of the error says to run a playwright.ps1 script (however such a script doesn't exist under bin/debug/netX/playwright.ps1). Could it be because this project uses packages config and not PackageReference? But don't see why I'd need to run a script if I've already side loaded a browser.

**Comment by mxschmitt** [comment]
The following works for me:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Playwright -->  
  <Playwright>
    <BrowserName>chromium</BrowserName>
    <ExpectTimeout>5000</ExpectTimeout>
    <LaunchOptions>
      <Headless>false</Headless>
      <ExecutablePath>/Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev</ExecutablePath>
    </LaunchOptions>
  </Playwright>
</RunSettings>
```

How do your tests look like? Are you launching the browser manually?

AFAIK it should also work with package config - we mostly test with PackageReferences and ne6+ projects.

**Comment by Jojoshua** [comment]
> The following works for me:
> 
> <?xml version="1.0" encoding="utf-8"?>
> <RunSettings>
>     
>   <Playwright>
>     <BrowserName>chromium</BrowserName>
>     <ExpectTimeout>5000</ExpectTimeout>
>     <LaunchOptions>
>       <Headless>false</Headless>
>       <ExecutablePath>/Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev</ExecutablePath>
>     </LaunchOptions>
>   </Playwright>
> </RunSettings>
> How do your tests look like? Are you launching the browser manually?
> 
> AFAIK it should also work with package config - we mostly test with PackageReferences and ne6+ projects.

I am just starting with the example from https://playwright.dev/dotnet/docs/test-runners#customizing-browsercontext-options-1 

Would you expect this to work if you created a brand new project, installed playwright nuget packages, and pointed your runsettings file to a browser? In other words, skipping the step that mentions running a playwright install script.

**Comment by mxschmitt** [comment]
Install is not required if you have your own channel or executable path - so that should not be the problem.

There might be an issue with net48/nunit integration since you mentioned 48.

Probably the same as https://github.com/microsoft/playwright-dotnet/issues/2353.

Maybe the workaround works for you as well there? https://github.com/microsoft/playwright-dotnet/issues/2353#issuecomment-1310170971

**Comment by Jojoshua** [comment]
> Install is not required if you have your own channel or executable path - so that should not be the problem.
> 
> There might be an issue with net48/nunit integration since you mentioned 48.
> 
> Probably the same as [#2353](https://github.com/microsoft/playwright-dotnet/issues/2353).
> 
> Maybe the workaround works for you as well there? [#2353 (comment)](https://github.com/microsoft/playwright-dotnet/issues/2353#issuecomment-1310170971)

Ok so all I had to do was add this and it started working. I don't understand why, but is this something we can rely on going forward?
`< DisableAppDomain>True</ DisableAppDomain>`

**Comment by mxschmitt** [comment]
I'll fold it into https://github.com/microsoft/playwright-dotnet/issues/2353#issuecomment-1310170971 - there was a RFC for it: https://github.com/microsoft/vstest-docs/blob/main/RFCs/0019-Disable-Appdomain-While-Running-Tests.md

This seems a setting of VSTest.
