### ISSUE TITLE
[Feature]: net9 docker images

### ISSUE THREAD

**Issue by martinalderson** [microsoft/playwright-dotnet#3052]
### 🚀 Feature Request

Please can we get net9 docker images?

### Example

We cannot upgrade to net9 until playwright docker base images support it.

### Motivation

Want to upgrade to net9.

**Comment by mxschmitt** [comment]
We recommend either to install net9.0 manually on top, see [here](https://playwright.dev/dotnet/docs/docker#using-a-different-net-version) or creating your own Docker image. Our Docker image only targets .NET LTS versions for simplicity.
