### ISSUE TITLE
Unable to perform checkbox actions using Playwright with C#

### ISSUE THREAD

**Issue by SanthiyaOptimum** [microsoft/playwright-dotnet#3069]
### Please do not submit this issue.

- [x] I understand

**Comment by SanthiyaOptimum** [comment]
![Image](https://github.com/user-attachments/assets/8b60b6af-4413-49f7-87ba-9b4a5fcbb9d0)

I want to check the pseudo check box and I've tried the following ways but no luck,
CheckPracticeOrLocationCheckbox(practice) is a helper method

1. await _page.CheckAsync("//span[contains(text(),\"P-10063\")]//parent::div//preceding-sibling::mat-pseudo-checkbox"); 
2. await _page.Locator(CheckPracticeOrLocationCheckbox(practice)).DispatchEventAsync("click");
3. await _page.EvaluateHandleAsync("document.getElementsByClassName('mat-pseudo-checkbox').click()");
4. await _page.ClickAsync(CheckPracticeOrLocationCheckbox(practice));
5. await _page.CheckAsync(CheckPracticeOrLocationCheckbox(practice)); //checkbox needs to be fixed
6. await _page.Locator(CheckPracticeOrLocationCheckbox(practice)).CheckAsync();

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
