### ISSUE TITLE
[Bug]: Chrome.exe missing signature causes .net Playwright to be non-usable

### ISSUE THREAD

**Issue by DipakTated** [microsoft/playwright-dotnet#3070]
### Version

1.40.0

### Steps to reproduce

It has now been established that it is the chrome.exe file that does not have a digital signature on the file that is blocked by Microsoft Applocker. The exe file is located outside C:\Program Files and C:\Program Files (x86) which causes files without a digital signature to be blocked by Microsoft Applocker. We have used our own certificate to temporarily solve the problem and have digitally signed the file and have tested that this is the cause. Would be good if the exe file has a digital signature from the beginning in future versions.

In the Windows log when Applocker blocked

%OSDRIVE%\USERS\uuyP\APPDATA\LOCAL\MS-PLAYWRIGHT\CHROMIUM-1091\CHROME-WIN\CHROME.EXE was prevented from running.

on further googling, this is what we found:

When you install Chromium through MS Playwright using C#, it downloads Chromium from the Playwright servers.
As Chromium is an open-source project, it may not have a digital signature because it's not necessarily released by an officially recognized entity that would provide a digital signature, such as Google or Microsoft.
 
However, if you need to add a digital signature to the Chromium executable for your specific use case, you would need a code-signing certificate and a tool like signtool.exe (part of the Windows SDK) to manually sign the executable.
 
Can Playwright solve this problem better, as its making Playwright non-usable.

### Expected behavior

Playwright should use Chrome.exe with digital signature for security reasons.

### Actual behavior

Playwright looks non-usable.

### Environment

```Text
Windows10 -  64 bit
```

**Comment by mxschmitt** [comment]
Thanks for the details. I'll fold it into https://github.com/microsoft/playwright/issues/17165 - please upvote it there. We didn't invest much time into it the past years since there was not a lot of demand for it.
