### ISSUE TITLE
[Feature]: TUnit support

### ISSUE THREAD

**Issue by dukedagmor** [microsoft/playwright-dotnet#3072]
### 🚀 Feature Request

TUnit is slowly making waves as a new standard testing library. 
It would be nice if I can add playwright without having to add NUnit

### Motivation

TUnit is fast, async and supports the new test runner.
Adding TUnit support would be amazing for the long term sustainability of Playwright-dotnet

**Comment by thomhurst** [comment]
@dukedagmor I made my own version for now. 

https://www.nuget.org/packages/TUnit.playwright

**Comment by mxschmitt** [comment]
Looks great! TUnit has 324 daily downloads on average so we won't invest for now.

Folding into https://github.com/microsoft/playwright-dotnet/issues/3007.
