### ISSUE TITLE
[Feature]: Support .NET 9 for docker

### ISSUE THREAD

**Issue by timbze** [microsoft/playwright-dotnet#3075]
### 🚀 Feature Request

Currently the docker image is built with .NET 8, when will there be .NET 9 support?

### Motivation

Makes it possible to do testing in CI after switching my projects to .NET 9.

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright-dotnet/pull/3077#issuecomment-2532370021.

**Comment by timbze** [comment]
As per @mxschmitt comment (https://github.com/microsoft/playwright-dotnet/pull/3077#issuecomment-2532370021) I realized that I could install dotnet 9 in my own docker image. In case someone wants to use this model: https://github.com/timbze/playwright-docker-plus. I install a few more things in the image for myself so if you like it probably best to create your own image.
