### ISSUE TITLE
IPage should implement IAsyncDisposable

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright-dotnet#898]
currently `IPage` has a CloseAsync method

The method contains a single parameter with a default value
```cs
Task CloseAsync(bool runBeforeUnload = false);
``` 
I think we could add something like this
```cs
Task CloseAsync() => CloseAsync(runBeforeUnload: false);
```

then we will be able to write:
```cs
await using IPage page = await browser.NewPageAsync();
```

**Comment by kblok** [comment]
I was thinking about this. I'm still not bought. 
We need to be sure that the browser and the driver are closed. But besides that, if you want to close the page or not is up to you.
One good thing about `IAsyncDisposable` is that it's not as strong as `IDisposable`. 
`IAsyncDisposable` as a syntax sugar doesn't sound bad. But if the user sees that the page is `IAsyncDisposable`, they may feel that they **need** use `using` when they do not necessarily need to.

**Comment by Meir017** [comment]
PuppeteerSharp has something similar to this

https://github.com/hardkoded/puppeteer-sharp/blob/865d1eeb47ecf93733693558d8b1d580d6f0fc5c/lib/PuppeteerSharp/Page.cs#L38
![image](https://user-images.githubusercontent.com/9786571/95007849-fdb0b780-061c-11eb-8355-73f978b87602.png)

**Comment by kblok** [comment]
Yeah, and I don't know if that was a good idea 🤓

**Comment by avodovnik** [comment]
I'm also not 100% sure on this. Technically speaking, `Close` and `Dispose` have a different semantic; as a developer, I expect `Dispose` to clean-up any resources it has, and holds, but for `Close`, I expect certain things to still be available to me. 

I'll close this for now, but happy to revisit if someone can explain to me why I'm wrong :-)
