### ISSUE TITLE
[Feature]: Add BrowserType.connect()

### ISSUE THREAD

**Issue by andliang** [microsoft/playwright-dotnet#986]
Can I connect to a browser instance by passing a web socket endpoint?

Playwright's Node API supports it as documented [here](https://github.com/microsoft/playwright/blob/master/docs/api.md#class-browserserver) (look for wsEndpoint.

**Comment by kblok** [comment]
@andliang, Playwright bindings don't have the browser server implemented (yet).
Could you share your use case so it can be prioritized?

**Comment by andliang** [comment]
I use browserless.io because Azure AppService doesn't allow chrome running in it. Browserless.io has sample code ([here](https://docs.browserless.io/docs/playwright.html)) on how to use their service using Node

**Comment by kblok** [comment]
cc @arjunattam

**Comment by kurtisane** [comment]
Any news on this ?

**Comment by kblok** [comment]
@kurtisane there is an open issue upstream https://github.com/microsoft/playwright/issues/4687
You can go and give your thumb there.

**Comment by Xeevis** [comment]
PlaywrightSharp doesn't have the `Connect` capability at all? I thought Playwright API does support it. My use-case is to use browserless hosted locally in a docker container to reliably consume multiple headless & isolated browser instances in parallel and with queues from multiple apps.

Guess I'll have to stick to PuppeteerSharp for the time being 😔

```csharp
var browser = await Puppeteer.ConnectAsync(new ConnectOptions() { BrowserWSEndpoint = "ws://localhost:3000" })
```

**Comment by sourav-kundu** [comment]
Is there any way by which I can connect to a **wsEndpoint** using PlaywrightSharp?
Its supported in the node API 
https://playwright.dev/docs/api/class-browsertype#browsertypeconnectparams

**Comment by kblok** [comment]
@sourav-kundu we will! not yet :)

**Comment by kblok** [comment]
cc @pavelfeldman

**Comment by avodovnik** [comment]
Moving this to `v1.14` as it's not looking like it'll get finished in time for 1.13.

**Comment by bbhxwl** [comment]
> Can I connect to a browser instance by passing a web socket endpoint?
> 
> Playwright's Node API supports it as documented [here](https://github.com/microsoft/playwright/blob/master/docs/api.md#class-browserserver) (look for wsEndpoint.

How to deploy a remote browser server using docker?
